version: 2
updates:
  - package-ecosystem: gomod
    directory: "/"
    schedule:
      interval: daily
    groups:
      golang:
        patterns:
          - "golang.org/x/*"
      mtgo-labs:
        patterns:
          - "github.com/mtgo-labs/*"

  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: daily
