// Code generated by tlgen. DO NOT EDIT.

package tg

import (
	"bytes"
	"io"
)

// InputAiComposeToneClass is the interface for TL type InputAiComposeTone.
// Implementations must satisfy TLObject and are used to represent
// any constructor of the InputAiComposeTone TL type.
type InputAiComposeToneClass interface {
	TLObject
	isInputAiComposeTone()
}

// InputAiComposeToneDefaultTypeID is the constructor ID for TL type inputAiComposeToneDefault.
const InputAiComposeToneDefaultTypeID = 0x1fe9a9bf

// InputAiComposeToneIDTypeID is the constructor ID for TL type inputAiComposeToneID.
const InputAiComposeToneIDTypeID = 0x0773c080

// InputAiComposeToneSlugTypeID is the constructor ID for TL type inputAiComposeToneSlug.
const InputAiComposeToneSlugTypeID = 0x1fa01357

// isInputAiComposeTone marks InputAiComposeToneDefault as implementing the InputAiComposeToneClass interface.
func (*InputAiComposeToneDefault) isInputAiComposeTone() {}

// isInputAiComposeTone marks InputAiComposeToneID as implementing the InputAiComposeToneClass interface.
func (*InputAiComposeToneID) isInputAiComposeTone() {}

// isInputAiComposeTone marks InputAiComposeToneSlug as implementing the InputAiComposeToneClass interface.
func (*InputAiComposeToneSlug) isInputAiComposeTone() {}

// InputAiComposeToneDefault represents the TL constructor inputAiComposeToneDefault (0x1fe9a9bf).
//
// See https://core.telegram.org/constructor/inputAiComposeToneDefault for reference.
type InputAiComposeToneDefault struct {
	Tone string `json:"tone,omitempty"`
}

// ConstructorID returns the TL constructor identifier 0x1fe9a9bf.
func (v *InputAiComposeToneDefault) ConstructorID() uint32 {
	return InputAiComposeToneDefaultTypeID
}

// Encode serializes InputAiComposeToneDefault to a bytes.Buffer using the TL binary protocol.
func (v *InputAiComposeToneDefault) Encode(b *bytes.Buffer) error {
	WriteInt(b, InputAiComposeToneDefaultTypeID)
	WriteString(b, v.Tone)
	return nil
}

// DecodeInputAiComposeToneDefault deserializes a InputAiComposeToneDefault from a reader using the TL binary protocol.
func DecodeInputAiComposeToneDefault(r io.Reader) (*InputAiComposeToneDefault, error) {
	v := &InputAiComposeToneDefault{}
	v.Tone = ReadString(r)
	return v, nil
}

func init() {
	Registry[InputAiComposeToneDefaultTypeID] = func(r io.Reader) (TLObject, error) {
		return DecodeInputAiComposeToneDefault(r)
	}
}

// InputAiComposeToneID represents the TL constructor inputAiComposeToneID (0x0773c080).
//
// See https://core.telegram.org/constructor/inputAiComposeToneID for reference.
type InputAiComposeToneID struct {
	ID         int64 `json:"id,omitempty"`
	AccessHash int64 `json:"access_hash,omitempty"`
}

// ConstructorID returns the TL constructor identifier 0x0773c080.
func (v *InputAiComposeToneID) ConstructorID() uint32 {
	return InputAiComposeToneIDTypeID
}

// Encode serializes InputAiComposeToneID to a bytes.Buffer using the TL binary protocol.
func (v *InputAiComposeToneID) Encode(b *bytes.Buffer) error {
	WriteInt(b, InputAiComposeToneIDTypeID)
	WriteLong(b, v.ID)
	WriteLong(b, v.AccessHash)
	return nil
}

// DecodeInputAiComposeToneID deserializes a InputAiComposeToneID from a reader using the TL binary protocol.
func DecodeInputAiComposeToneID(r io.Reader) (*InputAiComposeToneID, error) {
	v := &InputAiComposeToneID{}
	v.ID = ReadLong(r)
	v.AccessHash = ReadLong(r)
	return v, nil
}

func init() {
	Registry[InputAiComposeToneIDTypeID] = func(r io.Reader) (TLObject, error) {
		return DecodeInputAiComposeToneID(r)
	}
}

// InputAiComposeToneSlug represents the TL constructor inputAiComposeToneSlug (0x1fa01357).
//
// See https://core.telegram.org/constructor/inputAiComposeToneSlug for reference.
type InputAiComposeToneSlug struct {
	Slug string `json:"slug,omitempty"`
}

// ConstructorID returns the TL constructor identifier 0x1fa01357.
func (v *InputAiComposeToneSlug) ConstructorID() uint32 {
	return InputAiComposeToneSlugTypeID
}

// Encode serializes InputAiComposeToneSlug to a bytes.Buffer using the TL binary protocol.
func (v *InputAiComposeToneSlug) Encode(b *bytes.Buffer) error {
	WriteInt(b, InputAiComposeToneSlugTypeID)
	WriteString(b, v.Slug)
	return nil
}

// DecodeInputAiComposeToneSlug deserializes a InputAiComposeToneSlug from a reader using the TL binary protocol.
func DecodeInputAiComposeToneSlug(r io.Reader) (*InputAiComposeToneSlug, error) {
	v := &InputAiComposeToneSlug{}
	v.Slug = ReadString(r)
	return v, nil
}

func init() {
	Registry[InputAiComposeToneSlugTypeID] = func(r io.Reader) (TLObject, error) {
		return DecodeInputAiComposeToneSlug(r)
	}
}

// AiComposeToneClass is the interface for TL type AiComposeTone.
// Implementations must satisfy TLObject and are used to represent
// any constructor of the AiComposeTone TL type.
type AiComposeToneClass interface {
	TLObject
	isAiComposeTone()
}

// AiComposeToneTypeID is the constructor ID for TL type aiComposeTone.
const AiComposeToneTypeID = 0xcff63ea9

// AiComposeToneDefaultTypeID is the constructor ID for TL type aiComposeToneDefault.
const AiComposeToneDefaultTypeID = 0x9bad6414

// isAiComposeTone marks AiComposeTone as implementing the AiComposeToneClass interface.
func (*AiComposeTone) isAiComposeTone() {}

// isAiComposeTone marks AiComposeToneDefault as implementing the AiComposeToneClass interface.
func (*AiComposeToneDefault) isAiComposeTone() {}

// AiComposeTone represents the TL constructor aiComposeTone (0xcff63ea9).
//
// See https://core.telegram.org/constructor/aiComposeTone for reference.
type AiComposeTone struct {
	Flags          Fields                `json:"-"`
	Creator        bool                  `json:"creator,omitempty"`
	ID             int64                 `json:"id,omitempty"`
	AccessHash     int64                 `json:"access_hash,omitempty"`
	Slug           string                `json:"slug,omitempty"`
	Title          string                `json:"title,omitempty"`
	EmojiID        int64                 `json:"emoji_id,omitempty"`
	Prompt         string                `json:"prompt,omitempty"`
	InstallsCount  int32                 `json:"installs_count,omitempty"`
	AuthorID       int64                 `json:"author_id,omitempty"`
	ExampleEnglish *AiComposeToneExample `json:"example_english,omitempty"`
}

// SetFlags computes flags from non-zero optional fields.
func (v *AiComposeTone) SetFlags() {
	if v.Creator {
		v.Flags.Set(0)
	}
	if v.EmojiID != 0 {
		v.Flags.Set(1)
	}
	if v.Prompt != "" {
		v.Flags.Set(4)
	}
	if v.InstallsCount != 0 {
		v.Flags.Set(2)
	}
	if v.AuthorID != 0 {
		v.Flags.Set(3)
	}
	if v.ExampleEnglish != nil {
		v.Flags.Set(5)
	}
}

// ConstructorID returns the TL constructor identifier 0xcff63ea9.
func (v *AiComposeTone) ConstructorID() uint32 {
	return AiComposeToneTypeID
}

// Encode serializes AiComposeTone to a bytes.Buffer using the TL binary protocol.
func (v *AiComposeTone) Encode(b *bytes.Buffer) error {
	WriteInt(b, AiComposeToneTypeID)
	v.SetFlags()
	WriteInt(b, uint32(v.Flags))
	WriteLong(b, v.ID)
	WriteLong(b, v.AccessHash)
	WriteString(b, v.Slug)
	WriteString(b, v.Title)
	if v.Flags.Has(1) {
		WriteLong(b, v.EmojiID)
	}
	if v.Flags.Has(4) {
		WriteString(b, v.Prompt)
	}
	if v.Flags.Has(2) {
		WriteInt(b, uint32(v.InstallsCount))
	}
	if v.Flags.Has(3) {
		WriteLong(b, v.AuthorID)
	}
	if v.Flags.Has(5) {
		EncodeTLObject(b, v.ExampleEnglish)
	}
	return nil
}

// DecodeAiComposeTone deserializes a AiComposeTone from a reader using the TL binary protocol.
func DecodeAiComposeTone(r io.Reader) (*AiComposeTone, error) {
	v := &AiComposeTone{}
	{
		var _f uint32
		_f, _ = ReadIntErr(r)
		v.Flags = Fields(_f)
	}
	v.Creator = v.Flags.Has(0)
	v.ID = ReadLong(r)
	v.AccessHash = ReadLong(r)
	v.Slug = ReadString(r)
	v.Title = ReadString(r)
	if v.Flags.Has(1) {
		v.EmojiID = ReadLong(r)
	}
	if v.Flags.Has(4) {
		v.Prompt = ReadString(r)
	}
	if v.Flags.Has(2) {
		v.InstallsCount = int32(ReadInt(r))
	}
	if v.Flags.Has(3) {
		v.AuthorID = ReadLong(r)
	}
	if v.Flags.Has(5) {
		_objExampleEnglish, _ := ReadTLObject(r)
		v.ExampleEnglish = _objExampleEnglish.(*AiComposeToneExample)
	}
	return v, nil
}

func init() {
	Registry[AiComposeToneTypeID] = func(r io.Reader) (TLObject, error) {
		return DecodeAiComposeTone(r)
	}
}

// AiComposeToneDefault represents the TL constructor aiComposeToneDefault (0x9bad6414).
//
// See https://core.telegram.org/constructor/aiComposeToneDefault for reference.
type AiComposeToneDefault struct {
	Tone    string `json:"tone,omitempty"`
	EmojiID int64  `json:"emoji_id,omitempty"`
	Title   string `json:"title,omitempty"`
}

// ConstructorID returns the TL constructor identifier 0x9bad6414.
func (v *AiComposeToneDefault) ConstructorID() uint32 {
	return AiComposeToneDefaultTypeID
}

// Encode serializes AiComposeToneDefault to a bytes.Buffer using the TL binary protocol.
func (v *AiComposeToneDefault) Encode(b *bytes.Buffer) error {
	WriteInt(b, AiComposeToneDefaultTypeID)
	WriteString(b, v.Tone)
	WriteLong(b, v.EmojiID)
	WriteString(b, v.Title)
	return nil
}

// DecodeAiComposeToneDefault deserializes a AiComposeToneDefault from a reader using the TL binary protocol.
func DecodeAiComposeToneDefault(r io.Reader) (*AiComposeToneDefault, error) {
	v := &AiComposeToneDefault{}
	v.Tone = ReadString(r)
	v.EmojiID = ReadLong(r)
	v.Title = ReadString(r)
	return v, nil
}

func init() {
	Registry[AiComposeToneDefaultTypeID] = func(r io.Reader) (TLObject, error) {
		return DecodeAiComposeToneDefault(r)
	}
}

// TonesClass is the interface for TL type Tones.
// Implementations must satisfy TLObject and are used to represent
// any constructor of the Tones TL type.
type TonesClass interface {
	TLObject
	isTones()
}

// AicomposeTonesNotModifiedTypeID is the constructor ID for TL type aicompose.tonesNotModified.
const AicomposeTonesNotModifiedTypeID = 0xc1f46103

// AicomposeTonesTypeID is the constructor ID for TL type aicompose.tones.
const AicomposeTonesTypeID = 0x6c9d0efe

// isTones marks AicomposeTonesNotModified as implementing the TonesClass interface.
func (*AicomposeTonesNotModified) isTones() {}

// isTones marks AicomposeTones as implementing the TonesClass interface.
func (*AicomposeTones) isTones() {}

// AicomposeTonesNotModified represents the TL constructor aicompose.tonesNotModified (0xc1f46103).
//
// See https://core.telegram.org/constructor/aicompose.tonesNotModified for reference.
type AicomposeTonesNotModified struct {
}

// ConstructorID returns the TL constructor identifier 0xc1f46103.
func (v *AicomposeTonesNotModified) ConstructorID() uint32 {
	return AicomposeTonesNotModifiedTypeID
}

// Encode serializes AicomposeTonesNotModified to a bytes.Buffer using the TL binary protocol.
func (v *AicomposeTonesNotModified) Encode(b *bytes.Buffer) error {
	WriteInt(b, AicomposeTonesNotModifiedTypeID)
	return nil
}

// DecodeAicomposeTonesNotModified deserializes a AicomposeTonesNotModified from a reader using the TL binary protocol.
func DecodeAicomposeTonesNotModified(r io.Reader) (*AicomposeTonesNotModified, error) {
	v := &AicomposeTonesNotModified{}
	return v, nil
}

func init() {
	Registry[AicomposeTonesNotModifiedTypeID] = func(r io.Reader) (TLObject, error) {
		return DecodeAicomposeTonesNotModified(r)
	}
}

// AicomposeTones represents the TL constructor aicompose.tones (0x6c9d0efe).
//
// See https://core.telegram.org/constructor/aicompose.tones for reference.
type AicomposeTones struct {
	Hash  int64                `json:"hash,omitempty"`
	Tones []AiComposeToneClass `json:"tones,omitempty"`
	Users []UserClass          `json:"users,omitempty"`
}

// ConstructorID returns the TL constructor identifier 0x6c9d0efe.
func (v *AicomposeTones) ConstructorID() uint32 {
	return AicomposeTonesTypeID
}

// Encode serializes AicomposeTones to a bytes.Buffer using the TL binary protocol.
func (v *AicomposeTones) Encode(b *bytes.Buffer) error {
	WriteInt(b, AicomposeTonesTypeID)
	WriteLong(b, v.Hash)
	WriteInt(b, 0x1cb5c415)
	WriteInt(b, uint32(len(v.Tones)))
	for _, _item := range v.Tones {
		EncodeTLObject(b, _item)
	}
	WriteInt(b, 0x1cb5c415)
	WriteInt(b, uint32(len(v.Users)))
	for _, _item := range v.Users {
		EncodeTLObject(b, _item)
	}
	return nil
}

// DecodeAicomposeTones deserializes a AicomposeTones from a reader using the TL binary protocol.
func DecodeAicomposeTones(r io.Reader) (*AicomposeTones, error) {
	v := &AicomposeTones{}
	v.Hash = ReadLong(r)
	ReadInt(r)
	_cntTones := ReadInt(r)
	if err := checkVectorCount(_cntTones); err != nil {
		return nil, err
	}
	v.Tones = make([]AiComposeToneClass, _cntTones)
	for _iTones := range v.Tones {
		_objTones, _ := ReadTLObject(r)
		v.Tones[_iTones] = _objTones.(AiComposeToneClass)
	}
	ReadInt(r)
	_cntUsers := ReadInt(r)
	if err := checkVectorCount(_cntUsers); err != nil {
		return nil, err
	}
	v.Users = make([]UserClass, _cntUsers)
	for _iUsers := range v.Users {
		_objUsers, _ := ReadTLObject(r)
		v.Users[_iUsers] = _objUsers.(UserClass)
	}
	return v, nil
}

func init() {
	Registry[AicomposeTonesTypeID] = func(r io.Reader) (TLObject, error) {
		return DecodeAicomposeTones(r)
	}
}

// AiComposeToneExampleTypeID is the constructor ID for TL type aiComposeToneExample.
const AiComposeToneExampleTypeID = 0xf1d628ec

// AiComposeToneExample represents the TL constructor aiComposeToneExample (0xf1d628ec).
//
// See https://core.telegram.org/constructor/aiComposeToneExample for reference.
type AiComposeToneExample struct {
	From *TextWithEntities `json:"from,omitempty"`
	To   *TextWithEntities `json:"to,omitempty"`
}

// ConstructorID returns the TL constructor identifier 0xf1d628ec.
func (v *AiComposeToneExample) ConstructorID() uint32 {
	return AiComposeToneExampleTypeID
}

// Encode serializes AiComposeToneExample to a bytes.Buffer using the TL binary protocol.
func (v *AiComposeToneExample) Encode(b *bytes.Buffer) error {
	WriteInt(b, AiComposeToneExampleTypeID)
	EncodeTLObject(b, v.From)
	EncodeTLObject(b, v.To)
	return nil
}

// DecodeAiComposeToneExample deserializes a AiComposeToneExample from a reader using the TL binary protocol.
func DecodeAiComposeToneExample(r io.Reader) (*AiComposeToneExample, error) {
	v := &AiComposeToneExample{}
	_objFrom, _ := ReadTLObject(r)
	v.From = _objFrom.(*TextWithEntities)
	_objTo, _ := ReadTLObject(r)
	v.To = _objTo.(*TextWithEntities)
	return v, nil
}

func init() {
	Registry[AiComposeToneExampleTypeID] = func(r io.Reader) (TLObject, error) {
		return DecodeAiComposeToneExample(r)
	}
}
