// Code generated by tlgen. DO NOT EDIT.

package tg

import (
	"bytes"
	"context"
	"fmt"
	"io"
)

// ChatlistsExportChatlistInviteTypeID is the constructor ID for the RPC function chatlists.exportChatlistInvite.
const ChatlistsExportChatlistInviteTypeID = 0x8472478e

// ChatlistsExportChatlistInviteRequest represents TL type `chatlists.exportChatlistInvite#8472478e`.
//
// See https://core.telegram.org/method/chatlists/exportChatlistInvite for reference.
type ChatlistsExportChatlistInviteRequest struct {
	Chatlist *InputChatlistDialogFilter `json:"chatlist,omitempty"`
	Title    string                     `json:"title,omitempty"`
	Peers    []InputPeerClass           `json:"peers,omitempty"`
}

// ConstructorID returns the TL constructor identifier 0x8472478e.
func (v *ChatlistsExportChatlistInviteRequest) ConstructorID() uint32 {
	return ChatlistsExportChatlistInviteTypeID
}

// Encode serializes ChatlistsExportChatlistInviteRequest to a bytes.Buffer using the TL binary protocol.
func (v *ChatlistsExportChatlistInviteRequest) Encode(b *bytes.Buffer) error {
	WriteInt(b, ChatlistsExportChatlistInviteTypeID)
	EncodeTLObject(b, v.Chatlist)
	WriteString(b, v.Title)
	WriteInt(b, 0x1cb5c415)
	WriteInt(b, uint32(len(v.Peers)))
	for _, _item := range v.Peers {
		EncodeTLObject(b, _item)
	}
	return nil
}

// ChatlistsExportChatlistInvite invokes the chatlists.exportChatlistInvite RPC method on the server.
//
// Parameters:
//   - ctx: context for cancellation and timeout
//   - req: the request parameters
//
// Returns the result of the RPC call, or an error if the invocation fails.
func (c *RPCClient) ChatlistsExportChatlistInvite(ctx context.Context, req *ChatlistsExportChatlistInviteRequest) (ExportedChatlistInviteClass, error) {
	result, err := c.invoke(ctx, req, func(r io.Reader) (TLObject, error) {
		return ReadTLObject(r)
	})
	if err != nil {
		return nil, err
	}
	if _c, _ok := result.(ExportedChatlistInviteClass); _ok {
		return _c, nil
	}
	return nil, fmt.Errorf("unexpected result type %T", result)
}

// ChatlistsDeleteExportedInviteTypeID is the constructor ID for the RPC function chatlists.deleteExportedInvite.
const ChatlistsDeleteExportedInviteTypeID = 0x719c5c5e

// ChatlistsDeleteExportedInviteRequest represents TL type `chatlists.deleteExportedInvite#719c5c5e`.
//
// See https://core.telegram.org/method/chatlists/deleteExportedInvite for reference.
type ChatlistsDeleteExportedInviteRequest struct {
	Chatlist *InputChatlistDialogFilter `json:"chatlist,omitempty"`
	Slug     string                     `json:"slug,omitempty"`
}

// ConstructorID returns the TL constructor identifier 0x719c5c5e.
func (v *ChatlistsDeleteExportedInviteRequest) ConstructorID() uint32 {
	return ChatlistsDeleteExportedInviteTypeID
}

// Encode serializes ChatlistsDeleteExportedInviteRequest to a bytes.Buffer using the TL binary protocol.
func (v *ChatlistsDeleteExportedInviteRequest) Encode(b *bytes.Buffer) error {
	WriteInt(b, ChatlistsDeleteExportedInviteTypeID)
	EncodeTLObject(b, v.Chatlist)
	WriteString(b, v.Slug)
	return nil
}

// ChatlistsDeleteExportedInvite invokes the chatlists.deleteExportedInvite RPC method on the server.
//
// Parameters:
//   - ctx: context for cancellation and timeout
//   - req: the request parameters
//
// Returns the result of the RPC call, or an error if the invocation fails.
func (c *RPCClient) ChatlistsDeleteExportedInvite(ctx context.Context, req *ChatlistsDeleteExportedInviteRequest) (bool, error) {
	result, err := c.invoke(ctx, req, func(r io.Reader) (TLObject, error) {
		return ReadTLObject(r)
	})
	if err != nil {
		return false, err
	}
	_ = result
	return true, nil
}

// ChatlistsEditExportedInviteTypeID is the constructor ID for the RPC function chatlists.editExportedInvite.
const ChatlistsEditExportedInviteTypeID = 0x653db63d

// ChatlistsEditExportedInviteRequest represents TL type `chatlists.editExportedInvite#653db63d`.
//
// See https://core.telegram.org/method/chatlists/editExportedInvite for reference.
type ChatlistsEditExportedInviteRequest struct {
	Flags    Fields                     `json:"-"`
	Chatlist *InputChatlistDialogFilter `json:"chatlist,omitempty"`
	Slug     string                     `json:"slug,omitempty"`
	Title    string                     `json:"title,omitempty"`
	Peers    []InputPeerClass           `json:"peers,omitempty"`
}

// SetFlags computes flags from non-zero optional fields.
func (v *ChatlistsEditExportedInviteRequest) SetFlags() {
	if v.Title != "" {
		v.Flags.Set(1)
	}
	if v.Peers != nil {
		v.Flags.Set(2)
	}
}

// ConstructorID returns the TL constructor identifier 0x653db63d.
func (v *ChatlistsEditExportedInviteRequest) ConstructorID() uint32 {
	return ChatlistsEditExportedInviteTypeID
}

// Encode serializes ChatlistsEditExportedInviteRequest to a bytes.Buffer using the TL binary protocol.
func (v *ChatlistsEditExportedInviteRequest) Encode(b *bytes.Buffer) error {
	WriteInt(b, ChatlistsEditExportedInviteTypeID)
	v.SetFlags()
	WriteInt(b, uint32(v.Flags))
	EncodeTLObject(b, v.Chatlist)
	WriteString(b, v.Slug)
	if v.Flags.Has(1) {
		WriteString(b, v.Title)
	}
	if v.Flags.Has(2) {
		WriteInt(b, 0x1cb5c415)
		WriteInt(b, uint32(len(v.Peers)))
		for _, _item := range v.Peers {
			EncodeTLObject(b, _item)
		}
	}
	return nil
}

// ChatlistsEditExportedInvite invokes the chatlists.editExportedInvite RPC method on the server.
//
// Parameters:
//   - ctx: context for cancellation and timeout
//   - req: the request parameters
//
// Returns the result of the RPC call, or an error if the invocation fails.
func (c *RPCClient) ChatlistsEditExportedInvite(ctx context.Context, req *ChatlistsEditExportedInviteRequest) (ExportedChatlistInviteClass, error) {
	result, err := c.invoke(ctx, req, func(r io.Reader) (TLObject, error) {
		return ReadTLObject(r)
	})
	if err != nil {
		return nil, err
	}
	if _c, _ok := result.(ExportedChatlistInviteClass); _ok {
		return _c, nil
	}
	return nil, fmt.Errorf("unexpected result type %T", result)
}

// ChatlistsGetExportedInvitesTypeID is the constructor ID for the RPC function chatlists.getExportedInvites.
const ChatlistsGetExportedInvitesTypeID = 0xce03da83

// ChatlistsGetExportedInvitesRequest represents TL type `chatlists.getExportedInvites#ce03da83`.
//
// See https://core.telegram.org/method/chatlists/getExportedInvites for reference.
type ChatlistsGetExportedInvitesRequest struct {
	Chatlist *InputChatlistDialogFilter `json:"chatlist,omitempty"`
}

// ConstructorID returns the TL constructor identifier 0xce03da83.
func (v *ChatlistsGetExportedInvitesRequest) ConstructorID() uint32 {
	return ChatlistsGetExportedInvitesTypeID
}

// Encode serializes ChatlistsGetExportedInvitesRequest to a bytes.Buffer using the TL binary protocol.
func (v *ChatlistsGetExportedInvitesRequest) Encode(b *bytes.Buffer) error {
	WriteInt(b, ChatlistsGetExportedInvitesTypeID)
	EncodeTLObject(b, v.Chatlist)
	return nil
}

// ChatlistsGetExportedInvites invokes the chatlists.getExportedInvites RPC method on the server.
//
// Parameters:
//   - ctx: context for cancellation and timeout
//   - req: the request parameters
//
// Returns the result of the RPC call, or an error if the invocation fails.
func (c *RPCClient) ChatlistsGetExportedInvites(ctx context.Context, req *ChatlistsGetExportedInvitesRequest) (*ChatlistsExportedInvites, error) {
	result, err := c.invoke(ctx, req, func(r io.Reader) (TLObject, error) {
		return ReadTLObject(r)
	})
	if err != nil {
		return nil, err
	}
	if _c, _ok := result.(*ChatlistsExportedInvites); _ok {
		return _c, nil
	}
	return nil, fmt.Errorf("unexpected result type %T", result)
}

// ChatlistsCheckChatlistInviteTypeID is the constructor ID for the RPC function chatlists.checkChatlistInvite.
const ChatlistsCheckChatlistInviteTypeID = 0x41c10fff

// ChatlistsCheckChatlistInviteRequest represents TL type `chatlists.checkChatlistInvite#41c10fff`.
//
// See https://core.telegram.org/method/chatlists/checkChatlistInvite for reference.
type ChatlistsCheckChatlistInviteRequest struct {
	Slug string `json:"slug,omitempty"`
}

// ConstructorID returns the TL constructor identifier 0x41c10fff.
func (v *ChatlistsCheckChatlistInviteRequest) ConstructorID() uint32 {
	return ChatlistsCheckChatlistInviteTypeID
}

// Encode serializes ChatlistsCheckChatlistInviteRequest to a bytes.Buffer using the TL binary protocol.
func (v *ChatlistsCheckChatlistInviteRequest) Encode(b *bytes.Buffer) error {
	WriteInt(b, ChatlistsCheckChatlistInviteTypeID)
	WriteString(b, v.Slug)
	return nil
}

// ChatlistsCheckChatlistInvite invokes the chatlists.checkChatlistInvite RPC method on the server.
//
// Parameters:
//   - ctx: context for cancellation and timeout
//   - req: the request parameters
//
// Returns the result of the RPC call, or an error if the invocation fails.
func (c *RPCClient) ChatlistsCheckChatlistInvite(ctx context.Context, req *ChatlistsCheckChatlistInviteRequest) (ChatlistInviteClass, error) {
	result, err := c.invoke(ctx, req, func(r io.Reader) (TLObject, error) {
		return ReadTLObject(r)
	})
	if err != nil {
		return nil, err
	}
	if _c, _ok := result.(ChatlistInviteClass); _ok {
		return _c, nil
	}
	return nil, fmt.Errorf("unexpected result type %T", result)
}

// ChatlistsJoinChatlistInviteTypeID is the constructor ID for the RPC function chatlists.joinChatlistInvite.
const ChatlistsJoinChatlistInviteTypeID = 0xa6b1e39a

// ChatlistsJoinChatlistInviteRequest represents TL type `chatlists.joinChatlistInvite#a6b1e39a`.
//
// See https://core.telegram.org/method/chatlists/joinChatlistInvite for reference.
type ChatlistsJoinChatlistInviteRequest struct {
	Slug  string           `json:"slug,omitempty"`
	Peers []InputPeerClass `json:"peers,omitempty"`
}

// ConstructorID returns the TL constructor identifier 0xa6b1e39a.
func (v *ChatlistsJoinChatlistInviteRequest) ConstructorID() uint32 {
	return ChatlistsJoinChatlistInviteTypeID
}

// Encode serializes ChatlistsJoinChatlistInviteRequest to a bytes.Buffer using the TL binary protocol.
func (v *ChatlistsJoinChatlistInviteRequest) Encode(b *bytes.Buffer) error {
	WriteInt(b, ChatlistsJoinChatlistInviteTypeID)
	WriteString(b, v.Slug)
	WriteInt(b, 0x1cb5c415)
	WriteInt(b, uint32(len(v.Peers)))
	for _, _item := range v.Peers {
		EncodeTLObject(b, _item)
	}
	return nil
}

// ChatlistsJoinChatlistInvite invokes the chatlists.joinChatlistInvite RPC method on the server.
//
// Parameters:
//   - ctx: context for cancellation and timeout
//   - req: the request parameters
//
// Returns the result of the RPC call, or an error if the invocation fails.
func (c *RPCClient) ChatlistsJoinChatlistInvite(ctx context.Context, req *ChatlistsJoinChatlistInviteRequest) (UpdatesClass, error) {
	result, err := c.invoke(ctx, req, func(r io.Reader) (TLObject, error) {
		return ReadTLObject(r)
	})
	if err != nil {
		return nil, err
	}
	if _c, _ok := result.(UpdatesClass); _ok {
		return _c, nil
	}
	return nil, fmt.Errorf("unexpected result type %T", result)
}

// ChatlistsGetChatlistUpdatesTypeID is the constructor ID for the RPC function chatlists.getChatlistUpdates.
const ChatlistsGetChatlistUpdatesTypeID = 0x89419521

// ChatlistsGetChatlistUpdatesRequest represents TL type `chatlists.getChatlistUpdates#89419521`.
//
// See https://core.telegram.org/method/chatlists/getChatlistUpdates for reference.
type ChatlistsGetChatlistUpdatesRequest struct {
	Chatlist *InputChatlistDialogFilter `json:"chatlist,omitempty"`
}

// ConstructorID returns the TL constructor identifier 0x89419521.
func (v *ChatlistsGetChatlistUpdatesRequest) ConstructorID() uint32 {
	return ChatlistsGetChatlistUpdatesTypeID
}

// Encode serializes ChatlistsGetChatlistUpdatesRequest to a bytes.Buffer using the TL binary protocol.
func (v *ChatlistsGetChatlistUpdatesRequest) Encode(b *bytes.Buffer) error {
	WriteInt(b, ChatlistsGetChatlistUpdatesTypeID)
	EncodeTLObject(b, v.Chatlist)
	return nil
}

// ChatlistsGetChatlistUpdates invokes the chatlists.getChatlistUpdates RPC method on the server.
//
// Parameters:
//   - ctx: context for cancellation and timeout
//   - req: the request parameters
//
// Returns the result of the RPC call, or an error if the invocation fails.
func (c *RPCClient) ChatlistsGetChatlistUpdates(ctx context.Context, req *ChatlistsGetChatlistUpdatesRequest) (*ChatlistsChatlistUpdates, error) {
	result, err := c.invoke(ctx, req, func(r io.Reader) (TLObject, error) {
		return ReadTLObject(r)
	})
	if err != nil {
		return nil, err
	}
	if _c, _ok := result.(*ChatlistsChatlistUpdates); _ok {
		return _c, nil
	}
	return nil, fmt.Errorf("unexpected result type %T", result)
}

// ChatlistsJoinChatlistUpdatesTypeID is the constructor ID for the RPC function chatlists.joinChatlistUpdates.
const ChatlistsJoinChatlistUpdatesTypeID = 0xe089f8f5

// ChatlistsJoinChatlistUpdatesRequest represents TL type `chatlists.joinChatlistUpdates#e089f8f5`.
//
// See https://core.telegram.org/method/chatlists/joinChatlistUpdates for reference.
type ChatlistsJoinChatlistUpdatesRequest struct {
	Chatlist *InputChatlistDialogFilter `json:"chatlist,omitempty"`
	Peers    []InputPeerClass           `json:"peers,omitempty"`
}

// ConstructorID returns the TL constructor identifier 0xe089f8f5.
func (v *ChatlistsJoinChatlistUpdatesRequest) ConstructorID() uint32 {
	return ChatlistsJoinChatlistUpdatesTypeID
}

// Encode serializes ChatlistsJoinChatlistUpdatesRequest to a bytes.Buffer using the TL binary protocol.
func (v *ChatlistsJoinChatlistUpdatesRequest) Encode(b *bytes.Buffer) error {
	WriteInt(b, ChatlistsJoinChatlistUpdatesTypeID)
	EncodeTLObject(b, v.Chatlist)
	WriteInt(b, 0x1cb5c415)
	WriteInt(b, uint32(len(v.Peers)))
	for _, _item := range v.Peers {
		EncodeTLObject(b, _item)
	}
	return nil
}

// ChatlistsJoinChatlistUpdates invokes the chatlists.joinChatlistUpdates RPC method on the server.
//
// Parameters:
//   - ctx: context for cancellation and timeout
//   - req: the request parameters
//
// Returns the result of the RPC call, or an error if the invocation fails.
func (c *RPCClient) ChatlistsJoinChatlistUpdates(ctx context.Context, req *ChatlistsJoinChatlistUpdatesRequest) (UpdatesClass, error) {
	result, err := c.invoke(ctx, req, func(r io.Reader) (TLObject, error) {
		return ReadTLObject(r)
	})
	if err != nil {
		return nil, err
	}
	if _c, _ok := result.(UpdatesClass); _ok {
		return _c, nil
	}
	return nil, fmt.Errorf("unexpected result type %T", result)
}

// ChatlistsHideChatlistUpdatesTypeID is the constructor ID for the RPC function chatlists.hideChatlistUpdates.
const ChatlistsHideChatlistUpdatesTypeID = 0x66e486fb

// ChatlistsHideChatlistUpdatesRequest represents TL type `chatlists.hideChatlistUpdates#66e486fb`.
//
// See https://core.telegram.org/method/chatlists/hideChatlistUpdates for reference.
type ChatlistsHideChatlistUpdatesRequest struct {
	Chatlist *InputChatlistDialogFilter `json:"chatlist,omitempty"`
}

// ConstructorID returns the TL constructor identifier 0x66e486fb.
func (v *ChatlistsHideChatlistUpdatesRequest) ConstructorID() uint32 {
	return ChatlistsHideChatlistUpdatesTypeID
}

// Encode serializes ChatlistsHideChatlistUpdatesRequest to a bytes.Buffer using the TL binary protocol.
func (v *ChatlistsHideChatlistUpdatesRequest) Encode(b *bytes.Buffer) error {
	WriteInt(b, ChatlistsHideChatlistUpdatesTypeID)
	EncodeTLObject(b, v.Chatlist)
	return nil
}

// ChatlistsHideChatlistUpdates invokes the chatlists.hideChatlistUpdates RPC method on the server.
//
// Parameters:
//   - ctx: context for cancellation and timeout
//   - req: the request parameters
//
// Returns the result of the RPC call, or an error if the invocation fails.
func (c *RPCClient) ChatlistsHideChatlistUpdates(ctx context.Context, req *ChatlistsHideChatlistUpdatesRequest) (bool, error) {
	result, err := c.invoke(ctx, req, func(r io.Reader) (TLObject, error) {
		return ReadTLObject(r)
	})
	if err != nil {
		return false, err
	}
	_ = result
	return true, nil
}

// ChatlistsGetLeaveChatlistSuggestionsTypeID is the constructor ID for the RPC function chatlists.getLeaveChatlistSuggestions.
const ChatlistsGetLeaveChatlistSuggestionsTypeID = 0xfdbcd714

// ChatlistsGetLeaveChatlistSuggestionsRequest represents TL type `chatlists.getLeaveChatlistSuggestions#fdbcd714`.
//
// See https://core.telegram.org/method/chatlists/getLeaveChatlistSuggestions for reference.
type ChatlistsGetLeaveChatlistSuggestionsRequest struct {
	Chatlist *InputChatlistDialogFilter `json:"chatlist,omitempty"`
}

// ConstructorID returns the TL constructor identifier 0xfdbcd714.
func (v *ChatlistsGetLeaveChatlistSuggestionsRequest) ConstructorID() uint32 {
	return ChatlistsGetLeaveChatlistSuggestionsTypeID
}

// Encode serializes ChatlistsGetLeaveChatlistSuggestionsRequest to a bytes.Buffer using the TL binary protocol.
func (v *ChatlistsGetLeaveChatlistSuggestionsRequest) Encode(b *bytes.Buffer) error {
	WriteInt(b, ChatlistsGetLeaveChatlistSuggestionsTypeID)
	EncodeTLObject(b, v.Chatlist)
	return nil
}

// ChatlistsGetLeaveChatlistSuggestions invokes the chatlists.getLeaveChatlistSuggestions RPC method on the server.
//
// Parameters:
//   - ctx: context for cancellation and timeout
//   - req: the request parameters
//
// Returns the result of the RPC call, or an error if the invocation fails.
func (c *RPCClient) ChatlistsGetLeaveChatlistSuggestions(ctx context.Context, req *ChatlistsGetLeaveChatlistSuggestionsRequest) (TLObject, error) {
	result, err := c.invoke(ctx, req, func(r io.Reader) (TLObject, error) {
		return ReadTLObject(r)
	})
	if err != nil {
		return nil, err
	}
	return result, nil
}

// ChatlistsLeaveChatlistTypeID is the constructor ID for the RPC function chatlists.leaveChatlist.
const ChatlistsLeaveChatlistTypeID = 0x74fae13a

// ChatlistsLeaveChatlistRequest represents TL type `chatlists.leaveChatlist#74fae13a`.
//
// See https://core.telegram.org/method/chatlists/leaveChatlist for reference.
type ChatlistsLeaveChatlistRequest struct {
	Chatlist *InputChatlistDialogFilter `json:"chatlist,omitempty"`
	Peers    []InputPeerClass           `json:"peers,omitempty"`
}

// ConstructorID returns the TL constructor identifier 0x74fae13a.
func (v *ChatlistsLeaveChatlistRequest) ConstructorID() uint32 {
	return ChatlistsLeaveChatlistTypeID
}

// Encode serializes ChatlistsLeaveChatlistRequest to a bytes.Buffer using the TL binary protocol.
func (v *ChatlistsLeaveChatlistRequest) Encode(b *bytes.Buffer) error {
	WriteInt(b, ChatlistsLeaveChatlistTypeID)
	EncodeTLObject(b, v.Chatlist)
	WriteInt(b, 0x1cb5c415)
	WriteInt(b, uint32(len(v.Peers)))
	for _, _item := range v.Peers {
		EncodeTLObject(b, _item)
	}
	return nil
}

// ChatlistsLeaveChatlist invokes the chatlists.leaveChatlist RPC method on the server.
//
// Parameters:
//   - ctx: context for cancellation and timeout
//   - req: the request parameters
//
// Returns the result of the RPC call, or an error if the invocation fails.
func (c *RPCClient) ChatlistsLeaveChatlist(ctx context.Context, req *ChatlistsLeaveChatlistRequest) (UpdatesClass, error) {
	result, err := c.invoke(ctx, req, func(r io.Reader) (TLObject, error) {
		return ReadTLObject(r)
	})
	if err != nil {
		return nil, err
	}
	if _c, _ok := result.(UpdatesClass); _ok {
		return _c, nil
	}
	return nil, fmt.Errorf("unexpected result type %T", result)
}
