// Code generated by tlgen. DO NOT EDIT.

package tg

import (
	"bytes"
	"fmt"
)

// ContactsClass is the interface for TL type Contacts.
// Implementations must satisfy TLObject and are used to represent
// any constructor of the Contacts TL type.
type ContactsClass interface {
	TLObject
	isContacts()
}

// ContactsContactsNotModifiedTypeID is the constructor ID for TL type contacts.contactsNotModified.
const ContactsContactsNotModifiedTypeID = 0xb74ba9d2

// ContactsContactsTypeID is the constructor ID for TL type contacts.contacts.
const ContactsContactsTypeID = 0xeae87e42

// isContacts marks ContactsContactsNotModified as implementing the ContactsClass interface.
func (*ContactsContactsNotModified) isContacts() {}

// isContacts marks ContactsContacts as implementing the ContactsClass interface.
func (*ContactsContacts) isContacts() {}

// ContactsContactsNotModified represents the TL constructor contacts.contactsNotModified (0xb74ba9d2).
//
// See https://core.telegram.org/constructor/contacts.contactsNotModified for reference.
type ContactsContactsNotModified struct {
}

// ConstructorID returns the TL constructor identifier 0xb74ba9d2.
func (v *ContactsContactsNotModified) ConstructorID() uint32 {
	return ContactsContactsNotModifiedTypeID
}

// Encode serializes ContactsContactsNotModified to a bytes.Buffer using the TL binary protocol.
func (v *ContactsContactsNotModified) Encode(b *bytes.Buffer) error {
	WriteInt(b, ContactsContactsNotModifiedTypeID)
	return nil
}

// DecodeContactsContactsNotModified deserializes a ContactsContactsNotModified from a reader using the TL binary protocol.
func DecodeContactsContactsNotModified(r *Reader) (*ContactsContactsNotModified, error) {
	v := &ContactsContactsNotModified{}
	return v, nil
}

func init() {
	Registry[ContactsContactsNotModifiedTypeID] = func(r *Reader) (TLObject, error) {
		return DecodeContactsContactsNotModified(r)
	}
}

// ContactsContacts represents the TL constructor contacts.contacts (0xeae87e42).
//
// See https://core.telegram.org/constructor/contacts.contacts for reference.
type ContactsContacts struct {
	Contacts   []*Contact  `json:"contacts,omitempty"`
	SavedCount int32       `json:"saved_count,omitempty"`
	Users      []UserClass `json:"users,omitempty"`
}

// ConstructorID returns the TL constructor identifier 0xeae87e42.
func (v *ContactsContacts) ConstructorID() uint32 {
	return ContactsContactsTypeID
}

// Encode serializes ContactsContacts to a bytes.Buffer using the TL binary protocol.
func (v *ContactsContacts) Encode(b *bytes.Buffer) error {
	WriteInt(b, ContactsContactsTypeID)
	WriteInt(b, 0x1cb5c415)
	WriteInt(b, uint32(len(v.Contacts)))
	for _, _item := range v.Contacts {
		EncodeTLObject(b, _item)
	}
	WriteInt(b, uint32(v.SavedCount))
	WriteInt(b, 0x1cb5c415)
	WriteInt(b, uint32(len(v.Users)))
	for _, _item := range v.Users {
		EncodeTLObject(b, _item)
	}
	return nil
}

// DecodeContactsContacts deserializes a ContactsContacts from a reader using the TL binary protocol.
func DecodeContactsContacts(r *Reader) (*ContactsContacts, error) {
	v := &ContactsContacts{}
	_vhdrContacts, _ehdrContacts := r.ReadUint32()
	if _ehdrContacts != nil {
		return nil, _ehdrContacts
	}
	_cntContacts, _ecntContacts := r.ReadUint32()
	if _ecntContacts != nil {
		return nil, _ecntContacts
	}
	if _errContacts := checkVectorCount(_cntContacts); _errContacts != nil {
		return nil, _errContacts
	}
	v.Contacts = make([]*Contact, _cntContacts)
	for _iContacts := range v.Contacts {
		_objContacts, _errContacts := ReadTLObject(r)
		if _errContacts != nil {
			return nil, _errContacts
		}
		_cContacts, _okContacts := _objContacts.(*Contact)
		if !_okContacts {
			return nil, fmt.Errorf("decode: field contacts: unexpected type %T", _objContacts)
		}
		v.Contacts[_iContacts] = _cContacts
	}
	_ = _vhdrContacts
	_rSavedCount, _eSavedCount := r.ReadInt32()
	if _eSavedCount != nil {
		return nil, _eSavedCount
	}
	v.SavedCount = _rSavedCount
	_vhdrUsers, _ehdrUsers := r.ReadUint32()
	if _ehdrUsers != nil {
		return nil, _ehdrUsers
	}
	_cntUsers, _ecntUsers := r.ReadUint32()
	if _ecntUsers != nil {
		return nil, _ecntUsers
	}
	if _errUsers := checkVectorCount(_cntUsers); _errUsers != nil {
		return nil, _errUsers
	}
	v.Users = make([]UserClass, _cntUsers)
	for _iUsers := range v.Users {
		_objUsers, _errUsers := ReadTLObject(r)
		if _errUsers != nil {
			return nil, _errUsers
		}
		_cUsers, _okUsers := _objUsers.(UserClass)
		if !_okUsers {
			return nil, fmt.Errorf("decode: field users: unexpected type %T", _objUsers)
		}
		v.Users[_iUsers] = _cUsers
	}
	_ = _vhdrUsers
	return v, nil
}

func init() {
	Registry[ContactsContactsTypeID] = func(r *Reader) (TLObject, error) {
		return DecodeContactsContacts(r)
	}
}

// ContactsImportedContactsTypeID is the constructor ID for TL type contacts.importedContacts.
const ContactsImportedContactsTypeID = 0x77d01c3b

// ContactsImportedContacts represents the TL constructor contacts.importedContacts (0x77d01c3b).
//
// See https://core.telegram.org/constructor/contacts.importedContacts for reference.
type ContactsImportedContacts struct {
	Imported       []*ImportedContact `json:"imported,omitempty"`
	PopularInvites []*PopularContact  `json:"popular_invites,omitempty"`
	RetryContacts  []int64            `json:"retry_contacts,omitempty"`
	Users          []UserClass        `json:"users,omitempty"`
}

// ConstructorID returns the TL constructor identifier 0x77d01c3b.
func (v *ContactsImportedContacts) ConstructorID() uint32 {
	return ContactsImportedContactsTypeID
}

// Encode serializes ContactsImportedContacts to a bytes.Buffer using the TL binary protocol.
func (v *ContactsImportedContacts) Encode(b *bytes.Buffer) error {
	WriteInt(b, ContactsImportedContactsTypeID)
	WriteInt(b, 0x1cb5c415)
	WriteInt(b, uint32(len(v.Imported)))
	for _, _item := range v.Imported {
		EncodeTLObject(b, _item)
	}
	WriteInt(b, 0x1cb5c415)
	WriteInt(b, uint32(len(v.PopularInvites)))
	for _, _item := range v.PopularInvites {
		EncodeTLObject(b, _item)
	}
	WriteVectorLong(b, v.RetryContacts)
	WriteInt(b, 0x1cb5c415)
	WriteInt(b, uint32(len(v.Users)))
	for _, _item := range v.Users {
		EncodeTLObject(b, _item)
	}
	return nil
}

// DecodeContactsImportedContacts deserializes a ContactsImportedContacts from a reader using the TL binary protocol.
func DecodeContactsImportedContacts(r *Reader) (*ContactsImportedContacts, error) {
	v := &ContactsImportedContacts{}
	_vhdrImported, _ehdrImported := r.ReadUint32()
	if _ehdrImported != nil {
		return nil, _ehdrImported
	}
	_cntImported, _ecntImported := r.ReadUint32()
	if _ecntImported != nil {
		return nil, _ecntImported
	}
	if _errImported := checkVectorCount(_cntImported); _errImported != nil {
		return nil, _errImported
	}
	v.Imported = make([]*ImportedContact, _cntImported)
	for _iImported := range v.Imported {
		_objImported, _errImported := ReadTLObject(r)
		if _errImported != nil {
			return nil, _errImported
		}
		_cImported, _okImported := _objImported.(*ImportedContact)
		if !_okImported {
			return nil, fmt.Errorf("decode: field imported: unexpected type %T", _objImported)
		}
		v.Imported[_iImported] = _cImported
	}
	_ = _vhdrImported
	_vhdrPopularInvites, _ehdrPopularInvites := r.ReadUint32()
	if _ehdrPopularInvites != nil {
		return nil, _ehdrPopularInvites
	}
	_cntPopularInvites, _ecntPopularInvites := r.ReadUint32()
	if _ecntPopularInvites != nil {
		return nil, _ecntPopularInvites
	}
	if _errPopularInvites := checkVectorCount(_cntPopularInvites); _errPopularInvites != nil {
		return nil, _errPopularInvites
	}
	v.PopularInvites = make([]*PopularContact, _cntPopularInvites)
	for _iPopularInvites := range v.PopularInvites {
		_objPopularInvites, _errPopularInvites := ReadTLObject(r)
		if _errPopularInvites != nil {
			return nil, _errPopularInvites
		}
		_cPopularInvites, _okPopularInvites := _objPopularInvites.(*PopularContact)
		if !_okPopularInvites {
			return nil, fmt.Errorf("decode: field popular_invites: unexpected type %T", _objPopularInvites)
		}
		v.PopularInvites[_iPopularInvites] = _cPopularInvites
	}
	_ = _vhdrPopularInvites
	_vvRetryContacts, _veRetryContacts := r.ReadVectorLong()
	if _veRetryContacts != nil {
		return nil, _veRetryContacts
	}
	v.RetryContacts = _vvRetryContacts
	_vhdrUsers, _ehdrUsers := r.ReadUint32()
	if _ehdrUsers != nil {
		return nil, _ehdrUsers
	}
	_cntUsers, _ecntUsers := r.ReadUint32()
	if _ecntUsers != nil {
		return nil, _ecntUsers
	}
	if _errUsers := checkVectorCount(_cntUsers); _errUsers != nil {
		return nil, _errUsers
	}
	v.Users = make([]UserClass, _cntUsers)
	for _iUsers := range v.Users {
		_objUsers, _errUsers := ReadTLObject(r)
		if _errUsers != nil {
			return nil, _errUsers
		}
		_cUsers, _okUsers := _objUsers.(UserClass)
		if !_okUsers {
			return nil, fmt.Errorf("decode: field users: unexpected type %T", _objUsers)
		}
		v.Users[_iUsers] = _cUsers
	}
	_ = _vhdrUsers
	return v, nil
}

func init() {
	Registry[ContactsImportedContactsTypeID] = func(r *Reader) (TLObject, error) {
		return DecodeContactsImportedContacts(r)
	}
}

// BlockedClass is the interface for TL type Blocked.
// Implementations must satisfy TLObject and are used to represent
// any constructor of the Blocked TL type.
type BlockedClass interface {
	TLObject
	isBlocked()
}

// ContactsBlockedTypeID is the constructor ID for TL type contacts.blocked.
const ContactsBlockedTypeID = 0x0ade1591

// ContactsBlockedSliceTypeID is the constructor ID for TL type contacts.blockedSlice.
const ContactsBlockedSliceTypeID = 0xe1664194

// isBlocked marks ContactsBlocked as implementing the BlockedClass interface.
func (*ContactsBlocked) isBlocked() {}

// isBlocked marks ContactsBlockedSlice as implementing the BlockedClass interface.
func (*ContactsBlockedSlice) isBlocked() {}

// ContactsBlocked represents the TL constructor contacts.blocked (0x0ade1591).
//
// See https://core.telegram.org/constructor/contacts.blocked for reference.
type ContactsBlocked struct {
	Blocked []*PeerBlocked `json:"blocked,omitempty"`
	Chats   []ChatClass    `json:"chats,omitempty"`
	Users   []UserClass    `json:"users,omitempty"`
}

// ConstructorID returns the TL constructor identifier 0x0ade1591.
func (v *ContactsBlocked) ConstructorID() uint32 {
	return ContactsBlockedTypeID
}

// Encode serializes ContactsBlocked to a bytes.Buffer using the TL binary protocol.
func (v *ContactsBlocked) Encode(b *bytes.Buffer) error {
	WriteInt(b, ContactsBlockedTypeID)
	WriteInt(b, 0x1cb5c415)
	WriteInt(b, uint32(len(v.Blocked)))
	for _, _item := range v.Blocked {
		EncodeTLObject(b, _item)
	}
	WriteInt(b, 0x1cb5c415)
	WriteInt(b, uint32(len(v.Chats)))
	for _, _item := range v.Chats {
		EncodeTLObject(b, _item)
	}
	WriteInt(b, 0x1cb5c415)
	WriteInt(b, uint32(len(v.Users)))
	for _, _item := range v.Users {
		EncodeTLObject(b, _item)
	}
	return nil
}

// DecodeContactsBlocked deserializes a ContactsBlocked from a reader using the TL binary protocol.
func DecodeContactsBlocked(r *Reader) (*ContactsBlocked, error) {
	v := &ContactsBlocked{}
	_vhdrBlocked, _ehdrBlocked := r.ReadUint32()
	if _ehdrBlocked != nil {
		return nil, _ehdrBlocked
	}
	_cntBlocked, _ecntBlocked := r.ReadUint32()
	if _ecntBlocked != nil {
		return nil, _ecntBlocked
	}
	if _errBlocked := checkVectorCount(_cntBlocked); _errBlocked != nil {
		return nil, _errBlocked
	}
	v.Blocked = make([]*PeerBlocked, _cntBlocked)
	for _iBlocked := range v.Blocked {
		_objBlocked, _errBlocked := ReadTLObject(r)
		if _errBlocked != nil {
			return nil, _errBlocked
		}
		_cBlocked, _okBlocked := _objBlocked.(*PeerBlocked)
		if !_okBlocked {
			return nil, fmt.Errorf("decode: field blocked: unexpected type %T", _objBlocked)
		}
		v.Blocked[_iBlocked] = _cBlocked
	}
	_ = _vhdrBlocked
	_vhdrChats, _ehdrChats := r.ReadUint32()
	if _ehdrChats != nil {
		return nil, _ehdrChats
	}
	_cntChats, _ecntChats := r.ReadUint32()
	if _ecntChats != nil {
		return nil, _ecntChats
	}
	if _errChats := checkVectorCount(_cntChats); _errChats != nil {
		return nil, _errChats
	}
	v.Chats = make([]ChatClass, _cntChats)
	for _iChats := range v.Chats {
		_objChats, _errChats := ReadTLObject(r)
		if _errChats != nil {
			return nil, _errChats
		}
		_cChats, _okChats := _objChats.(ChatClass)
		if !_okChats {
			return nil, fmt.Errorf("decode: field chats: unexpected type %T", _objChats)
		}
		v.Chats[_iChats] = _cChats
	}
	_ = _vhdrChats
	_vhdrUsers, _ehdrUsers := r.ReadUint32()
	if _ehdrUsers != nil {
		return nil, _ehdrUsers
	}
	_cntUsers, _ecntUsers := r.ReadUint32()
	if _ecntUsers != nil {
		return nil, _ecntUsers
	}
	if _errUsers := checkVectorCount(_cntUsers); _errUsers != nil {
		return nil, _errUsers
	}
	v.Users = make([]UserClass, _cntUsers)
	for _iUsers := range v.Users {
		_objUsers, _errUsers := ReadTLObject(r)
		if _errUsers != nil {
			return nil, _errUsers
		}
		_cUsers, _okUsers := _objUsers.(UserClass)
		if !_okUsers {
			return nil, fmt.Errorf("decode: field users: unexpected type %T", _objUsers)
		}
		v.Users[_iUsers] = _cUsers
	}
	_ = _vhdrUsers
	return v, nil
}

func init() {
	Registry[ContactsBlockedTypeID] = func(r *Reader) (TLObject, error) {
		return DecodeContactsBlocked(r)
	}
}

// ContactsBlockedSlice represents the TL constructor contacts.blockedSlice (0xe1664194).
//
// See https://core.telegram.org/constructor/contacts.blockedSlice for reference.
type ContactsBlockedSlice struct {
	Count   int32          `json:"count,omitempty"`
	Blocked []*PeerBlocked `json:"blocked,omitempty"`
	Chats   []ChatClass    `json:"chats,omitempty"`
	Users   []UserClass    `json:"users,omitempty"`
}

// ConstructorID returns the TL constructor identifier 0xe1664194.
func (v *ContactsBlockedSlice) ConstructorID() uint32 {
	return ContactsBlockedSliceTypeID
}

// Encode serializes ContactsBlockedSlice to a bytes.Buffer using the TL binary protocol.
func (v *ContactsBlockedSlice) Encode(b *bytes.Buffer) error {
	WriteInt(b, ContactsBlockedSliceTypeID)
	WriteInt(b, uint32(v.Count))
	WriteInt(b, 0x1cb5c415)
	WriteInt(b, uint32(len(v.Blocked)))
	for _, _item := range v.Blocked {
		EncodeTLObject(b, _item)
	}
	WriteInt(b, 0x1cb5c415)
	WriteInt(b, uint32(len(v.Chats)))
	for _, _item := range v.Chats {
		EncodeTLObject(b, _item)
	}
	WriteInt(b, 0x1cb5c415)
	WriteInt(b, uint32(len(v.Users)))
	for _, _item := range v.Users {
		EncodeTLObject(b, _item)
	}
	return nil
}

// DecodeContactsBlockedSlice deserializes a ContactsBlockedSlice from a reader using the TL binary protocol.
func DecodeContactsBlockedSlice(r *Reader) (*ContactsBlockedSlice, error) {
	v := &ContactsBlockedSlice{}
	_rCount, _eCount := r.ReadInt32()
	if _eCount != nil {
		return nil, _eCount
	}
	v.Count = _rCount
	_vhdrBlocked, _ehdrBlocked := r.ReadUint32()
	if _ehdrBlocked != nil {
		return nil, _ehdrBlocked
	}
	_cntBlocked, _ecntBlocked := r.ReadUint32()
	if _ecntBlocked != nil {
		return nil, _ecntBlocked
	}
	if _errBlocked := checkVectorCount(_cntBlocked); _errBlocked != nil {
		return nil, _errBlocked
	}
	v.Blocked = make([]*PeerBlocked, _cntBlocked)
	for _iBlocked := range v.Blocked {
		_objBlocked, _errBlocked := ReadTLObject(r)
		if _errBlocked != nil {
			return nil, _errBlocked
		}
		_cBlocked, _okBlocked := _objBlocked.(*PeerBlocked)
		if !_okBlocked {
			return nil, fmt.Errorf("decode: field blocked: unexpected type %T", _objBlocked)
		}
		v.Blocked[_iBlocked] = _cBlocked
	}
	_ = _vhdrBlocked
	_vhdrChats, _ehdrChats := r.ReadUint32()
	if _ehdrChats != nil {
		return nil, _ehdrChats
	}
	_cntChats, _ecntChats := r.ReadUint32()
	if _ecntChats != nil {
		return nil, _ecntChats
	}
	if _errChats := checkVectorCount(_cntChats); _errChats != nil {
		return nil, _errChats
	}
	v.Chats = make([]ChatClass, _cntChats)
	for _iChats := range v.Chats {
		_objChats, _errChats := ReadTLObject(r)
		if _errChats != nil {
			return nil, _errChats
		}
		_cChats, _okChats := _objChats.(ChatClass)
		if !_okChats {
			return nil, fmt.Errorf("decode: field chats: unexpected type %T", _objChats)
		}
		v.Chats[_iChats] = _cChats
	}
	_ = _vhdrChats
	_vhdrUsers, _ehdrUsers := r.ReadUint32()
	if _ehdrUsers != nil {
		return nil, _ehdrUsers
	}
	_cntUsers, _ecntUsers := r.ReadUint32()
	if _ecntUsers != nil {
		return nil, _ecntUsers
	}
	if _errUsers := checkVectorCount(_cntUsers); _errUsers != nil {
		return nil, _errUsers
	}
	v.Users = make([]UserClass, _cntUsers)
	for _iUsers := range v.Users {
		_objUsers, _errUsers := ReadTLObject(r)
		if _errUsers != nil {
			return nil, _errUsers
		}
		_cUsers, _okUsers := _objUsers.(UserClass)
		if !_okUsers {
			return nil, fmt.Errorf("decode: field users: unexpected type %T", _objUsers)
		}
		v.Users[_iUsers] = _cUsers
	}
	_ = _vhdrUsers
	return v, nil
}

func init() {
	Registry[ContactsBlockedSliceTypeID] = func(r *Reader) (TLObject, error) {
		return DecodeContactsBlockedSlice(r)
	}
}

// ContactsFoundTypeID is the constructor ID for TL type contacts.found.
const ContactsFoundTypeID = 0xb3134d9d

// ContactsFound represents the TL constructor contacts.found (0xb3134d9d).
//
// See https://core.telegram.org/constructor/contacts.found for reference.
type ContactsFound struct {
	MyResults []PeerClass `json:"my_results,omitempty"`
	Results   []PeerClass `json:"results,omitempty"`
	Chats     []ChatClass `json:"chats,omitempty"`
	Users     []UserClass `json:"users,omitempty"`
}

// ConstructorID returns the TL constructor identifier 0xb3134d9d.
func (v *ContactsFound) ConstructorID() uint32 {
	return ContactsFoundTypeID
}

// Encode serializes ContactsFound to a bytes.Buffer using the TL binary protocol.
func (v *ContactsFound) Encode(b *bytes.Buffer) error {
	WriteInt(b, ContactsFoundTypeID)
	WriteInt(b, 0x1cb5c415)
	WriteInt(b, uint32(len(v.MyResults)))
	for _, _item := range v.MyResults {
		EncodeTLObject(b, _item)
	}
	WriteInt(b, 0x1cb5c415)
	WriteInt(b, uint32(len(v.Results)))
	for _, _item := range v.Results {
		EncodeTLObject(b, _item)
	}
	WriteInt(b, 0x1cb5c415)
	WriteInt(b, uint32(len(v.Chats)))
	for _, _item := range v.Chats {
		EncodeTLObject(b, _item)
	}
	WriteInt(b, 0x1cb5c415)
	WriteInt(b, uint32(len(v.Users)))
	for _, _item := range v.Users {
		EncodeTLObject(b, _item)
	}
	return nil
}

// DecodeContactsFound deserializes a ContactsFound from a reader using the TL binary protocol.
func DecodeContactsFound(r *Reader) (*ContactsFound, error) {
	v := &ContactsFound{}
	_vhdrMyResults, _ehdrMyResults := r.ReadUint32()
	if _ehdrMyResults != nil {
		return nil, _ehdrMyResults
	}
	_cntMyResults, _ecntMyResults := r.ReadUint32()
	if _ecntMyResults != nil {
		return nil, _ecntMyResults
	}
	if _errMyResults := checkVectorCount(_cntMyResults); _errMyResults != nil {
		return nil, _errMyResults
	}
	v.MyResults = make([]PeerClass, _cntMyResults)
	for _iMyResults := range v.MyResults {
		_objMyResults, _errMyResults := ReadTLObject(r)
		if _errMyResults != nil {
			return nil, _errMyResults
		}
		_cMyResults, _okMyResults := _objMyResults.(PeerClass)
		if !_okMyResults {
			return nil, fmt.Errorf("decode: field my_results: unexpected type %T", _objMyResults)
		}
		v.MyResults[_iMyResults] = _cMyResults
	}
	_ = _vhdrMyResults
	_vhdrResults, _ehdrResults := r.ReadUint32()
	if _ehdrResults != nil {
		return nil, _ehdrResults
	}
	_cntResults, _ecntResults := r.ReadUint32()
	if _ecntResults != nil {
		return nil, _ecntResults
	}
	if _errResults := checkVectorCount(_cntResults); _errResults != nil {
		return nil, _errResults
	}
	v.Results = make([]PeerClass, _cntResults)
	for _iResults := range v.Results {
		_objResults, _errResults := ReadTLObject(r)
		if _errResults != nil {
			return nil, _errResults
		}
		_cResults, _okResults := _objResults.(PeerClass)
		if !_okResults {
			return nil, fmt.Errorf("decode: field results: unexpected type %T", _objResults)
		}
		v.Results[_iResults] = _cResults
	}
	_ = _vhdrResults
	_vhdrChats, _ehdrChats := r.ReadUint32()
	if _ehdrChats != nil {
		return nil, _ehdrChats
	}
	_cntChats, _ecntChats := r.ReadUint32()
	if _ecntChats != nil {
		return nil, _ecntChats
	}
	if _errChats := checkVectorCount(_cntChats); _errChats != nil {
		return nil, _errChats
	}
	v.Chats = make([]ChatClass, _cntChats)
	for _iChats := range v.Chats {
		_objChats, _errChats := ReadTLObject(r)
		if _errChats != nil {
			return nil, _errChats
		}
		_cChats, _okChats := _objChats.(ChatClass)
		if !_okChats {
			return nil, fmt.Errorf("decode: field chats: unexpected type %T", _objChats)
		}
		v.Chats[_iChats] = _cChats
	}
	_ = _vhdrChats
	_vhdrUsers, _ehdrUsers := r.ReadUint32()
	if _ehdrUsers != nil {
		return nil, _ehdrUsers
	}
	_cntUsers, _ecntUsers := r.ReadUint32()
	if _ecntUsers != nil {
		return nil, _ecntUsers
	}
	if _errUsers := checkVectorCount(_cntUsers); _errUsers != nil {
		return nil, _errUsers
	}
	v.Users = make([]UserClass, _cntUsers)
	for _iUsers := range v.Users {
		_objUsers, _errUsers := ReadTLObject(r)
		if _errUsers != nil {
			return nil, _errUsers
		}
		_cUsers, _okUsers := _objUsers.(UserClass)
		if !_okUsers {
			return nil, fmt.Errorf("decode: field users: unexpected type %T", _objUsers)
		}
		v.Users[_iUsers] = _cUsers
	}
	_ = _vhdrUsers
	return v, nil
}

func init() {
	Registry[ContactsFoundTypeID] = func(r *Reader) (TLObject, error) {
		return DecodeContactsFound(r)
	}
}

// ContactsResolvedPeerTypeID is the constructor ID for TL type contacts.resolvedPeer.
const ContactsResolvedPeerTypeID = 0x7f077ad9

// ContactsResolvedPeer represents the TL constructor contacts.resolvedPeer (0x7f077ad9).
//
// See https://core.telegram.org/constructor/contacts.resolvedPeer for reference.
type ContactsResolvedPeer struct {
	Peer  PeerClass   `json:"peer,omitempty"`
	Chats []ChatClass `json:"chats,omitempty"`
	Users []UserClass `json:"users,omitempty"`
}

// ConstructorID returns the TL constructor identifier 0x7f077ad9.
func (v *ContactsResolvedPeer) ConstructorID() uint32 {
	return ContactsResolvedPeerTypeID
}

// Encode serializes ContactsResolvedPeer to a bytes.Buffer using the TL binary protocol.
func (v *ContactsResolvedPeer) Encode(b *bytes.Buffer) error {
	WriteInt(b, ContactsResolvedPeerTypeID)
	EncodeTLObject(b, v.Peer)
	WriteInt(b, 0x1cb5c415)
	WriteInt(b, uint32(len(v.Chats)))
	for _, _item := range v.Chats {
		EncodeTLObject(b, _item)
	}
	WriteInt(b, 0x1cb5c415)
	WriteInt(b, uint32(len(v.Users)))
	for _, _item := range v.Users {
		EncodeTLObject(b, _item)
	}
	return nil
}

// DecodeContactsResolvedPeer deserializes a ContactsResolvedPeer from a reader using the TL binary protocol.
func DecodeContactsResolvedPeer(r *Reader) (*ContactsResolvedPeer, error) {
	v := &ContactsResolvedPeer{}
	_objPeer, _errPeer := ReadTLObject(r)
	if _errPeer != nil {
		return nil, _errPeer
	}
	_cPeer, _okPeer := _objPeer.(PeerClass)
	if !_okPeer {
		return nil, fmt.Errorf("decode: field peer: unexpected type %T", _objPeer)
	}
	v.Peer = _cPeer
	_vhdrChats, _ehdrChats := r.ReadUint32()
	if _ehdrChats != nil {
		return nil, _ehdrChats
	}
	_cntChats, _ecntChats := r.ReadUint32()
	if _ecntChats != nil {
		return nil, _ecntChats
	}
	if _errChats := checkVectorCount(_cntChats); _errChats != nil {
		return nil, _errChats
	}
	v.Chats = make([]ChatClass, _cntChats)
	for _iChats := range v.Chats {
		_objChats, _errChats := ReadTLObject(r)
		if _errChats != nil {
			return nil, _errChats
		}
		_cChats, _okChats := _objChats.(ChatClass)
		if !_okChats {
			return nil, fmt.Errorf("decode: field chats: unexpected type %T", _objChats)
		}
		v.Chats[_iChats] = _cChats
	}
	_ = _vhdrChats
	_vhdrUsers, _ehdrUsers := r.ReadUint32()
	if _ehdrUsers != nil {
		return nil, _ehdrUsers
	}
	_cntUsers, _ecntUsers := r.ReadUint32()
	if _ecntUsers != nil {
		return nil, _ecntUsers
	}
	if _errUsers := checkVectorCount(_cntUsers); _errUsers != nil {
		return nil, _errUsers
	}
	v.Users = make([]UserClass, _cntUsers)
	for _iUsers := range v.Users {
		_objUsers, _errUsers := ReadTLObject(r)
		if _errUsers != nil {
			return nil, _errUsers
		}
		_cUsers, _okUsers := _objUsers.(UserClass)
		if !_okUsers {
			return nil, fmt.Errorf("decode: field users: unexpected type %T", _objUsers)
		}
		v.Users[_iUsers] = _cUsers
	}
	_ = _vhdrUsers
	return v, nil
}

func init() {
	Registry[ContactsResolvedPeerTypeID] = func(r *Reader) (TLObject, error) {
		return DecodeContactsResolvedPeer(r)
	}
}

// TopPeersClass is the interface for TL type TopPeers.
// Implementations must satisfy TLObject and are used to represent
// any constructor of the TopPeers TL type.
type TopPeersClass interface {
	TLObject
	isTopPeers()
}

// ContactsTopPeersNotModifiedTypeID is the constructor ID for TL type contacts.topPeersNotModified.
const ContactsTopPeersNotModifiedTypeID = 0xde266ef5

// ContactsTopPeersTypeID is the constructor ID for TL type contacts.topPeers.
const ContactsTopPeersTypeID = 0x70b772a8

// ContactsTopPeersDisabledTypeID is the constructor ID for TL type contacts.topPeersDisabled.
const ContactsTopPeersDisabledTypeID = 0xb52c939d

// isTopPeers marks ContactsTopPeersNotModified as implementing the TopPeersClass interface.
func (*ContactsTopPeersNotModified) isTopPeers() {}

// isTopPeers marks ContactsTopPeers as implementing the TopPeersClass interface.
func (*ContactsTopPeers) isTopPeers() {}

// isTopPeers marks ContactsTopPeersDisabled as implementing the TopPeersClass interface.
func (*ContactsTopPeersDisabled) isTopPeers() {}

// ContactsTopPeersNotModified represents the TL constructor contacts.topPeersNotModified (0xde266ef5).
//
// See https://core.telegram.org/constructor/contacts.topPeersNotModified for reference.
type ContactsTopPeersNotModified struct {
}

// ConstructorID returns the TL constructor identifier 0xde266ef5.
func (v *ContactsTopPeersNotModified) ConstructorID() uint32 {
	return ContactsTopPeersNotModifiedTypeID
}

// Encode serializes ContactsTopPeersNotModified to a bytes.Buffer using the TL binary protocol.
func (v *ContactsTopPeersNotModified) Encode(b *bytes.Buffer) error {
	WriteInt(b, ContactsTopPeersNotModifiedTypeID)
	return nil
}

// DecodeContactsTopPeersNotModified deserializes a ContactsTopPeersNotModified from a reader using the TL binary protocol.
func DecodeContactsTopPeersNotModified(r *Reader) (*ContactsTopPeersNotModified, error) {
	v := &ContactsTopPeersNotModified{}
	return v, nil
}

func init() {
	Registry[ContactsTopPeersNotModifiedTypeID] = func(r *Reader) (TLObject, error) {
		return DecodeContactsTopPeersNotModified(r)
	}
}

// ContactsTopPeers represents the TL constructor contacts.topPeers (0x70b772a8).
//
// See https://core.telegram.org/constructor/contacts.topPeers for reference.
type ContactsTopPeers struct {
	Categories []*TopPeerCategoryPeers `json:"categories,omitempty"`
	Chats      []ChatClass             `json:"chats,omitempty"`
	Users      []UserClass             `json:"users,omitempty"`
}

// ConstructorID returns the TL constructor identifier 0x70b772a8.
func (v *ContactsTopPeers) ConstructorID() uint32 {
	return ContactsTopPeersTypeID
}

// Encode serializes ContactsTopPeers to a bytes.Buffer using the TL binary protocol.
func (v *ContactsTopPeers) Encode(b *bytes.Buffer) error {
	WriteInt(b, ContactsTopPeersTypeID)
	WriteInt(b, 0x1cb5c415)
	WriteInt(b, uint32(len(v.Categories)))
	for _, _item := range v.Categories {
		EncodeTLObject(b, _item)
	}
	WriteInt(b, 0x1cb5c415)
	WriteInt(b, uint32(len(v.Chats)))
	for _, _item := range v.Chats {
		EncodeTLObject(b, _item)
	}
	WriteInt(b, 0x1cb5c415)
	WriteInt(b, uint32(len(v.Users)))
	for _, _item := range v.Users {
		EncodeTLObject(b, _item)
	}
	return nil
}

// DecodeContactsTopPeers deserializes a ContactsTopPeers from a reader using the TL binary protocol.
func DecodeContactsTopPeers(r *Reader) (*ContactsTopPeers, error) {
	v := &ContactsTopPeers{}
	_vhdrCategories, _ehdrCategories := r.ReadUint32()
	if _ehdrCategories != nil {
		return nil, _ehdrCategories
	}
	_cntCategories, _ecntCategories := r.ReadUint32()
	if _ecntCategories != nil {
		return nil, _ecntCategories
	}
	if _errCategories := checkVectorCount(_cntCategories); _errCategories != nil {
		return nil, _errCategories
	}
	v.Categories = make([]*TopPeerCategoryPeers, _cntCategories)
	for _iCategories := range v.Categories {
		_objCategories, _errCategories := ReadTLObject(r)
		if _errCategories != nil {
			return nil, _errCategories
		}
		_cCategories, _okCategories := _objCategories.(*TopPeerCategoryPeers)
		if !_okCategories {
			return nil, fmt.Errorf("decode: field categories: unexpected type %T", _objCategories)
		}
		v.Categories[_iCategories] = _cCategories
	}
	_ = _vhdrCategories
	_vhdrChats, _ehdrChats := r.ReadUint32()
	if _ehdrChats != nil {
		return nil, _ehdrChats
	}
	_cntChats, _ecntChats := r.ReadUint32()
	if _ecntChats != nil {
		return nil, _ecntChats
	}
	if _errChats := checkVectorCount(_cntChats); _errChats != nil {
		return nil, _errChats
	}
	v.Chats = make([]ChatClass, _cntChats)
	for _iChats := range v.Chats {
		_objChats, _errChats := ReadTLObject(r)
		if _errChats != nil {
			return nil, _errChats
		}
		_cChats, _okChats := _objChats.(ChatClass)
		if !_okChats {
			return nil, fmt.Errorf("decode: field chats: unexpected type %T", _objChats)
		}
		v.Chats[_iChats] = _cChats
	}
	_ = _vhdrChats
	_vhdrUsers, _ehdrUsers := r.ReadUint32()
	if _ehdrUsers != nil {
		return nil, _ehdrUsers
	}
	_cntUsers, _ecntUsers := r.ReadUint32()
	if _ecntUsers != nil {
		return nil, _ecntUsers
	}
	if _errUsers := checkVectorCount(_cntUsers); _errUsers != nil {
		return nil, _errUsers
	}
	v.Users = make([]UserClass, _cntUsers)
	for _iUsers := range v.Users {
		_objUsers, _errUsers := ReadTLObject(r)
		if _errUsers != nil {
			return nil, _errUsers
		}
		_cUsers, _okUsers := _objUsers.(UserClass)
		if !_okUsers {
			return nil, fmt.Errorf("decode: field users: unexpected type %T", _objUsers)
		}
		v.Users[_iUsers] = _cUsers
	}
	_ = _vhdrUsers
	return v, nil
}

func init() {
	Registry[ContactsTopPeersTypeID] = func(r *Reader) (TLObject, error) {
		return DecodeContactsTopPeers(r)
	}
}

// ContactsTopPeersDisabled represents the TL constructor contacts.topPeersDisabled (0xb52c939d).
//
// See https://core.telegram.org/constructor/contacts.topPeersDisabled for reference.
type ContactsTopPeersDisabled struct {
}

// ConstructorID returns the TL constructor identifier 0xb52c939d.
func (v *ContactsTopPeersDisabled) ConstructorID() uint32 {
	return ContactsTopPeersDisabledTypeID
}

// Encode serializes ContactsTopPeersDisabled to a bytes.Buffer using the TL binary protocol.
func (v *ContactsTopPeersDisabled) Encode(b *bytes.Buffer) error {
	WriteInt(b, ContactsTopPeersDisabledTypeID)
	return nil
}

// DecodeContactsTopPeersDisabled deserializes a ContactsTopPeersDisabled from a reader using the TL binary protocol.
func DecodeContactsTopPeersDisabled(r *Reader) (*ContactsTopPeersDisabled, error) {
	v := &ContactsTopPeersDisabled{}
	return v, nil
}

func init() {
	Registry[ContactsTopPeersDisabledTypeID] = func(r *Reader) (TLObject, error) {
		return DecodeContactsTopPeersDisabled(r)
	}
}

// ContactsContactBirthdaysTypeID is the constructor ID for TL type contacts.contactBirthdays.
const ContactsContactBirthdaysTypeID = 0x114ff30d

// ContactsContactBirthdays represents the TL constructor contacts.contactBirthdays (0x114ff30d).
//
// See https://core.telegram.org/constructor/contacts.contactBirthdays for reference.
type ContactsContactBirthdays struct {
	Contacts []*ContactBirthday `json:"contacts,omitempty"`
	Users    []UserClass        `json:"users,omitempty"`
}

// ConstructorID returns the TL constructor identifier 0x114ff30d.
func (v *ContactsContactBirthdays) ConstructorID() uint32 {
	return ContactsContactBirthdaysTypeID
}

// Encode serializes ContactsContactBirthdays to a bytes.Buffer using the TL binary protocol.
func (v *ContactsContactBirthdays) Encode(b *bytes.Buffer) error {
	WriteInt(b, ContactsContactBirthdaysTypeID)
	WriteInt(b, 0x1cb5c415)
	WriteInt(b, uint32(len(v.Contacts)))
	for _, _item := range v.Contacts {
		EncodeTLObject(b, _item)
	}
	WriteInt(b, 0x1cb5c415)
	WriteInt(b, uint32(len(v.Users)))
	for _, _item := range v.Users {
		EncodeTLObject(b, _item)
	}
	return nil
}

// DecodeContactsContactBirthdays deserializes a ContactsContactBirthdays from a reader using the TL binary protocol.
func DecodeContactsContactBirthdays(r *Reader) (*ContactsContactBirthdays, error) {
	v := &ContactsContactBirthdays{}
	_vhdrContacts, _ehdrContacts := r.ReadUint32()
	if _ehdrContacts != nil {
		return nil, _ehdrContacts
	}
	_cntContacts, _ecntContacts := r.ReadUint32()
	if _ecntContacts != nil {
		return nil, _ecntContacts
	}
	if _errContacts := checkVectorCount(_cntContacts); _errContacts != nil {
		return nil, _errContacts
	}
	v.Contacts = make([]*ContactBirthday, _cntContacts)
	for _iContacts := range v.Contacts {
		_objContacts, _errContacts := ReadTLObject(r)
		if _errContacts != nil {
			return nil, _errContacts
		}
		_cContacts, _okContacts := _objContacts.(*ContactBirthday)
		if !_okContacts {
			return nil, fmt.Errorf("decode: field contacts: unexpected type %T", _objContacts)
		}
		v.Contacts[_iContacts] = _cContacts
	}
	_ = _vhdrContacts
	_vhdrUsers, _ehdrUsers := r.ReadUint32()
	if _ehdrUsers != nil {
		return nil, _ehdrUsers
	}
	_cntUsers, _ecntUsers := r.ReadUint32()
	if _ecntUsers != nil {
		return nil, _ecntUsers
	}
	if _errUsers := checkVectorCount(_cntUsers); _errUsers != nil {
		return nil, _errUsers
	}
	v.Users = make([]UserClass, _cntUsers)
	for _iUsers := range v.Users {
		_objUsers, _errUsers := ReadTLObject(r)
		if _errUsers != nil {
			return nil, _errUsers
		}
		_cUsers, _okUsers := _objUsers.(UserClass)
		if !_okUsers {
			return nil, fmt.Errorf("decode: field users: unexpected type %T", _objUsers)
		}
		v.Users[_iUsers] = _cUsers
	}
	_ = _vhdrUsers
	return v, nil
}

func init() {
	Registry[ContactsContactBirthdaysTypeID] = func(r *Reader) (TLObject, error) {
		return DecodeContactsContactBirthdays(r)
	}
}

// SponsoredPeersClass is the interface for TL type SponsoredPeers.
// Implementations must satisfy TLObject and are used to represent
// any constructor of the SponsoredPeers TL type.
type SponsoredPeersClass interface {
	TLObject
	isSponsoredPeers()
}

// ContactsSponsoredPeersEmptyTypeID is the constructor ID for TL type contacts.sponsoredPeersEmpty.
const ContactsSponsoredPeersEmptyTypeID = 0xea32b4b1

// ContactsSponsoredPeersTypeID is the constructor ID for TL type contacts.sponsoredPeers.
const ContactsSponsoredPeersTypeID = 0xeb032884

// isSponsoredPeers marks ContactsSponsoredPeersEmpty as implementing the SponsoredPeersClass interface.
func (*ContactsSponsoredPeersEmpty) isSponsoredPeers() {}

// isSponsoredPeers marks ContactsSponsoredPeers as implementing the SponsoredPeersClass interface.
func (*ContactsSponsoredPeers) isSponsoredPeers() {}

// ContactsSponsoredPeersEmpty represents the TL constructor contacts.sponsoredPeersEmpty (0xea32b4b1).
//
// See https://core.telegram.org/constructor/contacts.sponsoredPeersEmpty for reference.
type ContactsSponsoredPeersEmpty struct {
}

// ConstructorID returns the TL constructor identifier 0xea32b4b1.
func (v *ContactsSponsoredPeersEmpty) ConstructorID() uint32 {
	return ContactsSponsoredPeersEmptyTypeID
}

// Encode serializes ContactsSponsoredPeersEmpty to a bytes.Buffer using the TL binary protocol.
func (v *ContactsSponsoredPeersEmpty) Encode(b *bytes.Buffer) error {
	WriteInt(b, ContactsSponsoredPeersEmptyTypeID)
	return nil
}

// DecodeContactsSponsoredPeersEmpty deserializes a ContactsSponsoredPeersEmpty from a reader using the TL binary protocol.
func DecodeContactsSponsoredPeersEmpty(r *Reader) (*ContactsSponsoredPeersEmpty, error) {
	v := &ContactsSponsoredPeersEmpty{}
	return v, nil
}

func init() {
	Registry[ContactsSponsoredPeersEmptyTypeID] = func(r *Reader) (TLObject, error) {
		return DecodeContactsSponsoredPeersEmpty(r)
	}
}

// ContactsSponsoredPeers represents the TL constructor contacts.sponsoredPeers (0xeb032884).
//
// See https://core.telegram.org/constructor/contacts.sponsoredPeers for reference.
type ContactsSponsoredPeers struct {
	Peers []*SponsoredPeer `json:"peers,omitempty"`
	Chats []ChatClass      `json:"chats,omitempty"`
	Users []UserClass      `json:"users,omitempty"`
}

// ConstructorID returns the TL constructor identifier 0xeb032884.
func (v *ContactsSponsoredPeers) ConstructorID() uint32 {
	return ContactsSponsoredPeersTypeID
}

// Encode serializes ContactsSponsoredPeers to a bytes.Buffer using the TL binary protocol.
func (v *ContactsSponsoredPeers) Encode(b *bytes.Buffer) error {
	WriteInt(b, ContactsSponsoredPeersTypeID)
	WriteInt(b, 0x1cb5c415)
	WriteInt(b, uint32(len(v.Peers)))
	for _, _item := range v.Peers {
		EncodeTLObject(b, _item)
	}
	WriteInt(b, 0x1cb5c415)
	WriteInt(b, uint32(len(v.Chats)))
	for _, _item := range v.Chats {
		EncodeTLObject(b, _item)
	}
	WriteInt(b, 0x1cb5c415)
	WriteInt(b, uint32(len(v.Users)))
	for _, _item := range v.Users {
		EncodeTLObject(b, _item)
	}
	return nil
}

// DecodeContactsSponsoredPeers deserializes a ContactsSponsoredPeers from a reader using the TL binary protocol.
func DecodeContactsSponsoredPeers(r *Reader) (*ContactsSponsoredPeers, error) {
	v := &ContactsSponsoredPeers{}
	_vhdrPeers, _ehdrPeers := r.ReadUint32()
	if _ehdrPeers != nil {
		return nil, _ehdrPeers
	}
	_cntPeers, _ecntPeers := r.ReadUint32()
	if _ecntPeers != nil {
		return nil, _ecntPeers
	}
	if _errPeers := checkVectorCount(_cntPeers); _errPeers != nil {
		return nil, _errPeers
	}
	v.Peers = make([]*SponsoredPeer, _cntPeers)
	for _iPeers := range v.Peers {
		_objPeers, _errPeers := ReadTLObject(r)
		if _errPeers != nil {
			return nil, _errPeers
		}
		_cPeers, _okPeers := _objPeers.(*SponsoredPeer)
		if !_okPeers {
			return nil, fmt.Errorf("decode: field peers: unexpected type %T", _objPeers)
		}
		v.Peers[_iPeers] = _cPeers
	}
	_ = _vhdrPeers
	_vhdrChats, _ehdrChats := r.ReadUint32()
	if _ehdrChats != nil {
		return nil, _ehdrChats
	}
	_cntChats, _ecntChats := r.ReadUint32()
	if _ecntChats != nil {
		return nil, _ecntChats
	}
	if _errChats := checkVectorCount(_cntChats); _errChats != nil {
		return nil, _errChats
	}
	v.Chats = make([]ChatClass, _cntChats)
	for _iChats := range v.Chats {
		_objChats, _errChats := ReadTLObject(r)
		if _errChats != nil {
			return nil, _errChats
		}
		_cChats, _okChats := _objChats.(ChatClass)
		if !_okChats {
			return nil, fmt.Errorf("decode: field chats: unexpected type %T", _objChats)
		}
		v.Chats[_iChats] = _cChats
	}
	_ = _vhdrChats
	_vhdrUsers, _ehdrUsers := r.ReadUint32()
	if _ehdrUsers != nil {
		return nil, _ehdrUsers
	}
	_cntUsers, _ecntUsers := r.ReadUint32()
	if _ecntUsers != nil {
		return nil, _ecntUsers
	}
	if _errUsers := checkVectorCount(_cntUsers); _errUsers != nil {
		return nil, _errUsers
	}
	v.Users = make([]UserClass, _cntUsers)
	for _iUsers := range v.Users {
		_objUsers, _errUsers := ReadTLObject(r)
		if _errUsers != nil {
			return nil, _errUsers
		}
		_cUsers, _okUsers := _objUsers.(UserClass)
		if !_okUsers {
			return nil, fmt.Errorf("decode: field users: unexpected type %T", _objUsers)
		}
		v.Users[_iUsers] = _cUsers
	}
	_ = _vhdrUsers
	return v, nil
}

func init() {
	Registry[ContactsSponsoredPeersTypeID] = func(r *Reader) (TLObject, error) {
		return DecodeContactsSponsoredPeers(r)
	}
}
