// Code generated by tlgen. DO NOT EDIT.

package tg

import (
	"bytes"
	"context"
	"fmt"
)

// FragmentGetCollectibleInfoTypeID is the constructor ID for the RPC function fragment.getCollectibleInfo.
const FragmentGetCollectibleInfoTypeID = 0xbe1e85ba

// FragmentGetCollectibleInfoRequest represents TL type `fragment.getCollectibleInfo#be1e85ba`.
//
// See https://core.telegram.org/method/fragment/getCollectibleInfo for reference.
type FragmentGetCollectibleInfoRequest struct {
	Collectible InputCollectibleClass `json:"collectible,omitempty"`
}

// ConstructorID returns the TL constructor identifier 0xbe1e85ba.
func (v *FragmentGetCollectibleInfoRequest) ConstructorID() uint32 {
	return FragmentGetCollectibleInfoTypeID
}

// Encode serializes FragmentGetCollectibleInfoRequest to a bytes.Buffer using the TL binary protocol.
func (v *FragmentGetCollectibleInfoRequest) Encode(b *bytes.Buffer) error {
	WriteInt(b, FragmentGetCollectibleInfoTypeID)
	EncodeTLObject(b, v.Collectible)
	return nil
}

// FragmentGetCollectibleInfo invokes the fragment.getCollectibleInfo RPC method on the server.
//
// Parameters:
//   - ctx: context for cancellation and timeout
//   - req: the request parameters
//
// Returns the result of the RPC call, or an error if the invocation fails.
func (c *RPCClient) FragmentGetCollectibleInfo(ctx context.Context, req *FragmentGetCollectibleInfoRequest) (*FragmentCollectibleInfo, error) {
	result, err := c.invoke(ctx, req, func(r *Reader) (TLObject, error) {
		return ReadTLObject(r)
	})
	if err != nil {
		return nil, err
	}
	if _c, _ok := result.(*FragmentCollectibleInfo); _ok {
		return _c, nil
	}
	return nil, fmt.Errorf("unexpected result type %T", result)
}
