// Code generated by tlgen. DO NOT EDIT.

package tg

import (
	"bytes"
	"io"
)

// InputPhotoClass is the interface for TL type InputPhoto.
// Implementations must satisfy TLObject and are used to represent
// any constructor of the InputPhoto TL type.
type InputPhotoClass interface {
	TLObject
	isInputPhoto()
}

// InputPhotoEmptyTypeID is the constructor ID for TL type inputPhotoEmpty.
const InputPhotoEmptyTypeID = 0x1cd7bf0d

// InputPhotoTypeID is the constructor ID for TL type inputPhoto.
const InputPhotoTypeID = 0x3bb3b94a

// isInputPhoto marks InputPhotoEmpty as implementing the InputPhotoClass interface.
func (*InputPhotoEmpty) isInputPhoto() {}

// isInputPhoto marks InputPhoto as implementing the InputPhotoClass interface.
func (*InputPhoto) isInputPhoto() {}

// InputPhotoEmpty represents the TL constructor inputPhotoEmpty (0x1cd7bf0d).
//
// See https://core.telegram.org/constructor/inputPhotoEmpty for reference.
type InputPhotoEmpty struct {
}

// ConstructorID returns the TL constructor identifier 0x1cd7bf0d.
func (v *InputPhotoEmpty) ConstructorID() uint32 {
	return InputPhotoEmptyTypeID
}

// Encode serializes InputPhotoEmpty to a bytes.Buffer using the TL binary protocol.
func (v *InputPhotoEmpty) Encode(b *bytes.Buffer) error {
	WriteInt(b, InputPhotoEmptyTypeID)
	return nil
}

// DecodeInputPhotoEmpty deserializes a InputPhotoEmpty from a reader using the TL binary protocol.
func DecodeInputPhotoEmpty(r io.Reader) (*InputPhotoEmpty, error) {
	v := &InputPhotoEmpty{}
	return v, nil
}

func init() {
	Registry[InputPhotoEmptyTypeID] = func(r io.Reader) (TLObject, error) {
		return DecodeInputPhotoEmpty(r)
	}
}

// InputPhoto represents the TL constructor inputPhoto (0x3bb3b94a).
//
// See https://core.telegram.org/constructor/inputPhoto for reference.
type InputPhoto struct {
	ID            int64  `json:"id,omitempty"`
	AccessHash    int64  `json:"access_hash,omitempty"`
	FileReference []byte `json:"file_reference,omitempty"`
}

// ConstructorID returns the TL constructor identifier 0x3bb3b94a.
func (v *InputPhoto) ConstructorID() uint32 {
	return InputPhotoTypeID
}

// Encode serializes InputPhoto to a bytes.Buffer using the TL binary protocol.
func (v *InputPhoto) Encode(b *bytes.Buffer) error {
	WriteInt(b, InputPhotoTypeID)
	WriteLong(b, v.ID)
	WriteLong(b, v.AccessHash)
	WriteBytes(b, v.FileReference)
	return nil
}

// DecodeInputPhoto deserializes a InputPhoto from a reader using the TL binary protocol.
func DecodeInputPhoto(r io.Reader) (*InputPhoto, error) {
	v := &InputPhoto{}
	v.ID = ReadLong(r)
	v.AccessHash = ReadLong(r)
	v.FileReference = ReadBytes(r)
	return v, nil
}

func init() {
	Registry[InputPhotoTypeID] = func(r io.Reader) (TLObject, error) {
		return DecodeInputPhoto(r)
	}
}

// PhotoSizeClass is the interface for TL type PhotoSize.
// Implementations must satisfy TLObject and are used to represent
// any constructor of the PhotoSize TL type.
type PhotoSizeClass interface {
	TLObject
	isPhotoSize()
}

// PhotoSizeEmptyTypeID is the constructor ID for TL type photoSizeEmpty.
const PhotoSizeEmptyTypeID = 0x0e17e23c

// PhotoSizeTypeID is the constructor ID for TL type photoSize.
const PhotoSizeTypeID = 0x75c78e60

// PhotoCachedSizeTypeID is the constructor ID for TL type photoCachedSize.
const PhotoCachedSizeTypeID = 0x021e1ad6

// PhotoStrippedSizeTypeID is the constructor ID for TL type photoStrippedSize.
const PhotoStrippedSizeTypeID = 0xe0b0bc2e

// PhotoSizeProgressiveTypeID is the constructor ID for TL type photoSizeProgressive.
const PhotoSizeProgressiveTypeID = 0xfa3efb95

// PhotoPathSizeTypeID is the constructor ID for TL type photoPathSize.
const PhotoPathSizeTypeID = 0xd8214d41

// isPhotoSize marks PhotoSizeEmpty as implementing the PhotoSizeClass interface.
func (*PhotoSizeEmpty) isPhotoSize() {}

// isPhotoSize marks PhotoSize as implementing the PhotoSizeClass interface.
func (*PhotoSize) isPhotoSize() {}

// isPhotoSize marks PhotoCachedSize as implementing the PhotoSizeClass interface.
func (*PhotoCachedSize) isPhotoSize() {}

// isPhotoSize marks PhotoStrippedSize as implementing the PhotoSizeClass interface.
func (*PhotoStrippedSize) isPhotoSize() {}

// isPhotoSize marks PhotoSizeProgressive as implementing the PhotoSizeClass interface.
func (*PhotoSizeProgressive) isPhotoSize() {}

// isPhotoSize marks PhotoPathSize as implementing the PhotoSizeClass interface.
func (*PhotoPathSize) isPhotoSize() {}

// PhotoSizeEmpty represents the TL constructor photoSizeEmpty (0x0e17e23c).
//
// See https://core.telegram.org/constructor/photoSizeEmpty for reference.
type PhotoSizeEmpty struct {
	Type string `json:"type,omitempty"`
}

// ConstructorID returns the TL constructor identifier 0x0e17e23c.
func (v *PhotoSizeEmpty) ConstructorID() uint32 {
	return PhotoSizeEmptyTypeID
}

// Encode serializes PhotoSizeEmpty to a bytes.Buffer using the TL binary protocol.
func (v *PhotoSizeEmpty) Encode(b *bytes.Buffer) error {
	WriteInt(b, PhotoSizeEmptyTypeID)
	WriteString(b, v.Type)
	return nil
}

// DecodePhotoSizeEmpty deserializes a PhotoSizeEmpty from a reader using the TL binary protocol.
func DecodePhotoSizeEmpty(r io.Reader) (*PhotoSizeEmpty, error) {
	v := &PhotoSizeEmpty{}
	v.Type = ReadString(r)
	return v, nil
}

func init() {
	Registry[PhotoSizeEmptyTypeID] = func(r io.Reader) (TLObject, error) {
		return DecodePhotoSizeEmpty(r)
	}
}

// PhotoSize represents the TL constructor photoSize (0x75c78e60).
//
// See https://core.telegram.org/constructor/photoSize for reference.
type PhotoSize struct {
	Type string `json:"type,omitempty"`
	W    int32  `json:"w,omitempty"`
	H    int32  `json:"h,omitempty"`
	Size int32  `json:"size,omitempty"`
}

// ConstructorID returns the TL constructor identifier 0x75c78e60.
func (v *PhotoSize) ConstructorID() uint32 {
	return PhotoSizeTypeID
}

// Encode serializes PhotoSize to a bytes.Buffer using the TL binary protocol.
func (v *PhotoSize) Encode(b *bytes.Buffer) error {
	WriteInt(b, PhotoSizeTypeID)
	WriteString(b, v.Type)
	WriteInt(b, uint32(v.W))
	WriteInt(b, uint32(v.H))
	WriteInt(b, uint32(v.Size))
	return nil
}

// DecodePhotoSize deserializes a PhotoSize from a reader using the TL binary protocol.
func DecodePhotoSize(r io.Reader) (*PhotoSize, error) {
	v := &PhotoSize{}
	v.Type = ReadString(r)
	v.W = int32(ReadInt(r))
	v.H = int32(ReadInt(r))
	v.Size = int32(ReadInt(r))
	return v, nil
}

func init() {
	Registry[PhotoSizeTypeID] = func(r io.Reader) (TLObject, error) {
		return DecodePhotoSize(r)
	}
}

// PhotoCachedSize represents the TL constructor photoCachedSize (0x021e1ad6).
//
// See https://core.telegram.org/constructor/photoCachedSize for reference.
type PhotoCachedSize struct {
	Type  string `json:"type,omitempty"`
	W     int32  `json:"w,omitempty"`
	H     int32  `json:"h,omitempty"`
	Bytes []byte `json:"bytes,omitempty"`
}

// ConstructorID returns the TL constructor identifier 0x021e1ad6.
func (v *PhotoCachedSize) ConstructorID() uint32 {
	return PhotoCachedSizeTypeID
}

// Encode serializes PhotoCachedSize to a bytes.Buffer using the TL binary protocol.
func (v *PhotoCachedSize) Encode(b *bytes.Buffer) error {
	WriteInt(b, PhotoCachedSizeTypeID)
	WriteString(b, v.Type)
	WriteInt(b, uint32(v.W))
	WriteInt(b, uint32(v.H))
	WriteBytes(b, v.Bytes)
	return nil
}

// DecodePhotoCachedSize deserializes a PhotoCachedSize from a reader using the TL binary protocol.
func DecodePhotoCachedSize(r io.Reader) (*PhotoCachedSize, error) {
	v := &PhotoCachedSize{}
	v.Type = ReadString(r)
	v.W = int32(ReadInt(r))
	v.H = int32(ReadInt(r))
	v.Bytes = ReadBytes(r)
	return v, nil
}

func init() {
	Registry[PhotoCachedSizeTypeID] = func(r io.Reader) (TLObject, error) {
		return DecodePhotoCachedSize(r)
	}
}

// PhotoStrippedSize represents the TL constructor photoStrippedSize (0xe0b0bc2e).
//
// See https://core.telegram.org/constructor/photoStrippedSize for reference.
type PhotoStrippedSize struct {
	Type  string `json:"type,omitempty"`
	Bytes []byte `json:"bytes,omitempty"`
}

// ConstructorID returns the TL constructor identifier 0xe0b0bc2e.
func (v *PhotoStrippedSize) ConstructorID() uint32 {
	return PhotoStrippedSizeTypeID
}

// Encode serializes PhotoStrippedSize to a bytes.Buffer using the TL binary protocol.
func (v *PhotoStrippedSize) Encode(b *bytes.Buffer) error {
	WriteInt(b, PhotoStrippedSizeTypeID)
	WriteString(b, v.Type)
	WriteBytes(b, v.Bytes)
	return nil
}

// DecodePhotoStrippedSize deserializes a PhotoStrippedSize from a reader using the TL binary protocol.
func DecodePhotoStrippedSize(r io.Reader) (*PhotoStrippedSize, error) {
	v := &PhotoStrippedSize{}
	v.Type = ReadString(r)
	v.Bytes = ReadBytes(r)
	return v, nil
}

func init() {
	Registry[PhotoStrippedSizeTypeID] = func(r io.Reader) (TLObject, error) {
		return DecodePhotoStrippedSize(r)
	}
}

// PhotoSizeProgressive represents the TL constructor photoSizeProgressive (0xfa3efb95).
//
// See https://core.telegram.org/constructor/photoSizeProgressive for reference.
type PhotoSizeProgressive struct {
	Type  string  `json:"type,omitempty"`
	W     int32   `json:"w,omitempty"`
	H     int32   `json:"h,omitempty"`
	Sizes []int32 `json:"sizes,omitempty"`
}

// ConstructorID returns the TL constructor identifier 0xfa3efb95.
func (v *PhotoSizeProgressive) ConstructorID() uint32 {
	return PhotoSizeProgressiveTypeID
}

// Encode serializes PhotoSizeProgressive to a bytes.Buffer using the TL binary protocol.
func (v *PhotoSizeProgressive) Encode(b *bytes.Buffer) error {
	WriteInt(b, PhotoSizeProgressiveTypeID)
	WriteString(b, v.Type)
	WriteInt(b, uint32(v.W))
	WriteInt(b, uint32(v.H))
	WriteVectorInt(b, v.Sizes)
	return nil
}

// DecodePhotoSizeProgressive deserializes a PhotoSizeProgressive from a reader using the TL binary protocol.
func DecodePhotoSizeProgressive(r io.Reader) (*PhotoSizeProgressive, error) {
	v := &PhotoSizeProgressive{}
	v.Type = ReadString(r)
	v.W = int32(ReadInt(r))
	v.H = int32(ReadInt(r))
	v.Sizes = ReadVectorInt(r)
	return v, nil
}

func init() {
	Registry[PhotoSizeProgressiveTypeID] = func(r io.Reader) (TLObject, error) {
		return DecodePhotoSizeProgressive(r)
	}
}

// PhotoPathSize represents the TL constructor photoPathSize (0xd8214d41).
//
// See https://core.telegram.org/constructor/photoPathSize for reference.
type PhotoPathSize struct {
	Type  string `json:"type,omitempty"`
	Bytes []byte `json:"bytes,omitempty"`
}

// ConstructorID returns the TL constructor identifier 0xd8214d41.
func (v *PhotoPathSize) ConstructorID() uint32 {
	return PhotoPathSizeTypeID
}

// Encode serializes PhotoPathSize to a bytes.Buffer using the TL binary protocol.
func (v *PhotoPathSize) Encode(b *bytes.Buffer) error {
	WriteInt(b, PhotoPathSizeTypeID)
	WriteString(b, v.Type)
	WriteBytes(b, v.Bytes)
	return nil
}

// DecodePhotoPathSize deserializes a PhotoPathSize from a reader using the TL binary protocol.
func DecodePhotoPathSize(r io.Reader) (*PhotoPathSize, error) {
	v := &PhotoPathSize{}
	v.Type = ReadString(r)
	v.Bytes = ReadBytes(r)
	return v, nil
}

func init() {
	Registry[PhotoPathSizeTypeID] = func(r io.Reader) (TLObject, error) {
		return DecodePhotoPathSize(r)
	}
}

// InputDocumentClass is the interface for TL type InputDocument.
// Implementations must satisfy TLObject and are used to represent
// any constructor of the InputDocument TL type.
type InputDocumentClass interface {
	TLObject
	isInputDocument()
}

// InputDocumentEmptyTypeID is the constructor ID for TL type inputDocumentEmpty.
const InputDocumentEmptyTypeID = 0x72f0eaae

// InputDocumentTypeID is the constructor ID for TL type inputDocument.
const InputDocumentTypeID = 0x1abfb575

// isInputDocument marks InputDocumentEmpty as implementing the InputDocumentClass interface.
func (*InputDocumentEmpty) isInputDocument() {}

// isInputDocument marks InputDocument as implementing the InputDocumentClass interface.
func (*InputDocument) isInputDocument() {}

// InputDocumentEmpty represents the TL constructor inputDocumentEmpty (0x72f0eaae).
//
// See https://core.telegram.org/constructor/inputDocumentEmpty for reference.
type InputDocumentEmpty struct {
}

// ConstructorID returns the TL constructor identifier 0x72f0eaae.
func (v *InputDocumentEmpty) ConstructorID() uint32 {
	return InputDocumentEmptyTypeID
}

// Encode serializes InputDocumentEmpty to a bytes.Buffer using the TL binary protocol.
func (v *InputDocumentEmpty) Encode(b *bytes.Buffer) error {
	WriteInt(b, InputDocumentEmptyTypeID)
	return nil
}

// DecodeInputDocumentEmpty deserializes a InputDocumentEmpty from a reader using the TL binary protocol.
func DecodeInputDocumentEmpty(r io.Reader) (*InputDocumentEmpty, error) {
	v := &InputDocumentEmpty{}
	return v, nil
}

func init() {
	Registry[InputDocumentEmptyTypeID] = func(r io.Reader) (TLObject, error) {
		return DecodeInputDocumentEmpty(r)
	}
}

// InputDocument represents the TL constructor inputDocument (0x1abfb575).
//
// See https://core.telegram.org/constructor/inputDocument for reference.
type InputDocument struct {
	ID            int64  `json:"id,omitempty"`
	AccessHash    int64  `json:"access_hash,omitempty"`
	FileReference []byte `json:"file_reference,omitempty"`
}

// ConstructorID returns the TL constructor identifier 0x1abfb575.
func (v *InputDocument) ConstructorID() uint32 {
	return InputDocumentTypeID
}

// Encode serializes InputDocument to a bytes.Buffer using the TL binary protocol.
func (v *InputDocument) Encode(b *bytes.Buffer) error {
	WriteInt(b, InputDocumentTypeID)
	WriteLong(b, v.ID)
	WriteLong(b, v.AccessHash)
	WriteBytes(b, v.FileReference)
	return nil
}

// DecodeInputDocument deserializes a InputDocument from a reader using the TL binary protocol.
func DecodeInputDocument(r io.Reader) (*InputDocument, error) {
	v := &InputDocument{}
	v.ID = ReadLong(r)
	v.AccessHash = ReadLong(r)
	v.FileReference = ReadBytes(r)
	return v, nil
}

func init() {
	Registry[InputDocumentTypeID] = func(r io.Reader) (TLObject, error) {
		return DecodeInputDocument(r)
	}
}

// DocumentClass is the interface for TL type Document.
// Implementations must satisfy TLObject and are used to represent
// any constructor of the Document TL type.
type DocumentClass interface {
	TLObject
	isDocument()
}

// DocumentEmptyTypeID is the constructor ID for TL type documentEmpty.
const DocumentEmptyTypeID = 0x36f8c871

// DocumentTypeID is the constructor ID for TL type document.
const DocumentTypeID = 0x8fd4c4d8

// isDocument marks DocumentEmpty as implementing the DocumentClass interface.
func (*DocumentEmpty) isDocument() {}

// isDocument marks Document as implementing the DocumentClass interface.
func (*Document) isDocument() {}

// DocumentEmpty represents the TL constructor documentEmpty (0x36f8c871).
//
// See https://core.telegram.org/constructor/documentEmpty for reference.
type DocumentEmpty struct {
	ID int64 `json:"id,omitempty"`
}

// ConstructorID returns the TL constructor identifier 0x36f8c871.
func (v *DocumentEmpty) ConstructorID() uint32 {
	return DocumentEmptyTypeID
}

// Encode serializes DocumentEmpty to a bytes.Buffer using the TL binary protocol.
func (v *DocumentEmpty) Encode(b *bytes.Buffer) error {
	WriteInt(b, DocumentEmptyTypeID)
	WriteLong(b, v.ID)
	return nil
}

// DecodeDocumentEmpty deserializes a DocumentEmpty from a reader using the TL binary protocol.
func DecodeDocumentEmpty(r io.Reader) (*DocumentEmpty, error) {
	v := &DocumentEmpty{}
	v.ID = ReadLong(r)
	return v, nil
}

func init() {
	Registry[DocumentEmptyTypeID] = func(r io.Reader) (TLObject, error) {
		return DecodeDocumentEmpty(r)
	}
}

// Document represents the TL constructor document (0x8fd4c4d8).
//
// See https://core.telegram.org/constructor/document for reference.
type Document struct {
	Flags         Fields                   `json:"-"`
	ID            int64                    `json:"id,omitempty"`
	AccessHash    int64                    `json:"access_hash,omitempty"`
	FileReference []byte                   `json:"file_reference,omitempty"`
	Date          int32                    `json:"date,omitempty"`
	MimeType      string                   `json:"mime_type,omitempty"`
	Size          int64                    `json:"size,omitempty"`
	Thumbs        []PhotoSizeClass         `json:"thumbs,omitempty"`
	VideoThumbs   []VideoSizeClass         `json:"video_thumbs,omitempty"`
	DCID          int32                    `json:"dcid,omitempty"`
	Attributes    []DocumentAttributeClass `json:"attributes,omitempty"`
}

// SetFlags computes flags from non-zero optional fields.
func (v *Document) SetFlags() {
	if v.Thumbs != nil {
		v.Flags.Set(0)
	}
	if v.VideoThumbs != nil {
		v.Flags.Set(1)
	}
}

// ConstructorID returns the TL constructor identifier 0x8fd4c4d8.
func (v *Document) ConstructorID() uint32 {
	return DocumentTypeID
}

// Encode serializes Document to a bytes.Buffer using the TL binary protocol.
func (v *Document) Encode(b *bytes.Buffer) error {
	WriteInt(b, DocumentTypeID)
	v.SetFlags()
	WriteInt(b, uint32(v.Flags))
	WriteLong(b, v.ID)
	WriteLong(b, v.AccessHash)
	WriteBytes(b, v.FileReference)
	WriteInt(b, uint32(v.Date))
	WriteString(b, v.MimeType)
	WriteLong(b, v.Size)
	if v.Flags.Has(0) {
		WriteInt(b, 0x1cb5c415)
		WriteInt(b, uint32(len(v.Thumbs)))
		for _, _item := range v.Thumbs {
			EncodeTLObject(b, _item)
		}
	}
	if v.Flags.Has(1) {
		WriteInt(b, 0x1cb5c415)
		WriteInt(b, uint32(len(v.VideoThumbs)))
		for _, _item := range v.VideoThumbs {
			EncodeTLObject(b, _item)
		}
	}
	WriteInt(b, uint32(v.DCID))
	WriteInt(b, 0x1cb5c415)
	WriteInt(b, uint32(len(v.Attributes)))
	for _, _item := range v.Attributes {
		EncodeTLObject(b, _item)
	}
	return nil
}

// DecodeDocument deserializes a Document from a reader using the TL binary protocol.
func DecodeDocument(r io.Reader) (*Document, error) {
	v := &Document{}
	{
		var _f uint32
		_f, _ = ReadIntErr(r)
		v.Flags = Fields(_f)
	}
	v.ID = ReadLong(r)
	v.AccessHash = ReadLong(r)
	v.FileReference = ReadBytes(r)
	v.Date = int32(ReadInt(r))
	v.MimeType = ReadString(r)
	v.Size = ReadLong(r)
	if v.Flags.Has(0) {
		ReadInt(r)
		_cntThumbs := ReadInt(r)
		if err := checkVectorCount(_cntThumbs); err != nil {
			return nil, err
		}
		v.Thumbs = make([]PhotoSizeClass, _cntThumbs)
		for _iThumbs := range v.Thumbs {
			_objThumbs, _ := ReadTLObject(r)
			v.Thumbs[_iThumbs] = _objThumbs.(PhotoSizeClass)
		}
	}
	if v.Flags.Has(1) {
		ReadInt(r)
		_cntVideoThumbs := ReadInt(r)
		if err := checkVectorCount(_cntVideoThumbs); err != nil {
			return nil, err
		}
		v.VideoThumbs = make([]VideoSizeClass, _cntVideoThumbs)
		for _iVideoThumbs := range v.VideoThumbs {
			_objVideoThumbs, _ := ReadTLObject(r)
			v.VideoThumbs[_iVideoThumbs] = _objVideoThumbs.(VideoSizeClass)
		}
	}
	v.DCID = int32(ReadInt(r))
	ReadInt(r)
	_cntAttributes := ReadInt(r)
	if err := checkVectorCount(_cntAttributes); err != nil {
		return nil, err
	}
	v.Attributes = make([]DocumentAttributeClass, _cntAttributes)
	for _iAttributes := range v.Attributes {
		_objAttributes, _ := ReadTLObject(r)
		v.Attributes[_iAttributes] = _objAttributes.(DocumentAttributeClass)
	}
	return v, nil
}

func init() {
	Registry[DocumentTypeID] = func(r io.Reader) (TLObject, error) {
		return DecodeDocument(r)
	}
}

// DocumentAttributeClass is the interface for TL type DocumentAttribute.
// Implementations must satisfy TLObject and are used to represent
// any constructor of the DocumentAttribute TL type.
type DocumentAttributeClass interface {
	TLObject
	isDocumentAttribute()
}

// DocumentAttributeImageSizeTypeID is the constructor ID for TL type documentAttributeImageSize.
const DocumentAttributeImageSizeTypeID = 0x6c37c15c

// DocumentAttributeAnimatedTypeID is the constructor ID for TL type documentAttributeAnimated.
const DocumentAttributeAnimatedTypeID = 0x11b58939

// DocumentAttributeStickerTypeID is the constructor ID for TL type documentAttributeSticker.
const DocumentAttributeStickerTypeID = 0x6319d612

// DocumentAttributeVideoTypeID is the constructor ID for TL type documentAttributeVideo.
const DocumentAttributeVideoTypeID = 0x43c57c48

// DocumentAttributeAudioTypeID is the constructor ID for TL type documentAttributeAudio.
const DocumentAttributeAudioTypeID = 0x9852f9c6

// DocumentAttributeFilenameTypeID is the constructor ID for TL type documentAttributeFilename.
const DocumentAttributeFilenameTypeID = 0x15590068

// DocumentAttributeHasStickersTypeID is the constructor ID for TL type documentAttributeHasStickers.
const DocumentAttributeHasStickersTypeID = 0x9801d2f7

// DocumentAttributeCustomEmojiTypeID is the constructor ID for TL type documentAttributeCustomEmoji.
const DocumentAttributeCustomEmojiTypeID = 0xfd149899

// isDocumentAttribute marks DocumentAttributeImageSize as implementing the DocumentAttributeClass interface.
func (*DocumentAttributeImageSize) isDocumentAttribute() {}

// isDocumentAttribute marks DocumentAttributeAnimated as implementing the DocumentAttributeClass interface.
func (*DocumentAttributeAnimated) isDocumentAttribute() {}

// isDocumentAttribute marks DocumentAttributeSticker as implementing the DocumentAttributeClass interface.
func (*DocumentAttributeSticker) isDocumentAttribute() {}

// isDocumentAttribute marks DocumentAttributeVideo as implementing the DocumentAttributeClass interface.
func (*DocumentAttributeVideo) isDocumentAttribute() {}

// isDocumentAttribute marks DocumentAttributeAudio as implementing the DocumentAttributeClass interface.
func (*DocumentAttributeAudio) isDocumentAttribute() {}

// isDocumentAttribute marks DocumentAttributeFilename as implementing the DocumentAttributeClass interface.
func (*DocumentAttributeFilename) isDocumentAttribute() {}

// isDocumentAttribute marks DocumentAttributeHasStickers as implementing the DocumentAttributeClass interface.
func (*DocumentAttributeHasStickers) isDocumentAttribute() {}

// isDocumentAttribute marks DocumentAttributeCustomEmoji as implementing the DocumentAttributeClass interface.
func (*DocumentAttributeCustomEmoji) isDocumentAttribute() {}

// DocumentAttributeImageSize represents the TL constructor documentAttributeImageSize (0x6c37c15c).
//
// See https://core.telegram.org/constructor/documentAttributeImageSize for reference.
type DocumentAttributeImageSize struct {
	W int32 `json:"w,omitempty"`
	H int32 `json:"h,omitempty"`
}

// ConstructorID returns the TL constructor identifier 0x6c37c15c.
func (v *DocumentAttributeImageSize) ConstructorID() uint32 {
	return DocumentAttributeImageSizeTypeID
}

// Encode serializes DocumentAttributeImageSize to a bytes.Buffer using the TL binary protocol.
func (v *DocumentAttributeImageSize) Encode(b *bytes.Buffer) error {
	WriteInt(b, DocumentAttributeImageSizeTypeID)
	WriteInt(b, uint32(v.W))
	WriteInt(b, uint32(v.H))
	return nil
}

// DecodeDocumentAttributeImageSize deserializes a DocumentAttributeImageSize from a reader using the TL binary protocol.
func DecodeDocumentAttributeImageSize(r io.Reader) (*DocumentAttributeImageSize, error) {
	v := &DocumentAttributeImageSize{}
	v.W = int32(ReadInt(r))
	v.H = int32(ReadInt(r))
	return v, nil
}

func init() {
	Registry[DocumentAttributeImageSizeTypeID] = func(r io.Reader) (TLObject, error) {
		return DecodeDocumentAttributeImageSize(r)
	}
}

// DocumentAttributeAnimated represents the TL constructor documentAttributeAnimated (0x11b58939).
//
// See https://core.telegram.org/constructor/documentAttributeAnimated for reference.
type DocumentAttributeAnimated struct {
}

// ConstructorID returns the TL constructor identifier 0x11b58939.
func (v *DocumentAttributeAnimated) ConstructorID() uint32 {
	return DocumentAttributeAnimatedTypeID
}

// Encode serializes DocumentAttributeAnimated to a bytes.Buffer using the TL binary protocol.
func (v *DocumentAttributeAnimated) Encode(b *bytes.Buffer) error {
	WriteInt(b, DocumentAttributeAnimatedTypeID)
	return nil
}

// DecodeDocumentAttributeAnimated deserializes a DocumentAttributeAnimated from a reader using the TL binary protocol.
func DecodeDocumentAttributeAnimated(r io.Reader) (*DocumentAttributeAnimated, error) {
	v := &DocumentAttributeAnimated{}
	return v, nil
}

func init() {
	Registry[DocumentAttributeAnimatedTypeID] = func(r io.Reader) (TLObject, error) {
		return DecodeDocumentAttributeAnimated(r)
	}
}

// DocumentAttributeSticker represents the TL constructor documentAttributeSticker (0x6319d612).
//
// See https://core.telegram.org/constructor/documentAttributeSticker for reference.
type DocumentAttributeSticker struct {
	Flags      Fields               `json:"-"`
	Mask       bool                 `json:"mask,omitempty"`
	Alt        string               `json:"alt,omitempty"`
	Stickerset InputStickerSetClass `json:"stickerset,omitempty"`
	MaskCoords *MaskCoords          `json:"mask_coords,omitempty"`
}

// SetFlags computes flags from non-zero optional fields.
func (v *DocumentAttributeSticker) SetFlags() {
	if v.Mask {
		v.Flags.Set(1)
	}
	if v.MaskCoords != nil {
		v.Flags.Set(0)
	}
}

// ConstructorID returns the TL constructor identifier 0x6319d612.
func (v *DocumentAttributeSticker) ConstructorID() uint32 {
	return DocumentAttributeStickerTypeID
}

// Encode serializes DocumentAttributeSticker to a bytes.Buffer using the TL binary protocol.
func (v *DocumentAttributeSticker) Encode(b *bytes.Buffer) error {
	WriteInt(b, DocumentAttributeStickerTypeID)
	v.SetFlags()
	WriteInt(b, uint32(v.Flags))
	WriteString(b, v.Alt)
	EncodeTLObject(b, v.Stickerset)
	if v.Flags.Has(0) {
		EncodeTLObject(b, v.MaskCoords)
	}
	return nil
}

// DecodeDocumentAttributeSticker deserializes a DocumentAttributeSticker from a reader using the TL binary protocol.
func DecodeDocumentAttributeSticker(r io.Reader) (*DocumentAttributeSticker, error) {
	v := &DocumentAttributeSticker{}
	{
		var _f uint32
		_f, _ = ReadIntErr(r)
		v.Flags = Fields(_f)
	}
	v.Mask = v.Flags.Has(1)
	v.Alt = ReadString(r)
	_objStickerset, _ := ReadTLObject(r)
	v.Stickerset = _objStickerset.(InputStickerSetClass)
	if v.Flags.Has(0) {
		_objMaskCoords, _ := ReadTLObject(r)
		v.MaskCoords = _objMaskCoords.(*MaskCoords)
	}
	return v, nil
}

func init() {
	Registry[DocumentAttributeStickerTypeID] = func(r io.Reader) (TLObject, error) {
		return DecodeDocumentAttributeSticker(r)
	}
}

// DocumentAttributeVideo represents the TL constructor documentAttributeVideo (0x43c57c48).
//
// See https://core.telegram.org/constructor/documentAttributeVideo for reference.
type DocumentAttributeVideo struct {
	Flags             Fields  `json:"-"`
	RoundMessage      bool    `json:"round_message,omitempty"`
	SupportsStreaming bool    `json:"supports_streaming,omitempty"`
	Nosound           bool    `json:"nosound,omitempty"`
	Duration          float64 `json:"duration,omitempty"`
	W                 int32   `json:"w,omitempty"`
	H                 int32   `json:"h,omitempty"`
	PreloadPrefixSize int32   `json:"preload_prefix_size,omitempty"`
	VideoStartTs      float64 `json:"video_start_ts,omitempty"`
	VideoCodec        string  `json:"video_codec,omitempty"`
}

// SetFlags computes flags from non-zero optional fields.
func (v *DocumentAttributeVideo) SetFlags() {
	if v.RoundMessage {
		v.Flags.Set(0)
	}
	if v.SupportsStreaming {
		v.Flags.Set(1)
	}
	if v.Nosound {
		v.Flags.Set(3)
	}
	if v.PreloadPrefixSize != 0 {
		v.Flags.Set(2)
	}
	if v.VideoStartTs != 0 {
		v.Flags.Set(4)
	}
	if v.VideoCodec != "" {
		v.Flags.Set(5)
	}
}

// ConstructorID returns the TL constructor identifier 0x43c57c48.
func (v *DocumentAttributeVideo) ConstructorID() uint32 {
	return DocumentAttributeVideoTypeID
}

// Encode serializes DocumentAttributeVideo to a bytes.Buffer using the TL binary protocol.
func (v *DocumentAttributeVideo) Encode(b *bytes.Buffer) error {
	WriteInt(b, DocumentAttributeVideoTypeID)
	v.SetFlags()
	WriteInt(b, uint32(v.Flags))
	WriteDouble(b, v.Duration)
	WriteInt(b, uint32(v.W))
	WriteInt(b, uint32(v.H))
	if v.Flags.Has(2) {
		WriteInt(b, uint32(v.PreloadPrefixSize))
	}
	if v.Flags.Has(4) {
		WriteDouble(b, v.VideoStartTs)
	}
	if v.Flags.Has(5) {
		WriteString(b, v.VideoCodec)
	}
	return nil
}

// DecodeDocumentAttributeVideo deserializes a DocumentAttributeVideo from a reader using the TL binary protocol.
func DecodeDocumentAttributeVideo(r io.Reader) (*DocumentAttributeVideo, error) {
	v := &DocumentAttributeVideo{}
	{
		var _f uint32
		_f, _ = ReadIntErr(r)
		v.Flags = Fields(_f)
	}
	v.RoundMessage = v.Flags.Has(0)
	v.SupportsStreaming = v.Flags.Has(1)
	v.Nosound = v.Flags.Has(3)
	v.Duration = ReadDouble(r)
	v.W = int32(ReadInt(r))
	v.H = int32(ReadInt(r))
	if v.Flags.Has(2) {
		v.PreloadPrefixSize = int32(ReadInt(r))
	}
	if v.Flags.Has(4) {
		v.VideoStartTs = ReadDouble(r)
	}
	if v.Flags.Has(5) {
		v.VideoCodec = ReadString(r)
	}
	return v, nil
}

func init() {
	Registry[DocumentAttributeVideoTypeID] = func(r io.Reader) (TLObject, error) {
		return DecodeDocumentAttributeVideo(r)
	}
}

// DocumentAttributeAudio represents the TL constructor documentAttributeAudio (0x9852f9c6).
//
// See https://core.telegram.org/constructor/documentAttributeAudio for reference.
type DocumentAttributeAudio struct {
	Flags     Fields `json:"-"`
	Voice     bool   `json:"voice,omitempty"`
	Duration  int32  `json:"duration,omitempty"`
	Title     string `json:"title,omitempty"`
	Performer string `json:"performer,omitempty"`
	Waveform  []byte `json:"waveform,omitempty"`
}

// SetFlags computes flags from non-zero optional fields.
func (v *DocumentAttributeAudio) SetFlags() {
	if v.Voice {
		v.Flags.Set(10)
	}
	if v.Title != "" {
		v.Flags.Set(0)
	}
	if v.Performer != "" {
		v.Flags.Set(1)
	}
	if v.Waveform != nil {
		v.Flags.Set(2)
	}
}

// ConstructorID returns the TL constructor identifier 0x9852f9c6.
func (v *DocumentAttributeAudio) ConstructorID() uint32 {
	return DocumentAttributeAudioTypeID
}

// Encode serializes DocumentAttributeAudio to a bytes.Buffer using the TL binary protocol.
func (v *DocumentAttributeAudio) Encode(b *bytes.Buffer) error {
	WriteInt(b, DocumentAttributeAudioTypeID)
	v.SetFlags()
	WriteInt(b, uint32(v.Flags))
	WriteInt(b, uint32(v.Duration))
	if v.Flags.Has(0) {
		WriteString(b, v.Title)
	}
	if v.Flags.Has(1) {
		WriteString(b, v.Performer)
	}
	if v.Flags.Has(2) {
		WriteBytes(b, v.Waveform)
	}
	return nil
}

// DecodeDocumentAttributeAudio deserializes a DocumentAttributeAudio from a reader using the TL binary protocol.
func DecodeDocumentAttributeAudio(r io.Reader) (*DocumentAttributeAudio, error) {
	v := &DocumentAttributeAudio{}
	{
		var _f uint32
		_f, _ = ReadIntErr(r)
		v.Flags = Fields(_f)
	}
	v.Voice = v.Flags.Has(10)
	v.Duration = int32(ReadInt(r))
	if v.Flags.Has(0) {
		v.Title = ReadString(r)
	}
	if v.Flags.Has(1) {
		v.Performer = ReadString(r)
	}
	if v.Flags.Has(2) {
		v.Waveform = ReadBytes(r)
	}
	return v, nil
}

func init() {
	Registry[DocumentAttributeAudioTypeID] = func(r io.Reader) (TLObject, error) {
		return DecodeDocumentAttributeAudio(r)
	}
}

// DocumentAttributeFilename represents the TL constructor documentAttributeFilename (0x15590068).
//
// See https://core.telegram.org/constructor/documentAttributeFilename for reference.
type DocumentAttributeFilename struct {
	FileName string `json:"file_name,omitempty"`
}

// ConstructorID returns the TL constructor identifier 0x15590068.
func (v *DocumentAttributeFilename) ConstructorID() uint32 {
	return DocumentAttributeFilenameTypeID
}

// Encode serializes DocumentAttributeFilename to a bytes.Buffer using the TL binary protocol.
func (v *DocumentAttributeFilename) Encode(b *bytes.Buffer) error {
	WriteInt(b, DocumentAttributeFilenameTypeID)
	WriteString(b, v.FileName)
	return nil
}

// DecodeDocumentAttributeFilename deserializes a DocumentAttributeFilename from a reader using the TL binary protocol.
func DecodeDocumentAttributeFilename(r io.Reader) (*DocumentAttributeFilename, error) {
	v := &DocumentAttributeFilename{}
	v.FileName = ReadString(r)
	return v, nil
}

func init() {
	Registry[DocumentAttributeFilenameTypeID] = func(r io.Reader) (TLObject, error) {
		return DecodeDocumentAttributeFilename(r)
	}
}

// DocumentAttributeHasStickers represents the TL constructor documentAttributeHasStickers (0x9801d2f7).
//
// See https://core.telegram.org/constructor/documentAttributeHasStickers for reference.
type DocumentAttributeHasStickers struct {
}

// ConstructorID returns the TL constructor identifier 0x9801d2f7.
func (v *DocumentAttributeHasStickers) ConstructorID() uint32 {
	return DocumentAttributeHasStickersTypeID
}

// Encode serializes DocumentAttributeHasStickers to a bytes.Buffer using the TL binary protocol.
func (v *DocumentAttributeHasStickers) Encode(b *bytes.Buffer) error {
	WriteInt(b, DocumentAttributeHasStickersTypeID)
	return nil
}

// DecodeDocumentAttributeHasStickers deserializes a DocumentAttributeHasStickers from a reader using the TL binary protocol.
func DecodeDocumentAttributeHasStickers(r io.Reader) (*DocumentAttributeHasStickers, error) {
	v := &DocumentAttributeHasStickers{}
	return v, nil
}

func init() {
	Registry[DocumentAttributeHasStickersTypeID] = func(r io.Reader) (TLObject, error) {
		return DecodeDocumentAttributeHasStickers(r)
	}
}

// DocumentAttributeCustomEmoji represents the TL constructor documentAttributeCustomEmoji (0xfd149899).
//
// See https://core.telegram.org/constructor/documentAttributeCustomEmoji for reference.
type DocumentAttributeCustomEmoji struct {
	Flags      Fields               `json:"-"`
	Free       bool                 `json:"free,omitempty"`
	TextColor  bool                 `json:"text_color,omitempty"`
	Alt        string               `json:"alt,omitempty"`
	Stickerset InputStickerSetClass `json:"stickerset,omitempty"`
}

// SetFlags computes flags from non-zero optional fields.
func (v *DocumentAttributeCustomEmoji) SetFlags() {
	if v.Free {
		v.Flags.Set(0)
	}
	if v.TextColor {
		v.Flags.Set(1)
	}
}

// ConstructorID returns the TL constructor identifier 0xfd149899.
func (v *DocumentAttributeCustomEmoji) ConstructorID() uint32 {
	return DocumentAttributeCustomEmojiTypeID
}

// Encode serializes DocumentAttributeCustomEmoji to a bytes.Buffer using the TL binary protocol.
func (v *DocumentAttributeCustomEmoji) Encode(b *bytes.Buffer) error {
	WriteInt(b, DocumentAttributeCustomEmojiTypeID)
	v.SetFlags()
	WriteInt(b, uint32(v.Flags))
	WriteString(b, v.Alt)
	EncodeTLObject(b, v.Stickerset)
	return nil
}

// DecodeDocumentAttributeCustomEmoji deserializes a DocumentAttributeCustomEmoji from a reader using the TL binary protocol.
func DecodeDocumentAttributeCustomEmoji(r io.Reader) (*DocumentAttributeCustomEmoji, error) {
	v := &DocumentAttributeCustomEmoji{}
	{
		var _f uint32
		_f, _ = ReadIntErr(r)
		v.Flags = Fields(_f)
	}
	v.Free = v.Flags.Has(0)
	v.TextColor = v.Flags.Has(1)
	v.Alt = ReadString(r)
	_objStickerset, _ := ReadTLObject(r)
	v.Stickerset = _objStickerset.(InputStickerSetClass)
	return v, nil
}

func init() {
	Registry[DocumentAttributeCustomEmojiTypeID] = func(r io.Reader) (TLObject, error) {
		return DecodeDocumentAttributeCustomEmoji(r)
	}
}

// MaskCoordsTypeID is the constructor ID for TL type maskCoords.
const MaskCoordsTypeID = 0xaed6dbb2

// MaskCoords represents the TL constructor maskCoords (0xaed6dbb2).
//
// See https://core.telegram.org/constructor/maskCoords for reference.
type MaskCoords struct {
	N    int32   `json:"n,omitempty"`
	X    float64 `json:"x,omitempty"`
	Y    float64 `json:"y,omitempty"`
	Zoom float64 `json:"zoom,omitempty"`
}

// ConstructorID returns the TL constructor identifier 0xaed6dbb2.
func (v *MaskCoords) ConstructorID() uint32 {
	return MaskCoordsTypeID
}

// Encode serializes MaskCoords to a bytes.Buffer using the TL binary protocol.
func (v *MaskCoords) Encode(b *bytes.Buffer) error {
	WriteInt(b, MaskCoordsTypeID)
	WriteInt(b, uint32(v.N))
	WriteDouble(b, v.X)
	WriteDouble(b, v.Y)
	WriteDouble(b, v.Zoom)
	return nil
}

// DecodeMaskCoords deserializes a MaskCoords from a reader using the TL binary protocol.
func DecodeMaskCoords(r io.Reader) (*MaskCoords, error) {
	v := &MaskCoords{}
	v.N = int32(ReadInt(r))
	v.X = ReadDouble(r)
	v.Y = ReadDouble(r)
	v.Zoom = ReadDouble(r)
	return v, nil
}

func init() {
	Registry[MaskCoordsTypeID] = func(r io.Reader) (TLObject, error) {
		return DecodeMaskCoords(r)
	}
}

// WebDocumentClass is the interface for TL type WebDocument.
// Implementations must satisfy TLObject and are used to represent
// any constructor of the WebDocument TL type.
type WebDocumentClass interface {
	TLObject
	isWebDocument()
}

// WebDocumentTypeID is the constructor ID for TL type webDocument.
const WebDocumentTypeID = 0x1c570ed1

// WebDocumentNoProxyTypeID is the constructor ID for TL type webDocumentNoProxy.
const WebDocumentNoProxyTypeID = 0xf9c8bcc6

// isWebDocument marks WebDocument as implementing the WebDocumentClass interface.
func (*WebDocument) isWebDocument() {}

// isWebDocument marks WebDocumentNoProxy as implementing the WebDocumentClass interface.
func (*WebDocumentNoProxy) isWebDocument() {}

// WebDocument represents the TL constructor webDocument (0x1c570ed1).
//
// See https://core.telegram.org/constructor/webDocument for reference.
type WebDocument struct {
	URL        string                   `json:"url,omitempty"`
	AccessHash int64                    `json:"access_hash,omitempty"`
	Size       int32                    `json:"size,omitempty"`
	MimeType   string                   `json:"mime_type,omitempty"`
	Attributes []DocumentAttributeClass `json:"attributes,omitempty"`
}

// ConstructorID returns the TL constructor identifier 0x1c570ed1.
func (v *WebDocument) ConstructorID() uint32 {
	return WebDocumentTypeID
}

// Encode serializes WebDocument to a bytes.Buffer using the TL binary protocol.
func (v *WebDocument) Encode(b *bytes.Buffer) error {
	WriteInt(b, WebDocumentTypeID)
	WriteString(b, v.URL)
	WriteLong(b, v.AccessHash)
	WriteInt(b, uint32(v.Size))
	WriteString(b, v.MimeType)
	WriteInt(b, 0x1cb5c415)
	WriteInt(b, uint32(len(v.Attributes)))
	for _, _item := range v.Attributes {
		EncodeTLObject(b, _item)
	}
	return nil
}

// DecodeWebDocument deserializes a WebDocument from a reader using the TL binary protocol.
func DecodeWebDocument(r io.Reader) (*WebDocument, error) {
	v := &WebDocument{}
	v.URL = ReadString(r)
	v.AccessHash = ReadLong(r)
	v.Size = int32(ReadInt(r))
	v.MimeType = ReadString(r)
	ReadInt(r)
	_cntAttributes := ReadInt(r)
	if err := checkVectorCount(_cntAttributes); err != nil {
		return nil, err
	}
	v.Attributes = make([]DocumentAttributeClass, _cntAttributes)
	for _iAttributes := range v.Attributes {
		_objAttributes, _ := ReadTLObject(r)
		v.Attributes[_iAttributes] = _objAttributes.(DocumentAttributeClass)
	}
	return v, nil
}

func init() {
	Registry[WebDocumentTypeID] = func(r io.Reader) (TLObject, error) {
		return DecodeWebDocument(r)
	}
}

// WebDocumentNoProxy represents the TL constructor webDocumentNoProxy (0xf9c8bcc6).
//
// See https://core.telegram.org/constructor/webDocumentNoProxy for reference.
type WebDocumentNoProxy struct {
	URL        string                   `json:"url,omitempty"`
	Size       int32                    `json:"size,omitempty"`
	MimeType   string                   `json:"mime_type,omitempty"`
	Attributes []DocumentAttributeClass `json:"attributes,omitempty"`
}

// ConstructorID returns the TL constructor identifier 0xf9c8bcc6.
func (v *WebDocumentNoProxy) ConstructorID() uint32 {
	return WebDocumentNoProxyTypeID
}

// Encode serializes WebDocumentNoProxy to a bytes.Buffer using the TL binary protocol.
func (v *WebDocumentNoProxy) Encode(b *bytes.Buffer) error {
	WriteInt(b, WebDocumentNoProxyTypeID)
	WriteString(b, v.URL)
	WriteInt(b, uint32(v.Size))
	WriteString(b, v.MimeType)
	WriteInt(b, 0x1cb5c415)
	WriteInt(b, uint32(len(v.Attributes)))
	for _, _item := range v.Attributes {
		EncodeTLObject(b, _item)
	}
	return nil
}

// DecodeWebDocumentNoProxy deserializes a WebDocumentNoProxy from a reader using the TL binary protocol.
func DecodeWebDocumentNoProxy(r io.Reader) (*WebDocumentNoProxy, error) {
	v := &WebDocumentNoProxy{}
	v.URL = ReadString(r)
	v.Size = int32(ReadInt(r))
	v.MimeType = ReadString(r)
	ReadInt(r)
	_cntAttributes := ReadInt(r)
	if err := checkVectorCount(_cntAttributes); err != nil {
		return nil, err
	}
	v.Attributes = make([]DocumentAttributeClass, _cntAttributes)
	for _iAttributes := range v.Attributes {
		_objAttributes, _ := ReadTLObject(r)
		v.Attributes[_iAttributes] = _objAttributes.(DocumentAttributeClass)
	}
	return v, nil
}

func init() {
	Registry[WebDocumentNoProxyTypeID] = func(r io.Reader) (TLObject, error) {
		return DecodeWebDocumentNoProxy(r)
	}
}

// InputWebDocumentTypeID is the constructor ID for TL type inputWebDocument.
const InputWebDocumentTypeID = 0x9bed434d

// InputWebDocument represents the TL constructor inputWebDocument (0x9bed434d).
//
// See https://core.telegram.org/constructor/inputWebDocument for reference.
type InputWebDocument struct {
	URL        string                   `json:"url,omitempty"`
	Size       int32                    `json:"size,omitempty"`
	MimeType   string                   `json:"mime_type,omitempty"`
	Attributes []DocumentAttributeClass `json:"attributes,omitempty"`
}

// ConstructorID returns the TL constructor identifier 0x9bed434d.
func (v *InputWebDocument) ConstructorID() uint32 {
	return InputWebDocumentTypeID
}

// Encode serializes InputWebDocument to a bytes.Buffer using the TL binary protocol.
func (v *InputWebDocument) Encode(b *bytes.Buffer) error {
	WriteInt(b, InputWebDocumentTypeID)
	WriteString(b, v.URL)
	WriteInt(b, uint32(v.Size))
	WriteString(b, v.MimeType)
	WriteInt(b, 0x1cb5c415)
	WriteInt(b, uint32(len(v.Attributes)))
	for _, _item := range v.Attributes {
		EncodeTLObject(b, _item)
	}
	return nil
}

// DecodeInputWebDocument deserializes a InputWebDocument from a reader using the TL binary protocol.
func DecodeInputWebDocument(r io.Reader) (*InputWebDocument, error) {
	v := &InputWebDocument{}
	v.URL = ReadString(r)
	v.Size = int32(ReadInt(r))
	v.MimeType = ReadString(r)
	ReadInt(r)
	_cntAttributes := ReadInt(r)
	if err := checkVectorCount(_cntAttributes); err != nil {
		return nil, err
	}
	v.Attributes = make([]DocumentAttributeClass, _cntAttributes)
	for _iAttributes := range v.Attributes {
		_objAttributes, _ := ReadTLObject(r)
		v.Attributes[_iAttributes] = _objAttributes.(DocumentAttributeClass)
	}
	return v, nil
}

func init() {
	Registry[InputWebDocumentTypeID] = func(r io.Reader) (TLObject, error) {
		return DecodeInputWebDocument(r)
	}
}

// WebPageAttributeClass is the interface for TL type WebPageAttribute.
// Implementations must satisfy TLObject and are used to represent
// any constructor of the WebPageAttribute TL type.
type WebPageAttributeClass interface {
	TLObject
	isWebPageAttribute()
}

// WebPageAttributeThemeTypeID is the constructor ID for TL type webPageAttributeTheme.
const WebPageAttributeThemeTypeID = 0x54b56617

// WebPageAttributeStoryTypeID is the constructor ID for TL type webPageAttributeStory.
const WebPageAttributeStoryTypeID = 0x2e94c3e7

// WebPageAttributeStickerSetTypeID is the constructor ID for TL type webPageAttributeStickerSet.
const WebPageAttributeStickerSetTypeID = 0x50cc03d3

// WebPageAttributeUniqueStarGiftTypeID is the constructor ID for TL type webPageAttributeUniqueStarGift.
const WebPageAttributeUniqueStarGiftTypeID = 0xcf6f6db8

// WebPageAttributeStarGiftCollectionTypeID is the constructor ID for TL type webPageAttributeStarGiftCollection.
const WebPageAttributeStarGiftCollectionTypeID = 0x31cad303

// WebPageAttributeStarGiftAuctionTypeID is the constructor ID for TL type webPageAttributeStarGiftAuction.
const WebPageAttributeStarGiftAuctionTypeID = 0x01c641c2

// WebPageAttributeAiComposeToneTypeID is the constructor ID for TL type webPageAttributeAiComposeTone.
const WebPageAttributeAiComposeToneTypeID = 0x7781fe18

// isWebPageAttribute marks WebPageAttributeTheme as implementing the WebPageAttributeClass interface.
func (*WebPageAttributeTheme) isWebPageAttribute() {}

// isWebPageAttribute marks WebPageAttributeStory as implementing the WebPageAttributeClass interface.
func (*WebPageAttributeStory) isWebPageAttribute() {}

// isWebPageAttribute marks WebPageAttributeStickerSet as implementing the WebPageAttributeClass interface.
func (*WebPageAttributeStickerSet) isWebPageAttribute() {}

// isWebPageAttribute marks WebPageAttributeUniqueStarGift as implementing the WebPageAttributeClass interface.
func (*WebPageAttributeUniqueStarGift) isWebPageAttribute() {}

// isWebPageAttribute marks WebPageAttributeStarGiftCollection as implementing the WebPageAttributeClass interface.
func (*WebPageAttributeStarGiftCollection) isWebPageAttribute() {}

// isWebPageAttribute marks WebPageAttributeStarGiftAuction as implementing the WebPageAttributeClass interface.
func (*WebPageAttributeStarGiftAuction) isWebPageAttribute() {}

// isWebPageAttribute marks WebPageAttributeAiComposeTone as implementing the WebPageAttributeClass interface.
func (*WebPageAttributeAiComposeTone) isWebPageAttribute() {}

// WebPageAttributeTheme represents the TL constructor webPageAttributeTheme (0x54b56617).
//
// See https://core.telegram.org/constructor/webPageAttributeTheme for reference.
type WebPageAttributeTheme struct {
	Flags     Fields          `json:"-"`
	Documents []DocumentClass `json:"documents,omitempty"`
	Settings  *ThemeSettings  `json:"settings,omitempty"`
}

// SetFlags computes flags from non-zero optional fields.
func (v *WebPageAttributeTheme) SetFlags() {
	if v.Documents != nil {
		v.Flags.Set(0)
	}
	if v.Settings != nil {
		v.Flags.Set(1)
	}
}

// ConstructorID returns the TL constructor identifier 0x54b56617.
func (v *WebPageAttributeTheme) ConstructorID() uint32 {
	return WebPageAttributeThemeTypeID
}

// Encode serializes WebPageAttributeTheme to a bytes.Buffer using the TL binary protocol.
func (v *WebPageAttributeTheme) Encode(b *bytes.Buffer) error {
	WriteInt(b, WebPageAttributeThemeTypeID)
	v.SetFlags()
	WriteInt(b, uint32(v.Flags))
	if v.Flags.Has(0) {
		WriteInt(b, 0x1cb5c415)
		WriteInt(b, uint32(len(v.Documents)))
		for _, _item := range v.Documents {
			EncodeTLObject(b, _item)
		}
	}
	if v.Flags.Has(1) {
		EncodeTLObject(b, v.Settings)
	}
	return nil
}

// DecodeWebPageAttributeTheme deserializes a WebPageAttributeTheme from a reader using the TL binary protocol.
func DecodeWebPageAttributeTheme(r io.Reader) (*WebPageAttributeTheme, error) {
	v := &WebPageAttributeTheme{}
	{
		var _f uint32
		_f, _ = ReadIntErr(r)
		v.Flags = Fields(_f)
	}
	if v.Flags.Has(0) {
		ReadInt(r)
		_cntDocuments := ReadInt(r)
		if err := checkVectorCount(_cntDocuments); err != nil {
			return nil, err
		}
		v.Documents = make([]DocumentClass, _cntDocuments)
		for _iDocuments := range v.Documents {
			_objDocuments, _ := ReadTLObject(r)
			v.Documents[_iDocuments] = _objDocuments.(DocumentClass)
		}
	}
	if v.Flags.Has(1) {
		_objSettings, _ := ReadTLObject(r)
		v.Settings = _objSettings.(*ThemeSettings)
	}
	return v, nil
}

func init() {
	Registry[WebPageAttributeThemeTypeID] = func(r io.Reader) (TLObject, error) {
		return DecodeWebPageAttributeTheme(r)
	}
}

// WebPageAttributeStory represents the TL constructor webPageAttributeStory (0x2e94c3e7).
//
// See https://core.telegram.org/constructor/webPageAttributeStory for reference.
type WebPageAttributeStory struct {
	Flags Fields         `json:"-"`
	Peer  PeerClass      `json:"peer,omitempty"`
	ID    int32          `json:"id,omitempty"`
	Story StoryItemClass `json:"story,omitempty"`
}

// SetFlags computes flags from non-zero optional fields.
func (v *WebPageAttributeStory) SetFlags() {
	if v.Story != nil {
		v.Flags.Set(0)
	}
}

// ConstructorID returns the TL constructor identifier 0x2e94c3e7.
func (v *WebPageAttributeStory) ConstructorID() uint32 {
	return WebPageAttributeStoryTypeID
}

// Encode serializes WebPageAttributeStory to a bytes.Buffer using the TL binary protocol.
func (v *WebPageAttributeStory) Encode(b *bytes.Buffer) error {
	WriteInt(b, WebPageAttributeStoryTypeID)
	v.SetFlags()
	WriteInt(b, uint32(v.Flags))
	EncodeTLObject(b, v.Peer)
	WriteInt(b, uint32(v.ID))
	if v.Flags.Has(0) {
		EncodeTLObject(b, v.Story)
	}
	return nil
}

// DecodeWebPageAttributeStory deserializes a WebPageAttributeStory from a reader using the TL binary protocol.
func DecodeWebPageAttributeStory(r io.Reader) (*WebPageAttributeStory, error) {
	v := &WebPageAttributeStory{}
	{
		var _f uint32
		_f, _ = ReadIntErr(r)
		v.Flags = Fields(_f)
	}
	_objPeer, _ := ReadTLObject(r)
	v.Peer = _objPeer.(PeerClass)
	v.ID = int32(ReadInt(r))
	if v.Flags.Has(0) {
		_objStory, _ := ReadTLObject(r)
		v.Story = _objStory.(StoryItemClass)
	}
	return v, nil
}

func init() {
	Registry[WebPageAttributeStoryTypeID] = func(r io.Reader) (TLObject, error) {
		return DecodeWebPageAttributeStory(r)
	}
}

// WebPageAttributeStickerSet represents the TL constructor webPageAttributeStickerSet (0x50cc03d3).
//
// See https://core.telegram.org/constructor/webPageAttributeStickerSet for reference.
type WebPageAttributeStickerSet struct {
	Flags     Fields          `json:"-"`
	Emojis    bool            `json:"emojis,omitempty"`
	TextColor bool            `json:"text_color,omitempty"`
	Stickers  []DocumentClass `json:"stickers,omitempty"`
}

// SetFlags computes flags from non-zero optional fields.
func (v *WebPageAttributeStickerSet) SetFlags() {
	if v.Emojis {
		v.Flags.Set(0)
	}
	if v.TextColor {
		v.Flags.Set(1)
	}
}

// ConstructorID returns the TL constructor identifier 0x50cc03d3.
func (v *WebPageAttributeStickerSet) ConstructorID() uint32 {
	return WebPageAttributeStickerSetTypeID
}

// Encode serializes WebPageAttributeStickerSet to a bytes.Buffer using the TL binary protocol.
func (v *WebPageAttributeStickerSet) Encode(b *bytes.Buffer) error {
	WriteInt(b, WebPageAttributeStickerSetTypeID)
	v.SetFlags()
	WriteInt(b, uint32(v.Flags))
	WriteInt(b, 0x1cb5c415)
	WriteInt(b, uint32(len(v.Stickers)))
	for _, _item := range v.Stickers {
		EncodeTLObject(b, _item)
	}
	return nil
}

// DecodeWebPageAttributeStickerSet deserializes a WebPageAttributeStickerSet from a reader using the TL binary protocol.
func DecodeWebPageAttributeStickerSet(r io.Reader) (*WebPageAttributeStickerSet, error) {
	v := &WebPageAttributeStickerSet{}
	{
		var _f uint32
		_f, _ = ReadIntErr(r)
		v.Flags = Fields(_f)
	}
	v.Emojis = v.Flags.Has(0)
	v.TextColor = v.Flags.Has(1)
	ReadInt(r)
	_cntStickers := ReadInt(r)
	if err := checkVectorCount(_cntStickers); err != nil {
		return nil, err
	}
	v.Stickers = make([]DocumentClass, _cntStickers)
	for _iStickers := range v.Stickers {
		_objStickers, _ := ReadTLObject(r)
		v.Stickers[_iStickers] = _objStickers.(DocumentClass)
	}
	return v, nil
}

func init() {
	Registry[WebPageAttributeStickerSetTypeID] = func(r io.Reader) (TLObject, error) {
		return DecodeWebPageAttributeStickerSet(r)
	}
}

// WebPageAttributeUniqueStarGift represents the TL constructor webPageAttributeUniqueStarGift (0xcf6f6db8).
//
// See https://core.telegram.org/constructor/webPageAttributeUniqueStarGift for reference.
type WebPageAttributeUniqueStarGift struct {
	Gift StarGiftClass `json:"gift,omitempty"`
}

// ConstructorID returns the TL constructor identifier 0xcf6f6db8.
func (v *WebPageAttributeUniqueStarGift) ConstructorID() uint32 {
	return WebPageAttributeUniqueStarGiftTypeID
}

// Encode serializes WebPageAttributeUniqueStarGift to a bytes.Buffer using the TL binary protocol.
func (v *WebPageAttributeUniqueStarGift) Encode(b *bytes.Buffer) error {
	WriteInt(b, WebPageAttributeUniqueStarGiftTypeID)
	EncodeTLObject(b, v.Gift)
	return nil
}

// DecodeWebPageAttributeUniqueStarGift deserializes a WebPageAttributeUniqueStarGift from a reader using the TL binary protocol.
func DecodeWebPageAttributeUniqueStarGift(r io.Reader) (*WebPageAttributeUniqueStarGift, error) {
	v := &WebPageAttributeUniqueStarGift{}
	_objGift, _ := ReadTLObject(r)
	v.Gift = _objGift.(StarGiftClass)
	return v, nil
}

func init() {
	Registry[WebPageAttributeUniqueStarGiftTypeID] = func(r io.Reader) (TLObject, error) {
		return DecodeWebPageAttributeUniqueStarGift(r)
	}
}

// WebPageAttributeStarGiftCollection represents the TL constructor webPageAttributeStarGiftCollection (0x31cad303).
//
// See https://core.telegram.org/constructor/webPageAttributeStarGiftCollection for reference.
type WebPageAttributeStarGiftCollection struct {
	Icons []DocumentClass `json:"icons,omitempty"`
}

// ConstructorID returns the TL constructor identifier 0x31cad303.
func (v *WebPageAttributeStarGiftCollection) ConstructorID() uint32 {
	return WebPageAttributeStarGiftCollectionTypeID
}

// Encode serializes WebPageAttributeStarGiftCollection to a bytes.Buffer using the TL binary protocol.
func (v *WebPageAttributeStarGiftCollection) Encode(b *bytes.Buffer) error {
	WriteInt(b, WebPageAttributeStarGiftCollectionTypeID)
	WriteInt(b, 0x1cb5c415)
	WriteInt(b, uint32(len(v.Icons)))
	for _, _item := range v.Icons {
		EncodeTLObject(b, _item)
	}
	return nil
}

// DecodeWebPageAttributeStarGiftCollection deserializes a WebPageAttributeStarGiftCollection from a reader using the TL binary protocol.
func DecodeWebPageAttributeStarGiftCollection(r io.Reader) (*WebPageAttributeStarGiftCollection, error) {
	v := &WebPageAttributeStarGiftCollection{}
	ReadInt(r)
	_cntIcons := ReadInt(r)
	if err := checkVectorCount(_cntIcons); err != nil {
		return nil, err
	}
	v.Icons = make([]DocumentClass, _cntIcons)
	for _iIcons := range v.Icons {
		_objIcons, _ := ReadTLObject(r)
		v.Icons[_iIcons] = _objIcons.(DocumentClass)
	}
	return v, nil
}

func init() {
	Registry[WebPageAttributeStarGiftCollectionTypeID] = func(r io.Reader) (TLObject, error) {
		return DecodeWebPageAttributeStarGiftCollection(r)
	}
}

// WebPageAttributeStarGiftAuction represents the TL constructor webPageAttributeStarGiftAuction (0x01c641c2).
//
// See https://core.telegram.org/constructor/webPageAttributeStarGiftAuction for reference.
type WebPageAttributeStarGiftAuction struct {
	Gift    StarGiftClass `json:"gift,omitempty"`
	EndDate int32         `json:"end_date,omitempty"`
}

// ConstructorID returns the TL constructor identifier 0x01c641c2.
func (v *WebPageAttributeStarGiftAuction) ConstructorID() uint32 {
	return WebPageAttributeStarGiftAuctionTypeID
}

// Encode serializes WebPageAttributeStarGiftAuction to a bytes.Buffer using the TL binary protocol.
func (v *WebPageAttributeStarGiftAuction) Encode(b *bytes.Buffer) error {
	WriteInt(b, WebPageAttributeStarGiftAuctionTypeID)
	EncodeTLObject(b, v.Gift)
	WriteInt(b, uint32(v.EndDate))
	return nil
}

// DecodeWebPageAttributeStarGiftAuction deserializes a WebPageAttributeStarGiftAuction from a reader using the TL binary protocol.
func DecodeWebPageAttributeStarGiftAuction(r io.Reader) (*WebPageAttributeStarGiftAuction, error) {
	v := &WebPageAttributeStarGiftAuction{}
	_objGift, _ := ReadTLObject(r)
	v.Gift = _objGift.(StarGiftClass)
	v.EndDate = int32(ReadInt(r))
	return v, nil
}

func init() {
	Registry[WebPageAttributeStarGiftAuctionTypeID] = func(r io.Reader) (TLObject, error) {
		return DecodeWebPageAttributeStarGiftAuction(r)
	}
}

// WebPageAttributeAiComposeTone represents the TL constructor webPageAttributeAiComposeTone (0x7781fe18).
//
// See https://core.telegram.org/constructor/webPageAttributeAiComposeTone for reference.
type WebPageAttributeAiComposeTone struct {
	EmojiID int64 `json:"emoji_id,omitempty"`
}

// ConstructorID returns the TL constructor identifier 0x7781fe18.
func (v *WebPageAttributeAiComposeTone) ConstructorID() uint32 {
	return WebPageAttributeAiComposeToneTypeID
}

// Encode serializes WebPageAttributeAiComposeTone to a bytes.Buffer using the TL binary protocol.
func (v *WebPageAttributeAiComposeTone) Encode(b *bytes.Buffer) error {
	WriteInt(b, WebPageAttributeAiComposeToneTypeID)
	WriteLong(b, v.EmojiID)
	return nil
}

// DecodeWebPageAttributeAiComposeTone deserializes a WebPageAttributeAiComposeTone from a reader using the TL binary protocol.
func DecodeWebPageAttributeAiComposeTone(r io.Reader) (*WebPageAttributeAiComposeTone, error) {
	v := &WebPageAttributeAiComposeTone{}
	v.EmojiID = ReadLong(r)
	return v, nil
}

func init() {
	Registry[WebPageAttributeAiComposeToneTypeID] = func(r io.Reader) (TLObject, error) {
		return DecodeWebPageAttributeAiComposeTone(r)
	}
}

// VideoSizeClass is the interface for TL type VideoSize.
// Implementations must satisfy TLObject and are used to represent
// any constructor of the VideoSize TL type.
type VideoSizeClass interface {
	TLObject
	isVideoSize()
}

// VideoSizeTypeID is the constructor ID for TL type videoSize.
const VideoSizeTypeID = 0xde33b094

// VideoSizeEmojiMarkupTypeID is the constructor ID for TL type videoSizeEmojiMarkup.
const VideoSizeEmojiMarkupTypeID = 0xf85c413c

// VideoSizeStickerMarkupTypeID is the constructor ID for TL type videoSizeStickerMarkup.
const VideoSizeStickerMarkupTypeID = 0x0da082fe

// isVideoSize marks VideoSize as implementing the VideoSizeClass interface.
func (*VideoSize) isVideoSize() {}

// isVideoSize marks VideoSizeEmojiMarkup as implementing the VideoSizeClass interface.
func (*VideoSizeEmojiMarkup) isVideoSize() {}

// isVideoSize marks VideoSizeStickerMarkup as implementing the VideoSizeClass interface.
func (*VideoSizeStickerMarkup) isVideoSize() {}

// VideoSize represents the TL constructor videoSize (0xde33b094).
//
// See https://core.telegram.org/constructor/videoSize for reference.
type VideoSize struct {
	Flags        Fields  `json:"-"`
	Type         string  `json:"type,omitempty"`
	W            int32   `json:"w,omitempty"`
	H            int32   `json:"h,omitempty"`
	Size         int32   `json:"size,omitempty"`
	VideoStartTs float64 `json:"video_start_ts,omitempty"`
}

// SetFlags computes flags from non-zero optional fields.
func (v *VideoSize) SetFlags() {
	if v.VideoStartTs != 0 {
		v.Flags.Set(0)
	}
}

// ConstructorID returns the TL constructor identifier 0xde33b094.
func (v *VideoSize) ConstructorID() uint32 {
	return VideoSizeTypeID
}

// Encode serializes VideoSize to a bytes.Buffer using the TL binary protocol.
func (v *VideoSize) Encode(b *bytes.Buffer) error {
	WriteInt(b, VideoSizeTypeID)
	v.SetFlags()
	WriteInt(b, uint32(v.Flags))
	WriteString(b, v.Type)
	WriteInt(b, uint32(v.W))
	WriteInt(b, uint32(v.H))
	WriteInt(b, uint32(v.Size))
	if v.Flags.Has(0) {
		WriteDouble(b, v.VideoStartTs)
	}
	return nil
}

// DecodeVideoSize deserializes a VideoSize from a reader using the TL binary protocol.
func DecodeVideoSize(r io.Reader) (*VideoSize, error) {
	v := &VideoSize{}
	{
		var _f uint32
		_f, _ = ReadIntErr(r)
		v.Flags = Fields(_f)
	}
	v.Type = ReadString(r)
	v.W = int32(ReadInt(r))
	v.H = int32(ReadInt(r))
	v.Size = int32(ReadInt(r))
	if v.Flags.Has(0) {
		v.VideoStartTs = ReadDouble(r)
	}
	return v, nil
}

func init() {
	Registry[VideoSizeTypeID] = func(r io.Reader) (TLObject, error) {
		return DecodeVideoSize(r)
	}
}

// VideoSizeEmojiMarkup represents the TL constructor videoSizeEmojiMarkup (0xf85c413c).
//
// See https://core.telegram.org/constructor/videoSizeEmojiMarkup for reference.
type VideoSizeEmojiMarkup struct {
	EmojiID          int64   `json:"emoji_id,omitempty"`
	BackgroundColors []int32 `json:"background_colors,omitempty"`
}

// ConstructorID returns the TL constructor identifier 0xf85c413c.
func (v *VideoSizeEmojiMarkup) ConstructorID() uint32 {
	return VideoSizeEmojiMarkupTypeID
}

// Encode serializes VideoSizeEmojiMarkup to a bytes.Buffer using the TL binary protocol.
func (v *VideoSizeEmojiMarkup) Encode(b *bytes.Buffer) error {
	WriteInt(b, VideoSizeEmojiMarkupTypeID)
	WriteLong(b, v.EmojiID)
	WriteVectorInt(b, v.BackgroundColors)
	return nil
}

// DecodeVideoSizeEmojiMarkup deserializes a VideoSizeEmojiMarkup from a reader using the TL binary protocol.
func DecodeVideoSizeEmojiMarkup(r io.Reader) (*VideoSizeEmojiMarkup, error) {
	v := &VideoSizeEmojiMarkup{}
	v.EmojiID = ReadLong(r)
	v.BackgroundColors = ReadVectorInt(r)
	return v, nil
}

func init() {
	Registry[VideoSizeEmojiMarkupTypeID] = func(r io.Reader) (TLObject, error) {
		return DecodeVideoSizeEmojiMarkup(r)
	}
}

// VideoSizeStickerMarkup represents the TL constructor videoSizeStickerMarkup (0x0da082fe).
//
// See https://core.telegram.org/constructor/videoSizeStickerMarkup for reference.
type VideoSizeStickerMarkup struct {
	Stickerset       InputStickerSetClass `json:"stickerset,omitempty"`
	StickerID        int64                `json:"sticker_id,omitempty"`
	BackgroundColors []int32              `json:"background_colors,omitempty"`
}

// ConstructorID returns the TL constructor identifier 0x0da082fe.
func (v *VideoSizeStickerMarkup) ConstructorID() uint32 {
	return VideoSizeStickerMarkupTypeID
}

// Encode serializes VideoSizeStickerMarkup to a bytes.Buffer using the TL binary protocol.
func (v *VideoSizeStickerMarkup) Encode(b *bytes.Buffer) error {
	WriteInt(b, VideoSizeStickerMarkupTypeID)
	EncodeTLObject(b, v.Stickerset)
	WriteLong(b, v.StickerID)
	WriteVectorInt(b, v.BackgroundColors)
	return nil
}

// DecodeVideoSizeStickerMarkup deserializes a VideoSizeStickerMarkup from a reader using the TL binary protocol.
func DecodeVideoSizeStickerMarkup(r io.Reader) (*VideoSizeStickerMarkup, error) {
	v := &VideoSizeStickerMarkup{}
	_objStickerset, _ := ReadTLObject(r)
	v.Stickerset = _objStickerset.(InputStickerSetClass)
	v.StickerID = ReadLong(r)
	v.BackgroundColors = ReadVectorInt(r)
	return v, nil
}

func init() {
	Registry[VideoSizeStickerMarkupTypeID] = func(r io.Reader) (TLObject, error) {
		return DecodeVideoSizeStickerMarkup(r)
	}
}
