// Code generated by tlgen. DO NOT EDIT.

package tg

import (
	"bytes"
	"context"
	"fmt"
	"io"
)

// PhoneGetCallConfigTypeID is the constructor ID for the RPC function phone.getCallConfig.
const PhoneGetCallConfigTypeID = 0x55451fa9

// PhoneGetCallConfigRequest represents TL type `phone.getCallConfig#55451fa9`.
//
// See https://core.telegram.org/method/phone/getCallConfig for reference.
type PhoneGetCallConfigRequest struct {
}

// ConstructorID returns the TL constructor identifier 0x55451fa9.
func (v *PhoneGetCallConfigRequest) ConstructorID() uint32 {
	return PhoneGetCallConfigTypeID
}

// Encode serializes PhoneGetCallConfigRequest to a bytes.Buffer using the TL binary protocol.
func (v *PhoneGetCallConfigRequest) Encode(b *bytes.Buffer) error {
	WriteInt(b, PhoneGetCallConfigTypeID)
	return nil
}

// PhoneGetCallConfig invokes the phone.getCallConfig RPC method on the server.
//
// Parameters:
//   - ctx: context for cancellation and timeout
//   - req: the request parameters
//
// Returns the result of the RPC call, or an error if the invocation fails.
func (c *RPCClient) PhoneGetCallConfig(ctx context.Context) (*DataJSON, error) {
	result, err := c.invoke(ctx, &PhoneGetCallConfigRequest{}, func(r io.Reader) (TLObject, error) {
		return ReadTLObject(r)
	})
	if err != nil {
		return nil, err
	}
	if _c, _ok := result.(*DataJSON); _ok {
		return _c, nil
	}
	return nil, fmt.Errorf("unexpected result type %T", result)
}

// PhoneRequestCallTypeID is the constructor ID for the RPC function phone.requestCall.
const PhoneRequestCallTypeID = 0x42ff96ed

// PhoneRequestCallRequest represents TL type `phone.requestCall#42ff96ed`.
//
// See https://core.telegram.org/method/phone/requestCall for reference.
type PhoneRequestCallRequest struct {
	Flags    Fields             `json:"-"`
	Video    bool               `json:"video,omitempty"`
	UserID   InputUserClass     `json:"user_id,omitempty"`
	RandomID int32              `json:"random_id,omitempty"`
	GAHash   []byte             `json:"ga_hash,omitempty"`
	Protocol *PhoneCallProtocol `json:"protocol,omitempty"`
}

// SetFlags computes flags from non-zero optional fields.
func (v *PhoneRequestCallRequest) SetFlags() {
	if v.Video {
		v.Flags.Set(0)
	}
}

// ConstructorID returns the TL constructor identifier 0x42ff96ed.
func (v *PhoneRequestCallRequest) ConstructorID() uint32 {
	return PhoneRequestCallTypeID
}

// Encode serializes PhoneRequestCallRequest to a bytes.Buffer using the TL binary protocol.
func (v *PhoneRequestCallRequest) Encode(b *bytes.Buffer) error {
	WriteInt(b, PhoneRequestCallTypeID)
	v.SetFlags()
	WriteInt(b, uint32(v.Flags))
	EncodeTLObject(b, v.UserID)
	WriteInt(b, uint32(v.RandomID))
	WriteBytes(b, v.GAHash)
	EncodeTLObject(b, v.Protocol)
	return nil
}

// PhoneRequestCall invokes the phone.requestCall RPC method on the server.
//
// Parameters:
//   - ctx: context for cancellation and timeout
//   - req: the request parameters
//
// Returns the result of the RPC call, or an error if the invocation fails.
func (c *RPCClient) PhoneRequestCall(ctx context.Context, req *PhoneRequestCallRequest) (PhoneCallClass, error) {
	result, err := c.invoke(ctx, req, func(r io.Reader) (TLObject, error) {
		return ReadTLObject(r)
	})
	if err != nil {
		return nil, err
	}
	if _c, _ok := result.(PhoneCallClass); _ok {
		return _c, nil
	}
	return nil, fmt.Errorf("unexpected result type %T", result)
}

// PhoneAcceptCallTypeID is the constructor ID for the RPC function phone.acceptCall.
const PhoneAcceptCallTypeID = 0x3bd2b4a0

// PhoneAcceptCallRequest represents TL type `phone.acceptCall#3bd2b4a0`.
//
// See https://core.telegram.org/method/phone/acceptCall for reference.
type PhoneAcceptCallRequest struct {
	Peer     *InputPhoneCall    `json:"peer,omitempty"`
	GB       []byte             `json:"gb,omitempty"`
	Protocol *PhoneCallProtocol `json:"protocol,omitempty"`
}

// ConstructorID returns the TL constructor identifier 0x3bd2b4a0.
func (v *PhoneAcceptCallRequest) ConstructorID() uint32 {
	return PhoneAcceptCallTypeID
}

// Encode serializes PhoneAcceptCallRequest to a bytes.Buffer using the TL binary protocol.
func (v *PhoneAcceptCallRequest) Encode(b *bytes.Buffer) error {
	WriteInt(b, PhoneAcceptCallTypeID)
	EncodeTLObject(b, v.Peer)
	WriteBytes(b, v.GB)
	EncodeTLObject(b, v.Protocol)
	return nil
}

// PhoneAcceptCall invokes the phone.acceptCall RPC method on the server.
//
// Parameters:
//   - ctx: context for cancellation and timeout
//   - req: the request parameters
//
// Returns the result of the RPC call, or an error if the invocation fails.
func (c *RPCClient) PhoneAcceptCall(ctx context.Context, req *PhoneAcceptCallRequest) (PhoneCallClass, error) {
	result, err := c.invoke(ctx, req, func(r io.Reader) (TLObject, error) {
		return ReadTLObject(r)
	})
	if err != nil {
		return nil, err
	}
	if _c, _ok := result.(PhoneCallClass); _ok {
		return _c, nil
	}
	return nil, fmt.Errorf("unexpected result type %T", result)
}

// PhoneConfirmCallTypeID is the constructor ID for the RPC function phone.confirmCall.
const PhoneConfirmCallTypeID = 0x2efe1722

// PhoneConfirmCallRequest represents TL type `phone.confirmCall#2efe1722`.
//
// See https://core.telegram.org/method/phone/confirmCall for reference.
type PhoneConfirmCallRequest struct {
	Peer           *InputPhoneCall    `json:"peer,omitempty"`
	GA             []byte             `json:"ga,omitempty"`
	KeyFingerprint int64              `json:"key_fingerprint,omitempty"`
	Protocol       *PhoneCallProtocol `json:"protocol,omitempty"`
}

// ConstructorID returns the TL constructor identifier 0x2efe1722.
func (v *PhoneConfirmCallRequest) ConstructorID() uint32 {
	return PhoneConfirmCallTypeID
}

// Encode serializes PhoneConfirmCallRequest to a bytes.Buffer using the TL binary protocol.
func (v *PhoneConfirmCallRequest) Encode(b *bytes.Buffer) error {
	WriteInt(b, PhoneConfirmCallTypeID)
	EncodeTLObject(b, v.Peer)
	WriteBytes(b, v.GA)
	WriteLong(b, v.KeyFingerprint)
	EncodeTLObject(b, v.Protocol)
	return nil
}

// PhoneConfirmCall invokes the phone.confirmCall RPC method on the server.
//
// Parameters:
//   - ctx: context for cancellation and timeout
//   - req: the request parameters
//
// Returns the result of the RPC call, or an error if the invocation fails.
func (c *RPCClient) PhoneConfirmCall(ctx context.Context, req *PhoneConfirmCallRequest) (PhoneCallClass, error) {
	result, err := c.invoke(ctx, req, func(r io.Reader) (TLObject, error) {
		return ReadTLObject(r)
	})
	if err != nil {
		return nil, err
	}
	if _c, _ok := result.(PhoneCallClass); _ok {
		return _c, nil
	}
	return nil, fmt.Errorf("unexpected result type %T", result)
}

// PhoneReceivedCallTypeID is the constructor ID for the RPC function phone.receivedCall.
const PhoneReceivedCallTypeID = 0x17d54f61

// PhoneReceivedCallRequest represents TL type `phone.receivedCall#17d54f61`.
//
// See https://core.telegram.org/method/phone/receivedCall for reference.
type PhoneReceivedCallRequest struct {
	Peer *InputPhoneCall `json:"peer,omitempty"`
}

// ConstructorID returns the TL constructor identifier 0x17d54f61.
func (v *PhoneReceivedCallRequest) ConstructorID() uint32 {
	return PhoneReceivedCallTypeID
}

// Encode serializes PhoneReceivedCallRequest to a bytes.Buffer using the TL binary protocol.
func (v *PhoneReceivedCallRequest) Encode(b *bytes.Buffer) error {
	WriteInt(b, PhoneReceivedCallTypeID)
	EncodeTLObject(b, v.Peer)
	return nil
}

// PhoneReceivedCall invokes the phone.receivedCall RPC method on the server.
//
// Parameters:
//   - ctx: context for cancellation and timeout
//   - req: the request parameters
//
// Returns the result of the RPC call, or an error if the invocation fails.
func (c *RPCClient) PhoneReceivedCall(ctx context.Context, req *PhoneReceivedCallRequest) (bool, error) {
	result, err := c.invoke(ctx, req, func(r io.Reader) (TLObject, error) {
		return ReadTLObject(r)
	})
	if err != nil {
		return false, err
	}
	_ = result
	return true, nil
}

// PhoneDiscardCallTypeID is the constructor ID for the RPC function phone.discardCall.
const PhoneDiscardCallTypeID = 0xb2cbc1c0

// PhoneDiscardCallRequest represents TL type `phone.discardCall#b2cbc1c0`.
//
// See https://core.telegram.org/method/phone/discardCall for reference.
type PhoneDiscardCallRequest struct {
	Flags        Fields                      `json:"-"`
	Video        bool                        `json:"video,omitempty"`
	Peer         *InputPhoneCall             `json:"peer,omitempty"`
	Duration     int32                       `json:"duration,omitempty"`
	Reason       PhoneCallDiscardReasonClass `json:"reason,omitempty"`
	ConnectionID int64                       `json:"connection_id,omitempty"`
}

// SetFlags computes flags from non-zero optional fields.
func (v *PhoneDiscardCallRequest) SetFlags() {
	if v.Video {
		v.Flags.Set(0)
	}
}

// ConstructorID returns the TL constructor identifier 0xb2cbc1c0.
func (v *PhoneDiscardCallRequest) ConstructorID() uint32 {
	return PhoneDiscardCallTypeID
}

// Encode serializes PhoneDiscardCallRequest to a bytes.Buffer using the TL binary protocol.
func (v *PhoneDiscardCallRequest) Encode(b *bytes.Buffer) error {
	WriteInt(b, PhoneDiscardCallTypeID)
	v.SetFlags()
	WriteInt(b, uint32(v.Flags))
	EncodeTLObject(b, v.Peer)
	WriteInt(b, uint32(v.Duration))
	EncodeTLObject(b, v.Reason)
	WriteLong(b, v.ConnectionID)
	return nil
}

// PhoneDiscardCall invokes the phone.discardCall RPC method on the server.
//
// Parameters:
//   - ctx: context for cancellation and timeout
//   - req: the request parameters
//
// Returns the result of the RPC call, or an error if the invocation fails.
func (c *RPCClient) PhoneDiscardCall(ctx context.Context, req *PhoneDiscardCallRequest) (UpdatesClass, error) {
	result, err := c.invoke(ctx, req, func(r io.Reader) (TLObject, error) {
		return ReadTLObject(r)
	})
	if err != nil {
		return nil, err
	}
	if _c, _ok := result.(UpdatesClass); _ok {
		return _c, nil
	}
	return nil, fmt.Errorf("unexpected result type %T", result)
}

// PhoneSetCallRatingTypeID is the constructor ID for the RPC function phone.setCallRating.
const PhoneSetCallRatingTypeID = 0x59ead627

// PhoneSetCallRatingRequest represents TL type `phone.setCallRating#59ead627`.
//
// See https://core.telegram.org/method/phone/setCallRating for reference.
type PhoneSetCallRatingRequest struct {
	Flags          Fields          `json:"-"`
	UserInitiative bool            `json:"user_initiative,omitempty"`
	Peer           *InputPhoneCall `json:"peer,omitempty"`
	Rating         int32           `json:"rating,omitempty"`
	Comment        string          `json:"comment,omitempty"`
}

// SetFlags computes flags from non-zero optional fields.
func (v *PhoneSetCallRatingRequest) SetFlags() {
	if v.UserInitiative {
		v.Flags.Set(0)
	}
}

// ConstructorID returns the TL constructor identifier 0x59ead627.
func (v *PhoneSetCallRatingRequest) ConstructorID() uint32 {
	return PhoneSetCallRatingTypeID
}

// Encode serializes PhoneSetCallRatingRequest to a bytes.Buffer using the TL binary protocol.
func (v *PhoneSetCallRatingRequest) Encode(b *bytes.Buffer) error {
	WriteInt(b, PhoneSetCallRatingTypeID)
	v.SetFlags()
	WriteInt(b, uint32(v.Flags))
	EncodeTLObject(b, v.Peer)
	WriteInt(b, uint32(v.Rating))
	WriteString(b, v.Comment)
	return nil
}

// PhoneSetCallRating invokes the phone.setCallRating RPC method on the server.
//
// Parameters:
//   - ctx: context for cancellation and timeout
//   - req: the request parameters
//
// Returns the result of the RPC call, or an error if the invocation fails.
func (c *RPCClient) PhoneSetCallRating(ctx context.Context, req *PhoneSetCallRatingRequest) (UpdatesClass, error) {
	result, err := c.invoke(ctx, req, func(r io.Reader) (TLObject, error) {
		return ReadTLObject(r)
	})
	if err != nil {
		return nil, err
	}
	if _c, _ok := result.(UpdatesClass); _ok {
		return _c, nil
	}
	return nil, fmt.Errorf("unexpected result type %T", result)
}

// PhoneSaveCallDebugTypeID is the constructor ID for the RPC function phone.saveCallDebug.
const PhoneSaveCallDebugTypeID = 0x277add7e

// PhoneSaveCallDebugRequest represents TL type `phone.saveCallDebug#277add7e`.
//
// See https://core.telegram.org/method/phone/saveCallDebug for reference.
type PhoneSaveCallDebugRequest struct {
	Peer  *InputPhoneCall `json:"peer,omitempty"`
	Debug *DataJSON       `json:"debug,omitempty"`
}

// ConstructorID returns the TL constructor identifier 0x277add7e.
func (v *PhoneSaveCallDebugRequest) ConstructorID() uint32 {
	return PhoneSaveCallDebugTypeID
}

// Encode serializes PhoneSaveCallDebugRequest to a bytes.Buffer using the TL binary protocol.
func (v *PhoneSaveCallDebugRequest) Encode(b *bytes.Buffer) error {
	WriteInt(b, PhoneSaveCallDebugTypeID)
	EncodeTLObject(b, v.Peer)
	EncodeTLObject(b, v.Debug)
	return nil
}

// PhoneSaveCallDebug invokes the phone.saveCallDebug RPC method on the server.
//
// Parameters:
//   - ctx: context for cancellation and timeout
//   - req: the request parameters
//
// Returns the result of the RPC call, or an error if the invocation fails.
func (c *RPCClient) PhoneSaveCallDebug(ctx context.Context, req *PhoneSaveCallDebugRequest) (bool, error) {
	result, err := c.invoke(ctx, req, func(r io.Reader) (TLObject, error) {
		return ReadTLObject(r)
	})
	if err != nil {
		return false, err
	}
	_ = result
	return true, nil
}

// PhoneSendSignalingDataTypeID is the constructor ID for the RPC function phone.sendSignalingData.
const PhoneSendSignalingDataTypeID = 0xff7a9383

// PhoneSendSignalingDataRequest represents TL type `phone.sendSignalingData#ff7a9383`.
//
// See https://core.telegram.org/method/phone/sendSignalingData for reference.
type PhoneSendSignalingDataRequest struct {
	Peer *InputPhoneCall `json:"peer,omitempty"`
	Data []byte          `json:"data,omitempty"`
}

// ConstructorID returns the TL constructor identifier 0xff7a9383.
func (v *PhoneSendSignalingDataRequest) ConstructorID() uint32 {
	return PhoneSendSignalingDataTypeID
}

// Encode serializes PhoneSendSignalingDataRequest to a bytes.Buffer using the TL binary protocol.
func (v *PhoneSendSignalingDataRequest) Encode(b *bytes.Buffer) error {
	WriteInt(b, PhoneSendSignalingDataTypeID)
	EncodeTLObject(b, v.Peer)
	WriteBytes(b, v.Data)
	return nil
}

// PhoneSendSignalingData invokes the phone.sendSignalingData RPC method on the server.
//
// Parameters:
//   - ctx: context for cancellation and timeout
//   - req: the request parameters
//
// Returns the result of the RPC call, or an error if the invocation fails.
func (c *RPCClient) PhoneSendSignalingData(ctx context.Context, req *PhoneSendSignalingDataRequest) (bool, error) {
	result, err := c.invoke(ctx, req, func(r io.Reader) (TLObject, error) {
		return ReadTLObject(r)
	})
	if err != nil {
		return false, err
	}
	_ = result
	return true, nil
}

// PhoneCreateGroupCallTypeID is the constructor ID for the RPC function phone.createGroupCall.
const PhoneCreateGroupCallTypeID = 0x48cdc6d8

// PhoneCreateGroupCallRequest represents TL type `phone.createGroupCall#48cdc6d8`.
//
// See https://core.telegram.org/method/phone/createGroupCall for reference.
type PhoneCreateGroupCallRequest struct {
	Flags        Fields         `json:"-"`
	RtmpStream   bool           `json:"rtmp_stream,omitempty"`
	Peer         InputPeerClass `json:"peer,omitempty"`
	RandomID     int32          `json:"random_id,omitempty"`
	Title        string         `json:"title,omitempty"`
	ScheduleDate int32          `json:"schedule_date,omitempty"`
}

// SetFlags computes flags from non-zero optional fields.
func (v *PhoneCreateGroupCallRequest) SetFlags() {
	if v.RtmpStream {
		v.Flags.Set(2)
	}
	if v.Title != "" {
		v.Flags.Set(0)
	}
	if v.ScheduleDate != 0 {
		v.Flags.Set(1)
	}
}

// ConstructorID returns the TL constructor identifier 0x48cdc6d8.
func (v *PhoneCreateGroupCallRequest) ConstructorID() uint32 {
	return PhoneCreateGroupCallTypeID
}

// Encode serializes PhoneCreateGroupCallRequest to a bytes.Buffer using the TL binary protocol.
func (v *PhoneCreateGroupCallRequest) Encode(b *bytes.Buffer) error {
	WriteInt(b, PhoneCreateGroupCallTypeID)
	v.SetFlags()
	WriteInt(b, uint32(v.Flags))
	EncodeTLObject(b, v.Peer)
	WriteInt(b, uint32(v.RandomID))
	if v.Flags.Has(0) {
		WriteString(b, v.Title)
	}
	if v.Flags.Has(1) {
		WriteInt(b, uint32(v.ScheduleDate))
	}
	return nil
}

// PhoneCreateGroupCall invokes the phone.createGroupCall RPC method on the server.
//
// Parameters:
//   - ctx: context for cancellation and timeout
//   - req: the request parameters
//
// Returns the result of the RPC call, or an error if the invocation fails.
func (c *RPCClient) PhoneCreateGroupCall(ctx context.Context, req *PhoneCreateGroupCallRequest) (UpdatesClass, error) {
	result, err := c.invoke(ctx, req, func(r io.Reader) (TLObject, error) {
		return ReadTLObject(r)
	})
	if err != nil {
		return nil, err
	}
	if _c, _ok := result.(UpdatesClass); _ok {
		return _c, nil
	}
	return nil, fmt.Errorf("unexpected result type %T", result)
}

// PhoneJoinGroupCallTypeID is the constructor ID for the RPC function phone.joinGroupCall.
const PhoneJoinGroupCallTypeID = 0x8fb53057

// PhoneJoinGroupCallRequest represents TL type `phone.joinGroupCall#8fb53057`.
//
// See https://core.telegram.org/method/phone/joinGroupCall for reference.
type PhoneJoinGroupCallRequest struct {
	Flags        Fields              `json:"-"`
	Muted        bool                `json:"muted,omitempty"`
	VideoStopped bool                `json:"video_stopped,omitempty"`
	Call         InputGroupCallClass `json:"call,omitempty"`
	JoinAs       InputPeerClass      `json:"join_as,omitempty"`
	InviteHash   string              `json:"invite_hash,omitempty"`
	PublicKey    *[32]byte           `json:"public_key,omitempty"`
	Block        []byte              `json:"block,omitempty"`
	Params       *DataJSON           `json:"params,omitempty"`
}

// SetFlags computes flags from non-zero optional fields.
func (v *PhoneJoinGroupCallRequest) SetFlags() {
	if v.Muted {
		v.Flags.Set(0)
	}
	if v.VideoStopped {
		v.Flags.Set(2)
	}
	if v.InviteHash != "" {
		v.Flags.Set(1)
	}
	if v.PublicKey != nil {
		v.Flags.Set(3)
	}
	if v.Block != nil {
		v.Flags.Set(3)
	}
}

// ConstructorID returns the TL constructor identifier 0x8fb53057.
func (v *PhoneJoinGroupCallRequest) ConstructorID() uint32 {
	return PhoneJoinGroupCallTypeID
}

// Encode serializes PhoneJoinGroupCallRequest to a bytes.Buffer using the TL binary protocol.
func (v *PhoneJoinGroupCallRequest) Encode(b *bytes.Buffer) error {
	WriteInt(b, PhoneJoinGroupCallTypeID)
	v.SetFlags()
	WriteInt(b, uint32(v.Flags))
	EncodeTLObject(b, v.Call)
	EncodeTLObject(b, v.JoinAs)
	if v.Flags.Has(1) {
		WriteString(b, v.InviteHash)
	}
	if v.Flags.Has(3) {
		WriteInt256(b, *v.PublicKey)
	}
	if v.Flags.Has(3) {
		WriteBytes(b, v.Block)
	}
	EncodeTLObject(b, v.Params)
	return nil
}

// PhoneJoinGroupCall invokes the phone.joinGroupCall RPC method on the server.
//
// Parameters:
//   - ctx: context for cancellation and timeout
//   - req: the request parameters
//
// Returns the result of the RPC call, or an error if the invocation fails.
func (c *RPCClient) PhoneJoinGroupCall(ctx context.Context, req *PhoneJoinGroupCallRequest) (UpdatesClass, error) {
	result, err := c.invoke(ctx, req, func(r io.Reader) (TLObject, error) {
		return ReadTLObject(r)
	})
	if err != nil {
		return nil, err
	}
	if _c, _ok := result.(UpdatesClass); _ok {
		return _c, nil
	}
	return nil, fmt.Errorf("unexpected result type %T", result)
}

// PhoneLeaveGroupCallTypeID is the constructor ID for the RPC function phone.leaveGroupCall.
const PhoneLeaveGroupCallTypeID = 0x500377f9

// PhoneLeaveGroupCallRequest represents TL type `phone.leaveGroupCall#500377f9`.
//
// See https://core.telegram.org/method/phone/leaveGroupCall for reference.
type PhoneLeaveGroupCallRequest struct {
	Call   InputGroupCallClass `json:"call,omitempty"`
	Source int32               `json:"source,omitempty"`
}

// ConstructorID returns the TL constructor identifier 0x500377f9.
func (v *PhoneLeaveGroupCallRequest) ConstructorID() uint32 {
	return PhoneLeaveGroupCallTypeID
}

// Encode serializes PhoneLeaveGroupCallRequest to a bytes.Buffer using the TL binary protocol.
func (v *PhoneLeaveGroupCallRequest) Encode(b *bytes.Buffer) error {
	WriteInt(b, PhoneLeaveGroupCallTypeID)
	EncodeTLObject(b, v.Call)
	WriteInt(b, uint32(v.Source))
	return nil
}

// PhoneLeaveGroupCall invokes the phone.leaveGroupCall RPC method on the server.
//
// Parameters:
//   - ctx: context for cancellation and timeout
//   - req: the request parameters
//
// Returns the result of the RPC call, or an error if the invocation fails.
func (c *RPCClient) PhoneLeaveGroupCall(ctx context.Context, req *PhoneLeaveGroupCallRequest) (UpdatesClass, error) {
	result, err := c.invoke(ctx, req, func(r io.Reader) (TLObject, error) {
		return ReadTLObject(r)
	})
	if err != nil {
		return nil, err
	}
	if _c, _ok := result.(UpdatesClass); _ok {
		return _c, nil
	}
	return nil, fmt.Errorf("unexpected result type %T", result)
}

// PhoneInviteToGroupCallTypeID is the constructor ID for the RPC function phone.inviteToGroupCall.
const PhoneInviteToGroupCallTypeID = 0x7b393160

// PhoneInviteToGroupCallRequest represents TL type `phone.inviteToGroupCall#7b393160`.
//
// See https://core.telegram.org/method/phone/inviteToGroupCall for reference.
type PhoneInviteToGroupCallRequest struct {
	Call  InputGroupCallClass `json:"call,omitempty"`
	Users []InputUserClass    `json:"users,omitempty"`
}

// ConstructorID returns the TL constructor identifier 0x7b393160.
func (v *PhoneInviteToGroupCallRequest) ConstructorID() uint32 {
	return PhoneInviteToGroupCallTypeID
}

// Encode serializes PhoneInviteToGroupCallRequest to a bytes.Buffer using the TL binary protocol.
func (v *PhoneInviteToGroupCallRequest) Encode(b *bytes.Buffer) error {
	WriteInt(b, PhoneInviteToGroupCallTypeID)
	EncodeTLObject(b, v.Call)
	WriteInt(b, 0x1cb5c415)
	WriteInt(b, uint32(len(v.Users)))
	for _, _item := range v.Users {
		EncodeTLObject(b, _item)
	}
	return nil
}

// PhoneInviteToGroupCall invokes the phone.inviteToGroupCall RPC method on the server.
//
// Parameters:
//   - ctx: context for cancellation and timeout
//   - req: the request parameters
//
// Returns the result of the RPC call, or an error if the invocation fails.
func (c *RPCClient) PhoneInviteToGroupCall(ctx context.Context, req *PhoneInviteToGroupCallRequest) (UpdatesClass, error) {
	result, err := c.invoke(ctx, req, func(r io.Reader) (TLObject, error) {
		return ReadTLObject(r)
	})
	if err != nil {
		return nil, err
	}
	if _c, _ok := result.(UpdatesClass); _ok {
		return _c, nil
	}
	return nil, fmt.Errorf("unexpected result type %T", result)
}

// PhoneDiscardGroupCallTypeID is the constructor ID for the RPC function phone.discardGroupCall.
const PhoneDiscardGroupCallTypeID = 0x7a777135

// PhoneDiscardGroupCallRequest represents TL type `phone.discardGroupCall#7a777135`.
//
// See https://core.telegram.org/method/phone/discardGroupCall for reference.
type PhoneDiscardGroupCallRequest struct {
	Call InputGroupCallClass `json:"call,omitempty"`
}

// ConstructorID returns the TL constructor identifier 0x7a777135.
func (v *PhoneDiscardGroupCallRequest) ConstructorID() uint32 {
	return PhoneDiscardGroupCallTypeID
}

// Encode serializes PhoneDiscardGroupCallRequest to a bytes.Buffer using the TL binary protocol.
func (v *PhoneDiscardGroupCallRequest) Encode(b *bytes.Buffer) error {
	WriteInt(b, PhoneDiscardGroupCallTypeID)
	EncodeTLObject(b, v.Call)
	return nil
}

// PhoneDiscardGroupCall invokes the phone.discardGroupCall RPC method on the server.
//
// Parameters:
//   - ctx: context for cancellation and timeout
//   - req: the request parameters
//
// Returns the result of the RPC call, or an error if the invocation fails.
func (c *RPCClient) PhoneDiscardGroupCall(ctx context.Context, req *PhoneDiscardGroupCallRequest) (UpdatesClass, error) {
	result, err := c.invoke(ctx, req, func(r io.Reader) (TLObject, error) {
		return ReadTLObject(r)
	})
	if err != nil {
		return nil, err
	}
	if _c, _ok := result.(UpdatesClass); _ok {
		return _c, nil
	}
	return nil, fmt.Errorf("unexpected result type %T", result)
}

// PhoneToggleGroupCallSettingsTypeID is the constructor ID for the RPC function phone.toggleGroupCallSettings.
const PhoneToggleGroupCallSettingsTypeID = 0x974392f2

// PhoneToggleGroupCallSettingsRequest represents TL type `phone.toggleGroupCallSettings#974392f2`.
//
// See https://core.telegram.org/method/phone/toggleGroupCallSettings for reference.
type PhoneToggleGroupCallSettingsRequest struct {
	Flags                 Fields              `json:"-"`
	ResetInviteHash       bool                `json:"reset_invite_hash,omitempty"`
	Call                  InputGroupCallClass `json:"call,omitempty"`
	JoinMuted             bool                `json:"join_muted,omitempty"`
	MessagesEnabled       bool                `json:"messages_enabled,omitempty"`
	SendPaidMessagesStars int64               `json:"send_paid_messages_stars,omitempty"`
}

// SetFlags computes flags from non-zero optional fields.
func (v *PhoneToggleGroupCallSettingsRequest) SetFlags() {
	if v.ResetInviteHash {
		v.Flags.Set(1)
	}
	if v.JoinMuted {
		v.Flags.Set(0)
	}
	if v.MessagesEnabled {
		v.Flags.Set(2)
	}
	if v.SendPaidMessagesStars != 0 {
		v.Flags.Set(3)
	}
}

// ConstructorID returns the TL constructor identifier 0x974392f2.
func (v *PhoneToggleGroupCallSettingsRequest) ConstructorID() uint32 {
	return PhoneToggleGroupCallSettingsTypeID
}

// Encode serializes PhoneToggleGroupCallSettingsRequest to a bytes.Buffer using the TL binary protocol.
func (v *PhoneToggleGroupCallSettingsRequest) Encode(b *bytes.Buffer) error {
	WriteInt(b, PhoneToggleGroupCallSettingsTypeID)
	v.SetFlags()
	WriteInt(b, uint32(v.Flags))
	EncodeTLObject(b, v.Call)
	if v.Flags.Has(0) {
		WriteBool(b, v.JoinMuted)
	}
	if v.Flags.Has(2) {
		WriteBool(b, v.MessagesEnabled)
	}
	if v.Flags.Has(3) {
		WriteLong(b, v.SendPaidMessagesStars)
	}
	return nil
}

// PhoneToggleGroupCallSettings invokes the phone.toggleGroupCallSettings RPC method on the server.
//
// Parameters:
//   - ctx: context for cancellation and timeout
//   - req: the request parameters
//
// Returns the result of the RPC call, or an error if the invocation fails.
func (c *RPCClient) PhoneToggleGroupCallSettings(ctx context.Context, req *PhoneToggleGroupCallSettingsRequest) (UpdatesClass, error) {
	result, err := c.invoke(ctx, req, func(r io.Reader) (TLObject, error) {
		return ReadTLObject(r)
	})
	if err != nil {
		return nil, err
	}
	if _c, _ok := result.(UpdatesClass); _ok {
		return _c, nil
	}
	return nil, fmt.Errorf("unexpected result type %T", result)
}

// PhoneGetGroupCallTypeID is the constructor ID for the RPC function phone.getGroupCall.
const PhoneGetGroupCallTypeID = 0x041845db

// PhoneGetGroupCallRequest represents TL type `phone.getGroupCall#041845db`.
//
// See https://core.telegram.org/method/phone/getGroupCall for reference.
type PhoneGetGroupCallRequest struct {
	Call  InputGroupCallClass `json:"call,omitempty"`
	Limit int32               `json:"limit,omitempty"`
}

// ConstructorID returns the TL constructor identifier 0x041845db.
func (v *PhoneGetGroupCallRequest) ConstructorID() uint32 {
	return PhoneGetGroupCallTypeID
}

// Encode serializes PhoneGetGroupCallRequest to a bytes.Buffer using the TL binary protocol.
func (v *PhoneGetGroupCallRequest) Encode(b *bytes.Buffer) error {
	WriteInt(b, PhoneGetGroupCallTypeID)
	EncodeTLObject(b, v.Call)
	WriteInt(b, uint32(v.Limit))
	return nil
}

// PhoneGetGroupCall invokes the phone.getGroupCall RPC method on the server.
//
// Parameters:
//   - ctx: context for cancellation and timeout
//   - req: the request parameters
//
// Returns the result of the RPC call, or an error if the invocation fails.
func (c *RPCClient) PhoneGetGroupCall(ctx context.Context, req *PhoneGetGroupCallRequest) (GroupCallClass, error) {
	result, err := c.invoke(ctx, req, func(r io.Reader) (TLObject, error) {
		return ReadTLObject(r)
	})
	if err != nil {
		return nil, err
	}
	if _c, _ok := result.(GroupCallClass); _ok {
		return _c, nil
	}
	return nil, fmt.Errorf("unexpected result type %T", result)
}

// PhoneGetGroupParticipantsTypeID is the constructor ID for the RPC function phone.getGroupParticipants.
const PhoneGetGroupParticipantsTypeID = 0xc558d8ab

// PhoneGetGroupParticipantsRequest represents TL type `phone.getGroupParticipants#c558d8ab`.
//
// See https://core.telegram.org/method/phone/getGroupParticipants for reference.
type PhoneGetGroupParticipantsRequest struct {
	Call    InputGroupCallClass `json:"call,omitempty"`
	Ids     []InputPeerClass    `json:"ids,omitempty"`
	Sources []int32             `json:"sources,omitempty"`
	Offset  string              `json:"offset,omitempty"`
	Limit   int32               `json:"limit,omitempty"`
}

// ConstructorID returns the TL constructor identifier 0xc558d8ab.
func (v *PhoneGetGroupParticipantsRequest) ConstructorID() uint32 {
	return PhoneGetGroupParticipantsTypeID
}

// Encode serializes PhoneGetGroupParticipantsRequest to a bytes.Buffer using the TL binary protocol.
func (v *PhoneGetGroupParticipantsRequest) Encode(b *bytes.Buffer) error {
	WriteInt(b, PhoneGetGroupParticipantsTypeID)
	EncodeTLObject(b, v.Call)
	WriteInt(b, 0x1cb5c415)
	WriteInt(b, uint32(len(v.Ids)))
	for _, _item := range v.Ids {
		EncodeTLObject(b, _item)
	}
	WriteVectorInt(b, v.Sources)
	WriteString(b, v.Offset)
	WriteInt(b, uint32(v.Limit))
	return nil
}

// PhoneGetGroupParticipants invokes the phone.getGroupParticipants RPC method on the server.
//
// Parameters:
//   - ctx: context for cancellation and timeout
//   - req: the request parameters
//
// Returns the result of the RPC call, or an error if the invocation fails.
func (c *RPCClient) PhoneGetGroupParticipants(ctx context.Context, req *PhoneGetGroupParticipantsRequest) (*PhoneGroupParticipants, error) {
	result, err := c.invoke(ctx, req, func(r io.Reader) (TLObject, error) {
		return ReadTLObject(r)
	})
	if err != nil {
		return nil, err
	}
	if _c, _ok := result.(*PhoneGroupParticipants); _ok {
		return _c, nil
	}
	return nil, fmt.Errorf("unexpected result type %T", result)
}

// PhoneCheckGroupCallTypeID is the constructor ID for the RPC function phone.checkGroupCall.
const PhoneCheckGroupCallTypeID = 0xb59cf977

// PhoneCheckGroupCallRequest represents TL type `phone.checkGroupCall#b59cf977`.
//
// See https://core.telegram.org/method/phone/checkGroupCall for reference.
type PhoneCheckGroupCallRequest struct {
	Call    InputGroupCallClass `json:"call,omitempty"`
	Sources []int32             `json:"sources,omitempty"`
}

// ConstructorID returns the TL constructor identifier 0xb59cf977.
func (v *PhoneCheckGroupCallRequest) ConstructorID() uint32 {
	return PhoneCheckGroupCallTypeID
}

// Encode serializes PhoneCheckGroupCallRequest to a bytes.Buffer using the TL binary protocol.
func (v *PhoneCheckGroupCallRequest) Encode(b *bytes.Buffer) error {
	WriteInt(b, PhoneCheckGroupCallTypeID)
	EncodeTLObject(b, v.Call)
	WriteVectorInt(b, v.Sources)
	return nil
}

// PhoneCheckGroupCall invokes the phone.checkGroupCall RPC method on the server.
//
// Parameters:
//   - ctx: context for cancellation and timeout
//   - req: the request parameters
//
// Returns the result of the RPC call, or an error if the invocation fails.
func (c *RPCClient) PhoneCheckGroupCall(ctx context.Context, req *PhoneCheckGroupCallRequest) (TLObject, error) {
	result, err := c.invoke(ctx, req, func(r io.Reader) (TLObject, error) {
		return ReadTLObject(r)
	})
	if err != nil {
		return nil, err
	}
	return result, nil
}

// PhoneToggleGroupCallRecordTypeID is the constructor ID for the RPC function phone.toggleGroupCallRecord.
const PhoneToggleGroupCallRecordTypeID = 0xf128c708

// PhoneToggleGroupCallRecordRequest represents TL type `phone.toggleGroupCallRecord#f128c708`.
//
// See https://core.telegram.org/method/phone/toggleGroupCallRecord for reference.
type PhoneToggleGroupCallRecordRequest struct {
	Flags         Fields              `json:"-"`
	Start         bool                `json:"start,omitempty"`
	Video         bool                `json:"video,omitempty"`
	Call          InputGroupCallClass `json:"call,omitempty"`
	Title         string              `json:"title,omitempty"`
	VideoPortrait bool                `json:"video_portrait,omitempty"`
}

// SetFlags computes flags from non-zero optional fields.
func (v *PhoneToggleGroupCallRecordRequest) SetFlags() {
	if v.Start {
		v.Flags.Set(0)
	}
	if v.Video {
		v.Flags.Set(2)
	}
	if v.Title != "" {
		v.Flags.Set(1)
	}
	if v.VideoPortrait {
		v.Flags.Set(2)
	}
}

// ConstructorID returns the TL constructor identifier 0xf128c708.
func (v *PhoneToggleGroupCallRecordRequest) ConstructorID() uint32 {
	return PhoneToggleGroupCallRecordTypeID
}

// Encode serializes PhoneToggleGroupCallRecordRequest to a bytes.Buffer using the TL binary protocol.
func (v *PhoneToggleGroupCallRecordRequest) Encode(b *bytes.Buffer) error {
	WriteInt(b, PhoneToggleGroupCallRecordTypeID)
	v.SetFlags()
	WriteInt(b, uint32(v.Flags))
	EncodeTLObject(b, v.Call)
	if v.Flags.Has(1) {
		WriteString(b, v.Title)
	}
	if v.Flags.Has(2) {
		WriteBool(b, v.VideoPortrait)
	}
	return nil
}

// PhoneToggleGroupCallRecord invokes the phone.toggleGroupCallRecord RPC method on the server.
//
// Parameters:
//   - ctx: context for cancellation and timeout
//   - req: the request parameters
//
// Returns the result of the RPC call, or an error if the invocation fails.
func (c *RPCClient) PhoneToggleGroupCallRecord(ctx context.Context, req *PhoneToggleGroupCallRecordRequest) (UpdatesClass, error) {
	result, err := c.invoke(ctx, req, func(r io.Reader) (TLObject, error) {
		return ReadTLObject(r)
	})
	if err != nil {
		return nil, err
	}
	if _c, _ok := result.(UpdatesClass); _ok {
		return _c, nil
	}
	return nil, fmt.Errorf("unexpected result type %T", result)
}

// PhoneEditGroupCallParticipantTypeID is the constructor ID for the RPC function phone.editGroupCallParticipant.
const PhoneEditGroupCallParticipantTypeID = 0xa5273abf

// PhoneEditGroupCallParticipantRequest represents TL type `phone.editGroupCallParticipant#a5273abf`.
//
// See https://core.telegram.org/method/phone/editGroupCallParticipant for reference.
type PhoneEditGroupCallParticipantRequest struct {
	Flags              Fields              `json:"-"`
	Call               InputGroupCallClass `json:"call,omitempty"`
	Participant        InputPeerClass      `json:"participant,omitempty"`
	Muted              bool                `json:"muted,omitempty"`
	Volume             int32               `json:"volume,omitempty"`
	RaiseHand          bool                `json:"raise_hand,omitempty"`
	VideoStopped       bool                `json:"video_stopped,omitempty"`
	VideoPaused        bool                `json:"video_paused,omitempty"`
	PresentationPaused bool                `json:"presentation_paused,omitempty"`
}

// SetFlags computes flags from non-zero optional fields.
func (v *PhoneEditGroupCallParticipantRequest) SetFlags() {
	if v.Muted {
		v.Flags.Set(0)
	}
	if v.Volume != 0 {
		v.Flags.Set(1)
	}
	if v.RaiseHand {
		v.Flags.Set(2)
	}
	if v.VideoStopped {
		v.Flags.Set(3)
	}
	if v.VideoPaused {
		v.Flags.Set(4)
	}
	if v.PresentationPaused {
		v.Flags.Set(5)
	}
}

// ConstructorID returns the TL constructor identifier 0xa5273abf.
func (v *PhoneEditGroupCallParticipantRequest) ConstructorID() uint32 {
	return PhoneEditGroupCallParticipantTypeID
}

// Encode serializes PhoneEditGroupCallParticipantRequest to a bytes.Buffer using the TL binary protocol.
func (v *PhoneEditGroupCallParticipantRequest) Encode(b *bytes.Buffer) error {
	WriteInt(b, PhoneEditGroupCallParticipantTypeID)
	v.SetFlags()
	WriteInt(b, uint32(v.Flags))
	EncodeTLObject(b, v.Call)
	EncodeTLObject(b, v.Participant)
	if v.Flags.Has(0) {
		WriteBool(b, v.Muted)
	}
	if v.Flags.Has(1) {
		WriteInt(b, uint32(v.Volume))
	}
	if v.Flags.Has(2) {
		WriteBool(b, v.RaiseHand)
	}
	if v.Flags.Has(3) {
		WriteBool(b, v.VideoStopped)
	}
	if v.Flags.Has(4) {
		WriteBool(b, v.VideoPaused)
	}
	if v.Flags.Has(5) {
		WriteBool(b, v.PresentationPaused)
	}
	return nil
}

// PhoneEditGroupCallParticipant invokes the phone.editGroupCallParticipant RPC method on the server.
//
// Parameters:
//   - ctx: context for cancellation and timeout
//   - req: the request parameters
//
// Returns the result of the RPC call, or an error if the invocation fails.
func (c *RPCClient) PhoneEditGroupCallParticipant(ctx context.Context, req *PhoneEditGroupCallParticipantRequest) (UpdatesClass, error) {
	result, err := c.invoke(ctx, req, func(r io.Reader) (TLObject, error) {
		return ReadTLObject(r)
	})
	if err != nil {
		return nil, err
	}
	if _c, _ok := result.(UpdatesClass); _ok {
		return _c, nil
	}
	return nil, fmt.Errorf("unexpected result type %T", result)
}

// PhoneEditGroupCallTitleTypeID is the constructor ID for the RPC function phone.editGroupCallTitle.
const PhoneEditGroupCallTitleTypeID = 0x1ca6ac0a

// PhoneEditGroupCallTitleRequest represents TL type `phone.editGroupCallTitle#1ca6ac0a`.
//
// See https://core.telegram.org/method/phone/editGroupCallTitle for reference.
type PhoneEditGroupCallTitleRequest struct {
	Call  InputGroupCallClass `json:"call,omitempty"`
	Title string              `json:"title,omitempty"`
}

// ConstructorID returns the TL constructor identifier 0x1ca6ac0a.
func (v *PhoneEditGroupCallTitleRequest) ConstructorID() uint32 {
	return PhoneEditGroupCallTitleTypeID
}

// Encode serializes PhoneEditGroupCallTitleRequest to a bytes.Buffer using the TL binary protocol.
func (v *PhoneEditGroupCallTitleRequest) Encode(b *bytes.Buffer) error {
	WriteInt(b, PhoneEditGroupCallTitleTypeID)
	EncodeTLObject(b, v.Call)
	WriteString(b, v.Title)
	return nil
}

// PhoneEditGroupCallTitle invokes the phone.editGroupCallTitle RPC method on the server.
//
// Parameters:
//   - ctx: context for cancellation and timeout
//   - req: the request parameters
//
// Returns the result of the RPC call, or an error if the invocation fails.
func (c *RPCClient) PhoneEditGroupCallTitle(ctx context.Context, req *PhoneEditGroupCallTitleRequest) (UpdatesClass, error) {
	result, err := c.invoke(ctx, req, func(r io.Reader) (TLObject, error) {
		return ReadTLObject(r)
	})
	if err != nil {
		return nil, err
	}
	if _c, _ok := result.(UpdatesClass); _ok {
		return _c, nil
	}
	return nil, fmt.Errorf("unexpected result type %T", result)
}

// PhoneGetGroupCallJoinAsTypeID is the constructor ID for the RPC function phone.getGroupCallJoinAs.
const PhoneGetGroupCallJoinAsTypeID = 0xef7c213a

// PhoneGetGroupCallJoinAsRequest represents TL type `phone.getGroupCallJoinAs#ef7c213a`.
//
// See https://core.telegram.org/method/phone/getGroupCallJoinAs for reference.
type PhoneGetGroupCallJoinAsRequest struct {
	Peer InputPeerClass `json:"peer,omitempty"`
}

// ConstructorID returns the TL constructor identifier 0xef7c213a.
func (v *PhoneGetGroupCallJoinAsRequest) ConstructorID() uint32 {
	return PhoneGetGroupCallJoinAsTypeID
}

// Encode serializes PhoneGetGroupCallJoinAsRequest to a bytes.Buffer using the TL binary protocol.
func (v *PhoneGetGroupCallJoinAsRequest) Encode(b *bytes.Buffer) error {
	WriteInt(b, PhoneGetGroupCallJoinAsTypeID)
	EncodeTLObject(b, v.Peer)
	return nil
}

// PhoneGetGroupCallJoinAs invokes the phone.getGroupCallJoinAs RPC method on the server.
//
// Parameters:
//   - ctx: context for cancellation and timeout
//   - req: the request parameters
//
// Returns the result of the RPC call, or an error if the invocation fails.
func (c *RPCClient) PhoneGetGroupCallJoinAs(ctx context.Context, req *PhoneGetGroupCallJoinAsRequest) (*PhoneJoinAsPeers, error) {
	result, err := c.invoke(ctx, req, func(r io.Reader) (TLObject, error) {
		return ReadTLObject(r)
	})
	if err != nil {
		return nil, err
	}
	if _c, _ok := result.(*PhoneJoinAsPeers); _ok {
		return _c, nil
	}
	return nil, fmt.Errorf("unexpected result type %T", result)
}

// PhoneExportGroupCallInviteTypeID is the constructor ID for the RPC function phone.exportGroupCallInvite.
const PhoneExportGroupCallInviteTypeID = 0xe6aa647f

// PhoneExportGroupCallInviteRequest represents TL type `phone.exportGroupCallInvite#e6aa647f`.
//
// See https://core.telegram.org/method/phone/exportGroupCallInvite for reference.
type PhoneExportGroupCallInviteRequest struct {
	Flags         Fields              `json:"-"`
	CanSelfUnmute bool                `json:"can_self_unmute,omitempty"`
	Call          InputGroupCallClass `json:"call,omitempty"`
}

// SetFlags computes flags from non-zero optional fields.
func (v *PhoneExportGroupCallInviteRequest) SetFlags() {
	if v.CanSelfUnmute {
		v.Flags.Set(0)
	}
}

// ConstructorID returns the TL constructor identifier 0xe6aa647f.
func (v *PhoneExportGroupCallInviteRequest) ConstructorID() uint32 {
	return PhoneExportGroupCallInviteTypeID
}

// Encode serializes PhoneExportGroupCallInviteRequest to a bytes.Buffer using the TL binary protocol.
func (v *PhoneExportGroupCallInviteRequest) Encode(b *bytes.Buffer) error {
	WriteInt(b, PhoneExportGroupCallInviteTypeID)
	v.SetFlags()
	WriteInt(b, uint32(v.Flags))
	EncodeTLObject(b, v.Call)
	return nil
}

// PhoneExportGroupCallInvite invokes the phone.exportGroupCallInvite RPC method on the server.
//
// Parameters:
//   - ctx: context for cancellation and timeout
//   - req: the request parameters
//
// Returns the result of the RPC call, or an error if the invocation fails.
func (c *RPCClient) PhoneExportGroupCallInvite(ctx context.Context, req *PhoneExportGroupCallInviteRequest) (*PhoneExportedGroupCallInvite, error) {
	result, err := c.invoke(ctx, req, func(r io.Reader) (TLObject, error) {
		return ReadTLObject(r)
	})
	if err != nil {
		return nil, err
	}
	if _c, _ok := result.(*PhoneExportedGroupCallInvite); _ok {
		return _c, nil
	}
	return nil, fmt.Errorf("unexpected result type %T", result)
}

// PhoneToggleGroupCallStartSubscriptionTypeID is the constructor ID for the RPC function phone.toggleGroupCallStartSubscription.
const PhoneToggleGroupCallStartSubscriptionTypeID = 0x219c34e6

// PhoneToggleGroupCallStartSubscriptionRequest represents TL type `phone.toggleGroupCallStartSubscription#219c34e6`.
//
// See https://core.telegram.org/method/phone/toggleGroupCallStartSubscription for reference.
type PhoneToggleGroupCallStartSubscriptionRequest struct {
	Call       InputGroupCallClass `json:"call,omitempty"`
	Subscribed bool                `json:"subscribed,omitempty"`
}

// ConstructorID returns the TL constructor identifier 0x219c34e6.
func (v *PhoneToggleGroupCallStartSubscriptionRequest) ConstructorID() uint32 {
	return PhoneToggleGroupCallStartSubscriptionTypeID
}

// Encode serializes PhoneToggleGroupCallStartSubscriptionRequest to a bytes.Buffer using the TL binary protocol.
func (v *PhoneToggleGroupCallStartSubscriptionRequest) Encode(b *bytes.Buffer) error {
	WriteInt(b, PhoneToggleGroupCallStartSubscriptionTypeID)
	EncodeTLObject(b, v.Call)
	WriteBool(b, v.Subscribed)
	return nil
}

// PhoneToggleGroupCallStartSubscription invokes the phone.toggleGroupCallStartSubscription RPC method on the server.
//
// Parameters:
//   - ctx: context for cancellation and timeout
//   - req: the request parameters
//
// Returns the result of the RPC call, or an error if the invocation fails.
func (c *RPCClient) PhoneToggleGroupCallStartSubscription(ctx context.Context, req *PhoneToggleGroupCallStartSubscriptionRequest) (UpdatesClass, error) {
	result, err := c.invoke(ctx, req, func(r io.Reader) (TLObject, error) {
		return ReadTLObject(r)
	})
	if err != nil {
		return nil, err
	}
	if _c, _ok := result.(UpdatesClass); _ok {
		return _c, nil
	}
	return nil, fmt.Errorf("unexpected result type %T", result)
}

// PhoneStartScheduledGroupCallTypeID is the constructor ID for the RPC function phone.startScheduledGroupCall.
const PhoneStartScheduledGroupCallTypeID = 0x5680e342

// PhoneStartScheduledGroupCallRequest represents TL type `phone.startScheduledGroupCall#5680e342`.
//
// See https://core.telegram.org/method/phone/startScheduledGroupCall for reference.
type PhoneStartScheduledGroupCallRequest struct {
	Call InputGroupCallClass `json:"call,omitempty"`
}

// ConstructorID returns the TL constructor identifier 0x5680e342.
func (v *PhoneStartScheduledGroupCallRequest) ConstructorID() uint32 {
	return PhoneStartScheduledGroupCallTypeID
}

// Encode serializes PhoneStartScheduledGroupCallRequest to a bytes.Buffer using the TL binary protocol.
func (v *PhoneStartScheduledGroupCallRequest) Encode(b *bytes.Buffer) error {
	WriteInt(b, PhoneStartScheduledGroupCallTypeID)
	EncodeTLObject(b, v.Call)
	return nil
}

// PhoneStartScheduledGroupCall invokes the phone.startScheduledGroupCall RPC method on the server.
//
// Parameters:
//   - ctx: context for cancellation and timeout
//   - req: the request parameters
//
// Returns the result of the RPC call, or an error if the invocation fails.
func (c *RPCClient) PhoneStartScheduledGroupCall(ctx context.Context, req *PhoneStartScheduledGroupCallRequest) (UpdatesClass, error) {
	result, err := c.invoke(ctx, req, func(r io.Reader) (TLObject, error) {
		return ReadTLObject(r)
	})
	if err != nil {
		return nil, err
	}
	if _c, _ok := result.(UpdatesClass); _ok {
		return _c, nil
	}
	return nil, fmt.Errorf("unexpected result type %T", result)
}

// PhoneSaveDefaultGroupCallJoinAsTypeID is the constructor ID for the RPC function phone.saveDefaultGroupCallJoinAs.
const PhoneSaveDefaultGroupCallJoinAsTypeID = 0x575e1f8c

// PhoneSaveDefaultGroupCallJoinAsRequest represents TL type `phone.saveDefaultGroupCallJoinAs#575e1f8c`.
//
// See https://core.telegram.org/method/phone/saveDefaultGroupCallJoinAs for reference.
type PhoneSaveDefaultGroupCallJoinAsRequest struct {
	Peer   InputPeerClass `json:"peer,omitempty"`
	JoinAs InputPeerClass `json:"join_as,omitempty"`
}

// ConstructorID returns the TL constructor identifier 0x575e1f8c.
func (v *PhoneSaveDefaultGroupCallJoinAsRequest) ConstructorID() uint32 {
	return PhoneSaveDefaultGroupCallJoinAsTypeID
}

// Encode serializes PhoneSaveDefaultGroupCallJoinAsRequest to a bytes.Buffer using the TL binary protocol.
func (v *PhoneSaveDefaultGroupCallJoinAsRequest) Encode(b *bytes.Buffer) error {
	WriteInt(b, PhoneSaveDefaultGroupCallJoinAsTypeID)
	EncodeTLObject(b, v.Peer)
	EncodeTLObject(b, v.JoinAs)
	return nil
}

// PhoneSaveDefaultGroupCallJoinAs invokes the phone.saveDefaultGroupCallJoinAs RPC method on the server.
//
// Parameters:
//   - ctx: context for cancellation and timeout
//   - req: the request parameters
//
// Returns the result of the RPC call, or an error if the invocation fails.
func (c *RPCClient) PhoneSaveDefaultGroupCallJoinAs(ctx context.Context, req *PhoneSaveDefaultGroupCallJoinAsRequest) (bool, error) {
	result, err := c.invoke(ctx, req, func(r io.Reader) (TLObject, error) {
		return ReadTLObject(r)
	})
	if err != nil {
		return false, err
	}
	_ = result
	return true, nil
}

// PhoneJoinGroupCallPresentationTypeID is the constructor ID for the RPC function phone.joinGroupCallPresentation.
const PhoneJoinGroupCallPresentationTypeID = 0xcbea6bc4

// PhoneJoinGroupCallPresentationRequest represents TL type `phone.joinGroupCallPresentation#cbea6bc4`.
//
// See https://core.telegram.org/method/phone/joinGroupCallPresentation for reference.
type PhoneJoinGroupCallPresentationRequest struct {
	Call   InputGroupCallClass `json:"call,omitempty"`
	Params *DataJSON           `json:"params,omitempty"`
}

// ConstructorID returns the TL constructor identifier 0xcbea6bc4.
func (v *PhoneJoinGroupCallPresentationRequest) ConstructorID() uint32 {
	return PhoneJoinGroupCallPresentationTypeID
}

// Encode serializes PhoneJoinGroupCallPresentationRequest to a bytes.Buffer using the TL binary protocol.
func (v *PhoneJoinGroupCallPresentationRequest) Encode(b *bytes.Buffer) error {
	WriteInt(b, PhoneJoinGroupCallPresentationTypeID)
	EncodeTLObject(b, v.Call)
	EncodeTLObject(b, v.Params)
	return nil
}

// PhoneJoinGroupCallPresentation invokes the phone.joinGroupCallPresentation RPC method on the server.
//
// Parameters:
//   - ctx: context for cancellation and timeout
//   - req: the request parameters
//
// Returns the result of the RPC call, or an error if the invocation fails.
func (c *RPCClient) PhoneJoinGroupCallPresentation(ctx context.Context, req *PhoneJoinGroupCallPresentationRequest) (UpdatesClass, error) {
	result, err := c.invoke(ctx, req, func(r io.Reader) (TLObject, error) {
		return ReadTLObject(r)
	})
	if err != nil {
		return nil, err
	}
	if _c, _ok := result.(UpdatesClass); _ok {
		return _c, nil
	}
	return nil, fmt.Errorf("unexpected result type %T", result)
}

// PhoneLeaveGroupCallPresentationTypeID is the constructor ID for the RPC function phone.leaveGroupCallPresentation.
const PhoneLeaveGroupCallPresentationTypeID = 0x1c50d144

// PhoneLeaveGroupCallPresentationRequest represents TL type `phone.leaveGroupCallPresentation#1c50d144`.
//
// See https://core.telegram.org/method/phone/leaveGroupCallPresentation for reference.
type PhoneLeaveGroupCallPresentationRequest struct {
	Call InputGroupCallClass `json:"call,omitempty"`
}

// ConstructorID returns the TL constructor identifier 0x1c50d144.
func (v *PhoneLeaveGroupCallPresentationRequest) ConstructorID() uint32 {
	return PhoneLeaveGroupCallPresentationTypeID
}

// Encode serializes PhoneLeaveGroupCallPresentationRequest to a bytes.Buffer using the TL binary protocol.
func (v *PhoneLeaveGroupCallPresentationRequest) Encode(b *bytes.Buffer) error {
	WriteInt(b, PhoneLeaveGroupCallPresentationTypeID)
	EncodeTLObject(b, v.Call)
	return nil
}

// PhoneLeaveGroupCallPresentation invokes the phone.leaveGroupCallPresentation RPC method on the server.
//
// Parameters:
//   - ctx: context for cancellation and timeout
//   - req: the request parameters
//
// Returns the result of the RPC call, or an error if the invocation fails.
func (c *RPCClient) PhoneLeaveGroupCallPresentation(ctx context.Context, req *PhoneLeaveGroupCallPresentationRequest) (UpdatesClass, error) {
	result, err := c.invoke(ctx, req, func(r io.Reader) (TLObject, error) {
		return ReadTLObject(r)
	})
	if err != nil {
		return nil, err
	}
	if _c, _ok := result.(UpdatesClass); _ok {
		return _c, nil
	}
	return nil, fmt.Errorf("unexpected result type %T", result)
}

// PhoneGetGroupCallStreamChannelsTypeID is the constructor ID for the RPC function phone.getGroupCallStreamChannels.
const PhoneGetGroupCallStreamChannelsTypeID = 0x1ab21940

// PhoneGetGroupCallStreamChannelsRequest represents TL type `phone.getGroupCallStreamChannels#1ab21940`.
//
// See https://core.telegram.org/method/phone/getGroupCallStreamChannels for reference.
type PhoneGetGroupCallStreamChannelsRequest struct {
	Call InputGroupCallClass `json:"call,omitempty"`
}

// ConstructorID returns the TL constructor identifier 0x1ab21940.
func (v *PhoneGetGroupCallStreamChannelsRequest) ConstructorID() uint32 {
	return PhoneGetGroupCallStreamChannelsTypeID
}

// Encode serializes PhoneGetGroupCallStreamChannelsRequest to a bytes.Buffer using the TL binary protocol.
func (v *PhoneGetGroupCallStreamChannelsRequest) Encode(b *bytes.Buffer) error {
	WriteInt(b, PhoneGetGroupCallStreamChannelsTypeID)
	EncodeTLObject(b, v.Call)
	return nil
}

// PhoneGetGroupCallStreamChannels invokes the phone.getGroupCallStreamChannels RPC method on the server.
//
// Parameters:
//   - ctx: context for cancellation and timeout
//   - req: the request parameters
//
// Returns the result of the RPC call, or an error if the invocation fails.
func (c *RPCClient) PhoneGetGroupCallStreamChannels(ctx context.Context, req *PhoneGetGroupCallStreamChannelsRequest) (*PhoneGroupCallStreamChannels, error) {
	result, err := c.invoke(ctx, req, func(r io.Reader) (TLObject, error) {
		return ReadTLObject(r)
	})
	if err != nil {
		return nil, err
	}
	if _c, _ok := result.(*PhoneGroupCallStreamChannels); _ok {
		return _c, nil
	}
	return nil, fmt.Errorf("unexpected result type %T", result)
}

// PhoneGetGroupCallStreamRtmpURLTypeID is the constructor ID for the RPC function phone.getGroupCallStreamRtmpUrl.
const PhoneGetGroupCallStreamRtmpURLTypeID = 0x5af4c73a

// PhoneGetGroupCallStreamRtmpURLRequest represents TL type `phone.getGroupCallStreamRtmpUrl#5af4c73a`.
//
// See https://core.telegram.org/method/phone/getGroupCallStreamRtmpUrl for reference.
type PhoneGetGroupCallStreamRtmpURLRequest struct {
	Flags     Fields         `json:"-"`
	LiveStory bool           `json:"live_story,omitempty"`
	Peer      InputPeerClass `json:"peer,omitempty"`
	Revoke    bool           `json:"revoke,omitempty"`
}

// SetFlags computes flags from non-zero optional fields.
func (v *PhoneGetGroupCallStreamRtmpURLRequest) SetFlags() {
	if v.LiveStory {
		v.Flags.Set(0)
	}
}

// ConstructorID returns the TL constructor identifier 0x5af4c73a.
func (v *PhoneGetGroupCallStreamRtmpURLRequest) ConstructorID() uint32 {
	return PhoneGetGroupCallStreamRtmpURLTypeID
}

// Encode serializes PhoneGetGroupCallStreamRtmpURLRequest to a bytes.Buffer using the TL binary protocol.
func (v *PhoneGetGroupCallStreamRtmpURLRequest) Encode(b *bytes.Buffer) error {
	WriteInt(b, PhoneGetGroupCallStreamRtmpURLTypeID)
	v.SetFlags()
	WriteInt(b, uint32(v.Flags))
	EncodeTLObject(b, v.Peer)
	WriteBool(b, v.Revoke)
	return nil
}

// PhoneGetGroupCallStreamRtmpURL invokes the phone.getGroupCallStreamRtmpUrl RPC method on the server.
//
// Parameters:
//   - ctx: context for cancellation and timeout
//   - req: the request parameters
//
// Returns the result of the RPC call, or an error if the invocation fails.
func (c *RPCClient) PhoneGetGroupCallStreamRtmpURL(ctx context.Context, req *PhoneGetGroupCallStreamRtmpURLRequest) (*PhoneGroupCallStreamRtmpURL, error) {
	result, err := c.invoke(ctx, req, func(r io.Reader) (TLObject, error) {
		return ReadTLObject(r)
	})
	if err != nil {
		return nil, err
	}
	if _c, _ok := result.(*PhoneGroupCallStreamRtmpURL); _ok {
		return _c, nil
	}
	return nil, fmt.Errorf("unexpected result type %T", result)
}

// PhoneSaveCallLogTypeID is the constructor ID for the RPC function phone.saveCallLog.
const PhoneSaveCallLogTypeID = 0x41248786

// PhoneSaveCallLogRequest represents TL type `phone.saveCallLog#41248786`.
//
// See https://core.telegram.org/method/phone/saveCallLog for reference.
type PhoneSaveCallLogRequest struct {
	Peer *InputPhoneCall `json:"peer,omitempty"`
	File InputFileClass  `json:"file,omitempty"`
}

// ConstructorID returns the TL constructor identifier 0x41248786.
func (v *PhoneSaveCallLogRequest) ConstructorID() uint32 {
	return PhoneSaveCallLogTypeID
}

// Encode serializes PhoneSaveCallLogRequest to a bytes.Buffer using the TL binary protocol.
func (v *PhoneSaveCallLogRequest) Encode(b *bytes.Buffer) error {
	WriteInt(b, PhoneSaveCallLogTypeID)
	EncodeTLObject(b, v.Peer)
	EncodeTLObject(b, v.File)
	return nil
}

// PhoneSaveCallLog invokes the phone.saveCallLog RPC method on the server.
//
// Parameters:
//   - ctx: context for cancellation and timeout
//   - req: the request parameters
//
// Returns the result of the RPC call, or an error if the invocation fails.
func (c *RPCClient) PhoneSaveCallLog(ctx context.Context, req *PhoneSaveCallLogRequest) (bool, error) {
	result, err := c.invoke(ctx, req, func(r io.Reader) (TLObject, error) {
		return ReadTLObject(r)
	})
	if err != nil {
		return false, err
	}
	_ = result
	return true, nil
}

// PhoneCreateConferenceCallTypeID is the constructor ID for the RPC function phone.createConferenceCall.
const PhoneCreateConferenceCallTypeID = 0x7d0444bb

// PhoneCreateConferenceCallRequest represents TL type `phone.createConferenceCall#7d0444bb`.
//
// See https://core.telegram.org/method/phone/createConferenceCall for reference.
type PhoneCreateConferenceCallRequest struct {
	Flags        Fields    `json:"-"`
	Muted        bool      `json:"muted,omitempty"`
	VideoStopped bool      `json:"video_stopped,omitempty"`
	Join         bool      `json:"join,omitempty"`
	RandomID     int32     `json:"random_id,omitempty"`
	PublicKey    *[32]byte `json:"public_key,omitempty"`
	Block        []byte    `json:"block,omitempty"`
	Params       *DataJSON `json:"params,omitempty"`
}

// SetFlags computes flags from non-zero optional fields.
func (v *PhoneCreateConferenceCallRequest) SetFlags() {
	if v.Muted {
		v.Flags.Set(0)
	}
	if v.VideoStopped {
		v.Flags.Set(2)
	}
	if v.Join {
		v.Flags.Set(3)
	}
	if v.PublicKey != nil {
		v.Flags.Set(3)
	}
	if v.Block != nil {
		v.Flags.Set(3)
	}
	if v.Params != nil {
		v.Flags.Set(3)
	}
}

// ConstructorID returns the TL constructor identifier 0x7d0444bb.
func (v *PhoneCreateConferenceCallRequest) ConstructorID() uint32 {
	return PhoneCreateConferenceCallTypeID
}

// Encode serializes PhoneCreateConferenceCallRequest to a bytes.Buffer using the TL binary protocol.
func (v *PhoneCreateConferenceCallRequest) Encode(b *bytes.Buffer) error {
	WriteInt(b, PhoneCreateConferenceCallTypeID)
	v.SetFlags()
	WriteInt(b, uint32(v.Flags))
	WriteInt(b, uint32(v.RandomID))
	if v.Flags.Has(3) {
		WriteInt256(b, *v.PublicKey)
	}
	if v.Flags.Has(3) {
		WriteBytes(b, v.Block)
	}
	if v.Flags.Has(3) {
		EncodeTLObject(b, v.Params)
	}
	return nil
}

// PhoneCreateConferenceCall invokes the phone.createConferenceCall RPC method on the server.
//
// Parameters:
//   - ctx: context for cancellation and timeout
//   - req: the request parameters
//
// Returns the result of the RPC call, or an error if the invocation fails.
func (c *RPCClient) PhoneCreateConferenceCall(ctx context.Context, req *PhoneCreateConferenceCallRequest) (UpdatesClass, error) {
	result, err := c.invoke(ctx, req, func(r io.Reader) (TLObject, error) {
		return ReadTLObject(r)
	})
	if err != nil {
		return nil, err
	}
	if _c, _ok := result.(UpdatesClass); _ok {
		return _c, nil
	}
	return nil, fmt.Errorf("unexpected result type %T", result)
}

// PhoneDeleteConferenceCallParticipantsTypeID is the constructor ID for the RPC function phone.deleteConferenceCallParticipants.
const PhoneDeleteConferenceCallParticipantsTypeID = 0x8ca60525

// PhoneDeleteConferenceCallParticipantsRequest represents TL type `phone.deleteConferenceCallParticipants#8ca60525`.
//
// See https://core.telegram.org/method/phone/deleteConferenceCallParticipants for reference.
type PhoneDeleteConferenceCallParticipantsRequest struct {
	Flags    Fields              `json:"-"`
	OnlyLeft bool                `json:"only_left,omitempty"`
	Kick     bool                `json:"kick,omitempty"`
	Call     InputGroupCallClass `json:"call,omitempty"`
	Ids      []int64             `json:"ids,omitempty"`
	Block    []byte              `json:"block,omitempty"`
}

// SetFlags computes flags from non-zero optional fields.
func (v *PhoneDeleteConferenceCallParticipantsRequest) SetFlags() {
	if v.OnlyLeft {
		v.Flags.Set(0)
	}
	if v.Kick {
		v.Flags.Set(1)
	}
}

// ConstructorID returns the TL constructor identifier 0x8ca60525.
func (v *PhoneDeleteConferenceCallParticipantsRequest) ConstructorID() uint32 {
	return PhoneDeleteConferenceCallParticipantsTypeID
}

// Encode serializes PhoneDeleteConferenceCallParticipantsRequest to a bytes.Buffer using the TL binary protocol.
func (v *PhoneDeleteConferenceCallParticipantsRequest) Encode(b *bytes.Buffer) error {
	WriteInt(b, PhoneDeleteConferenceCallParticipantsTypeID)
	v.SetFlags()
	WriteInt(b, uint32(v.Flags))
	EncodeTLObject(b, v.Call)
	WriteVectorLong(b, v.Ids)
	WriteBytes(b, v.Block)
	return nil
}

// PhoneDeleteConferenceCallParticipants invokes the phone.deleteConferenceCallParticipants RPC method on the server.
//
// Parameters:
//   - ctx: context for cancellation and timeout
//   - req: the request parameters
//
// Returns the result of the RPC call, or an error if the invocation fails.
func (c *RPCClient) PhoneDeleteConferenceCallParticipants(ctx context.Context, req *PhoneDeleteConferenceCallParticipantsRequest) (UpdatesClass, error) {
	result, err := c.invoke(ctx, req, func(r io.Reader) (TLObject, error) {
		return ReadTLObject(r)
	})
	if err != nil {
		return nil, err
	}
	if _c, _ok := result.(UpdatesClass); _ok {
		return _c, nil
	}
	return nil, fmt.Errorf("unexpected result type %T", result)
}

// PhoneSendConferenceCallBroadcastTypeID is the constructor ID for the RPC function phone.sendConferenceCallBroadcast.
const PhoneSendConferenceCallBroadcastTypeID = 0xc6701900

// PhoneSendConferenceCallBroadcastRequest represents TL type `phone.sendConferenceCallBroadcast#c6701900`.
//
// See https://core.telegram.org/method/phone/sendConferenceCallBroadcast for reference.
type PhoneSendConferenceCallBroadcastRequest struct {
	Call  InputGroupCallClass `json:"call,omitempty"`
	Block []byte              `json:"block,omitempty"`
}

// ConstructorID returns the TL constructor identifier 0xc6701900.
func (v *PhoneSendConferenceCallBroadcastRequest) ConstructorID() uint32 {
	return PhoneSendConferenceCallBroadcastTypeID
}

// Encode serializes PhoneSendConferenceCallBroadcastRequest to a bytes.Buffer using the TL binary protocol.
func (v *PhoneSendConferenceCallBroadcastRequest) Encode(b *bytes.Buffer) error {
	WriteInt(b, PhoneSendConferenceCallBroadcastTypeID)
	EncodeTLObject(b, v.Call)
	WriteBytes(b, v.Block)
	return nil
}

// PhoneSendConferenceCallBroadcast invokes the phone.sendConferenceCallBroadcast RPC method on the server.
//
// Parameters:
//   - ctx: context for cancellation and timeout
//   - req: the request parameters
//
// Returns the result of the RPC call, or an error if the invocation fails.
func (c *RPCClient) PhoneSendConferenceCallBroadcast(ctx context.Context, req *PhoneSendConferenceCallBroadcastRequest) (UpdatesClass, error) {
	result, err := c.invoke(ctx, req, func(r io.Reader) (TLObject, error) {
		return ReadTLObject(r)
	})
	if err != nil {
		return nil, err
	}
	if _c, _ok := result.(UpdatesClass); _ok {
		return _c, nil
	}
	return nil, fmt.Errorf("unexpected result type %T", result)
}

// PhoneInviteConferenceCallParticipantTypeID is the constructor ID for the RPC function phone.inviteConferenceCallParticipant.
const PhoneInviteConferenceCallParticipantTypeID = 0xbcf22685

// PhoneInviteConferenceCallParticipantRequest represents TL type `phone.inviteConferenceCallParticipant#bcf22685`.
//
// See https://core.telegram.org/method/phone/inviteConferenceCallParticipant for reference.
type PhoneInviteConferenceCallParticipantRequest struct {
	Flags  Fields              `json:"-"`
	Video  bool                `json:"video,omitempty"`
	Call   InputGroupCallClass `json:"call,omitempty"`
	UserID InputUserClass      `json:"user_id,omitempty"`
}

// SetFlags computes flags from non-zero optional fields.
func (v *PhoneInviteConferenceCallParticipantRequest) SetFlags() {
	if v.Video {
		v.Flags.Set(0)
	}
}

// ConstructorID returns the TL constructor identifier 0xbcf22685.
func (v *PhoneInviteConferenceCallParticipantRequest) ConstructorID() uint32 {
	return PhoneInviteConferenceCallParticipantTypeID
}

// Encode serializes PhoneInviteConferenceCallParticipantRequest to a bytes.Buffer using the TL binary protocol.
func (v *PhoneInviteConferenceCallParticipantRequest) Encode(b *bytes.Buffer) error {
	WriteInt(b, PhoneInviteConferenceCallParticipantTypeID)
	v.SetFlags()
	WriteInt(b, uint32(v.Flags))
	EncodeTLObject(b, v.Call)
	EncodeTLObject(b, v.UserID)
	return nil
}

// PhoneInviteConferenceCallParticipant invokes the phone.inviteConferenceCallParticipant RPC method on the server.
//
// Parameters:
//   - ctx: context for cancellation and timeout
//   - req: the request parameters
//
// Returns the result of the RPC call, or an error if the invocation fails.
func (c *RPCClient) PhoneInviteConferenceCallParticipant(ctx context.Context, req *PhoneInviteConferenceCallParticipantRequest) (UpdatesClass, error) {
	result, err := c.invoke(ctx, req, func(r io.Reader) (TLObject, error) {
		return ReadTLObject(r)
	})
	if err != nil {
		return nil, err
	}
	if _c, _ok := result.(UpdatesClass); _ok {
		return _c, nil
	}
	return nil, fmt.Errorf("unexpected result type %T", result)
}

// PhoneDeclineConferenceCallInviteTypeID is the constructor ID for the RPC function phone.declineConferenceCallInvite.
const PhoneDeclineConferenceCallInviteTypeID = 0x3c479971

// PhoneDeclineConferenceCallInviteRequest represents TL type `phone.declineConferenceCallInvite#3c479971`.
//
// See https://core.telegram.org/method/phone/declineConferenceCallInvite for reference.
type PhoneDeclineConferenceCallInviteRequest struct {
	MsgID int32 `json:"msg_id,omitempty"`
}

// ConstructorID returns the TL constructor identifier 0x3c479971.
func (v *PhoneDeclineConferenceCallInviteRequest) ConstructorID() uint32 {
	return PhoneDeclineConferenceCallInviteTypeID
}

// Encode serializes PhoneDeclineConferenceCallInviteRequest to a bytes.Buffer using the TL binary protocol.
func (v *PhoneDeclineConferenceCallInviteRequest) Encode(b *bytes.Buffer) error {
	WriteInt(b, PhoneDeclineConferenceCallInviteTypeID)
	WriteInt(b, uint32(v.MsgID))
	return nil
}

// PhoneDeclineConferenceCallInvite invokes the phone.declineConferenceCallInvite RPC method on the server.
//
// Parameters:
//   - ctx: context for cancellation and timeout
//   - req: the request parameters
//
// Returns the result of the RPC call, or an error if the invocation fails.
func (c *RPCClient) PhoneDeclineConferenceCallInvite(ctx context.Context, req *PhoneDeclineConferenceCallInviteRequest) (UpdatesClass, error) {
	result, err := c.invoke(ctx, req, func(r io.Reader) (TLObject, error) {
		return ReadTLObject(r)
	})
	if err != nil {
		return nil, err
	}
	if _c, _ok := result.(UpdatesClass); _ok {
		return _c, nil
	}
	return nil, fmt.Errorf("unexpected result type %T", result)
}

// PhoneGetGroupCallChainBlocksTypeID is the constructor ID for the RPC function phone.getGroupCallChainBlocks.
const PhoneGetGroupCallChainBlocksTypeID = 0xee9f88a6

// PhoneGetGroupCallChainBlocksRequest represents TL type `phone.getGroupCallChainBlocks#ee9f88a6`.
//
// See https://core.telegram.org/method/phone/getGroupCallChainBlocks for reference.
type PhoneGetGroupCallChainBlocksRequest struct {
	Call       InputGroupCallClass `json:"call,omitempty"`
	SubChainID int32               `json:"sub_chain_id,omitempty"`
	Offset     int32               `json:"offset,omitempty"`
	Limit      int32               `json:"limit,omitempty"`
}

// ConstructorID returns the TL constructor identifier 0xee9f88a6.
func (v *PhoneGetGroupCallChainBlocksRequest) ConstructorID() uint32 {
	return PhoneGetGroupCallChainBlocksTypeID
}

// Encode serializes PhoneGetGroupCallChainBlocksRequest to a bytes.Buffer using the TL binary protocol.
func (v *PhoneGetGroupCallChainBlocksRequest) Encode(b *bytes.Buffer) error {
	WriteInt(b, PhoneGetGroupCallChainBlocksTypeID)
	EncodeTLObject(b, v.Call)
	WriteInt(b, uint32(v.SubChainID))
	WriteInt(b, uint32(v.Offset))
	WriteInt(b, uint32(v.Limit))
	return nil
}

// PhoneGetGroupCallChainBlocks invokes the phone.getGroupCallChainBlocks RPC method on the server.
//
// Parameters:
//   - ctx: context for cancellation and timeout
//   - req: the request parameters
//
// Returns the result of the RPC call, or an error if the invocation fails.
func (c *RPCClient) PhoneGetGroupCallChainBlocks(ctx context.Context, req *PhoneGetGroupCallChainBlocksRequest) (UpdatesClass, error) {
	result, err := c.invoke(ctx, req, func(r io.Reader) (TLObject, error) {
		return ReadTLObject(r)
	})
	if err != nil {
		return nil, err
	}
	if _c, _ok := result.(UpdatesClass); _ok {
		return _c, nil
	}
	return nil, fmt.Errorf("unexpected result type %T", result)
}

// PhoneSendGroupCallMessageTypeID is the constructor ID for the RPC function phone.sendGroupCallMessage.
const PhoneSendGroupCallMessageTypeID = 0xb1d11410

// PhoneSendGroupCallMessageRequest represents TL type `phone.sendGroupCallMessage#b1d11410`.
//
// See https://core.telegram.org/method/phone/sendGroupCallMessage for reference.
type PhoneSendGroupCallMessageRequest struct {
	Flags          Fields              `json:"-"`
	Call           InputGroupCallClass `json:"call,omitempty"`
	RandomID       int64               `json:"random_id,omitempty"`
	Message        *TextWithEntities   `json:"message,omitempty"`
	AllowPaidStars int64               `json:"allow_paid_stars,omitempty"`
	SendAs         InputPeerClass      `json:"send_as,omitempty"`
}

// SetFlags computes flags from non-zero optional fields.
func (v *PhoneSendGroupCallMessageRequest) SetFlags() {
	if v.AllowPaidStars != 0 {
		v.Flags.Set(0)
	}
	if v.SendAs != nil {
		v.Flags.Set(1)
	}
}

// ConstructorID returns the TL constructor identifier 0xb1d11410.
func (v *PhoneSendGroupCallMessageRequest) ConstructorID() uint32 {
	return PhoneSendGroupCallMessageTypeID
}

// Encode serializes PhoneSendGroupCallMessageRequest to a bytes.Buffer using the TL binary protocol.
func (v *PhoneSendGroupCallMessageRequest) Encode(b *bytes.Buffer) error {
	WriteInt(b, PhoneSendGroupCallMessageTypeID)
	v.SetFlags()
	WriteInt(b, uint32(v.Flags))
	EncodeTLObject(b, v.Call)
	WriteLong(b, v.RandomID)
	EncodeTLObject(b, v.Message)
	if v.Flags.Has(0) {
		WriteLong(b, v.AllowPaidStars)
	}
	if v.Flags.Has(1) {
		EncodeTLObject(b, v.SendAs)
	}
	return nil
}

// PhoneSendGroupCallMessage invokes the phone.sendGroupCallMessage RPC method on the server.
//
// Parameters:
//   - ctx: context for cancellation and timeout
//   - req: the request parameters
//
// Returns the result of the RPC call, or an error if the invocation fails.
func (c *RPCClient) PhoneSendGroupCallMessage(ctx context.Context, req *PhoneSendGroupCallMessageRequest) (UpdatesClass, error) {
	result, err := c.invoke(ctx, req, func(r io.Reader) (TLObject, error) {
		return ReadTLObject(r)
	})
	if err != nil {
		return nil, err
	}
	if _c, _ok := result.(UpdatesClass); _ok {
		return _c, nil
	}
	return nil, fmt.Errorf("unexpected result type %T", result)
}

// PhoneSendGroupCallEncryptedMessageTypeID is the constructor ID for the RPC function phone.sendGroupCallEncryptedMessage.
const PhoneSendGroupCallEncryptedMessageTypeID = 0xe5afa56d

// PhoneSendGroupCallEncryptedMessageRequest represents TL type `phone.sendGroupCallEncryptedMessage#e5afa56d`.
//
// See https://core.telegram.org/method/phone/sendGroupCallEncryptedMessage for reference.
type PhoneSendGroupCallEncryptedMessageRequest struct {
	Call             InputGroupCallClass `json:"call,omitempty"`
	EncryptedMessage []byte              `json:"encrypted_message,omitempty"`
}

// ConstructorID returns the TL constructor identifier 0xe5afa56d.
func (v *PhoneSendGroupCallEncryptedMessageRequest) ConstructorID() uint32 {
	return PhoneSendGroupCallEncryptedMessageTypeID
}

// Encode serializes PhoneSendGroupCallEncryptedMessageRequest to a bytes.Buffer using the TL binary protocol.
func (v *PhoneSendGroupCallEncryptedMessageRequest) Encode(b *bytes.Buffer) error {
	WriteInt(b, PhoneSendGroupCallEncryptedMessageTypeID)
	EncodeTLObject(b, v.Call)
	WriteBytes(b, v.EncryptedMessage)
	return nil
}

// PhoneSendGroupCallEncryptedMessage invokes the phone.sendGroupCallEncryptedMessage RPC method on the server.
//
// Parameters:
//   - ctx: context for cancellation and timeout
//   - req: the request parameters
//
// Returns the result of the RPC call, or an error if the invocation fails.
func (c *RPCClient) PhoneSendGroupCallEncryptedMessage(ctx context.Context, req *PhoneSendGroupCallEncryptedMessageRequest) (bool, error) {
	result, err := c.invoke(ctx, req, func(r io.Reader) (TLObject, error) {
		return ReadTLObject(r)
	})
	if err != nil {
		return false, err
	}
	_ = result
	return true, nil
}

// PhoneDeleteGroupCallMessagesTypeID is the constructor ID for the RPC function phone.deleteGroupCallMessages.
const PhoneDeleteGroupCallMessagesTypeID = 0xf64f54f7

// PhoneDeleteGroupCallMessagesRequest represents TL type `phone.deleteGroupCallMessages#f64f54f7`.
//
// See https://core.telegram.org/method/phone/deleteGroupCallMessages for reference.
type PhoneDeleteGroupCallMessagesRequest struct {
	Flags      Fields              `json:"-"`
	ReportSpam bool                `json:"report_spam,omitempty"`
	Call       InputGroupCallClass `json:"call,omitempty"`
	Messages   []int32             `json:"messages,omitempty"`
}

// SetFlags computes flags from non-zero optional fields.
func (v *PhoneDeleteGroupCallMessagesRequest) SetFlags() {
	if v.ReportSpam {
		v.Flags.Set(0)
	}
}

// ConstructorID returns the TL constructor identifier 0xf64f54f7.
func (v *PhoneDeleteGroupCallMessagesRequest) ConstructorID() uint32 {
	return PhoneDeleteGroupCallMessagesTypeID
}

// Encode serializes PhoneDeleteGroupCallMessagesRequest to a bytes.Buffer using the TL binary protocol.
func (v *PhoneDeleteGroupCallMessagesRequest) Encode(b *bytes.Buffer) error {
	WriteInt(b, PhoneDeleteGroupCallMessagesTypeID)
	v.SetFlags()
	WriteInt(b, uint32(v.Flags))
	EncodeTLObject(b, v.Call)
	WriteVectorInt(b, v.Messages)
	return nil
}

// PhoneDeleteGroupCallMessages invokes the phone.deleteGroupCallMessages RPC method on the server.
//
// Parameters:
//   - ctx: context for cancellation and timeout
//   - req: the request parameters
//
// Returns the result of the RPC call, or an error if the invocation fails.
func (c *RPCClient) PhoneDeleteGroupCallMessages(ctx context.Context, req *PhoneDeleteGroupCallMessagesRequest) (UpdatesClass, error) {
	result, err := c.invoke(ctx, req, func(r io.Reader) (TLObject, error) {
		return ReadTLObject(r)
	})
	if err != nil {
		return nil, err
	}
	if _c, _ok := result.(UpdatesClass); _ok {
		return _c, nil
	}
	return nil, fmt.Errorf("unexpected result type %T", result)
}

// PhoneDeleteGroupCallParticipantMessagesTypeID is the constructor ID for the RPC function phone.deleteGroupCallParticipantMessages.
const PhoneDeleteGroupCallParticipantMessagesTypeID = 0x1dbfeca0

// PhoneDeleteGroupCallParticipantMessagesRequest represents TL type `phone.deleteGroupCallParticipantMessages#1dbfeca0`.
//
// See https://core.telegram.org/method/phone/deleteGroupCallParticipantMessages for reference.
type PhoneDeleteGroupCallParticipantMessagesRequest struct {
	Flags       Fields              `json:"-"`
	ReportSpam  bool                `json:"report_spam,omitempty"`
	Call        InputGroupCallClass `json:"call,omitempty"`
	Participant InputPeerClass      `json:"participant,omitempty"`
}

// SetFlags computes flags from non-zero optional fields.
func (v *PhoneDeleteGroupCallParticipantMessagesRequest) SetFlags() {
	if v.ReportSpam {
		v.Flags.Set(0)
	}
}

// ConstructorID returns the TL constructor identifier 0x1dbfeca0.
func (v *PhoneDeleteGroupCallParticipantMessagesRequest) ConstructorID() uint32 {
	return PhoneDeleteGroupCallParticipantMessagesTypeID
}

// Encode serializes PhoneDeleteGroupCallParticipantMessagesRequest to a bytes.Buffer using the TL binary protocol.
func (v *PhoneDeleteGroupCallParticipantMessagesRequest) Encode(b *bytes.Buffer) error {
	WriteInt(b, PhoneDeleteGroupCallParticipantMessagesTypeID)
	v.SetFlags()
	WriteInt(b, uint32(v.Flags))
	EncodeTLObject(b, v.Call)
	EncodeTLObject(b, v.Participant)
	return nil
}

// PhoneDeleteGroupCallParticipantMessages invokes the phone.deleteGroupCallParticipantMessages RPC method on the server.
//
// Parameters:
//   - ctx: context for cancellation and timeout
//   - req: the request parameters
//
// Returns the result of the RPC call, or an error if the invocation fails.
func (c *RPCClient) PhoneDeleteGroupCallParticipantMessages(ctx context.Context, req *PhoneDeleteGroupCallParticipantMessagesRequest) (UpdatesClass, error) {
	result, err := c.invoke(ctx, req, func(r io.Reader) (TLObject, error) {
		return ReadTLObject(r)
	})
	if err != nil {
		return nil, err
	}
	if _c, _ok := result.(UpdatesClass); _ok {
		return _c, nil
	}
	return nil, fmt.Errorf("unexpected result type %T", result)
}

// PhoneGetGroupCallStarsTypeID is the constructor ID for the RPC function phone.getGroupCallStars.
const PhoneGetGroupCallStarsTypeID = 0x6f636302

// PhoneGetGroupCallStarsRequest represents TL type `phone.getGroupCallStars#6f636302`.
//
// See https://core.telegram.org/method/phone/getGroupCallStars for reference.
type PhoneGetGroupCallStarsRequest struct {
	Call InputGroupCallClass `json:"call,omitempty"`
}

// ConstructorID returns the TL constructor identifier 0x6f636302.
func (v *PhoneGetGroupCallStarsRequest) ConstructorID() uint32 {
	return PhoneGetGroupCallStarsTypeID
}

// Encode serializes PhoneGetGroupCallStarsRequest to a bytes.Buffer using the TL binary protocol.
func (v *PhoneGetGroupCallStarsRequest) Encode(b *bytes.Buffer) error {
	WriteInt(b, PhoneGetGroupCallStarsTypeID)
	EncodeTLObject(b, v.Call)
	return nil
}

// PhoneGetGroupCallStars invokes the phone.getGroupCallStars RPC method on the server.
//
// Parameters:
//   - ctx: context for cancellation and timeout
//   - req: the request parameters
//
// Returns the result of the RPC call, or an error if the invocation fails.
func (c *RPCClient) PhoneGetGroupCallStars(ctx context.Context, req *PhoneGetGroupCallStarsRequest) (*PhoneGroupCallStars, error) {
	result, err := c.invoke(ctx, req, func(r io.Reader) (TLObject, error) {
		return ReadTLObject(r)
	})
	if err != nil {
		return nil, err
	}
	if _c, _ok := result.(*PhoneGroupCallStars); _ok {
		return _c, nil
	}
	return nil, fmt.Errorf("unexpected result type %T", result)
}

// PhoneSaveDefaultSendAsTypeID is the constructor ID for the RPC function phone.saveDefaultSendAs.
const PhoneSaveDefaultSendAsTypeID = 0x4167add1

// PhoneSaveDefaultSendAsRequest represents TL type `phone.saveDefaultSendAs#4167add1`.
//
// See https://core.telegram.org/method/phone/saveDefaultSendAs for reference.
type PhoneSaveDefaultSendAsRequest struct {
	Call   InputGroupCallClass `json:"call,omitempty"`
	SendAs InputPeerClass      `json:"send_as,omitempty"`
}

// ConstructorID returns the TL constructor identifier 0x4167add1.
func (v *PhoneSaveDefaultSendAsRequest) ConstructorID() uint32 {
	return PhoneSaveDefaultSendAsTypeID
}

// Encode serializes PhoneSaveDefaultSendAsRequest to a bytes.Buffer using the TL binary protocol.
func (v *PhoneSaveDefaultSendAsRequest) Encode(b *bytes.Buffer) error {
	WriteInt(b, PhoneSaveDefaultSendAsTypeID)
	EncodeTLObject(b, v.Call)
	EncodeTLObject(b, v.SendAs)
	return nil
}

// PhoneSaveDefaultSendAs invokes the phone.saveDefaultSendAs RPC method on the server.
//
// Parameters:
//   - ctx: context for cancellation and timeout
//   - req: the request parameters
//
// Returns the result of the RPC call, or an error if the invocation fails.
func (c *RPCClient) PhoneSaveDefaultSendAs(ctx context.Context, req *PhoneSaveDefaultSendAsRequest) (bool, error) {
	result, err := c.invoke(ctx, req, func(r io.Reader) (TLObject, error) {
		return ReadTLObject(r)
	})
	if err != nil {
		return false, err
	}
	_ = result
	return true, nil
}
