// Code generated by tlgen. DO NOT EDIT.

package tg

import (
	"bytes"
	"io"
)

// PhoneCallDiscardReasonClass is the interface for TL type PhoneCallDiscardReason.
// Implementations must satisfy TLObject and are used to represent
// any constructor of the PhoneCallDiscardReason TL type.
type PhoneCallDiscardReasonClass interface {
	TLObject
	isPhoneCallDiscardReason()
}

// PhoneCallDiscardReasonMissedTypeID is the constructor ID for TL type phoneCallDiscardReasonMissed.
const PhoneCallDiscardReasonMissedTypeID = 0x85e42301

// PhoneCallDiscardReasonDisconnectTypeID is the constructor ID for TL type phoneCallDiscardReasonDisconnect.
const PhoneCallDiscardReasonDisconnectTypeID = 0xe095c1a0

// PhoneCallDiscardReasonHangupTypeID is the constructor ID for TL type phoneCallDiscardReasonHangup.
const PhoneCallDiscardReasonHangupTypeID = 0x57adc690

// PhoneCallDiscardReasonBusyTypeID is the constructor ID for TL type phoneCallDiscardReasonBusy.
const PhoneCallDiscardReasonBusyTypeID = 0xfaf7e8c9

// PhoneCallDiscardReasonMigrateConferenceCallTypeID is the constructor ID for TL type phoneCallDiscardReasonMigrateConferenceCall.
const PhoneCallDiscardReasonMigrateConferenceCallTypeID = 0x9fbbf1f7

// isPhoneCallDiscardReason marks PhoneCallDiscardReasonMissed as implementing the PhoneCallDiscardReasonClass interface.
func (*PhoneCallDiscardReasonMissed) isPhoneCallDiscardReason() {}

// isPhoneCallDiscardReason marks PhoneCallDiscardReasonDisconnect as implementing the PhoneCallDiscardReasonClass interface.
func (*PhoneCallDiscardReasonDisconnect) isPhoneCallDiscardReason() {}

// isPhoneCallDiscardReason marks PhoneCallDiscardReasonHangup as implementing the PhoneCallDiscardReasonClass interface.
func (*PhoneCallDiscardReasonHangup) isPhoneCallDiscardReason() {}

// isPhoneCallDiscardReason marks PhoneCallDiscardReasonBusy as implementing the PhoneCallDiscardReasonClass interface.
func (*PhoneCallDiscardReasonBusy) isPhoneCallDiscardReason() {}

// isPhoneCallDiscardReason marks PhoneCallDiscardReasonMigrateConferenceCall as implementing the PhoneCallDiscardReasonClass interface.
func (*PhoneCallDiscardReasonMigrateConferenceCall) isPhoneCallDiscardReason() {}

// PhoneCallDiscardReasonMissed represents the TL constructor phoneCallDiscardReasonMissed (0x85e42301).
//
// See https://core.telegram.org/constructor/phoneCallDiscardReasonMissed for reference.
type PhoneCallDiscardReasonMissed struct {
}

// ConstructorID returns the TL constructor identifier 0x85e42301.
func (v *PhoneCallDiscardReasonMissed) ConstructorID() uint32 {
	return PhoneCallDiscardReasonMissedTypeID
}

// Encode serializes PhoneCallDiscardReasonMissed to a bytes.Buffer using the TL binary protocol.
func (v *PhoneCallDiscardReasonMissed) Encode(b *bytes.Buffer) error {
	WriteInt(b, PhoneCallDiscardReasonMissedTypeID)
	return nil
}

// DecodePhoneCallDiscardReasonMissed deserializes a PhoneCallDiscardReasonMissed from a reader using the TL binary protocol.
func DecodePhoneCallDiscardReasonMissed(r io.Reader) (*PhoneCallDiscardReasonMissed, error) {
	v := &PhoneCallDiscardReasonMissed{}
	return v, nil
}

func init() {
	Registry[PhoneCallDiscardReasonMissedTypeID] = func(r io.Reader) (TLObject, error) {
		return DecodePhoneCallDiscardReasonMissed(r)
	}
}

// PhoneCallDiscardReasonDisconnect represents the TL constructor phoneCallDiscardReasonDisconnect (0xe095c1a0).
//
// See https://core.telegram.org/constructor/phoneCallDiscardReasonDisconnect for reference.
type PhoneCallDiscardReasonDisconnect struct {
}

// ConstructorID returns the TL constructor identifier 0xe095c1a0.
func (v *PhoneCallDiscardReasonDisconnect) ConstructorID() uint32 {
	return PhoneCallDiscardReasonDisconnectTypeID
}

// Encode serializes PhoneCallDiscardReasonDisconnect to a bytes.Buffer using the TL binary protocol.
func (v *PhoneCallDiscardReasonDisconnect) Encode(b *bytes.Buffer) error {
	WriteInt(b, PhoneCallDiscardReasonDisconnectTypeID)
	return nil
}

// DecodePhoneCallDiscardReasonDisconnect deserializes a PhoneCallDiscardReasonDisconnect from a reader using the TL binary protocol.
func DecodePhoneCallDiscardReasonDisconnect(r io.Reader) (*PhoneCallDiscardReasonDisconnect, error) {
	v := &PhoneCallDiscardReasonDisconnect{}
	return v, nil
}

func init() {
	Registry[PhoneCallDiscardReasonDisconnectTypeID] = func(r io.Reader) (TLObject, error) {
		return DecodePhoneCallDiscardReasonDisconnect(r)
	}
}

// PhoneCallDiscardReasonHangup represents the TL constructor phoneCallDiscardReasonHangup (0x57adc690).
//
// See https://core.telegram.org/constructor/phoneCallDiscardReasonHangup for reference.
type PhoneCallDiscardReasonHangup struct {
}

// ConstructorID returns the TL constructor identifier 0x57adc690.
func (v *PhoneCallDiscardReasonHangup) ConstructorID() uint32 {
	return PhoneCallDiscardReasonHangupTypeID
}

// Encode serializes PhoneCallDiscardReasonHangup to a bytes.Buffer using the TL binary protocol.
func (v *PhoneCallDiscardReasonHangup) Encode(b *bytes.Buffer) error {
	WriteInt(b, PhoneCallDiscardReasonHangupTypeID)
	return nil
}

// DecodePhoneCallDiscardReasonHangup deserializes a PhoneCallDiscardReasonHangup from a reader using the TL binary protocol.
func DecodePhoneCallDiscardReasonHangup(r io.Reader) (*PhoneCallDiscardReasonHangup, error) {
	v := &PhoneCallDiscardReasonHangup{}
	return v, nil
}

func init() {
	Registry[PhoneCallDiscardReasonHangupTypeID] = func(r io.Reader) (TLObject, error) {
		return DecodePhoneCallDiscardReasonHangup(r)
	}
}

// PhoneCallDiscardReasonBusy represents the TL constructor phoneCallDiscardReasonBusy (0xfaf7e8c9).
//
// See https://core.telegram.org/constructor/phoneCallDiscardReasonBusy for reference.
type PhoneCallDiscardReasonBusy struct {
}

// ConstructorID returns the TL constructor identifier 0xfaf7e8c9.
func (v *PhoneCallDiscardReasonBusy) ConstructorID() uint32 {
	return PhoneCallDiscardReasonBusyTypeID
}

// Encode serializes PhoneCallDiscardReasonBusy to a bytes.Buffer using the TL binary protocol.
func (v *PhoneCallDiscardReasonBusy) Encode(b *bytes.Buffer) error {
	WriteInt(b, PhoneCallDiscardReasonBusyTypeID)
	return nil
}

// DecodePhoneCallDiscardReasonBusy deserializes a PhoneCallDiscardReasonBusy from a reader using the TL binary protocol.
func DecodePhoneCallDiscardReasonBusy(r io.Reader) (*PhoneCallDiscardReasonBusy, error) {
	v := &PhoneCallDiscardReasonBusy{}
	return v, nil
}

func init() {
	Registry[PhoneCallDiscardReasonBusyTypeID] = func(r io.Reader) (TLObject, error) {
		return DecodePhoneCallDiscardReasonBusy(r)
	}
}

// PhoneCallDiscardReasonMigrateConferenceCall represents the TL constructor phoneCallDiscardReasonMigrateConferenceCall (0x9fbbf1f7).
//
// See https://core.telegram.org/constructor/phoneCallDiscardReasonMigrateConferenceCall for reference.
type PhoneCallDiscardReasonMigrateConferenceCall struct {
	Slug string `json:"slug,omitempty"`
}

// ConstructorID returns the TL constructor identifier 0x9fbbf1f7.
func (v *PhoneCallDiscardReasonMigrateConferenceCall) ConstructorID() uint32 {
	return PhoneCallDiscardReasonMigrateConferenceCallTypeID
}

// Encode serializes PhoneCallDiscardReasonMigrateConferenceCall to a bytes.Buffer using the TL binary protocol.
func (v *PhoneCallDiscardReasonMigrateConferenceCall) Encode(b *bytes.Buffer) error {
	WriteInt(b, PhoneCallDiscardReasonMigrateConferenceCallTypeID)
	WriteString(b, v.Slug)
	return nil
}

// DecodePhoneCallDiscardReasonMigrateConferenceCall deserializes a PhoneCallDiscardReasonMigrateConferenceCall from a reader using the TL binary protocol.
func DecodePhoneCallDiscardReasonMigrateConferenceCall(r io.Reader) (*PhoneCallDiscardReasonMigrateConferenceCall, error) {
	v := &PhoneCallDiscardReasonMigrateConferenceCall{}
	v.Slug = ReadString(r)
	return v, nil
}

func init() {
	Registry[PhoneCallDiscardReasonMigrateConferenceCallTypeID] = func(r io.Reader) (TLObject, error) {
		return DecodePhoneCallDiscardReasonMigrateConferenceCall(r)
	}
}

// InputPhoneCallTypeID is the constructor ID for TL type inputPhoneCall.
const InputPhoneCallTypeID = 0x1e36fded

// InputPhoneCall represents the TL constructor inputPhoneCall (0x1e36fded).
//
// See https://core.telegram.org/constructor/inputPhoneCall for reference.
type InputPhoneCall struct {
	ID         int64 `json:"id,omitempty"`
	AccessHash int64 `json:"access_hash,omitempty"`
}

// ConstructorID returns the TL constructor identifier 0x1e36fded.
func (v *InputPhoneCall) ConstructorID() uint32 {
	return InputPhoneCallTypeID
}

// Encode serializes InputPhoneCall to a bytes.Buffer using the TL binary protocol.
func (v *InputPhoneCall) Encode(b *bytes.Buffer) error {
	WriteInt(b, InputPhoneCallTypeID)
	WriteLong(b, v.ID)
	WriteLong(b, v.AccessHash)
	return nil
}

// DecodeInputPhoneCall deserializes a InputPhoneCall from a reader using the TL binary protocol.
func DecodeInputPhoneCall(r io.Reader) (*InputPhoneCall, error) {
	v := &InputPhoneCall{}
	v.ID = ReadLong(r)
	v.AccessHash = ReadLong(r)
	return v, nil
}

func init() {
	Registry[InputPhoneCallTypeID] = func(r io.Reader) (TLObject, error) {
		return DecodeInputPhoneCall(r)
	}
}

// PhoneCallClass is the interface for TL type PhoneCall.
// Implementations must satisfy TLObject and are used to represent
// any constructor of the PhoneCall TL type.
type PhoneCallClass interface {
	TLObject
	isPhoneCall()
}

// PhoneCallEmptyTypeID is the constructor ID for TL type phoneCallEmpty.
const PhoneCallEmptyTypeID = 0x5366c915

// PhoneCallWaitingTypeID is the constructor ID for TL type phoneCallWaiting.
const PhoneCallWaitingTypeID = 0xc5226f17

// PhoneCallRequestedTypeID is the constructor ID for TL type phoneCallRequested.
const PhoneCallRequestedTypeID = 0x14b0ed0c

// PhoneCallAcceptedTypeID is the constructor ID for TL type phoneCallAccepted.
const PhoneCallAcceptedTypeID = 0x3660c311

// PhoneCallTypeID is the constructor ID for TL type phoneCall.
const PhoneCallTypeID = 0x30535af5

// PhoneCallDiscardedTypeID is the constructor ID for TL type phoneCallDiscarded.
const PhoneCallDiscardedTypeID = 0x50ca4de1

// PhonePhoneCallTypeID is the constructor ID for TL type phone.phoneCall.
const PhonePhoneCallTypeID = 0xec82e140

// isPhoneCall marks PhoneCallEmpty as implementing the PhoneCallClass interface.
func (*PhoneCallEmpty) isPhoneCall() {}

// isPhoneCall marks PhoneCallWaiting as implementing the PhoneCallClass interface.
func (*PhoneCallWaiting) isPhoneCall() {}

// isPhoneCall marks PhoneCallRequested as implementing the PhoneCallClass interface.
func (*PhoneCallRequested) isPhoneCall() {}

// isPhoneCall marks PhoneCallAccepted as implementing the PhoneCallClass interface.
func (*PhoneCallAccepted) isPhoneCall() {}

// isPhoneCall marks PhoneCall as implementing the PhoneCallClass interface.
func (*PhoneCall) isPhoneCall() {}

// isPhoneCall marks PhoneCallDiscarded as implementing the PhoneCallClass interface.
func (*PhoneCallDiscarded) isPhoneCall() {}

// isPhoneCall marks PhonePhoneCall as implementing the PhoneCallClass interface.
func (*PhonePhoneCall) isPhoneCall() {}

// PhoneCallEmpty represents the TL constructor phoneCallEmpty (0x5366c915).
//
// See https://core.telegram.org/constructor/phoneCallEmpty for reference.
type PhoneCallEmpty struct {
	ID int64 `json:"id,omitempty"`
}

// ConstructorID returns the TL constructor identifier 0x5366c915.
func (v *PhoneCallEmpty) ConstructorID() uint32 {
	return PhoneCallEmptyTypeID
}

// Encode serializes PhoneCallEmpty to a bytes.Buffer using the TL binary protocol.
func (v *PhoneCallEmpty) Encode(b *bytes.Buffer) error {
	WriteInt(b, PhoneCallEmptyTypeID)
	WriteLong(b, v.ID)
	return nil
}

// DecodePhoneCallEmpty deserializes a PhoneCallEmpty from a reader using the TL binary protocol.
func DecodePhoneCallEmpty(r io.Reader) (*PhoneCallEmpty, error) {
	v := &PhoneCallEmpty{}
	v.ID = ReadLong(r)
	return v, nil
}

func init() {
	Registry[PhoneCallEmptyTypeID] = func(r io.Reader) (TLObject, error) {
		return DecodePhoneCallEmpty(r)
	}
}

// PhoneCallWaiting represents the TL constructor phoneCallWaiting (0xc5226f17).
//
// See https://core.telegram.org/constructor/phoneCallWaiting for reference.
type PhoneCallWaiting struct {
	Flags         Fields             `json:"-"`
	Video         bool               `json:"video,omitempty"`
	ID            int64              `json:"id,omitempty"`
	AccessHash    int64              `json:"access_hash,omitempty"`
	Date          int32              `json:"date,omitempty"`
	AdminID       int64              `json:"admin_id,omitempty"`
	ParticipantID int64              `json:"participant_id,omitempty"`
	Protocol      *PhoneCallProtocol `json:"protocol,omitempty"`
	ReceiveDate   int32              `json:"receive_date,omitempty"`
}

// SetFlags computes flags from non-zero optional fields.
func (v *PhoneCallWaiting) SetFlags() {
	if v.Video {
		v.Flags.Set(6)
	}
	if v.ReceiveDate != 0 {
		v.Flags.Set(0)
	}
}

// ConstructorID returns the TL constructor identifier 0xc5226f17.
func (v *PhoneCallWaiting) ConstructorID() uint32 {
	return PhoneCallWaitingTypeID
}

// Encode serializes PhoneCallWaiting to a bytes.Buffer using the TL binary protocol.
func (v *PhoneCallWaiting) Encode(b *bytes.Buffer) error {
	WriteInt(b, PhoneCallWaitingTypeID)
	v.SetFlags()
	WriteInt(b, uint32(v.Flags))
	WriteLong(b, v.ID)
	WriteLong(b, v.AccessHash)
	WriteInt(b, uint32(v.Date))
	WriteLong(b, v.AdminID)
	WriteLong(b, v.ParticipantID)
	EncodeTLObject(b, v.Protocol)
	if v.Flags.Has(0) {
		WriteInt(b, uint32(v.ReceiveDate))
	}
	return nil
}

// DecodePhoneCallWaiting deserializes a PhoneCallWaiting from a reader using the TL binary protocol.
func DecodePhoneCallWaiting(r io.Reader) (*PhoneCallWaiting, error) {
	v := &PhoneCallWaiting{}
	{
		var _f uint32
		_f, _ = ReadIntErr(r)
		v.Flags = Fields(_f)
	}
	v.Video = v.Flags.Has(6)
	v.ID = ReadLong(r)
	v.AccessHash = ReadLong(r)
	v.Date = int32(ReadInt(r))
	v.AdminID = ReadLong(r)
	v.ParticipantID = ReadLong(r)
	_objProtocol, _ := ReadTLObject(r)
	v.Protocol = _objProtocol.(*PhoneCallProtocol)
	if v.Flags.Has(0) {
		v.ReceiveDate = int32(ReadInt(r))
	}
	return v, nil
}

func init() {
	Registry[PhoneCallWaitingTypeID] = func(r io.Reader) (TLObject, error) {
		return DecodePhoneCallWaiting(r)
	}
}

// PhoneCallRequested represents the TL constructor phoneCallRequested (0x14b0ed0c).
//
// See https://core.telegram.org/constructor/phoneCallRequested for reference.
type PhoneCallRequested struct {
	Flags         Fields             `json:"-"`
	Video         bool               `json:"video,omitempty"`
	ID            int64              `json:"id,omitempty"`
	AccessHash    int64              `json:"access_hash,omitempty"`
	Date          int32              `json:"date,omitempty"`
	AdminID       int64              `json:"admin_id,omitempty"`
	ParticipantID int64              `json:"participant_id,omitempty"`
	GAHash        []byte             `json:"ga_hash,omitempty"`
	Protocol      *PhoneCallProtocol `json:"protocol,omitempty"`
}

// SetFlags computes flags from non-zero optional fields.
func (v *PhoneCallRequested) SetFlags() {
	if v.Video {
		v.Flags.Set(6)
	}
}

// ConstructorID returns the TL constructor identifier 0x14b0ed0c.
func (v *PhoneCallRequested) ConstructorID() uint32 {
	return PhoneCallRequestedTypeID
}

// Encode serializes PhoneCallRequested to a bytes.Buffer using the TL binary protocol.
func (v *PhoneCallRequested) Encode(b *bytes.Buffer) error {
	WriteInt(b, PhoneCallRequestedTypeID)
	v.SetFlags()
	WriteInt(b, uint32(v.Flags))
	WriteLong(b, v.ID)
	WriteLong(b, v.AccessHash)
	WriteInt(b, uint32(v.Date))
	WriteLong(b, v.AdminID)
	WriteLong(b, v.ParticipantID)
	WriteBytes(b, v.GAHash)
	EncodeTLObject(b, v.Protocol)
	return nil
}

// DecodePhoneCallRequested deserializes a PhoneCallRequested from a reader using the TL binary protocol.
func DecodePhoneCallRequested(r io.Reader) (*PhoneCallRequested, error) {
	v := &PhoneCallRequested{}
	{
		var _f uint32
		_f, _ = ReadIntErr(r)
		v.Flags = Fields(_f)
	}
	v.Video = v.Flags.Has(6)
	v.ID = ReadLong(r)
	v.AccessHash = ReadLong(r)
	v.Date = int32(ReadInt(r))
	v.AdminID = ReadLong(r)
	v.ParticipantID = ReadLong(r)
	v.GAHash = ReadBytes(r)
	_objProtocol, _ := ReadTLObject(r)
	v.Protocol = _objProtocol.(*PhoneCallProtocol)
	return v, nil
}

func init() {
	Registry[PhoneCallRequestedTypeID] = func(r io.Reader) (TLObject, error) {
		return DecodePhoneCallRequested(r)
	}
}

// PhoneCallAccepted represents the TL constructor phoneCallAccepted (0x3660c311).
//
// See https://core.telegram.org/constructor/phoneCallAccepted for reference.
type PhoneCallAccepted struct {
	Flags         Fields             `json:"-"`
	Video         bool               `json:"video,omitempty"`
	ID            int64              `json:"id,omitempty"`
	AccessHash    int64              `json:"access_hash,omitempty"`
	Date          int32              `json:"date,omitempty"`
	AdminID       int64              `json:"admin_id,omitempty"`
	ParticipantID int64              `json:"participant_id,omitempty"`
	GB            []byte             `json:"gb,omitempty"`
	Protocol      *PhoneCallProtocol `json:"protocol,omitempty"`
}

// SetFlags computes flags from non-zero optional fields.
func (v *PhoneCallAccepted) SetFlags() {
	if v.Video {
		v.Flags.Set(6)
	}
}

// ConstructorID returns the TL constructor identifier 0x3660c311.
func (v *PhoneCallAccepted) ConstructorID() uint32 {
	return PhoneCallAcceptedTypeID
}

// Encode serializes PhoneCallAccepted to a bytes.Buffer using the TL binary protocol.
func (v *PhoneCallAccepted) Encode(b *bytes.Buffer) error {
	WriteInt(b, PhoneCallAcceptedTypeID)
	v.SetFlags()
	WriteInt(b, uint32(v.Flags))
	WriteLong(b, v.ID)
	WriteLong(b, v.AccessHash)
	WriteInt(b, uint32(v.Date))
	WriteLong(b, v.AdminID)
	WriteLong(b, v.ParticipantID)
	WriteBytes(b, v.GB)
	EncodeTLObject(b, v.Protocol)
	return nil
}

// DecodePhoneCallAccepted deserializes a PhoneCallAccepted from a reader using the TL binary protocol.
func DecodePhoneCallAccepted(r io.Reader) (*PhoneCallAccepted, error) {
	v := &PhoneCallAccepted{}
	{
		var _f uint32
		_f, _ = ReadIntErr(r)
		v.Flags = Fields(_f)
	}
	v.Video = v.Flags.Has(6)
	v.ID = ReadLong(r)
	v.AccessHash = ReadLong(r)
	v.Date = int32(ReadInt(r))
	v.AdminID = ReadLong(r)
	v.ParticipantID = ReadLong(r)
	v.GB = ReadBytes(r)
	_objProtocol, _ := ReadTLObject(r)
	v.Protocol = _objProtocol.(*PhoneCallProtocol)
	return v, nil
}

func init() {
	Registry[PhoneCallAcceptedTypeID] = func(r io.Reader) (TLObject, error) {
		return DecodePhoneCallAccepted(r)
	}
}

// PhoneCall represents the TL constructor phoneCall (0x30535af5).
//
// See https://core.telegram.org/constructor/phoneCall for reference.
type PhoneCall struct {
	Flags               Fields                 `json:"-"`
	P2pAllowed          bool                   `json:"p2p_allowed,omitempty"`
	Video               bool                   `json:"video,omitempty"`
	ConferenceSupported bool                   `json:"conference_supported,omitempty"`
	ID                  int64                  `json:"id,omitempty"`
	AccessHash          int64                  `json:"access_hash,omitempty"`
	Date                int32                  `json:"date,omitempty"`
	AdminID             int64                  `json:"admin_id,omitempty"`
	ParticipantID       int64                  `json:"participant_id,omitempty"`
	GAOrB               []byte                 `json:"ga_or_b,omitempty"`
	KeyFingerprint      int64                  `json:"key_fingerprint,omitempty"`
	Protocol            *PhoneCallProtocol     `json:"protocol,omitempty"`
	Connections         []PhoneConnectionClass `json:"connections,omitempty"`
	StartDate           int32                  `json:"start_date,omitempty"`
	CustomParameters    *DataJSON              `json:"custom_parameters,omitempty"`
}

// SetFlags computes flags from non-zero optional fields.
func (v *PhoneCall) SetFlags() {
	if v.P2pAllowed {
		v.Flags.Set(5)
	}
	if v.Video {
		v.Flags.Set(6)
	}
	if v.ConferenceSupported {
		v.Flags.Set(8)
	}
	if v.CustomParameters != nil {
		v.Flags.Set(7)
	}
}

// ConstructorID returns the TL constructor identifier 0x30535af5.
func (v *PhoneCall) ConstructorID() uint32 {
	return PhoneCallTypeID
}

// Encode serializes PhoneCall to a bytes.Buffer using the TL binary protocol.
func (v *PhoneCall) Encode(b *bytes.Buffer) error {
	WriteInt(b, PhoneCallTypeID)
	v.SetFlags()
	WriteInt(b, uint32(v.Flags))
	WriteLong(b, v.ID)
	WriteLong(b, v.AccessHash)
	WriteInt(b, uint32(v.Date))
	WriteLong(b, v.AdminID)
	WriteLong(b, v.ParticipantID)
	WriteBytes(b, v.GAOrB)
	WriteLong(b, v.KeyFingerprint)
	EncodeTLObject(b, v.Protocol)
	WriteInt(b, 0x1cb5c415)
	WriteInt(b, uint32(len(v.Connections)))
	for _, _item := range v.Connections {
		EncodeTLObject(b, _item)
	}
	WriteInt(b, uint32(v.StartDate))
	if v.Flags.Has(7) {
		EncodeTLObject(b, v.CustomParameters)
	}
	return nil
}

// DecodePhoneCall deserializes a PhoneCall from a reader using the TL binary protocol.
func DecodePhoneCall(r io.Reader) (*PhoneCall, error) {
	v := &PhoneCall{}
	{
		var _f uint32
		_f, _ = ReadIntErr(r)
		v.Flags = Fields(_f)
	}
	v.P2pAllowed = v.Flags.Has(5)
	v.Video = v.Flags.Has(6)
	v.ConferenceSupported = v.Flags.Has(8)
	v.ID = ReadLong(r)
	v.AccessHash = ReadLong(r)
	v.Date = int32(ReadInt(r))
	v.AdminID = ReadLong(r)
	v.ParticipantID = ReadLong(r)
	v.GAOrB = ReadBytes(r)
	v.KeyFingerprint = ReadLong(r)
	_objProtocol, _ := ReadTLObject(r)
	v.Protocol = _objProtocol.(*PhoneCallProtocol)
	ReadInt(r)
	_cntConnections := ReadInt(r)
	if err := checkVectorCount(_cntConnections); err != nil {
		return nil, err
	}
	v.Connections = make([]PhoneConnectionClass, _cntConnections)
	for _iConnections := range v.Connections {
		_objConnections, _ := ReadTLObject(r)
		v.Connections[_iConnections] = _objConnections.(PhoneConnectionClass)
	}
	v.StartDate = int32(ReadInt(r))
	if v.Flags.Has(7) {
		_objCustomParameters, _ := ReadTLObject(r)
		v.CustomParameters = _objCustomParameters.(*DataJSON)
	}
	return v, nil
}

func init() {
	Registry[PhoneCallTypeID] = func(r io.Reader) (TLObject, error) {
		return DecodePhoneCall(r)
	}
}

// PhoneCallDiscarded represents the TL constructor phoneCallDiscarded (0x50ca4de1).
//
// See https://core.telegram.org/constructor/phoneCallDiscarded for reference.
type PhoneCallDiscarded struct {
	Flags      Fields                      `json:"-"`
	NeedRating bool                        `json:"need_rating,omitempty"`
	NeedDebug  bool                        `json:"need_debug,omitempty"`
	Video      bool                        `json:"video,omitempty"`
	ID         int64                       `json:"id,omitempty"`
	Reason     PhoneCallDiscardReasonClass `json:"reason,omitempty"`
	Duration   int32                       `json:"duration,omitempty"`
}

// SetFlags computes flags from non-zero optional fields.
func (v *PhoneCallDiscarded) SetFlags() {
	if v.NeedRating {
		v.Flags.Set(2)
	}
	if v.NeedDebug {
		v.Flags.Set(3)
	}
	if v.Video {
		v.Flags.Set(6)
	}
	if v.Reason != nil {
		v.Flags.Set(0)
	}
	if v.Duration != 0 {
		v.Flags.Set(1)
	}
}

// ConstructorID returns the TL constructor identifier 0x50ca4de1.
func (v *PhoneCallDiscarded) ConstructorID() uint32 {
	return PhoneCallDiscardedTypeID
}

// Encode serializes PhoneCallDiscarded to a bytes.Buffer using the TL binary protocol.
func (v *PhoneCallDiscarded) Encode(b *bytes.Buffer) error {
	WriteInt(b, PhoneCallDiscardedTypeID)
	v.SetFlags()
	WriteInt(b, uint32(v.Flags))
	WriteLong(b, v.ID)
	if v.Flags.Has(0) {
		EncodeTLObject(b, v.Reason)
	}
	if v.Flags.Has(1) {
		WriteInt(b, uint32(v.Duration))
	}
	return nil
}

// DecodePhoneCallDiscarded deserializes a PhoneCallDiscarded from a reader using the TL binary protocol.
func DecodePhoneCallDiscarded(r io.Reader) (*PhoneCallDiscarded, error) {
	v := &PhoneCallDiscarded{}
	{
		var _f uint32
		_f, _ = ReadIntErr(r)
		v.Flags = Fields(_f)
	}
	v.NeedRating = v.Flags.Has(2)
	v.NeedDebug = v.Flags.Has(3)
	v.Video = v.Flags.Has(6)
	v.ID = ReadLong(r)
	if v.Flags.Has(0) {
		_objReason, _ := ReadTLObject(r)
		v.Reason = _objReason.(PhoneCallDiscardReasonClass)
	}
	if v.Flags.Has(1) {
		v.Duration = int32(ReadInt(r))
	}
	return v, nil
}

func init() {
	Registry[PhoneCallDiscardedTypeID] = func(r io.Reader) (TLObject, error) {
		return DecodePhoneCallDiscarded(r)
	}
}

// PhonePhoneCall represents the TL constructor phone.phoneCall (0xec82e140).
//
// See https://core.telegram.org/constructor/phone.phoneCall for reference.
type PhonePhoneCall struct {
	PhoneCall PhoneCallClass `json:"phone_call,omitempty"`
	Users     []UserClass    `json:"users,omitempty"`
}

// ConstructorID returns the TL constructor identifier 0xec82e140.
func (v *PhonePhoneCall) ConstructorID() uint32 {
	return PhonePhoneCallTypeID
}

// Encode serializes PhonePhoneCall to a bytes.Buffer using the TL binary protocol.
func (v *PhonePhoneCall) Encode(b *bytes.Buffer) error {
	WriteInt(b, PhonePhoneCallTypeID)
	EncodeTLObject(b, v.PhoneCall)
	WriteInt(b, 0x1cb5c415)
	WriteInt(b, uint32(len(v.Users)))
	for _, _item := range v.Users {
		EncodeTLObject(b, _item)
	}
	return nil
}

// DecodePhonePhoneCall deserializes a PhonePhoneCall from a reader using the TL binary protocol.
func DecodePhonePhoneCall(r io.Reader) (*PhonePhoneCall, error) {
	v := &PhonePhoneCall{}
	_objPhoneCall, _ := ReadTLObject(r)
	v.PhoneCall = _objPhoneCall.(PhoneCallClass)
	ReadInt(r)
	_cntUsers := ReadInt(r)
	if err := checkVectorCount(_cntUsers); err != nil {
		return nil, err
	}
	v.Users = make([]UserClass, _cntUsers)
	for _iUsers := range v.Users {
		_objUsers, _ := ReadTLObject(r)
		v.Users[_iUsers] = _objUsers.(UserClass)
	}
	return v, nil
}

func init() {
	Registry[PhonePhoneCallTypeID] = func(r io.Reader) (TLObject, error) {
		return DecodePhonePhoneCall(r)
	}
}

// PhoneConnectionClass is the interface for TL type PhoneConnection.
// Implementations must satisfy TLObject and are used to represent
// any constructor of the PhoneConnection TL type.
type PhoneConnectionClass interface {
	TLObject
	isPhoneConnection()
}

// PhoneConnectionTypeID is the constructor ID for TL type phoneConnection.
const PhoneConnectionTypeID = 0x9cc123c7

// PhoneConnectionWebrtcTypeID is the constructor ID for TL type phoneConnectionWebrtc.
const PhoneConnectionWebrtcTypeID = 0x635fe375

// isPhoneConnection marks PhoneConnection as implementing the PhoneConnectionClass interface.
func (*PhoneConnection) isPhoneConnection() {}

// isPhoneConnection marks PhoneConnectionWebrtc as implementing the PhoneConnectionClass interface.
func (*PhoneConnectionWebrtc) isPhoneConnection() {}

// PhoneConnection represents the TL constructor phoneConnection (0x9cc123c7).
//
// See https://core.telegram.org/constructor/phoneConnection for reference.
type PhoneConnection struct {
	Flags   Fields `json:"-"`
	TCP     bool   `json:"tcp,omitempty"`
	ID      int64  `json:"id,omitempty"`
	Ip      string `json:"ip,omitempty"`
	IPv6    string `json:"i_pv6,omitempty"`
	Port    int32  `json:"port,omitempty"`
	PeerTag []byte `json:"peer_tag,omitempty"`
}

// SetFlags computes flags from non-zero optional fields.
func (v *PhoneConnection) SetFlags() {
	if v.TCP {
		v.Flags.Set(0)
	}
}

// ConstructorID returns the TL constructor identifier 0x9cc123c7.
func (v *PhoneConnection) ConstructorID() uint32 {
	return PhoneConnectionTypeID
}

// Encode serializes PhoneConnection to a bytes.Buffer using the TL binary protocol.
func (v *PhoneConnection) Encode(b *bytes.Buffer) error {
	WriteInt(b, PhoneConnectionTypeID)
	v.SetFlags()
	WriteInt(b, uint32(v.Flags))
	WriteLong(b, v.ID)
	WriteString(b, v.Ip)
	WriteString(b, v.IPv6)
	WriteInt(b, uint32(v.Port))
	WriteBytes(b, v.PeerTag)
	return nil
}

// DecodePhoneConnection deserializes a PhoneConnection from a reader using the TL binary protocol.
func DecodePhoneConnection(r io.Reader) (*PhoneConnection, error) {
	v := &PhoneConnection{}
	{
		var _f uint32
		_f, _ = ReadIntErr(r)
		v.Flags = Fields(_f)
	}
	v.TCP = v.Flags.Has(0)
	v.ID = ReadLong(r)
	v.Ip = ReadString(r)
	v.IPv6 = ReadString(r)
	v.Port = int32(ReadInt(r))
	v.PeerTag = ReadBytes(r)
	return v, nil
}

func init() {
	Registry[PhoneConnectionTypeID] = func(r io.Reader) (TLObject, error) {
		return DecodePhoneConnection(r)
	}
}

// PhoneConnectionWebrtc represents the TL constructor phoneConnectionWebrtc (0x635fe375).
//
// See https://core.telegram.org/constructor/phoneConnectionWebrtc for reference.
type PhoneConnectionWebrtc struct {
	Flags    Fields `json:"-"`
	Turn     bool   `json:"turn,omitempty"`
	Stun     bool   `json:"stun,omitempty"`
	ID       int64  `json:"id,omitempty"`
	Ip       string `json:"ip,omitempty"`
	IPv6     string `json:"i_pv6,omitempty"`
	Port     int32  `json:"port,omitempty"`
	Username string `json:"username,omitempty"`
	Password string `json:"password,omitempty"`
}

// SetFlags computes flags from non-zero optional fields.
func (v *PhoneConnectionWebrtc) SetFlags() {
	if v.Turn {
		v.Flags.Set(0)
	}
	if v.Stun {
		v.Flags.Set(1)
	}
}

// ConstructorID returns the TL constructor identifier 0x635fe375.
func (v *PhoneConnectionWebrtc) ConstructorID() uint32 {
	return PhoneConnectionWebrtcTypeID
}

// Encode serializes PhoneConnectionWebrtc to a bytes.Buffer using the TL binary protocol.
func (v *PhoneConnectionWebrtc) Encode(b *bytes.Buffer) error {
	WriteInt(b, PhoneConnectionWebrtcTypeID)
	v.SetFlags()
	WriteInt(b, uint32(v.Flags))
	WriteLong(b, v.ID)
	WriteString(b, v.Ip)
	WriteString(b, v.IPv6)
	WriteInt(b, uint32(v.Port))
	WriteString(b, v.Username)
	WriteString(b, v.Password)
	return nil
}

// DecodePhoneConnectionWebrtc deserializes a PhoneConnectionWebrtc from a reader using the TL binary protocol.
func DecodePhoneConnectionWebrtc(r io.Reader) (*PhoneConnectionWebrtc, error) {
	v := &PhoneConnectionWebrtc{}
	{
		var _f uint32
		_f, _ = ReadIntErr(r)
		v.Flags = Fields(_f)
	}
	v.Turn = v.Flags.Has(0)
	v.Stun = v.Flags.Has(1)
	v.ID = ReadLong(r)
	v.Ip = ReadString(r)
	v.IPv6 = ReadString(r)
	v.Port = int32(ReadInt(r))
	v.Username = ReadString(r)
	v.Password = ReadString(r)
	return v, nil
}

func init() {
	Registry[PhoneConnectionWebrtcTypeID] = func(r io.Reader) (TLObject, error) {
		return DecodePhoneConnectionWebrtc(r)
	}
}

// PhoneCallProtocolTypeID is the constructor ID for TL type phoneCallProtocol.
const PhoneCallProtocolTypeID = 0xfc878fc8

// PhoneCallProtocol represents the TL constructor phoneCallProtocol (0xfc878fc8).
//
// See https://core.telegram.org/constructor/phoneCallProtocol for reference.
type PhoneCallProtocol struct {
	Flags           Fields   `json:"-"`
	UDPP2p          bool     `json:"udpp2p,omitempty"`
	UDPReflector    bool     `json:"udp_reflector,omitempty"`
	MinLayer        int32    `json:"min_layer,omitempty"`
	MaxLayer        int32    `json:"max_layer,omitempty"`
	LibraryVersions []string `json:"library_versions,omitempty"`
}

// SetFlags computes flags from non-zero optional fields.
func (v *PhoneCallProtocol) SetFlags() {
	if v.UDPP2p {
		v.Flags.Set(0)
	}
	if v.UDPReflector {
		v.Flags.Set(1)
	}
}

// ConstructorID returns the TL constructor identifier 0xfc878fc8.
func (v *PhoneCallProtocol) ConstructorID() uint32 {
	return PhoneCallProtocolTypeID
}

// Encode serializes PhoneCallProtocol to a bytes.Buffer using the TL binary protocol.
func (v *PhoneCallProtocol) Encode(b *bytes.Buffer) error {
	WriteInt(b, PhoneCallProtocolTypeID)
	v.SetFlags()
	WriteInt(b, uint32(v.Flags))
	WriteInt(b, uint32(v.MinLayer))
	WriteInt(b, uint32(v.MaxLayer))
	WriteVectorString(b, v.LibraryVersions)
	return nil
}

// DecodePhoneCallProtocol deserializes a PhoneCallProtocol from a reader using the TL binary protocol.
func DecodePhoneCallProtocol(r io.Reader) (*PhoneCallProtocol, error) {
	v := &PhoneCallProtocol{}
	{
		var _f uint32
		_f, _ = ReadIntErr(r)
		v.Flags = Fields(_f)
	}
	v.UDPP2p = v.Flags.Has(0)
	v.UDPReflector = v.Flags.Has(1)
	v.MinLayer = int32(ReadInt(r))
	v.MaxLayer = int32(ReadInt(r))
	v.LibraryVersions = ReadVectorString(r)
	return v, nil
}

func init() {
	Registry[PhoneCallProtocolTypeID] = func(r io.Reader) (TLObject, error) {
		return DecodePhoneCallProtocol(r)
	}
}

// GroupCallClass is the interface for TL type GroupCall.
// Implementations must satisfy TLObject and are used to represent
// any constructor of the GroupCall TL type.
type GroupCallClass interface {
	TLObject
	isGroupCall()
}

// GroupCallDiscardedTypeID is the constructor ID for TL type groupCallDiscarded.
const GroupCallDiscardedTypeID = 0x7780bcb4

// GroupCallTypeID is the constructor ID for TL type groupCall.
const GroupCallTypeID = 0xefb2b617

// PhoneGroupCallTypeID is the constructor ID for TL type phone.groupCall.
const PhoneGroupCallTypeID = 0x9e727aad

// isGroupCall marks GroupCallDiscarded as implementing the GroupCallClass interface.
func (*GroupCallDiscarded) isGroupCall() {}

// isGroupCall marks GroupCall as implementing the GroupCallClass interface.
func (*GroupCall) isGroupCall() {}

// isGroupCall marks PhoneGroupCall as implementing the GroupCallClass interface.
func (*PhoneGroupCall) isGroupCall() {}

// GroupCallDiscarded represents the TL constructor groupCallDiscarded (0x7780bcb4).
//
// See https://core.telegram.org/constructor/groupCallDiscarded for reference.
type GroupCallDiscarded struct {
	ID         int64 `json:"id,omitempty"`
	AccessHash int64 `json:"access_hash,omitempty"`
	Duration   int32 `json:"duration,omitempty"`
}

// ConstructorID returns the TL constructor identifier 0x7780bcb4.
func (v *GroupCallDiscarded) ConstructorID() uint32 {
	return GroupCallDiscardedTypeID
}

// Encode serializes GroupCallDiscarded to a bytes.Buffer using the TL binary protocol.
func (v *GroupCallDiscarded) Encode(b *bytes.Buffer) error {
	WriteInt(b, GroupCallDiscardedTypeID)
	WriteLong(b, v.ID)
	WriteLong(b, v.AccessHash)
	WriteInt(b, uint32(v.Duration))
	return nil
}

// DecodeGroupCallDiscarded deserializes a GroupCallDiscarded from a reader using the TL binary protocol.
func DecodeGroupCallDiscarded(r io.Reader) (*GroupCallDiscarded, error) {
	v := &GroupCallDiscarded{}
	v.ID = ReadLong(r)
	v.AccessHash = ReadLong(r)
	v.Duration = int32(ReadInt(r))
	return v, nil
}

func init() {
	Registry[GroupCallDiscardedTypeID] = func(r io.Reader) (TLObject, error) {
		return DecodeGroupCallDiscarded(r)
	}
}

// GroupCall represents the TL constructor groupCall (0xefb2b617).
//
// See https://core.telegram.org/constructor/groupCall for reference.
type GroupCall struct {
	Flags                    Fields    `json:"-"`
	JoinMuted                bool      `json:"join_muted,omitempty"`
	CanChangeJoinMuted       bool      `json:"can_change_join_muted,omitempty"`
	JoinDateAsc              bool      `json:"join_date_asc,omitempty"`
	ScheduleStartSubscribed  bool      `json:"schedule_start_subscribed,omitempty"`
	CanStartVideo            bool      `json:"can_start_video,omitempty"`
	RecordVideoActive        bool      `json:"record_video_active,omitempty"`
	RtmpStream               bool      `json:"rtmp_stream,omitempty"`
	ListenersHidden          bool      `json:"listeners_hidden,omitempty"`
	Conference               bool      `json:"conference,omitempty"`
	Creator                  bool      `json:"creator,omitempty"`
	MessagesEnabled          bool      `json:"messages_enabled,omitempty"`
	CanChangeMessagesEnabled bool      `json:"can_change_messages_enabled,omitempty"`
	Min                      bool      `json:"min,omitempty"`
	ID                       int64     `json:"id,omitempty"`
	AccessHash               int64     `json:"access_hash,omitempty"`
	ParticipantsCount        int32     `json:"participants_count,omitempty"`
	Title                    string    `json:"title,omitempty"`
	StreamDCID               int32     `json:"stream_dcid,omitempty"`
	RecordStartDate          int32     `json:"record_start_date,omitempty"`
	ScheduleDate             int32     `json:"schedule_date,omitempty"`
	UnmutedVideoCount        int32     `json:"unmuted_video_count,omitempty"`
	UnmutedVideoLimit        int32     `json:"unmuted_video_limit,omitempty"`
	Version                  int32     `json:"version,omitempty"`
	InviteLink               string    `json:"invite_link,omitempty"`
	SendPaidMessagesStars    int64     `json:"send_paid_messages_stars,omitempty"`
	DefaultSendAs            PeerClass `json:"default_send_as,omitempty"`
}

// SetFlags computes flags from non-zero optional fields.
func (v *GroupCall) SetFlags() {
	if v.JoinMuted {
		v.Flags.Set(1)
	}
	if v.CanChangeJoinMuted {
		v.Flags.Set(2)
	}
	if v.JoinDateAsc {
		v.Flags.Set(6)
	}
	if v.ScheduleStartSubscribed {
		v.Flags.Set(8)
	}
	if v.CanStartVideo {
		v.Flags.Set(9)
	}
	if v.RecordVideoActive {
		v.Flags.Set(11)
	}
	if v.RtmpStream {
		v.Flags.Set(12)
	}
	if v.ListenersHidden {
		v.Flags.Set(13)
	}
	if v.Conference {
		v.Flags.Set(14)
	}
	if v.Creator {
		v.Flags.Set(15)
	}
	if v.MessagesEnabled {
		v.Flags.Set(17)
	}
	if v.CanChangeMessagesEnabled {
		v.Flags.Set(18)
	}
	if v.Min {
		v.Flags.Set(19)
	}
	if v.Title != "" {
		v.Flags.Set(3)
	}
	if v.StreamDCID != 0 {
		v.Flags.Set(4)
	}
	if v.RecordStartDate != 0 {
		v.Flags.Set(5)
	}
	if v.ScheduleDate != 0 {
		v.Flags.Set(7)
	}
	if v.UnmutedVideoCount != 0 {
		v.Flags.Set(10)
	}
	if v.InviteLink != "" {
		v.Flags.Set(16)
	}
	if v.SendPaidMessagesStars != 0 {
		v.Flags.Set(20)
	}
	if v.DefaultSendAs != nil {
		v.Flags.Set(21)
	}
}

// ConstructorID returns the TL constructor identifier 0xefb2b617.
func (v *GroupCall) ConstructorID() uint32 {
	return GroupCallTypeID
}

// Encode serializes GroupCall to a bytes.Buffer using the TL binary protocol.
func (v *GroupCall) Encode(b *bytes.Buffer) error {
	WriteInt(b, GroupCallTypeID)
	v.SetFlags()
	WriteInt(b, uint32(v.Flags))
	WriteLong(b, v.ID)
	WriteLong(b, v.AccessHash)
	WriteInt(b, uint32(v.ParticipantsCount))
	if v.Flags.Has(3) {
		WriteString(b, v.Title)
	}
	if v.Flags.Has(4) {
		WriteInt(b, uint32(v.StreamDCID))
	}
	if v.Flags.Has(5) {
		WriteInt(b, uint32(v.RecordStartDate))
	}
	if v.Flags.Has(7) {
		WriteInt(b, uint32(v.ScheduleDate))
	}
	if v.Flags.Has(10) {
		WriteInt(b, uint32(v.UnmutedVideoCount))
	}
	WriteInt(b, uint32(v.UnmutedVideoLimit))
	WriteInt(b, uint32(v.Version))
	if v.Flags.Has(16) {
		WriteString(b, v.InviteLink)
	}
	if v.Flags.Has(20) {
		WriteLong(b, v.SendPaidMessagesStars)
	}
	if v.Flags.Has(21) {
		EncodeTLObject(b, v.DefaultSendAs)
	}
	return nil
}

// DecodeGroupCall deserializes a GroupCall from a reader using the TL binary protocol.
func DecodeGroupCall(r io.Reader) (*GroupCall, error) {
	v := &GroupCall{}
	{
		var _f uint32
		_f, _ = ReadIntErr(r)
		v.Flags = Fields(_f)
	}
	v.JoinMuted = v.Flags.Has(1)
	v.CanChangeJoinMuted = v.Flags.Has(2)
	v.JoinDateAsc = v.Flags.Has(6)
	v.ScheduleStartSubscribed = v.Flags.Has(8)
	v.CanStartVideo = v.Flags.Has(9)
	v.RecordVideoActive = v.Flags.Has(11)
	v.RtmpStream = v.Flags.Has(12)
	v.ListenersHidden = v.Flags.Has(13)
	v.Conference = v.Flags.Has(14)
	v.Creator = v.Flags.Has(15)
	v.MessagesEnabled = v.Flags.Has(17)
	v.CanChangeMessagesEnabled = v.Flags.Has(18)
	v.Min = v.Flags.Has(19)
	v.ID = ReadLong(r)
	v.AccessHash = ReadLong(r)
	v.ParticipantsCount = int32(ReadInt(r))
	if v.Flags.Has(3) {
		v.Title = ReadString(r)
	}
	if v.Flags.Has(4) {
		v.StreamDCID = int32(ReadInt(r))
	}
	if v.Flags.Has(5) {
		v.RecordStartDate = int32(ReadInt(r))
	}
	if v.Flags.Has(7) {
		v.ScheduleDate = int32(ReadInt(r))
	}
	if v.Flags.Has(10) {
		v.UnmutedVideoCount = int32(ReadInt(r))
	}
	v.UnmutedVideoLimit = int32(ReadInt(r))
	v.Version = int32(ReadInt(r))
	if v.Flags.Has(16) {
		v.InviteLink = ReadString(r)
	}
	if v.Flags.Has(20) {
		v.SendPaidMessagesStars = ReadLong(r)
	}
	if v.Flags.Has(21) {
		_objDefaultSendAs, _ := ReadTLObject(r)
		v.DefaultSendAs = _objDefaultSendAs.(PeerClass)
	}
	return v, nil
}

func init() {
	Registry[GroupCallTypeID] = func(r io.Reader) (TLObject, error) {
		return DecodeGroupCall(r)
	}
}

// PhoneGroupCall represents the TL constructor phone.groupCall (0x9e727aad).
//
// See https://core.telegram.org/constructor/phone.groupCall for reference.
type PhoneGroupCall struct {
	Call                   GroupCallClass          `json:"call,omitempty"`
	Participants           []*GroupCallParticipant `json:"participants,omitempty"`
	ParticipantsNextOffset string                  `json:"participants_next_offset,omitempty"`
	Chats                  []ChatClass             `json:"chats,omitempty"`
	Users                  []UserClass             `json:"users,omitempty"`
}

// ConstructorID returns the TL constructor identifier 0x9e727aad.
func (v *PhoneGroupCall) ConstructorID() uint32 {
	return PhoneGroupCallTypeID
}

// Encode serializes PhoneGroupCall to a bytes.Buffer using the TL binary protocol.
func (v *PhoneGroupCall) Encode(b *bytes.Buffer) error {
	WriteInt(b, PhoneGroupCallTypeID)
	EncodeTLObject(b, v.Call)
	WriteInt(b, 0x1cb5c415)
	WriteInt(b, uint32(len(v.Participants)))
	for _, _item := range v.Participants {
		EncodeTLObject(b, _item)
	}
	WriteString(b, v.ParticipantsNextOffset)
	WriteInt(b, 0x1cb5c415)
	WriteInt(b, uint32(len(v.Chats)))
	for _, _item := range v.Chats {
		EncodeTLObject(b, _item)
	}
	WriteInt(b, 0x1cb5c415)
	WriteInt(b, uint32(len(v.Users)))
	for _, _item := range v.Users {
		EncodeTLObject(b, _item)
	}
	return nil
}

// DecodePhoneGroupCall deserializes a PhoneGroupCall from a reader using the TL binary protocol.
func DecodePhoneGroupCall(r io.Reader) (*PhoneGroupCall, error) {
	v := &PhoneGroupCall{}
	_objCall, _ := ReadTLObject(r)
	v.Call = _objCall.(GroupCallClass)
	ReadInt(r)
	_cntParticipants := ReadInt(r)
	if err := checkVectorCount(_cntParticipants); err != nil {
		return nil, err
	}
	v.Participants = make([]*GroupCallParticipant, _cntParticipants)
	for _iParticipants := range v.Participants {
		_objParticipants, _ := ReadTLObject(r)
		v.Participants[_iParticipants] = _objParticipants.(*GroupCallParticipant)
	}
	v.ParticipantsNextOffset = ReadString(r)
	ReadInt(r)
	_cntChats := ReadInt(r)
	if err := checkVectorCount(_cntChats); err != nil {
		return nil, err
	}
	v.Chats = make([]ChatClass, _cntChats)
	for _iChats := range v.Chats {
		_objChats, _ := ReadTLObject(r)
		v.Chats[_iChats] = _objChats.(ChatClass)
	}
	ReadInt(r)
	_cntUsers := ReadInt(r)
	if err := checkVectorCount(_cntUsers); err != nil {
		return nil, err
	}
	v.Users = make([]UserClass, _cntUsers)
	for _iUsers := range v.Users {
		_objUsers, _ := ReadTLObject(r)
		v.Users[_iUsers] = _objUsers.(UserClass)
	}
	return v, nil
}

func init() {
	Registry[PhoneGroupCallTypeID] = func(r io.Reader) (TLObject, error) {
		return DecodePhoneGroupCall(r)
	}
}

// InputGroupCallClass is the interface for TL type InputGroupCall.
// Implementations must satisfy TLObject and are used to represent
// any constructor of the InputGroupCall TL type.
type InputGroupCallClass interface {
	TLObject
	isInputGroupCall()
}

// InputGroupCallTypeID is the constructor ID for TL type inputGroupCall.
const InputGroupCallTypeID = 0xd8aa840f

// InputGroupCallSlugTypeID is the constructor ID for TL type inputGroupCallSlug.
const InputGroupCallSlugTypeID = 0xfe06823f

// InputGroupCallInviteMessageTypeID is the constructor ID for TL type inputGroupCallInviteMessage.
const InputGroupCallInviteMessageTypeID = 0x8c10603f

// isInputGroupCall marks InputGroupCall as implementing the InputGroupCallClass interface.
func (*InputGroupCall) isInputGroupCall() {}

// isInputGroupCall marks InputGroupCallSlug as implementing the InputGroupCallClass interface.
func (*InputGroupCallSlug) isInputGroupCall() {}

// isInputGroupCall marks InputGroupCallInviteMessage as implementing the InputGroupCallClass interface.
func (*InputGroupCallInviteMessage) isInputGroupCall() {}

// InputGroupCall represents the TL constructor inputGroupCall (0xd8aa840f).
//
// See https://core.telegram.org/constructor/inputGroupCall for reference.
type InputGroupCall struct {
	ID         int64 `json:"id,omitempty"`
	AccessHash int64 `json:"access_hash,omitempty"`
}

// ConstructorID returns the TL constructor identifier 0xd8aa840f.
func (v *InputGroupCall) ConstructorID() uint32 {
	return InputGroupCallTypeID
}

// Encode serializes InputGroupCall to a bytes.Buffer using the TL binary protocol.
func (v *InputGroupCall) Encode(b *bytes.Buffer) error {
	WriteInt(b, InputGroupCallTypeID)
	WriteLong(b, v.ID)
	WriteLong(b, v.AccessHash)
	return nil
}

// DecodeInputGroupCall deserializes a InputGroupCall from a reader using the TL binary protocol.
func DecodeInputGroupCall(r io.Reader) (*InputGroupCall, error) {
	v := &InputGroupCall{}
	v.ID = ReadLong(r)
	v.AccessHash = ReadLong(r)
	return v, nil
}

func init() {
	Registry[InputGroupCallTypeID] = func(r io.Reader) (TLObject, error) {
		return DecodeInputGroupCall(r)
	}
}

// InputGroupCallSlug represents the TL constructor inputGroupCallSlug (0xfe06823f).
//
// See https://core.telegram.org/constructor/inputGroupCallSlug for reference.
type InputGroupCallSlug struct {
	Slug string `json:"slug,omitempty"`
}

// ConstructorID returns the TL constructor identifier 0xfe06823f.
func (v *InputGroupCallSlug) ConstructorID() uint32 {
	return InputGroupCallSlugTypeID
}

// Encode serializes InputGroupCallSlug to a bytes.Buffer using the TL binary protocol.
func (v *InputGroupCallSlug) Encode(b *bytes.Buffer) error {
	WriteInt(b, InputGroupCallSlugTypeID)
	WriteString(b, v.Slug)
	return nil
}

// DecodeInputGroupCallSlug deserializes a InputGroupCallSlug from a reader using the TL binary protocol.
func DecodeInputGroupCallSlug(r io.Reader) (*InputGroupCallSlug, error) {
	v := &InputGroupCallSlug{}
	v.Slug = ReadString(r)
	return v, nil
}

func init() {
	Registry[InputGroupCallSlugTypeID] = func(r io.Reader) (TLObject, error) {
		return DecodeInputGroupCallSlug(r)
	}
}

// InputGroupCallInviteMessage represents the TL constructor inputGroupCallInviteMessage (0x8c10603f).
//
// See https://core.telegram.org/constructor/inputGroupCallInviteMessage for reference.
type InputGroupCallInviteMessage struct {
	MsgID int32 `json:"msg_id,omitempty"`
}

// ConstructorID returns the TL constructor identifier 0x8c10603f.
func (v *InputGroupCallInviteMessage) ConstructorID() uint32 {
	return InputGroupCallInviteMessageTypeID
}

// Encode serializes InputGroupCallInviteMessage to a bytes.Buffer using the TL binary protocol.
func (v *InputGroupCallInviteMessage) Encode(b *bytes.Buffer) error {
	WriteInt(b, InputGroupCallInviteMessageTypeID)
	WriteInt(b, uint32(v.MsgID))
	return nil
}

// DecodeInputGroupCallInviteMessage deserializes a InputGroupCallInviteMessage from a reader using the TL binary protocol.
func DecodeInputGroupCallInviteMessage(r io.Reader) (*InputGroupCallInviteMessage, error) {
	v := &InputGroupCallInviteMessage{}
	v.MsgID = int32(ReadInt(r))
	return v, nil
}

func init() {
	Registry[InputGroupCallInviteMessageTypeID] = func(r io.Reader) (TLObject, error) {
		return DecodeInputGroupCallInviteMessage(r)
	}
}

// PhoneGroupParticipantsTypeID is the constructor ID for TL type phone.groupParticipants.
const PhoneGroupParticipantsTypeID = 0xf47751b6

// PhoneGroupParticipants represents the TL constructor phone.groupParticipants (0xf47751b6).
//
// See https://core.telegram.org/constructor/phone.groupParticipants for reference.
type PhoneGroupParticipants struct {
	Count        int32                   `json:"count,omitempty"`
	Participants []*GroupCallParticipant `json:"participants,omitempty"`
	NextOffset   string                  `json:"next_offset,omitempty"`
	Chats        []ChatClass             `json:"chats,omitempty"`
	Users        []UserClass             `json:"users,omitempty"`
	Version      int32                   `json:"version,omitempty"`
}

// ConstructorID returns the TL constructor identifier 0xf47751b6.
func (v *PhoneGroupParticipants) ConstructorID() uint32 {
	return PhoneGroupParticipantsTypeID
}

// Encode serializes PhoneGroupParticipants to a bytes.Buffer using the TL binary protocol.
func (v *PhoneGroupParticipants) Encode(b *bytes.Buffer) error {
	WriteInt(b, PhoneGroupParticipantsTypeID)
	WriteInt(b, uint32(v.Count))
	WriteInt(b, 0x1cb5c415)
	WriteInt(b, uint32(len(v.Participants)))
	for _, _item := range v.Participants {
		EncodeTLObject(b, _item)
	}
	WriteString(b, v.NextOffset)
	WriteInt(b, 0x1cb5c415)
	WriteInt(b, uint32(len(v.Chats)))
	for _, _item := range v.Chats {
		EncodeTLObject(b, _item)
	}
	WriteInt(b, 0x1cb5c415)
	WriteInt(b, uint32(len(v.Users)))
	for _, _item := range v.Users {
		EncodeTLObject(b, _item)
	}
	WriteInt(b, uint32(v.Version))
	return nil
}

// DecodePhoneGroupParticipants deserializes a PhoneGroupParticipants from a reader using the TL binary protocol.
func DecodePhoneGroupParticipants(r io.Reader) (*PhoneGroupParticipants, error) {
	v := &PhoneGroupParticipants{}
	v.Count = int32(ReadInt(r))
	ReadInt(r)
	_cntParticipants := ReadInt(r)
	if err := checkVectorCount(_cntParticipants); err != nil {
		return nil, err
	}
	v.Participants = make([]*GroupCallParticipant, _cntParticipants)
	for _iParticipants := range v.Participants {
		_objParticipants, _ := ReadTLObject(r)
		v.Participants[_iParticipants] = _objParticipants.(*GroupCallParticipant)
	}
	v.NextOffset = ReadString(r)
	ReadInt(r)
	_cntChats := ReadInt(r)
	if err := checkVectorCount(_cntChats); err != nil {
		return nil, err
	}
	v.Chats = make([]ChatClass, _cntChats)
	for _iChats := range v.Chats {
		_objChats, _ := ReadTLObject(r)
		v.Chats[_iChats] = _objChats.(ChatClass)
	}
	ReadInt(r)
	_cntUsers := ReadInt(r)
	if err := checkVectorCount(_cntUsers); err != nil {
		return nil, err
	}
	v.Users = make([]UserClass, _cntUsers)
	for _iUsers := range v.Users {
		_objUsers, _ := ReadTLObject(r)
		v.Users[_iUsers] = _objUsers.(UserClass)
	}
	v.Version = int32(ReadInt(r))
	return v, nil
}

func init() {
	Registry[PhoneGroupParticipantsTypeID] = func(r io.Reader) (TLObject, error) {
		return DecodePhoneGroupParticipants(r)
	}
}

// PhoneJoinAsPeersTypeID is the constructor ID for TL type phone.joinAsPeers.
const PhoneJoinAsPeersTypeID = 0xafe5623f

// PhoneJoinAsPeers represents the TL constructor phone.joinAsPeers (0xafe5623f).
//
// See https://core.telegram.org/constructor/phone.joinAsPeers for reference.
type PhoneJoinAsPeers struct {
	Peers []PeerClass `json:"peers,omitempty"`
	Chats []ChatClass `json:"chats,omitempty"`
	Users []UserClass `json:"users,omitempty"`
}

// ConstructorID returns the TL constructor identifier 0xafe5623f.
func (v *PhoneJoinAsPeers) ConstructorID() uint32 {
	return PhoneJoinAsPeersTypeID
}

// Encode serializes PhoneJoinAsPeers to a bytes.Buffer using the TL binary protocol.
func (v *PhoneJoinAsPeers) Encode(b *bytes.Buffer) error {
	WriteInt(b, PhoneJoinAsPeersTypeID)
	WriteInt(b, 0x1cb5c415)
	WriteInt(b, uint32(len(v.Peers)))
	for _, _item := range v.Peers {
		EncodeTLObject(b, _item)
	}
	WriteInt(b, 0x1cb5c415)
	WriteInt(b, uint32(len(v.Chats)))
	for _, _item := range v.Chats {
		EncodeTLObject(b, _item)
	}
	WriteInt(b, 0x1cb5c415)
	WriteInt(b, uint32(len(v.Users)))
	for _, _item := range v.Users {
		EncodeTLObject(b, _item)
	}
	return nil
}

// DecodePhoneJoinAsPeers deserializes a PhoneJoinAsPeers from a reader using the TL binary protocol.
func DecodePhoneJoinAsPeers(r io.Reader) (*PhoneJoinAsPeers, error) {
	v := &PhoneJoinAsPeers{}
	ReadInt(r)
	_cntPeers := ReadInt(r)
	if err := checkVectorCount(_cntPeers); err != nil {
		return nil, err
	}
	v.Peers = make([]PeerClass, _cntPeers)
	for _iPeers := range v.Peers {
		_objPeers, _ := ReadTLObject(r)
		v.Peers[_iPeers] = _objPeers.(PeerClass)
	}
	ReadInt(r)
	_cntChats := ReadInt(r)
	if err := checkVectorCount(_cntChats); err != nil {
		return nil, err
	}
	v.Chats = make([]ChatClass, _cntChats)
	for _iChats := range v.Chats {
		_objChats, _ := ReadTLObject(r)
		v.Chats[_iChats] = _objChats.(ChatClass)
	}
	ReadInt(r)
	_cntUsers := ReadInt(r)
	if err := checkVectorCount(_cntUsers); err != nil {
		return nil, err
	}
	v.Users = make([]UserClass, _cntUsers)
	for _iUsers := range v.Users {
		_objUsers, _ := ReadTLObject(r)
		v.Users[_iUsers] = _objUsers.(UserClass)
	}
	return v, nil
}

func init() {
	Registry[PhoneJoinAsPeersTypeID] = func(r io.Reader) (TLObject, error) {
		return DecodePhoneJoinAsPeers(r)
	}
}

// PhoneExportedGroupCallInviteTypeID is the constructor ID for TL type phone.exportedGroupCallInvite.
const PhoneExportedGroupCallInviteTypeID = 0x204bd158

// PhoneExportedGroupCallInvite represents the TL constructor phone.exportedGroupCallInvite (0x204bd158).
//
// See https://core.telegram.org/constructor/phone.exportedGroupCallInvite for reference.
type PhoneExportedGroupCallInvite struct {
	Link string `json:"link,omitempty"`
}

// ConstructorID returns the TL constructor identifier 0x204bd158.
func (v *PhoneExportedGroupCallInvite) ConstructorID() uint32 {
	return PhoneExportedGroupCallInviteTypeID
}

// Encode serializes PhoneExportedGroupCallInvite to a bytes.Buffer using the TL binary protocol.
func (v *PhoneExportedGroupCallInvite) Encode(b *bytes.Buffer) error {
	WriteInt(b, PhoneExportedGroupCallInviteTypeID)
	WriteString(b, v.Link)
	return nil
}

// DecodePhoneExportedGroupCallInvite deserializes a PhoneExportedGroupCallInvite from a reader using the TL binary protocol.
func DecodePhoneExportedGroupCallInvite(r io.Reader) (*PhoneExportedGroupCallInvite, error) {
	v := &PhoneExportedGroupCallInvite{}
	v.Link = ReadString(r)
	return v, nil
}

func init() {
	Registry[PhoneExportedGroupCallInviteTypeID] = func(r io.Reader) (TLObject, error) {
		return DecodePhoneExportedGroupCallInvite(r)
	}
}

// PhoneGroupCallStreamChannelsTypeID is the constructor ID for TL type phone.groupCallStreamChannels.
const PhoneGroupCallStreamChannelsTypeID = 0xd0e482b2

// PhoneGroupCallStreamChannels represents the TL constructor phone.groupCallStreamChannels (0xd0e482b2).
//
// See https://core.telegram.org/constructor/phone.groupCallStreamChannels for reference.
type PhoneGroupCallStreamChannels struct {
	Channels []*GroupCallStreamChannel `json:"channels,omitempty"`
}

// ConstructorID returns the TL constructor identifier 0xd0e482b2.
func (v *PhoneGroupCallStreamChannels) ConstructorID() uint32 {
	return PhoneGroupCallStreamChannelsTypeID
}

// Encode serializes PhoneGroupCallStreamChannels to a bytes.Buffer using the TL binary protocol.
func (v *PhoneGroupCallStreamChannels) Encode(b *bytes.Buffer) error {
	WriteInt(b, PhoneGroupCallStreamChannelsTypeID)
	WriteInt(b, 0x1cb5c415)
	WriteInt(b, uint32(len(v.Channels)))
	for _, _item := range v.Channels {
		EncodeTLObject(b, _item)
	}
	return nil
}

// DecodePhoneGroupCallStreamChannels deserializes a PhoneGroupCallStreamChannels from a reader using the TL binary protocol.
func DecodePhoneGroupCallStreamChannels(r io.Reader) (*PhoneGroupCallStreamChannels, error) {
	v := &PhoneGroupCallStreamChannels{}
	ReadInt(r)
	_cntChannels := ReadInt(r)
	if err := checkVectorCount(_cntChannels); err != nil {
		return nil, err
	}
	v.Channels = make([]*GroupCallStreamChannel, _cntChannels)
	for _iChannels := range v.Channels {
		_objChannels, _ := ReadTLObject(r)
		v.Channels[_iChannels] = _objChannels.(*GroupCallStreamChannel)
	}
	return v, nil
}

func init() {
	Registry[PhoneGroupCallStreamChannelsTypeID] = func(r io.Reader) (TLObject, error) {
		return DecodePhoneGroupCallStreamChannels(r)
	}
}

// PhoneGroupCallStreamRtmpURLTypeID is the constructor ID for TL type phone.groupCallStreamRtmpUrl.
const PhoneGroupCallStreamRtmpURLTypeID = 0x2dbf3432

// PhoneGroupCallStreamRtmpURL represents the TL constructor phone.groupCallStreamRtmpUrl (0x2dbf3432).
//
// See https://core.telegram.org/constructor/phone.groupCallStreamRtmpUrl for reference.
type PhoneGroupCallStreamRtmpURL struct {
	URL string `json:"url,omitempty"`
	Key string `json:"key,omitempty"`
}

// ConstructorID returns the TL constructor identifier 0x2dbf3432.
func (v *PhoneGroupCallStreamRtmpURL) ConstructorID() uint32 {
	return PhoneGroupCallStreamRtmpURLTypeID
}

// Encode serializes PhoneGroupCallStreamRtmpURL to a bytes.Buffer using the TL binary protocol.
func (v *PhoneGroupCallStreamRtmpURL) Encode(b *bytes.Buffer) error {
	WriteInt(b, PhoneGroupCallStreamRtmpURLTypeID)
	WriteString(b, v.URL)
	WriteString(b, v.Key)
	return nil
}

// DecodePhoneGroupCallStreamRtmpURL deserializes a PhoneGroupCallStreamRtmpURL from a reader using the TL binary protocol.
func DecodePhoneGroupCallStreamRtmpURL(r io.Reader) (*PhoneGroupCallStreamRtmpURL, error) {
	v := &PhoneGroupCallStreamRtmpURL{}
	v.URL = ReadString(r)
	v.Key = ReadString(r)
	return v, nil
}

func init() {
	Registry[PhoneGroupCallStreamRtmpURLTypeID] = func(r io.Reader) (TLObject, error) {
		return DecodePhoneGroupCallStreamRtmpURL(r)
	}
}

// GroupCallDonorTypeID is the constructor ID for TL type groupCallDonor.
const GroupCallDonorTypeID = 0xee430c85

// GroupCallDonor represents the TL constructor groupCallDonor (0xee430c85).
//
// See https://core.telegram.org/constructor/groupCallDonor for reference.
type GroupCallDonor struct {
	Flags  Fields    `json:"-"`
	Top    bool      `json:"top,omitempty"`
	My     bool      `json:"my,omitempty"`
	PeerID PeerClass `json:"peer_id,omitempty"`
	Stars  int64     `json:"stars,omitempty"`
}

// SetFlags computes flags from non-zero optional fields.
func (v *GroupCallDonor) SetFlags() {
	if v.Top {
		v.Flags.Set(0)
	}
	if v.My {
		v.Flags.Set(1)
	}
	if v.PeerID != nil {
		v.Flags.Set(3)
	}
}

// ConstructorID returns the TL constructor identifier 0xee430c85.
func (v *GroupCallDonor) ConstructorID() uint32 {
	return GroupCallDonorTypeID
}

// Encode serializes GroupCallDonor to a bytes.Buffer using the TL binary protocol.
func (v *GroupCallDonor) Encode(b *bytes.Buffer) error {
	WriteInt(b, GroupCallDonorTypeID)
	v.SetFlags()
	WriteInt(b, uint32(v.Flags))
	if v.Flags.Has(3) {
		EncodeTLObject(b, v.PeerID)
	}
	WriteLong(b, v.Stars)
	return nil
}

// DecodeGroupCallDonor deserializes a GroupCallDonor from a reader using the TL binary protocol.
func DecodeGroupCallDonor(r io.Reader) (*GroupCallDonor, error) {
	v := &GroupCallDonor{}
	{
		var _f uint32
		_f, _ = ReadIntErr(r)
		v.Flags = Fields(_f)
	}
	v.Top = v.Flags.Has(0)
	v.My = v.Flags.Has(1)
	if v.Flags.Has(3) {
		_objPeerID, _ := ReadTLObject(r)
		v.PeerID = _objPeerID.(PeerClass)
	}
	v.Stars = ReadLong(r)
	return v, nil
}

func init() {
	Registry[GroupCallDonorTypeID] = func(r io.Reader) (TLObject, error) {
		return DecodeGroupCallDonor(r)
	}
}

// PhoneGroupCallStarsTypeID is the constructor ID for TL type phone.groupCallStars.
const PhoneGroupCallStarsTypeID = 0x9d1dbd26

// PhoneGroupCallStars represents the TL constructor phone.groupCallStars (0x9d1dbd26).
//
// See https://core.telegram.org/constructor/phone.groupCallStars for reference.
type PhoneGroupCallStars struct {
	TotalStars int64             `json:"total_stars,omitempty"`
	TopDonors  []*GroupCallDonor `json:"top_donors,omitempty"`
	Chats      []ChatClass       `json:"chats,omitempty"`
	Users      []UserClass       `json:"users,omitempty"`
}

// ConstructorID returns the TL constructor identifier 0x9d1dbd26.
func (v *PhoneGroupCallStars) ConstructorID() uint32 {
	return PhoneGroupCallStarsTypeID
}

// Encode serializes PhoneGroupCallStars to a bytes.Buffer using the TL binary protocol.
func (v *PhoneGroupCallStars) Encode(b *bytes.Buffer) error {
	WriteInt(b, PhoneGroupCallStarsTypeID)
	WriteLong(b, v.TotalStars)
	WriteInt(b, 0x1cb5c415)
	WriteInt(b, uint32(len(v.TopDonors)))
	for _, _item := range v.TopDonors {
		EncodeTLObject(b, _item)
	}
	WriteInt(b, 0x1cb5c415)
	WriteInt(b, uint32(len(v.Chats)))
	for _, _item := range v.Chats {
		EncodeTLObject(b, _item)
	}
	WriteInt(b, 0x1cb5c415)
	WriteInt(b, uint32(len(v.Users)))
	for _, _item := range v.Users {
		EncodeTLObject(b, _item)
	}
	return nil
}

// DecodePhoneGroupCallStars deserializes a PhoneGroupCallStars from a reader using the TL binary protocol.
func DecodePhoneGroupCallStars(r io.Reader) (*PhoneGroupCallStars, error) {
	v := &PhoneGroupCallStars{}
	v.TotalStars = ReadLong(r)
	ReadInt(r)
	_cntTopDonors := ReadInt(r)
	if err := checkVectorCount(_cntTopDonors); err != nil {
		return nil, err
	}
	v.TopDonors = make([]*GroupCallDonor, _cntTopDonors)
	for _iTopDonors := range v.TopDonors {
		_objTopDonors, _ := ReadTLObject(r)
		v.TopDonors[_iTopDonors] = _objTopDonors.(*GroupCallDonor)
	}
	ReadInt(r)
	_cntChats := ReadInt(r)
	if err := checkVectorCount(_cntChats); err != nil {
		return nil, err
	}
	v.Chats = make([]ChatClass, _cntChats)
	for _iChats := range v.Chats {
		_objChats, _ := ReadTLObject(r)
		v.Chats[_iChats] = _objChats.(ChatClass)
	}
	ReadInt(r)
	_cntUsers := ReadInt(r)
	if err := checkVectorCount(_cntUsers); err != nil {
		return nil, err
	}
	v.Users = make([]UserClass, _cntUsers)
	for _iUsers := range v.Users {
		_objUsers, _ := ReadTLObject(r)
		v.Users[_iUsers] = _objUsers.(UserClass)
	}
	return v, nil
}

func init() {
	Registry[PhoneGroupCallStarsTypeID] = func(r io.Reader) (TLObject, error) {
		return DecodePhoneGroupCallStars(r)
	}
}
