// Code generated by tlgen. DO NOT EDIT.

package tg

import (
	"bytes"
	"context"
	"fmt"
	"io"
)

// StatsGetBroadcastStatsTypeID is the constructor ID for the RPC function stats.getBroadcastStats.
const StatsGetBroadcastStatsTypeID = 0xab42441a

// StatsGetBroadcastStatsRequest represents TL type `stats.getBroadcastStats#ab42441a`.
//
// See https://core.telegram.org/method/stats/getBroadcastStats for reference.
type StatsGetBroadcastStatsRequest struct {
	Flags   Fields            `json:"-"`
	Dark    bool              `json:"dark,omitempty"`
	Channel InputChannelClass `json:"channel,omitempty"`
}

// SetFlags computes flags from non-zero optional fields.
func (v *StatsGetBroadcastStatsRequest) SetFlags() {
	if v.Dark {
		v.Flags.Set(0)
	}
}

// ConstructorID returns the TL constructor identifier 0xab42441a.
func (v *StatsGetBroadcastStatsRequest) ConstructorID() uint32 {
	return StatsGetBroadcastStatsTypeID
}

// Encode serializes StatsGetBroadcastStatsRequest to a bytes.Buffer using the TL binary protocol.
func (v *StatsGetBroadcastStatsRequest) Encode(b *bytes.Buffer) error {
	WriteInt(b, StatsGetBroadcastStatsTypeID)
	v.SetFlags()
	WriteInt(b, uint32(v.Flags))
	if v.Flags.Has(0) {
		WriteBool(b, v.Dark)
	}
	EncodeTLObject(b, v.Channel)
	return nil
}

// StatsGetBroadcastStats invokes the stats.getBroadcastStats RPC method on the server.
//
// Parameters:
//   - ctx: context for cancellation and timeout
//   - req: the request parameters
//
// Returns the result of the RPC call, or an error if the invocation fails.
func (c *RPCClient) StatsGetBroadcastStats(ctx context.Context, req *StatsGetBroadcastStatsRequest) (*StatsBroadcastStats, error) {
	result, err := c.invoke(ctx, req, func(r io.Reader) (TLObject, error) {
		return ReadTLObject(r)
	})
	if err != nil {
		return nil, err
	}
	if _c, _ok := result.(*StatsBroadcastStats); _ok {
		return _c, nil
	}
	return nil, fmt.Errorf("unexpected result type %T", result)
}

// StatsLoadAsyncGraphTypeID is the constructor ID for the RPC function stats.loadAsyncGraph.
const StatsLoadAsyncGraphTypeID = 0x621d5fa0

// StatsLoadAsyncGraphRequest represents TL type `stats.loadAsyncGraph#621d5fa0`.
//
// See https://core.telegram.org/method/stats/loadAsyncGraph for reference.
type StatsLoadAsyncGraphRequest struct {
	Flags Fields `json:"-"`
	Token string `json:"token,omitempty"`
	X     int64  `json:"x,omitempty"`
}

// SetFlags computes flags from non-zero optional fields.
func (v *StatsLoadAsyncGraphRequest) SetFlags() {
	if v.X != 0 {
		v.Flags.Set(0)
	}
}

// ConstructorID returns the TL constructor identifier 0x621d5fa0.
func (v *StatsLoadAsyncGraphRequest) ConstructorID() uint32 {
	return StatsLoadAsyncGraphTypeID
}

// Encode serializes StatsLoadAsyncGraphRequest to a bytes.Buffer using the TL binary protocol.
func (v *StatsLoadAsyncGraphRequest) Encode(b *bytes.Buffer) error {
	WriteInt(b, StatsLoadAsyncGraphTypeID)
	v.SetFlags()
	WriteInt(b, uint32(v.Flags))
	WriteString(b, v.Token)
	if v.Flags.Has(0) {
		WriteLong(b, v.X)
	}
	return nil
}

// StatsLoadAsyncGraph invokes the stats.loadAsyncGraph RPC method on the server.
//
// Parameters:
//   - ctx: context for cancellation and timeout
//   - req: the request parameters
//
// Returns the result of the RPC call, or an error if the invocation fails.
func (c *RPCClient) StatsLoadAsyncGraph(ctx context.Context, req *StatsLoadAsyncGraphRequest) (StatsGraphClass, error) {
	result, err := c.invoke(ctx, req, func(r io.Reader) (TLObject, error) {
		return ReadTLObject(r)
	})
	if err != nil {
		return nil, err
	}
	if _c, _ok := result.(StatsGraphClass); _ok {
		return _c, nil
	}
	return nil, fmt.Errorf("unexpected result type %T", result)
}

// StatsGetMegagroupStatsTypeID is the constructor ID for the RPC function stats.getMegagroupStats.
const StatsGetMegagroupStatsTypeID = 0xdcdf8607

// StatsGetMegagroupStatsRequest represents TL type `stats.getMegagroupStats#dcdf8607`.
//
// See https://core.telegram.org/method/stats/getMegagroupStats for reference.
type StatsGetMegagroupStatsRequest struct {
	Flags   Fields            `json:"-"`
	Dark    bool              `json:"dark,omitempty"`
	Channel InputChannelClass `json:"channel,omitempty"`
}

// SetFlags computes flags from non-zero optional fields.
func (v *StatsGetMegagroupStatsRequest) SetFlags() {
	if v.Dark {
		v.Flags.Set(0)
	}
}

// ConstructorID returns the TL constructor identifier 0xdcdf8607.
func (v *StatsGetMegagroupStatsRequest) ConstructorID() uint32 {
	return StatsGetMegagroupStatsTypeID
}

// Encode serializes StatsGetMegagroupStatsRequest to a bytes.Buffer using the TL binary protocol.
func (v *StatsGetMegagroupStatsRequest) Encode(b *bytes.Buffer) error {
	WriteInt(b, StatsGetMegagroupStatsTypeID)
	v.SetFlags()
	WriteInt(b, uint32(v.Flags))
	if v.Flags.Has(0) {
		WriteBool(b, v.Dark)
	}
	EncodeTLObject(b, v.Channel)
	return nil
}

// StatsGetMegagroupStats invokes the stats.getMegagroupStats RPC method on the server.
//
// Parameters:
//   - ctx: context for cancellation and timeout
//   - req: the request parameters
//
// Returns the result of the RPC call, or an error if the invocation fails.
func (c *RPCClient) StatsGetMegagroupStats(ctx context.Context, req *StatsGetMegagroupStatsRequest) (*StatsMegagroupStats, error) {
	result, err := c.invoke(ctx, req, func(r io.Reader) (TLObject, error) {
		return ReadTLObject(r)
	})
	if err != nil {
		return nil, err
	}
	if _c, _ok := result.(*StatsMegagroupStats); _ok {
		return _c, nil
	}
	return nil, fmt.Errorf("unexpected result type %T", result)
}

// StatsGetMessagePublicForwardsTypeID is the constructor ID for the RPC function stats.getMessagePublicForwards.
const StatsGetMessagePublicForwardsTypeID = 0x5f150144

// StatsGetMessagePublicForwardsRequest represents TL type `stats.getMessagePublicForwards#5f150144`.
//
// See https://core.telegram.org/method/stats/getMessagePublicForwards for reference.
type StatsGetMessagePublicForwardsRequest struct {
	Channel InputChannelClass `json:"channel,omitempty"`
	MsgID   int32             `json:"msg_id,omitempty"`
	Offset  string            `json:"offset,omitempty"`
	Limit   int32             `json:"limit,omitempty"`
}

// ConstructorID returns the TL constructor identifier 0x5f150144.
func (v *StatsGetMessagePublicForwardsRequest) ConstructorID() uint32 {
	return StatsGetMessagePublicForwardsTypeID
}

// Encode serializes StatsGetMessagePublicForwardsRequest to a bytes.Buffer using the TL binary protocol.
func (v *StatsGetMessagePublicForwardsRequest) Encode(b *bytes.Buffer) error {
	WriteInt(b, StatsGetMessagePublicForwardsTypeID)
	EncodeTLObject(b, v.Channel)
	WriteInt(b, uint32(v.MsgID))
	WriteString(b, v.Offset)
	WriteInt(b, uint32(v.Limit))
	return nil
}

// StatsGetMessagePublicForwards invokes the stats.getMessagePublicForwards RPC method on the server.
//
// Parameters:
//   - ctx: context for cancellation and timeout
//   - req: the request parameters
//
// Returns the result of the RPC call, or an error if the invocation fails.
func (c *RPCClient) StatsGetMessagePublicForwards(ctx context.Context, req *StatsGetMessagePublicForwardsRequest) (*StatsPublicForwards, error) {
	result, err := c.invoke(ctx, req, func(r io.Reader) (TLObject, error) {
		return ReadTLObject(r)
	})
	if err != nil {
		return nil, err
	}
	if _c, _ok := result.(*StatsPublicForwards); _ok {
		return _c, nil
	}
	return nil, fmt.Errorf("unexpected result type %T", result)
}

// StatsGetMessageStatsTypeID is the constructor ID for the RPC function stats.getMessageStats.
const StatsGetMessageStatsTypeID = 0xb6e0a3f5

// StatsGetMessageStatsRequest represents TL type `stats.getMessageStats#b6e0a3f5`.
//
// See https://core.telegram.org/method/stats/getMessageStats for reference.
type StatsGetMessageStatsRequest struct {
	Flags   Fields            `json:"-"`
	Dark    bool              `json:"dark,omitempty"`
	Channel InputChannelClass `json:"channel,omitempty"`
	MsgID   int32             `json:"msg_id,omitempty"`
}

// SetFlags computes flags from non-zero optional fields.
func (v *StatsGetMessageStatsRequest) SetFlags() {
	if v.Dark {
		v.Flags.Set(0)
	}
}

// ConstructorID returns the TL constructor identifier 0xb6e0a3f5.
func (v *StatsGetMessageStatsRequest) ConstructorID() uint32 {
	return StatsGetMessageStatsTypeID
}

// Encode serializes StatsGetMessageStatsRequest to a bytes.Buffer using the TL binary protocol.
func (v *StatsGetMessageStatsRequest) Encode(b *bytes.Buffer) error {
	WriteInt(b, StatsGetMessageStatsTypeID)
	v.SetFlags()
	WriteInt(b, uint32(v.Flags))
	if v.Flags.Has(0) {
		WriteBool(b, v.Dark)
	}
	EncodeTLObject(b, v.Channel)
	WriteInt(b, uint32(v.MsgID))
	return nil
}

// StatsGetMessageStats invokes the stats.getMessageStats RPC method on the server.
//
// Parameters:
//   - ctx: context for cancellation and timeout
//   - req: the request parameters
//
// Returns the result of the RPC call, or an error if the invocation fails.
func (c *RPCClient) StatsGetMessageStats(ctx context.Context, req *StatsGetMessageStatsRequest) (*StatsMessageStats, error) {
	result, err := c.invoke(ctx, req, func(r io.Reader) (TLObject, error) {
		return ReadTLObject(r)
	})
	if err != nil {
		return nil, err
	}
	if _c, _ok := result.(*StatsMessageStats); _ok {
		return _c, nil
	}
	return nil, fmt.Errorf("unexpected result type %T", result)
}

// StatsGetStoryStatsTypeID is the constructor ID for the RPC function stats.getStoryStats.
const StatsGetStoryStatsTypeID = 0x374fef40

// StatsGetStoryStatsRequest represents TL type `stats.getStoryStats#374fef40`.
//
// See https://core.telegram.org/method/stats/getStoryStats for reference.
type StatsGetStoryStatsRequest struct {
	Flags Fields         `json:"-"`
	Dark  bool           `json:"dark,omitempty"`
	Peer  InputPeerClass `json:"peer,omitempty"`
	ID    int32          `json:"id,omitempty"`
}

// SetFlags computes flags from non-zero optional fields.
func (v *StatsGetStoryStatsRequest) SetFlags() {
	if v.Dark {
		v.Flags.Set(0)
	}
}

// ConstructorID returns the TL constructor identifier 0x374fef40.
func (v *StatsGetStoryStatsRequest) ConstructorID() uint32 {
	return StatsGetStoryStatsTypeID
}

// Encode serializes StatsGetStoryStatsRequest to a bytes.Buffer using the TL binary protocol.
func (v *StatsGetStoryStatsRequest) Encode(b *bytes.Buffer) error {
	WriteInt(b, StatsGetStoryStatsTypeID)
	v.SetFlags()
	WriteInt(b, uint32(v.Flags))
	if v.Flags.Has(0) {
		WriteBool(b, v.Dark)
	}
	EncodeTLObject(b, v.Peer)
	WriteInt(b, uint32(v.ID))
	return nil
}

// StatsGetStoryStats invokes the stats.getStoryStats RPC method on the server.
//
// Parameters:
//   - ctx: context for cancellation and timeout
//   - req: the request parameters
//
// Returns the result of the RPC call, or an error if the invocation fails.
func (c *RPCClient) StatsGetStoryStats(ctx context.Context, req *StatsGetStoryStatsRequest) (*StatsStoryStats, error) {
	result, err := c.invoke(ctx, req, func(r io.Reader) (TLObject, error) {
		return ReadTLObject(r)
	})
	if err != nil {
		return nil, err
	}
	if _c, _ok := result.(*StatsStoryStats); _ok {
		return _c, nil
	}
	return nil, fmt.Errorf("unexpected result type %T", result)
}

// StatsGetStoryPublicForwardsTypeID is the constructor ID for the RPC function stats.getStoryPublicForwards.
const StatsGetStoryPublicForwardsTypeID = 0xa6437ef6

// StatsGetStoryPublicForwardsRequest represents TL type `stats.getStoryPublicForwards#a6437ef6`.
//
// See https://core.telegram.org/method/stats/getStoryPublicForwards for reference.
type StatsGetStoryPublicForwardsRequest struct {
	Peer   InputPeerClass `json:"peer,omitempty"`
	ID     int32          `json:"id,omitempty"`
	Offset string         `json:"offset,omitempty"`
	Limit  int32          `json:"limit,omitempty"`
}

// ConstructorID returns the TL constructor identifier 0xa6437ef6.
func (v *StatsGetStoryPublicForwardsRequest) ConstructorID() uint32 {
	return StatsGetStoryPublicForwardsTypeID
}

// Encode serializes StatsGetStoryPublicForwardsRequest to a bytes.Buffer using the TL binary protocol.
func (v *StatsGetStoryPublicForwardsRequest) Encode(b *bytes.Buffer) error {
	WriteInt(b, StatsGetStoryPublicForwardsTypeID)
	EncodeTLObject(b, v.Peer)
	WriteInt(b, uint32(v.ID))
	WriteString(b, v.Offset)
	WriteInt(b, uint32(v.Limit))
	return nil
}

// StatsGetStoryPublicForwards invokes the stats.getStoryPublicForwards RPC method on the server.
//
// Parameters:
//   - ctx: context for cancellation and timeout
//   - req: the request parameters
//
// Returns the result of the RPC call, or an error if the invocation fails.
func (c *RPCClient) StatsGetStoryPublicForwards(ctx context.Context, req *StatsGetStoryPublicForwardsRequest) (*StatsPublicForwards, error) {
	result, err := c.invoke(ctx, req, func(r io.Reader) (TLObject, error) {
		return ReadTLObject(r)
	})
	if err != nil {
		return nil, err
	}
	if _c, _ok := result.(*StatsPublicForwards); _ok {
		return _c, nil
	}
	return nil, fmt.Errorf("unexpected result type %T", result)
}

// StatsGetPollStatsTypeID is the constructor ID for the RPC function stats.getPollStats.
const StatsGetPollStatsTypeID = 0xc27dfa68

// StatsGetPollStatsRequest represents TL type `stats.getPollStats#c27dfa68`.
//
// See https://core.telegram.org/method/stats/getPollStats for reference.
type StatsGetPollStatsRequest struct {
	Flags Fields         `json:"-"`
	Dark  bool           `json:"dark,omitempty"`
	Peer  InputPeerClass `json:"peer,omitempty"`
	MsgID int32          `json:"msg_id,omitempty"`
}

// SetFlags computes flags from non-zero optional fields.
func (v *StatsGetPollStatsRequest) SetFlags() {
	if v.Dark {
		v.Flags.Set(0)
	}
}

// ConstructorID returns the TL constructor identifier 0xc27dfa68.
func (v *StatsGetPollStatsRequest) ConstructorID() uint32 {
	return StatsGetPollStatsTypeID
}

// Encode serializes StatsGetPollStatsRequest to a bytes.Buffer using the TL binary protocol.
func (v *StatsGetPollStatsRequest) Encode(b *bytes.Buffer) error {
	WriteInt(b, StatsGetPollStatsTypeID)
	v.SetFlags()
	WriteInt(b, uint32(v.Flags))
	if v.Flags.Has(0) {
		WriteBool(b, v.Dark)
	}
	EncodeTLObject(b, v.Peer)
	WriteInt(b, uint32(v.MsgID))
	return nil
}

// StatsGetPollStats invokes the stats.getPollStats RPC method on the server.
//
// Parameters:
//   - ctx: context for cancellation and timeout
//   - req: the request parameters
//
// Returns the result of the RPC call, or an error if the invocation fails.
func (c *RPCClient) StatsGetPollStats(ctx context.Context, req *StatsGetPollStatsRequest) (*StatsPollStats, error) {
	result, err := c.invoke(ctx, req, func(r io.Reader) (TLObject, error) {
		return ReadTLObject(r)
	})
	if err != nil {
		return nil, err
	}
	if _c, _ok := result.(*StatsPollStats); _ok {
		return _c, nil
	}
	return nil, fmt.Errorf("unexpected result type %T", result)
}
