// Code generated by tlgen. DO NOT EDIT.

package tg

import (
	"bytes"
	"context"
	"fmt"
	"io"
)

// StickersCreateStickerSetTypeID is the constructor ID for the RPC function stickers.createStickerSet.
const StickersCreateStickerSetTypeID = 0x9021ab67

// StickersCreateStickerSetRequest represents TL type `stickers.createStickerSet#9021ab67`.
//
// See https://core.telegram.org/method/stickers/createStickerSet for reference.
type StickersCreateStickerSetRequest struct {
	Flags     Fields                 `json:"-"`
	Masks     bool                   `json:"masks,omitempty"`
	Emojis    bool                   `json:"emojis,omitempty"`
	TextColor bool                   `json:"text_color,omitempty"`
	UserID    InputUserClass         `json:"user_id,omitempty"`
	Title     string                 `json:"title,omitempty"`
	ShortName string                 `json:"short_name,omitempty"`
	Thumb     InputDocumentClass     `json:"thumb,omitempty"`
	Stickers  []*InputStickerSetItem `json:"stickers,omitempty"`
	Software  string                 `json:"software,omitempty"`
}

// SetFlags computes flags from non-zero optional fields.
func (v *StickersCreateStickerSetRequest) SetFlags() {
	if v.Masks {
		v.Flags.Set(0)
	}
	if v.Emojis {
		v.Flags.Set(5)
	}
	if v.TextColor {
		v.Flags.Set(6)
	}
	if v.Thumb != nil {
		v.Flags.Set(2)
	}
	if v.Software != "" {
		v.Flags.Set(3)
	}
}

// ConstructorID returns the TL constructor identifier 0x9021ab67.
func (v *StickersCreateStickerSetRequest) ConstructorID() uint32 {
	return StickersCreateStickerSetTypeID
}

// Encode serializes StickersCreateStickerSetRequest to a bytes.Buffer using the TL binary protocol.
func (v *StickersCreateStickerSetRequest) Encode(b *bytes.Buffer) error {
	WriteInt(b, StickersCreateStickerSetTypeID)
	v.SetFlags()
	WriteInt(b, uint32(v.Flags))
	if v.Flags.Has(0) {
		WriteBool(b, v.Masks)
	}
	if v.Flags.Has(5) {
		WriteBool(b, v.Emojis)
	}
	if v.Flags.Has(6) {
		WriteBool(b, v.TextColor)
	}
	EncodeTLObject(b, v.UserID)
	WriteString(b, v.Title)
	WriteString(b, v.ShortName)
	if v.Flags.Has(2) {
		EncodeTLObject(b, v.Thumb)
	}
	WriteInt(b, 0x1cb5c415)
	WriteInt(b, uint32(len(v.Stickers)))
	for _, _item := range v.Stickers {
		EncodeTLObject(b, _item)
	}
	if v.Flags.Has(3) {
		WriteString(b, v.Software)
	}
	return nil
}

// StickersCreateStickerSet invokes the stickers.createStickerSet RPC method on the server.
//
// Parameters:
//   - ctx: context for cancellation and timeout
//   - req: the request parameters
//
// Returns the result of the RPC call, or an error if the invocation fails.
func (c *RPCClient) StickersCreateStickerSet(ctx context.Context, req *StickersCreateStickerSetRequest) (StickerSetClass, error) {
	result, err := c.invoke(ctx, req, func(r io.Reader) (TLObject, error) {
		return ReadTLObject(r)
	})
	if err != nil {
		return nil, err
	}
	if _c, _ok := result.(StickerSetClass); _ok {
		return _c, nil
	}
	return nil, fmt.Errorf("unexpected result type %T", result)
}

// StickersRemoveStickerFromSetTypeID is the constructor ID for the RPC function stickers.removeStickerFromSet.
const StickersRemoveStickerFromSetTypeID = 0xf7760f51

// StickersRemoveStickerFromSetRequest represents TL type `stickers.removeStickerFromSet#f7760f51`.
//
// See https://core.telegram.org/method/stickers/removeStickerFromSet for reference.
type StickersRemoveStickerFromSetRequest struct {
	Sticker InputDocumentClass `json:"sticker,omitempty"`
}

// ConstructorID returns the TL constructor identifier 0xf7760f51.
func (v *StickersRemoveStickerFromSetRequest) ConstructorID() uint32 {
	return StickersRemoveStickerFromSetTypeID
}

// Encode serializes StickersRemoveStickerFromSetRequest to a bytes.Buffer using the TL binary protocol.
func (v *StickersRemoveStickerFromSetRequest) Encode(b *bytes.Buffer) error {
	WriteInt(b, StickersRemoveStickerFromSetTypeID)
	EncodeTLObject(b, v.Sticker)
	return nil
}

// StickersRemoveStickerFromSet invokes the stickers.removeStickerFromSet RPC method on the server.
//
// Parameters:
//   - ctx: context for cancellation and timeout
//   - req: the request parameters
//
// Returns the result of the RPC call, or an error if the invocation fails.
func (c *RPCClient) StickersRemoveStickerFromSet(ctx context.Context, req *StickersRemoveStickerFromSetRequest) (StickerSetClass, error) {
	result, err := c.invoke(ctx, req, func(r io.Reader) (TLObject, error) {
		return ReadTLObject(r)
	})
	if err != nil {
		return nil, err
	}
	if _c, _ok := result.(StickerSetClass); _ok {
		return _c, nil
	}
	return nil, fmt.Errorf("unexpected result type %T", result)
}

// StickersChangeStickerPositionTypeID is the constructor ID for the RPC function stickers.changeStickerPosition.
const StickersChangeStickerPositionTypeID = 0xffb6d4ca

// StickersChangeStickerPositionRequest represents TL type `stickers.changeStickerPosition#ffb6d4ca`.
//
// See https://core.telegram.org/method/stickers/changeStickerPosition for reference.
type StickersChangeStickerPositionRequest struct {
	Sticker  InputDocumentClass `json:"sticker,omitempty"`
	Position int32              `json:"position,omitempty"`
}

// ConstructorID returns the TL constructor identifier 0xffb6d4ca.
func (v *StickersChangeStickerPositionRequest) ConstructorID() uint32 {
	return StickersChangeStickerPositionTypeID
}

// Encode serializes StickersChangeStickerPositionRequest to a bytes.Buffer using the TL binary protocol.
func (v *StickersChangeStickerPositionRequest) Encode(b *bytes.Buffer) error {
	WriteInt(b, StickersChangeStickerPositionTypeID)
	EncodeTLObject(b, v.Sticker)
	WriteInt(b, uint32(v.Position))
	return nil
}

// StickersChangeStickerPosition invokes the stickers.changeStickerPosition RPC method on the server.
//
// Parameters:
//   - ctx: context for cancellation and timeout
//   - req: the request parameters
//
// Returns the result of the RPC call, or an error if the invocation fails.
func (c *RPCClient) StickersChangeStickerPosition(ctx context.Context, req *StickersChangeStickerPositionRequest) (StickerSetClass, error) {
	result, err := c.invoke(ctx, req, func(r io.Reader) (TLObject, error) {
		return ReadTLObject(r)
	})
	if err != nil {
		return nil, err
	}
	if _c, _ok := result.(StickerSetClass); _ok {
		return _c, nil
	}
	return nil, fmt.Errorf("unexpected result type %T", result)
}

// StickersAddStickerToSetTypeID is the constructor ID for the RPC function stickers.addStickerToSet.
const StickersAddStickerToSetTypeID = 0x8653febe

// StickersAddStickerToSetRequest represents TL type `stickers.addStickerToSet#8653febe`.
//
// See https://core.telegram.org/method/stickers/addStickerToSet for reference.
type StickersAddStickerToSetRequest struct {
	Stickerset InputStickerSetClass `json:"stickerset,omitempty"`
	Sticker    *InputStickerSetItem `json:"sticker,omitempty"`
}

// ConstructorID returns the TL constructor identifier 0x8653febe.
func (v *StickersAddStickerToSetRequest) ConstructorID() uint32 {
	return StickersAddStickerToSetTypeID
}

// Encode serializes StickersAddStickerToSetRequest to a bytes.Buffer using the TL binary protocol.
func (v *StickersAddStickerToSetRequest) Encode(b *bytes.Buffer) error {
	WriteInt(b, StickersAddStickerToSetTypeID)
	EncodeTLObject(b, v.Stickerset)
	EncodeTLObject(b, v.Sticker)
	return nil
}

// StickersAddStickerToSet invokes the stickers.addStickerToSet RPC method on the server.
//
// Parameters:
//   - ctx: context for cancellation and timeout
//   - req: the request parameters
//
// Returns the result of the RPC call, or an error if the invocation fails.
func (c *RPCClient) StickersAddStickerToSet(ctx context.Context, req *StickersAddStickerToSetRequest) (StickerSetClass, error) {
	result, err := c.invoke(ctx, req, func(r io.Reader) (TLObject, error) {
		return ReadTLObject(r)
	})
	if err != nil {
		return nil, err
	}
	if _c, _ok := result.(StickerSetClass); _ok {
		return _c, nil
	}
	return nil, fmt.Errorf("unexpected result type %T", result)
}

// StickersSetStickerSetThumbTypeID is the constructor ID for the RPC function stickers.setStickerSetThumb.
const StickersSetStickerSetThumbTypeID = 0xa76a5392

// StickersSetStickerSetThumbRequest represents TL type `stickers.setStickerSetThumb#a76a5392`.
//
// See https://core.telegram.org/method/stickers/setStickerSetThumb for reference.
type StickersSetStickerSetThumbRequest struct {
	Flags           Fields               `json:"-"`
	Stickerset      InputStickerSetClass `json:"stickerset,omitempty"`
	Thumb           InputDocumentClass   `json:"thumb,omitempty"`
	ThumbDocumentID int64                `json:"thumb_document_id,omitempty"`
}

// SetFlags computes flags from non-zero optional fields.
func (v *StickersSetStickerSetThumbRequest) SetFlags() {
	if v.Thumb != nil {
		v.Flags.Set(0)
	}
	if v.ThumbDocumentID != 0 {
		v.Flags.Set(1)
	}
}

// ConstructorID returns the TL constructor identifier 0xa76a5392.
func (v *StickersSetStickerSetThumbRequest) ConstructorID() uint32 {
	return StickersSetStickerSetThumbTypeID
}

// Encode serializes StickersSetStickerSetThumbRequest to a bytes.Buffer using the TL binary protocol.
func (v *StickersSetStickerSetThumbRequest) Encode(b *bytes.Buffer) error {
	WriteInt(b, StickersSetStickerSetThumbTypeID)
	v.SetFlags()
	WriteInt(b, uint32(v.Flags))
	EncodeTLObject(b, v.Stickerset)
	if v.Flags.Has(0) {
		EncodeTLObject(b, v.Thumb)
	}
	if v.Flags.Has(1) {
		WriteLong(b, v.ThumbDocumentID)
	}
	return nil
}

// StickersSetStickerSetThumb invokes the stickers.setStickerSetThumb RPC method on the server.
//
// Parameters:
//   - ctx: context for cancellation and timeout
//   - req: the request parameters
//
// Returns the result of the RPC call, or an error if the invocation fails.
func (c *RPCClient) StickersSetStickerSetThumb(ctx context.Context, req *StickersSetStickerSetThumbRequest) (StickerSetClass, error) {
	result, err := c.invoke(ctx, req, func(r io.Reader) (TLObject, error) {
		return ReadTLObject(r)
	})
	if err != nil {
		return nil, err
	}
	if _c, _ok := result.(StickerSetClass); _ok {
		return _c, nil
	}
	return nil, fmt.Errorf("unexpected result type %T", result)
}

// StickersCheckShortNameTypeID is the constructor ID for the RPC function stickers.checkShortName.
const StickersCheckShortNameTypeID = 0x284b3639

// StickersCheckShortNameRequest represents TL type `stickers.checkShortName#284b3639`.
//
// See https://core.telegram.org/method/stickers/checkShortName for reference.
type StickersCheckShortNameRequest struct {
	ShortName string `json:"short_name,omitempty"`
}

// ConstructorID returns the TL constructor identifier 0x284b3639.
func (v *StickersCheckShortNameRequest) ConstructorID() uint32 {
	return StickersCheckShortNameTypeID
}

// Encode serializes StickersCheckShortNameRequest to a bytes.Buffer using the TL binary protocol.
func (v *StickersCheckShortNameRequest) Encode(b *bytes.Buffer) error {
	WriteInt(b, StickersCheckShortNameTypeID)
	WriteString(b, v.ShortName)
	return nil
}

// StickersCheckShortName invokes the stickers.checkShortName RPC method on the server.
//
// Parameters:
//   - ctx: context for cancellation and timeout
//   - req: the request parameters
//
// Returns the result of the RPC call, or an error if the invocation fails.
func (c *RPCClient) StickersCheckShortName(ctx context.Context, req *StickersCheckShortNameRequest) (bool, error) {
	result, err := c.invoke(ctx, req, func(r io.Reader) (TLObject, error) {
		return ReadTLObject(r)
	})
	if err != nil {
		return false, err
	}
	_ = result
	return true, nil
}

// StickersSuggestShortNameTypeID is the constructor ID for the RPC function stickers.suggestShortName.
const StickersSuggestShortNameTypeID = 0x4dafc503

// StickersSuggestShortNameRequest represents TL type `stickers.suggestShortName#4dafc503`.
//
// See https://core.telegram.org/method/stickers/suggestShortName for reference.
type StickersSuggestShortNameRequest struct {
	Title string `json:"title,omitempty"`
}

// ConstructorID returns the TL constructor identifier 0x4dafc503.
func (v *StickersSuggestShortNameRequest) ConstructorID() uint32 {
	return StickersSuggestShortNameTypeID
}

// Encode serializes StickersSuggestShortNameRequest to a bytes.Buffer using the TL binary protocol.
func (v *StickersSuggestShortNameRequest) Encode(b *bytes.Buffer) error {
	WriteInt(b, StickersSuggestShortNameTypeID)
	WriteString(b, v.Title)
	return nil
}

// StickersSuggestShortName invokes the stickers.suggestShortName RPC method on the server.
//
// Parameters:
//   - ctx: context for cancellation and timeout
//   - req: the request parameters
//
// Returns the result of the RPC call, or an error if the invocation fails.
func (c *RPCClient) StickersSuggestShortName(ctx context.Context, req *StickersSuggestShortNameRequest) (*StickersSuggestedShortName, error) {
	result, err := c.invoke(ctx, req, func(r io.Reader) (TLObject, error) {
		return ReadTLObject(r)
	})
	if err != nil {
		return nil, err
	}
	if _c, _ok := result.(*StickersSuggestedShortName); _ok {
		return _c, nil
	}
	return nil, fmt.Errorf("unexpected result type %T", result)
}

// StickersChangeStickerTypeID is the constructor ID for the RPC function stickers.changeSticker.
const StickersChangeStickerTypeID = 0xf5537ebc

// StickersChangeStickerRequest represents TL type `stickers.changeSticker#f5537ebc`.
//
// See https://core.telegram.org/method/stickers/changeSticker for reference.
type StickersChangeStickerRequest struct {
	Flags      Fields             `json:"-"`
	Sticker    InputDocumentClass `json:"sticker,omitempty"`
	Emoji      string             `json:"emoji,omitempty"`
	MaskCoords *MaskCoords        `json:"mask_coords,omitempty"`
	Keywords   string             `json:"keywords,omitempty"`
}

// SetFlags computes flags from non-zero optional fields.
func (v *StickersChangeStickerRequest) SetFlags() {
	if v.Emoji != "" {
		v.Flags.Set(0)
	}
	if v.MaskCoords != nil {
		v.Flags.Set(1)
	}
	if v.Keywords != "" {
		v.Flags.Set(2)
	}
}

// ConstructorID returns the TL constructor identifier 0xf5537ebc.
func (v *StickersChangeStickerRequest) ConstructorID() uint32 {
	return StickersChangeStickerTypeID
}

// Encode serializes StickersChangeStickerRequest to a bytes.Buffer using the TL binary protocol.
func (v *StickersChangeStickerRequest) Encode(b *bytes.Buffer) error {
	WriteInt(b, StickersChangeStickerTypeID)
	v.SetFlags()
	WriteInt(b, uint32(v.Flags))
	EncodeTLObject(b, v.Sticker)
	if v.Flags.Has(0) {
		WriteString(b, v.Emoji)
	}
	if v.Flags.Has(1) {
		EncodeTLObject(b, v.MaskCoords)
	}
	if v.Flags.Has(2) {
		WriteString(b, v.Keywords)
	}
	return nil
}

// StickersChangeSticker invokes the stickers.changeSticker RPC method on the server.
//
// Parameters:
//   - ctx: context for cancellation and timeout
//   - req: the request parameters
//
// Returns the result of the RPC call, or an error if the invocation fails.
func (c *RPCClient) StickersChangeSticker(ctx context.Context, req *StickersChangeStickerRequest) (StickerSetClass, error) {
	result, err := c.invoke(ctx, req, func(r io.Reader) (TLObject, error) {
		return ReadTLObject(r)
	})
	if err != nil {
		return nil, err
	}
	if _c, _ok := result.(StickerSetClass); _ok {
		return _c, nil
	}
	return nil, fmt.Errorf("unexpected result type %T", result)
}

// StickersRenameStickerSetTypeID is the constructor ID for the RPC function stickers.renameStickerSet.
const StickersRenameStickerSetTypeID = 0x124b1c00

// StickersRenameStickerSetRequest represents TL type `stickers.renameStickerSet#124b1c00`.
//
// See https://core.telegram.org/method/stickers/renameStickerSet for reference.
type StickersRenameStickerSetRequest struct {
	Stickerset InputStickerSetClass `json:"stickerset,omitempty"`
	Title      string               `json:"title,omitempty"`
}

// ConstructorID returns the TL constructor identifier 0x124b1c00.
func (v *StickersRenameStickerSetRequest) ConstructorID() uint32 {
	return StickersRenameStickerSetTypeID
}

// Encode serializes StickersRenameStickerSetRequest to a bytes.Buffer using the TL binary protocol.
func (v *StickersRenameStickerSetRequest) Encode(b *bytes.Buffer) error {
	WriteInt(b, StickersRenameStickerSetTypeID)
	EncodeTLObject(b, v.Stickerset)
	WriteString(b, v.Title)
	return nil
}

// StickersRenameStickerSet invokes the stickers.renameStickerSet RPC method on the server.
//
// Parameters:
//   - ctx: context for cancellation and timeout
//   - req: the request parameters
//
// Returns the result of the RPC call, or an error if the invocation fails.
func (c *RPCClient) StickersRenameStickerSet(ctx context.Context, req *StickersRenameStickerSetRequest) (StickerSetClass, error) {
	result, err := c.invoke(ctx, req, func(r io.Reader) (TLObject, error) {
		return ReadTLObject(r)
	})
	if err != nil {
		return nil, err
	}
	if _c, _ok := result.(StickerSetClass); _ok {
		return _c, nil
	}
	return nil, fmt.Errorf("unexpected result type %T", result)
}

// StickersDeleteStickerSetTypeID is the constructor ID for the RPC function stickers.deleteStickerSet.
const StickersDeleteStickerSetTypeID = 0x87704394

// StickersDeleteStickerSetRequest represents TL type `stickers.deleteStickerSet#87704394`.
//
// See https://core.telegram.org/method/stickers/deleteStickerSet for reference.
type StickersDeleteStickerSetRequest struct {
	Stickerset InputStickerSetClass `json:"stickerset,omitempty"`
}

// ConstructorID returns the TL constructor identifier 0x87704394.
func (v *StickersDeleteStickerSetRequest) ConstructorID() uint32 {
	return StickersDeleteStickerSetTypeID
}

// Encode serializes StickersDeleteStickerSetRequest to a bytes.Buffer using the TL binary protocol.
func (v *StickersDeleteStickerSetRequest) Encode(b *bytes.Buffer) error {
	WriteInt(b, StickersDeleteStickerSetTypeID)
	EncodeTLObject(b, v.Stickerset)
	return nil
}

// StickersDeleteStickerSet invokes the stickers.deleteStickerSet RPC method on the server.
//
// Parameters:
//   - ctx: context for cancellation and timeout
//   - req: the request parameters
//
// Returns the result of the RPC call, or an error if the invocation fails.
func (c *RPCClient) StickersDeleteStickerSet(ctx context.Context, req *StickersDeleteStickerSetRequest) (bool, error) {
	result, err := c.invoke(ctx, req, func(r io.Reader) (TLObject, error) {
		return ReadTLObject(r)
	})
	if err != nil {
		return false, err
	}
	_ = result
	return true, nil
}

// StickersReplaceStickerTypeID is the constructor ID for the RPC function stickers.replaceSticker.
const StickersReplaceStickerTypeID = 0x4696459a

// StickersReplaceStickerRequest represents TL type `stickers.replaceSticker#4696459a`.
//
// See https://core.telegram.org/method/stickers/replaceSticker for reference.
type StickersReplaceStickerRequest struct {
	Sticker    InputDocumentClass   `json:"sticker,omitempty"`
	NewSticker *InputStickerSetItem `json:"new_sticker,omitempty"`
}

// ConstructorID returns the TL constructor identifier 0x4696459a.
func (v *StickersReplaceStickerRequest) ConstructorID() uint32 {
	return StickersReplaceStickerTypeID
}

// Encode serializes StickersReplaceStickerRequest to a bytes.Buffer using the TL binary protocol.
func (v *StickersReplaceStickerRequest) Encode(b *bytes.Buffer) error {
	WriteInt(b, StickersReplaceStickerTypeID)
	EncodeTLObject(b, v.Sticker)
	EncodeTLObject(b, v.NewSticker)
	return nil
}

// StickersReplaceSticker invokes the stickers.replaceSticker RPC method on the server.
//
// Parameters:
//   - ctx: context for cancellation and timeout
//   - req: the request parameters
//
// Returns the result of the RPC call, or an error if the invocation fails.
func (c *RPCClient) StickersReplaceSticker(ctx context.Context, req *StickersReplaceStickerRequest) (StickerSetClass, error) {
	result, err := c.invoke(ctx, req, func(r io.Reader) (TLObject, error) {
		return ReadTLObject(r)
	})
	if err != nil {
		return nil, err
	}
	if _c, _ok := result.(StickerSetClass); _ok {
		return _c, nil
	}
	return nil, fmt.Errorf("unexpected result type %T", result)
}
