// Code generated by tlgen. DO NOT EDIT.

package e2e

import (
	"bytes"
	"encoding/binary"
	"io"

	"github.com/mtgo-labs/mtgo/tg"
)

// Registry maps TL constructor IDs to factory functions.
var Registry = map[uint32]func(io.Reader) (tg.TLObject, error){}

// ReadE2ETLObject reads a TLObject from r using the e2e Registry.
func ReadE2ETLObject(r io.Reader) (tg.TLObject, error) {
	var id uint32
	if err := binary.Read(r, binary.LittleEndian, &id); err != nil {
		return nil, err
	}
	constructor, ok := Registry[id]
	if !ok {
		return nil, &tg.UnknownConstructorError{ID: id}
	}
	return constructor(r)
}

const vectorBareID uint32 = 0x1cb5c415

// EncodeTLObject encodes any TLObject to the buffer.
func EncodeTLObject(b *bytes.Buffer, obj tg.TLObject) error {
	return obj.Encode(b)
}
