// Code generated by tlgen. DO NOT EDIT.

package e2e

import (
	"bytes"
	"github.com/mtgo-labs/mtgo/tg"
)

// FileLocationClass is the interface for TL type FileLocation.
// Implementations must satisfy tg.TLObject and are used to represent
// any constructor of the FileLocation TL type.
type FileLocationClass interface {
	tg.TLObject
	isFileLocation()
}

// FileLocationUnavailableTypeID is the constructor ID for TL type fileLocationUnavailable.
const FileLocationUnavailableTypeID = 0x7c596b46

// FileLocationTypeID is the constructor ID for TL type fileLocation.
const FileLocationTypeID = 0x53d69076

// isFileLocation marks FileLocationUnavailable as implementing the FileLocationClass interface.
func (*FileLocationUnavailable) isFileLocation() {}

// isFileLocation marks FileLocation as implementing the FileLocationClass interface.
func (*FileLocation) isFileLocation() {}

// FileLocationUnavailable represents the TL constructor fileLocationUnavailable (0x7c596b46).
type FileLocationUnavailable struct {
	VolumeID int64 `json:"volume_id,omitempty"`
	LocalID  int32 `json:"local_id,omitempty"`
	Secret   int64 `json:"secret,omitempty"`
}

// ConstructorID returns the TL constructor identifier 0x7c596b46.
func (v *FileLocationUnavailable) ConstructorID() uint32 {
	return FileLocationUnavailableTypeID
}

// Encode serializes FileLocationUnavailable to a bytes.Buffer using the TL binary protocol.
func (v *FileLocationUnavailable) Encode(b *bytes.Buffer) error {
	tg.WriteInt(b, FileLocationUnavailableTypeID)
	tg.WriteLong(b, v.VolumeID)
	tg.WriteInt(b, uint32(v.LocalID))
	tg.WriteLong(b, v.Secret)
	return nil
}

// DecodeFileLocationUnavailable deserializes a FileLocationUnavailable from a reader using the TL binary protocol.
func DecodeFileLocationUnavailable(r *tg.Reader) (*FileLocationUnavailable, error) {
	v := &FileLocationUnavailable{}
	_rVolumeID, _eVolumeID := r.ReadInt64()
	if _eVolumeID != nil {
		return nil, _eVolumeID
	}
	v.VolumeID = _rVolumeID
	_rLocalID, _eLocalID := r.ReadInt32()
	if _eLocalID != nil {
		return nil, _eLocalID
	}
	v.LocalID = _rLocalID
	_rSecret, _eSecret := r.ReadInt64()
	if _eSecret != nil {
		return nil, _eSecret
	}
	v.Secret = _rSecret
	return v, nil
}

func init() {
	Registry[FileLocationUnavailableTypeID] = func(r *tg.Reader) (tg.TLObject, error) {
		return DecodeFileLocationUnavailable(r)
	}
}

// FileLocation represents the TL constructor fileLocation (0x53d69076).
type FileLocation struct {
	DCID     int32 `json:"dc_id,omitempty"`
	VolumeID int64 `json:"volume_id,omitempty"`
	LocalID  int32 `json:"local_id,omitempty"`
	Secret   int64 `json:"secret,omitempty"`
}

// ConstructorID returns the TL constructor identifier 0x53d69076.
func (v *FileLocation) ConstructorID() uint32 {
	return FileLocationTypeID
}

// Encode serializes FileLocation to a bytes.Buffer using the TL binary protocol.
func (v *FileLocation) Encode(b *bytes.Buffer) error {
	tg.WriteInt(b, FileLocationTypeID)
	tg.WriteInt(b, uint32(v.DCID))
	tg.WriteLong(b, v.VolumeID)
	tg.WriteInt(b, uint32(v.LocalID))
	tg.WriteLong(b, v.Secret)
	return nil
}

// DecodeFileLocation deserializes a FileLocation from a reader using the TL binary protocol.
func DecodeFileLocation(r *tg.Reader) (*FileLocation, error) {
	v := &FileLocation{}
	_rDCID, _eDCID := r.ReadInt32()
	if _eDCID != nil {
		return nil, _eDCID
	}
	v.DCID = _rDCID
	_rVolumeID, _eVolumeID := r.ReadInt64()
	if _eVolumeID != nil {
		return nil, _eVolumeID
	}
	v.VolumeID = _rVolumeID
	_rLocalID, _eLocalID := r.ReadInt32()
	if _eLocalID != nil {
		return nil, _eLocalID
	}
	v.LocalID = _rLocalID
	_rSecret, _eSecret := r.ReadInt64()
	if _eSecret != nil {
		return nil, _eSecret
	}
	v.Secret = _rSecret
	return v, nil
}

func init() {
	Registry[FileLocationTypeID] = func(r *tg.Reader) (tg.TLObject, error) {
		return DecodeFileLocation(r)
	}
}
