// Code generated by tlgen. DO NOT EDIT.

package e2e

import (
	"bytes"
	"github.com/mtgo-labs/mtgo/tg"
)

// DecryptedMessageActionClass is the interface for TL type DecryptedMessageAction.
// Implementations must satisfy tg.TLObject and are used to represent
// any constructor of the DecryptedMessageAction TL type.
type DecryptedMessageActionClass interface {
	tg.TLObject
	isDecryptedMessageAction()
}

// DecryptedMessageActionSetMessageTTLTypeID is the constructor ID for TL type decryptedMessageActionSetMessageTTL.
const DecryptedMessageActionSetMessageTTLTypeID = 0xa1733aec

// DecryptedMessageActionReadMessagesTypeID is the constructor ID for TL type decryptedMessageActionReadMessages.
const DecryptedMessageActionReadMessagesTypeID = 0x0c4f40be

// DecryptedMessageActionDeleteMessagesTypeID is the constructor ID for TL type decryptedMessageActionDeleteMessages.
const DecryptedMessageActionDeleteMessagesTypeID = 0x65614304

// DecryptedMessageActionScreenshotMessagesTypeID is the constructor ID for TL type decryptedMessageActionScreenshotMessages.
const DecryptedMessageActionScreenshotMessagesTypeID = 0x8ac1f475

// DecryptedMessageActionFlushHistoryTypeID is the constructor ID for TL type decryptedMessageActionFlushHistory.
const DecryptedMessageActionFlushHistoryTypeID = 0x6719e45c

// DecryptedMessageActionResendTypeID is the constructor ID for TL type decryptedMessageActionResend.
const DecryptedMessageActionResendTypeID = 0x511110b0

// DecryptedMessageActionNotifyLayerTypeID is the constructor ID for TL type decryptedMessageActionNotifyLayer.
const DecryptedMessageActionNotifyLayerTypeID = 0xf3048883

// DecryptedMessageActionTypingTypeID is the constructor ID for TL type decryptedMessageActionTyping.
const DecryptedMessageActionTypingTypeID = 0xccb27641

// DecryptedMessageActionRequestKeyTypeID is the constructor ID for TL type decryptedMessageActionRequestKey.
const DecryptedMessageActionRequestKeyTypeID = 0xf3c9611b

// DecryptedMessageActionAcceptKeyTypeID is the constructor ID for TL type decryptedMessageActionAcceptKey.
const DecryptedMessageActionAcceptKeyTypeID = 0x6fe1735b

// DecryptedMessageActionAbortKeyTypeID is the constructor ID for TL type decryptedMessageActionAbortKey.
const DecryptedMessageActionAbortKeyTypeID = 0xdd05ec6b

// DecryptedMessageActionCommitKeyTypeID is the constructor ID for TL type decryptedMessageActionCommitKey.
const DecryptedMessageActionCommitKeyTypeID = 0xec2e0b9b

// DecryptedMessageActionNoopTypeID is the constructor ID for TL type decryptedMessageActionNoop.
const DecryptedMessageActionNoopTypeID = 0xa82fdd63

// isDecryptedMessageAction marks DecryptedMessageActionSetMessageTTL as implementing the DecryptedMessageActionClass interface.
func (*DecryptedMessageActionSetMessageTTL) isDecryptedMessageAction() {}

// isDecryptedMessageAction marks DecryptedMessageActionReadMessages as implementing the DecryptedMessageActionClass interface.
func (*DecryptedMessageActionReadMessages) isDecryptedMessageAction() {}

// isDecryptedMessageAction marks DecryptedMessageActionDeleteMessages as implementing the DecryptedMessageActionClass interface.
func (*DecryptedMessageActionDeleteMessages) isDecryptedMessageAction() {}

// isDecryptedMessageAction marks DecryptedMessageActionScreenshotMessages as implementing the DecryptedMessageActionClass interface.
func (*DecryptedMessageActionScreenshotMessages) isDecryptedMessageAction() {}

// isDecryptedMessageAction marks DecryptedMessageActionFlushHistory as implementing the DecryptedMessageActionClass interface.
func (*DecryptedMessageActionFlushHistory) isDecryptedMessageAction() {}

// isDecryptedMessageAction marks DecryptedMessageActionResend as implementing the DecryptedMessageActionClass interface.
func (*DecryptedMessageActionResend) isDecryptedMessageAction() {}

// isDecryptedMessageAction marks DecryptedMessageActionNotifyLayer as implementing the DecryptedMessageActionClass interface.
func (*DecryptedMessageActionNotifyLayer) isDecryptedMessageAction() {}

// isDecryptedMessageAction marks DecryptedMessageActionTyping as implementing the DecryptedMessageActionClass interface.
func (*DecryptedMessageActionTyping) isDecryptedMessageAction() {}

// isDecryptedMessageAction marks DecryptedMessageActionRequestKey as implementing the DecryptedMessageActionClass interface.
func (*DecryptedMessageActionRequestKey) isDecryptedMessageAction() {}

// isDecryptedMessageAction marks DecryptedMessageActionAcceptKey as implementing the DecryptedMessageActionClass interface.
func (*DecryptedMessageActionAcceptKey) isDecryptedMessageAction() {}

// isDecryptedMessageAction marks DecryptedMessageActionAbortKey as implementing the DecryptedMessageActionClass interface.
func (*DecryptedMessageActionAbortKey) isDecryptedMessageAction() {}

// isDecryptedMessageAction marks DecryptedMessageActionCommitKey as implementing the DecryptedMessageActionClass interface.
func (*DecryptedMessageActionCommitKey) isDecryptedMessageAction() {}

// isDecryptedMessageAction marks DecryptedMessageActionNoop as implementing the DecryptedMessageActionClass interface.
func (*DecryptedMessageActionNoop) isDecryptedMessageAction() {}

// DecryptedMessageActionSetMessageTTL represents the TL constructor decryptedMessageActionSetMessageTTL (0xa1733aec).
type DecryptedMessageActionSetMessageTTL struct {
	TTLSeconds int32 `json:"ttl_seconds,omitempty"`
}

// ConstructorID returns the TL constructor identifier 0xa1733aec.
func (v *DecryptedMessageActionSetMessageTTL) ConstructorID() uint32 {
	return DecryptedMessageActionSetMessageTTLTypeID
}

// Encode serializes DecryptedMessageActionSetMessageTTL to a bytes.Buffer using the TL binary protocol.
func (v *DecryptedMessageActionSetMessageTTL) Encode(b *bytes.Buffer) error {
	tg.WriteInt(b, DecryptedMessageActionSetMessageTTLTypeID)
	tg.WriteInt(b, uint32(v.TTLSeconds))
	return nil
}

// DecodeDecryptedMessageActionSetMessageTTL deserializes a DecryptedMessageActionSetMessageTTL from a reader using the TL binary protocol.
func DecodeDecryptedMessageActionSetMessageTTL(r *tg.Reader) (*DecryptedMessageActionSetMessageTTL, error) {
	v := &DecryptedMessageActionSetMessageTTL{}
	_rTTLSeconds, _eTTLSeconds := r.ReadInt32()
	if _eTTLSeconds != nil {
		return nil, _eTTLSeconds
	}
	v.TTLSeconds = _rTTLSeconds
	return v, nil
}

func init() {
	Registry[DecryptedMessageActionSetMessageTTLTypeID] = func(r *tg.Reader) (tg.TLObject, error) {
		return DecodeDecryptedMessageActionSetMessageTTL(r)
	}
}

// DecryptedMessageActionReadMessages represents the TL constructor decryptedMessageActionReadMessages (0x0c4f40be).
type DecryptedMessageActionReadMessages struct {
	RandomIds []int64 `json:"random_ids,omitempty"`
}

// ConstructorID returns the TL constructor identifier 0x0c4f40be.
func (v *DecryptedMessageActionReadMessages) ConstructorID() uint32 {
	return DecryptedMessageActionReadMessagesTypeID
}

// Encode serializes DecryptedMessageActionReadMessages to a bytes.Buffer using the TL binary protocol.
func (v *DecryptedMessageActionReadMessages) Encode(b *bytes.Buffer) error {
	tg.WriteInt(b, DecryptedMessageActionReadMessagesTypeID)
	tg.WriteVectorLong(b, v.RandomIds)
	return nil
}

// DecodeDecryptedMessageActionReadMessages deserializes a DecryptedMessageActionReadMessages from a reader using the TL binary protocol.
func DecodeDecryptedMessageActionReadMessages(r *tg.Reader) (*DecryptedMessageActionReadMessages, error) {
	v := &DecryptedMessageActionReadMessages{}
	_vvRandomIds, _veRandomIds := r.ReadVectorLong()
	if _veRandomIds != nil {
		return nil, _veRandomIds
	}
	v.RandomIds = _vvRandomIds
	return v, nil
}

func init() {
	Registry[DecryptedMessageActionReadMessagesTypeID] = func(r *tg.Reader) (tg.TLObject, error) {
		return DecodeDecryptedMessageActionReadMessages(r)
	}
}

// DecryptedMessageActionDeleteMessages represents the TL constructor decryptedMessageActionDeleteMessages (0x65614304).
type DecryptedMessageActionDeleteMessages struct {
	RandomIds []int64 `json:"random_ids,omitempty"`
}

// ConstructorID returns the TL constructor identifier 0x65614304.
func (v *DecryptedMessageActionDeleteMessages) ConstructorID() uint32 {
	return DecryptedMessageActionDeleteMessagesTypeID
}

// Encode serializes DecryptedMessageActionDeleteMessages to a bytes.Buffer using the TL binary protocol.
func (v *DecryptedMessageActionDeleteMessages) Encode(b *bytes.Buffer) error {
	tg.WriteInt(b, DecryptedMessageActionDeleteMessagesTypeID)
	tg.WriteVectorLong(b, v.RandomIds)
	return nil
}

// DecodeDecryptedMessageActionDeleteMessages deserializes a DecryptedMessageActionDeleteMessages from a reader using the TL binary protocol.
func DecodeDecryptedMessageActionDeleteMessages(r *tg.Reader) (*DecryptedMessageActionDeleteMessages, error) {
	v := &DecryptedMessageActionDeleteMessages{}
	_vvRandomIds, _veRandomIds := r.ReadVectorLong()
	if _veRandomIds != nil {
		return nil, _veRandomIds
	}
	v.RandomIds = _vvRandomIds
	return v, nil
}

func init() {
	Registry[DecryptedMessageActionDeleteMessagesTypeID] = func(r *tg.Reader) (tg.TLObject, error) {
		return DecodeDecryptedMessageActionDeleteMessages(r)
	}
}

// DecryptedMessageActionScreenshotMessages represents the TL constructor decryptedMessageActionScreenshotMessages (0x8ac1f475).
type DecryptedMessageActionScreenshotMessages struct {
	RandomIds []int64 `json:"random_ids,omitempty"`
}

// ConstructorID returns the TL constructor identifier 0x8ac1f475.
func (v *DecryptedMessageActionScreenshotMessages) ConstructorID() uint32 {
	return DecryptedMessageActionScreenshotMessagesTypeID
}

// Encode serializes DecryptedMessageActionScreenshotMessages to a bytes.Buffer using the TL binary protocol.
func (v *DecryptedMessageActionScreenshotMessages) Encode(b *bytes.Buffer) error {
	tg.WriteInt(b, DecryptedMessageActionScreenshotMessagesTypeID)
	tg.WriteVectorLong(b, v.RandomIds)
	return nil
}

// DecodeDecryptedMessageActionScreenshotMessages deserializes a DecryptedMessageActionScreenshotMessages from a reader using the TL binary protocol.
func DecodeDecryptedMessageActionScreenshotMessages(r *tg.Reader) (*DecryptedMessageActionScreenshotMessages, error) {
	v := &DecryptedMessageActionScreenshotMessages{}
	_vvRandomIds, _veRandomIds := r.ReadVectorLong()
	if _veRandomIds != nil {
		return nil, _veRandomIds
	}
	v.RandomIds = _vvRandomIds
	return v, nil
}

func init() {
	Registry[DecryptedMessageActionScreenshotMessagesTypeID] = func(r *tg.Reader) (tg.TLObject, error) {
		return DecodeDecryptedMessageActionScreenshotMessages(r)
	}
}

// DecryptedMessageActionFlushHistory represents the TL constructor decryptedMessageActionFlushHistory (0x6719e45c).
type DecryptedMessageActionFlushHistory struct {
}

// ConstructorID returns the TL constructor identifier 0x6719e45c.
func (v *DecryptedMessageActionFlushHistory) ConstructorID() uint32 {
	return DecryptedMessageActionFlushHistoryTypeID
}

// Encode serializes DecryptedMessageActionFlushHistory to a bytes.Buffer using the TL binary protocol.
func (v *DecryptedMessageActionFlushHistory) Encode(b *bytes.Buffer) error {
	tg.WriteInt(b, DecryptedMessageActionFlushHistoryTypeID)
	return nil
}

// DecodeDecryptedMessageActionFlushHistory deserializes a DecryptedMessageActionFlushHistory from a reader using the TL binary protocol.
func DecodeDecryptedMessageActionFlushHistory(r *tg.Reader) (*DecryptedMessageActionFlushHistory, error) {
	v := &DecryptedMessageActionFlushHistory{}
	return v, nil
}

func init() {
	Registry[DecryptedMessageActionFlushHistoryTypeID] = func(r *tg.Reader) (tg.TLObject, error) {
		return DecodeDecryptedMessageActionFlushHistory(r)
	}
}

// DecryptedMessageActionResend represents the TL constructor decryptedMessageActionResend (0x511110b0).
type DecryptedMessageActionResend struct {
	StartSeqNo int32 `json:"start_seq_no,omitempty"`
	EndSeqNo   int32 `json:"end_seq_no,omitempty"`
}

// ConstructorID returns the TL constructor identifier 0x511110b0.
func (v *DecryptedMessageActionResend) ConstructorID() uint32 {
	return DecryptedMessageActionResendTypeID
}

// Encode serializes DecryptedMessageActionResend to a bytes.Buffer using the TL binary protocol.
func (v *DecryptedMessageActionResend) Encode(b *bytes.Buffer) error {
	tg.WriteInt(b, DecryptedMessageActionResendTypeID)
	tg.WriteInt(b, uint32(v.StartSeqNo))
	tg.WriteInt(b, uint32(v.EndSeqNo))
	return nil
}

// DecodeDecryptedMessageActionResend deserializes a DecryptedMessageActionResend from a reader using the TL binary protocol.
func DecodeDecryptedMessageActionResend(r *tg.Reader) (*DecryptedMessageActionResend, error) {
	v := &DecryptedMessageActionResend{}
	_rStartSeqNo, _eStartSeqNo := r.ReadInt32()
	if _eStartSeqNo != nil {
		return nil, _eStartSeqNo
	}
	v.StartSeqNo = _rStartSeqNo
	_rEndSeqNo, _eEndSeqNo := r.ReadInt32()
	if _eEndSeqNo != nil {
		return nil, _eEndSeqNo
	}
	v.EndSeqNo = _rEndSeqNo
	return v, nil
}

func init() {
	Registry[DecryptedMessageActionResendTypeID] = func(r *tg.Reader) (tg.TLObject, error) {
		return DecodeDecryptedMessageActionResend(r)
	}
}

// DecryptedMessageActionNotifyLayer represents the TL constructor decryptedMessageActionNotifyLayer (0xf3048883).
type DecryptedMessageActionNotifyLayer struct {
	Layer int32 `json:"layer,omitempty"`
}

// ConstructorID returns the TL constructor identifier 0xf3048883.
func (v *DecryptedMessageActionNotifyLayer) ConstructorID() uint32 {
	return DecryptedMessageActionNotifyLayerTypeID
}

// Encode serializes DecryptedMessageActionNotifyLayer to a bytes.Buffer using the TL binary protocol.
func (v *DecryptedMessageActionNotifyLayer) Encode(b *bytes.Buffer) error {
	tg.WriteInt(b, DecryptedMessageActionNotifyLayerTypeID)
	tg.WriteInt(b, uint32(v.Layer))
	return nil
}

// DecodeDecryptedMessageActionNotifyLayer deserializes a DecryptedMessageActionNotifyLayer from a reader using the TL binary protocol.
func DecodeDecryptedMessageActionNotifyLayer(r *tg.Reader) (*DecryptedMessageActionNotifyLayer, error) {
	v := &DecryptedMessageActionNotifyLayer{}
	_rLayer, _eLayer := r.ReadInt32()
	if _eLayer != nil {
		return nil, _eLayer
	}
	v.Layer = _rLayer
	return v, nil
}

func init() {
	Registry[DecryptedMessageActionNotifyLayerTypeID] = func(r *tg.Reader) (tg.TLObject, error) {
		return DecodeDecryptedMessageActionNotifyLayer(r)
	}
}

// DecryptedMessageActionTyping represents the TL constructor decryptedMessageActionTyping (0xccb27641).
type DecryptedMessageActionTyping struct {
	Action SendMessageActionClass `json:"action,omitempty"`
}

// ConstructorID returns the TL constructor identifier 0xccb27641.
func (v *DecryptedMessageActionTyping) ConstructorID() uint32 {
	return DecryptedMessageActionTypingTypeID
}

// Encode serializes DecryptedMessageActionTyping to a bytes.Buffer using the TL binary protocol.
func (v *DecryptedMessageActionTyping) Encode(b *bytes.Buffer) error {
	tg.WriteInt(b, DecryptedMessageActionTypingTypeID)
	tg.EncodeTLObject(b, v.Action)
	return nil
}

// DecodeDecryptedMessageActionTyping deserializes a DecryptedMessageActionTyping from a reader using the TL binary protocol.
func DecodeDecryptedMessageActionTyping(r *tg.Reader) (*DecryptedMessageActionTyping, error) {
	v := &DecryptedMessageActionTyping{}
	_objAction, _errAction := ReadE2ETLObject(r)
	if _errAction != nil {
		return nil, _errAction
	}
	v.Action = _objAction.(SendMessageActionClass)
	return v, nil
}

func init() {
	Registry[DecryptedMessageActionTypingTypeID] = func(r *tg.Reader) (tg.TLObject, error) {
		return DecodeDecryptedMessageActionTyping(r)
	}
}

// DecryptedMessageActionRequestKey represents the TL constructor decryptedMessageActionRequestKey (0xf3c9611b).
type DecryptedMessageActionRequestKey struct {
	ExchangeID int64  `json:"exchange_id,omitempty"`
	GA         []byte `json:"ga,omitempty"`
}

// ConstructorID returns the TL constructor identifier 0xf3c9611b.
func (v *DecryptedMessageActionRequestKey) ConstructorID() uint32 {
	return DecryptedMessageActionRequestKeyTypeID
}

// Encode serializes DecryptedMessageActionRequestKey to a bytes.Buffer using the TL binary protocol.
func (v *DecryptedMessageActionRequestKey) Encode(b *bytes.Buffer) error {
	tg.WriteInt(b, DecryptedMessageActionRequestKeyTypeID)
	tg.WriteLong(b, v.ExchangeID)
	tg.WriteBytes(b, v.GA)
	return nil
}

// DecodeDecryptedMessageActionRequestKey deserializes a DecryptedMessageActionRequestKey from a reader using the TL binary protocol.
func DecodeDecryptedMessageActionRequestKey(r *tg.Reader) (*DecryptedMessageActionRequestKey, error) {
	v := &DecryptedMessageActionRequestKey{}
	_rExchangeID, _eExchangeID := r.ReadInt64()
	if _eExchangeID != nil {
		return nil, _eExchangeID
	}
	v.ExchangeID = _rExchangeID
	_rGA, _eGA := r.ReadBytes()
	if _eGA != nil {
		return nil, _eGA
	}
	v.GA = _rGA
	return v, nil
}

func init() {
	Registry[DecryptedMessageActionRequestKeyTypeID] = func(r *tg.Reader) (tg.TLObject, error) {
		return DecodeDecryptedMessageActionRequestKey(r)
	}
}

// DecryptedMessageActionAcceptKey represents the TL constructor decryptedMessageActionAcceptKey (0x6fe1735b).
type DecryptedMessageActionAcceptKey struct {
	ExchangeID     int64  `json:"exchange_id,omitempty"`
	GB             []byte `json:"gb,omitempty"`
	KeyFingerprint int64  `json:"key_fingerprint,omitempty"`
}

// ConstructorID returns the TL constructor identifier 0x6fe1735b.
func (v *DecryptedMessageActionAcceptKey) ConstructorID() uint32 {
	return DecryptedMessageActionAcceptKeyTypeID
}

// Encode serializes DecryptedMessageActionAcceptKey to a bytes.Buffer using the TL binary protocol.
func (v *DecryptedMessageActionAcceptKey) Encode(b *bytes.Buffer) error {
	tg.WriteInt(b, DecryptedMessageActionAcceptKeyTypeID)
	tg.WriteLong(b, v.ExchangeID)
	tg.WriteBytes(b, v.GB)
	tg.WriteLong(b, v.KeyFingerprint)
	return nil
}

// DecodeDecryptedMessageActionAcceptKey deserializes a DecryptedMessageActionAcceptKey from a reader using the TL binary protocol.
func DecodeDecryptedMessageActionAcceptKey(r *tg.Reader) (*DecryptedMessageActionAcceptKey, error) {
	v := &DecryptedMessageActionAcceptKey{}
	_rExchangeID, _eExchangeID := r.ReadInt64()
	if _eExchangeID != nil {
		return nil, _eExchangeID
	}
	v.ExchangeID = _rExchangeID
	_rGB, _eGB := r.ReadBytes()
	if _eGB != nil {
		return nil, _eGB
	}
	v.GB = _rGB
	_rKeyFingerprint, _eKeyFingerprint := r.ReadInt64()
	if _eKeyFingerprint != nil {
		return nil, _eKeyFingerprint
	}
	v.KeyFingerprint = _rKeyFingerprint
	return v, nil
}

func init() {
	Registry[DecryptedMessageActionAcceptKeyTypeID] = func(r *tg.Reader) (tg.TLObject, error) {
		return DecodeDecryptedMessageActionAcceptKey(r)
	}
}

// DecryptedMessageActionAbortKey represents the TL constructor decryptedMessageActionAbortKey (0xdd05ec6b).
type DecryptedMessageActionAbortKey struct {
	ExchangeID int64 `json:"exchange_id,omitempty"`
}

// ConstructorID returns the TL constructor identifier 0xdd05ec6b.
func (v *DecryptedMessageActionAbortKey) ConstructorID() uint32 {
	return DecryptedMessageActionAbortKeyTypeID
}

// Encode serializes DecryptedMessageActionAbortKey to a bytes.Buffer using the TL binary protocol.
func (v *DecryptedMessageActionAbortKey) Encode(b *bytes.Buffer) error {
	tg.WriteInt(b, DecryptedMessageActionAbortKeyTypeID)
	tg.WriteLong(b, v.ExchangeID)
	return nil
}

// DecodeDecryptedMessageActionAbortKey deserializes a DecryptedMessageActionAbortKey from a reader using the TL binary protocol.
func DecodeDecryptedMessageActionAbortKey(r *tg.Reader) (*DecryptedMessageActionAbortKey, error) {
	v := &DecryptedMessageActionAbortKey{}
	_rExchangeID, _eExchangeID := r.ReadInt64()
	if _eExchangeID != nil {
		return nil, _eExchangeID
	}
	v.ExchangeID = _rExchangeID
	return v, nil
}

func init() {
	Registry[DecryptedMessageActionAbortKeyTypeID] = func(r *tg.Reader) (tg.TLObject, error) {
		return DecodeDecryptedMessageActionAbortKey(r)
	}
}

// DecryptedMessageActionCommitKey represents the TL constructor decryptedMessageActionCommitKey (0xec2e0b9b).
type DecryptedMessageActionCommitKey struct {
	ExchangeID     int64 `json:"exchange_id,omitempty"`
	KeyFingerprint int64 `json:"key_fingerprint,omitempty"`
}

// ConstructorID returns the TL constructor identifier 0xec2e0b9b.
func (v *DecryptedMessageActionCommitKey) ConstructorID() uint32 {
	return DecryptedMessageActionCommitKeyTypeID
}

// Encode serializes DecryptedMessageActionCommitKey to a bytes.Buffer using the TL binary protocol.
func (v *DecryptedMessageActionCommitKey) Encode(b *bytes.Buffer) error {
	tg.WriteInt(b, DecryptedMessageActionCommitKeyTypeID)
	tg.WriteLong(b, v.ExchangeID)
	tg.WriteLong(b, v.KeyFingerprint)
	return nil
}

// DecodeDecryptedMessageActionCommitKey deserializes a DecryptedMessageActionCommitKey from a reader using the TL binary protocol.
func DecodeDecryptedMessageActionCommitKey(r *tg.Reader) (*DecryptedMessageActionCommitKey, error) {
	v := &DecryptedMessageActionCommitKey{}
	_rExchangeID, _eExchangeID := r.ReadInt64()
	if _eExchangeID != nil {
		return nil, _eExchangeID
	}
	v.ExchangeID = _rExchangeID
	_rKeyFingerprint, _eKeyFingerprint := r.ReadInt64()
	if _eKeyFingerprint != nil {
		return nil, _eKeyFingerprint
	}
	v.KeyFingerprint = _rKeyFingerprint
	return v, nil
}

func init() {
	Registry[DecryptedMessageActionCommitKeyTypeID] = func(r *tg.Reader) (tg.TLObject, error) {
		return DecodeDecryptedMessageActionCommitKey(r)
	}
}

// DecryptedMessageActionNoop represents the TL constructor decryptedMessageActionNoop (0xa82fdd63).
type DecryptedMessageActionNoop struct {
}

// ConstructorID returns the TL constructor identifier 0xa82fdd63.
func (v *DecryptedMessageActionNoop) ConstructorID() uint32 {
	return DecryptedMessageActionNoopTypeID
}

// Encode serializes DecryptedMessageActionNoop to a bytes.Buffer using the TL binary protocol.
func (v *DecryptedMessageActionNoop) Encode(b *bytes.Buffer) error {
	tg.WriteInt(b, DecryptedMessageActionNoopTypeID)
	return nil
}

// DecodeDecryptedMessageActionNoop deserializes a DecryptedMessageActionNoop from a reader using the TL binary protocol.
func DecodeDecryptedMessageActionNoop(r *tg.Reader) (*DecryptedMessageActionNoop, error) {
	v := &DecryptedMessageActionNoop{}
	return v, nil
}

func init() {
	Registry[DecryptedMessageActionNoopTypeID] = func(r *tg.Reader) (tg.TLObject, error) {
		return DecodeDecryptedMessageActionNoop(r)
	}
}
