// Code generated by tlgen. DO NOT EDIT.

package e2e

import (
	"bytes"
	"github.com/mtgo-labs/mtgo/tg"
)

// DecryptedMessageMediaClass is the interface for TL type DecryptedMessageMedia.
// Implementations must satisfy tg.TLObject and are used to represent
// any constructor of the DecryptedMessageMedia TL type.
type DecryptedMessageMediaClass interface {
	tg.TLObject
	isDecryptedMessageMedia()
}

// DecryptedMessageMediaEmptyTypeID is the constructor ID for TL type decryptedMessageMediaEmpty.
const DecryptedMessageMediaEmptyTypeID = 0x089f5c4a

// DecryptedMessageMediaPhoto8TypeID is the constructor ID for TL type decryptedMessageMediaPhoto8.
const DecryptedMessageMediaPhoto8TypeID = 0x32798a8c

// DecryptedMessageMediaVideo8TypeID is the constructor ID for TL type decryptedMessageMediaVideo8.
const DecryptedMessageMediaVideo8TypeID = 0x4cee6ef3

// DecryptedMessageMediaGeoPointTypeID is the constructor ID for TL type decryptedMessageMediaGeoPoint.
const DecryptedMessageMediaGeoPointTypeID = 0x35480a59

// DecryptedMessageMediaContactTypeID is the constructor ID for TL type decryptedMessageMediaContact.
const DecryptedMessageMediaContactTypeID = 0x588a0a97

// DecryptedMessageMediaDocument8TypeID is the constructor ID for TL type decryptedMessageMediaDocument8.
const DecryptedMessageMediaDocument8TypeID = 0xb095434b

// DecryptedMessageMediaAudio8TypeID is the constructor ID for TL type decryptedMessageMediaAudio8.
const DecryptedMessageMediaAudio8TypeID = 0x6080758f

// DecryptedMessageMediaVideo23TypeID is the constructor ID for TL type decryptedMessageMediaVideo23.
const DecryptedMessageMediaVideo23TypeID = 0x524a415d

// DecryptedMessageMediaAudioTypeID is the constructor ID for TL type decryptedMessageMediaAudio.
const DecryptedMessageMediaAudioTypeID = 0x57e0a9cb

// DecryptedMessageMediaExternalDocumentTypeID is the constructor ID for TL type decryptedMessageMediaExternalDocument.
const DecryptedMessageMediaExternalDocumentTypeID = 0xfa95b0dd

// DecryptedMessageMediaPhotoTypeID is the constructor ID for TL type decryptedMessageMediaPhoto.
const DecryptedMessageMediaPhotoTypeID = 0xf1fa8d78

// DecryptedMessageMediaVideoTypeID is the constructor ID for TL type decryptedMessageMediaVideo.
const DecryptedMessageMediaVideoTypeID = 0x970c8c0e

// DecryptedMessageMediaDocument46TypeID is the constructor ID for TL type decryptedMessageMediaDocument46.
const DecryptedMessageMediaDocument46TypeID = 0x7afe8ae2

// DecryptedMessageMediaVenueTypeID is the constructor ID for TL type decryptedMessageMediaVenue.
const DecryptedMessageMediaVenueTypeID = 0x8a0df56f

// DecryptedMessageMediaWebPageTypeID is the constructor ID for TL type decryptedMessageMediaWebPage.
const DecryptedMessageMediaWebPageTypeID = 0xe50511d8

// DecryptedMessageMediaDocumentTypeID is the constructor ID for TL type decryptedMessageMediaDocument.
const DecryptedMessageMediaDocumentTypeID = 0x6abd9782

// isDecryptedMessageMedia marks DecryptedMessageMediaEmpty as implementing the DecryptedMessageMediaClass interface.
func (*DecryptedMessageMediaEmpty) isDecryptedMessageMedia() {}

// isDecryptedMessageMedia marks DecryptedMessageMediaPhoto8 as implementing the DecryptedMessageMediaClass interface.
func (*DecryptedMessageMediaPhoto8) isDecryptedMessageMedia() {}

// isDecryptedMessageMedia marks DecryptedMessageMediaVideo8 as implementing the DecryptedMessageMediaClass interface.
func (*DecryptedMessageMediaVideo8) isDecryptedMessageMedia() {}

// isDecryptedMessageMedia marks DecryptedMessageMediaGeoPoint as implementing the DecryptedMessageMediaClass interface.
func (*DecryptedMessageMediaGeoPoint) isDecryptedMessageMedia() {}

// isDecryptedMessageMedia marks DecryptedMessageMediaContact as implementing the DecryptedMessageMediaClass interface.
func (*DecryptedMessageMediaContact) isDecryptedMessageMedia() {}

// isDecryptedMessageMedia marks DecryptedMessageMediaDocument8 as implementing the DecryptedMessageMediaClass interface.
func (*DecryptedMessageMediaDocument8) isDecryptedMessageMedia() {}

// isDecryptedMessageMedia marks DecryptedMessageMediaAudio8 as implementing the DecryptedMessageMediaClass interface.
func (*DecryptedMessageMediaAudio8) isDecryptedMessageMedia() {}

// isDecryptedMessageMedia marks DecryptedMessageMediaVideo23 as implementing the DecryptedMessageMediaClass interface.
func (*DecryptedMessageMediaVideo23) isDecryptedMessageMedia() {}

// isDecryptedMessageMedia marks DecryptedMessageMediaAudio as implementing the DecryptedMessageMediaClass interface.
func (*DecryptedMessageMediaAudio) isDecryptedMessageMedia() {}

// isDecryptedMessageMedia marks DecryptedMessageMediaExternalDocument as implementing the DecryptedMessageMediaClass interface.
func (*DecryptedMessageMediaExternalDocument) isDecryptedMessageMedia() {}

// isDecryptedMessageMedia marks DecryptedMessageMediaPhoto as implementing the DecryptedMessageMediaClass interface.
func (*DecryptedMessageMediaPhoto) isDecryptedMessageMedia() {}

// isDecryptedMessageMedia marks DecryptedMessageMediaVideo as implementing the DecryptedMessageMediaClass interface.
func (*DecryptedMessageMediaVideo) isDecryptedMessageMedia() {}

// isDecryptedMessageMedia marks DecryptedMessageMediaDocument46 as implementing the DecryptedMessageMediaClass interface.
func (*DecryptedMessageMediaDocument46) isDecryptedMessageMedia() {}

// isDecryptedMessageMedia marks DecryptedMessageMediaVenue as implementing the DecryptedMessageMediaClass interface.
func (*DecryptedMessageMediaVenue) isDecryptedMessageMedia() {}

// isDecryptedMessageMedia marks DecryptedMessageMediaWebPage as implementing the DecryptedMessageMediaClass interface.
func (*DecryptedMessageMediaWebPage) isDecryptedMessageMedia() {}

// isDecryptedMessageMedia marks DecryptedMessageMediaDocument as implementing the DecryptedMessageMediaClass interface.
func (*DecryptedMessageMediaDocument) isDecryptedMessageMedia() {}

// DecryptedMessageMediaEmpty represents the TL constructor decryptedMessageMediaEmpty (0x089f5c4a).
type DecryptedMessageMediaEmpty struct {
}

// ConstructorID returns the TL constructor identifier 0x089f5c4a.
func (v *DecryptedMessageMediaEmpty) ConstructorID() uint32 {
	return DecryptedMessageMediaEmptyTypeID
}

// Encode serializes DecryptedMessageMediaEmpty to a bytes.Buffer using the TL binary protocol.
func (v *DecryptedMessageMediaEmpty) Encode(b *bytes.Buffer) error {
	tg.WriteInt(b, DecryptedMessageMediaEmptyTypeID)
	return nil
}

// DecodeDecryptedMessageMediaEmpty deserializes a DecryptedMessageMediaEmpty from a reader using the TL binary protocol.
func DecodeDecryptedMessageMediaEmpty(r *tg.Reader) (*DecryptedMessageMediaEmpty, error) {
	v := &DecryptedMessageMediaEmpty{}
	return v, nil
}

func init() {
	Registry[DecryptedMessageMediaEmptyTypeID] = func(r *tg.Reader) (tg.TLObject, error) {
		return DecodeDecryptedMessageMediaEmpty(r)
	}
}

// DecryptedMessageMediaPhoto8 represents the TL constructor decryptedMessageMediaPhoto8 (0x32798a8c).
type DecryptedMessageMediaPhoto8 struct {
	Thumb  []byte `json:"thumb,omitempty"`
	ThumbW int32  `json:"thumb_w,omitempty"`
	ThumbH int32  `json:"thumb_h,omitempty"`
	W      int32  `json:"w,omitempty"`
	H      int32  `json:"h,omitempty"`
	Size   int32  `json:"size,omitempty"`
	Key    []byte `json:"key,omitempty"`
	Iv     []byte `json:"iv,omitempty"`
}

// ConstructorID returns the TL constructor identifier 0x32798a8c.
func (v *DecryptedMessageMediaPhoto8) ConstructorID() uint32 {
	return DecryptedMessageMediaPhoto8TypeID
}

// Encode serializes DecryptedMessageMediaPhoto8 to a bytes.Buffer using the TL binary protocol.
func (v *DecryptedMessageMediaPhoto8) Encode(b *bytes.Buffer) error {
	tg.WriteInt(b, DecryptedMessageMediaPhoto8TypeID)
	tg.WriteBytes(b, v.Thumb)
	tg.WriteInt(b, uint32(v.ThumbW))
	tg.WriteInt(b, uint32(v.ThumbH))
	tg.WriteInt(b, uint32(v.W))
	tg.WriteInt(b, uint32(v.H))
	tg.WriteInt(b, uint32(v.Size))
	tg.WriteBytes(b, v.Key)
	tg.WriteBytes(b, v.Iv)
	return nil
}

// DecodeDecryptedMessageMediaPhoto8 deserializes a DecryptedMessageMediaPhoto8 from a reader using the TL binary protocol.
func DecodeDecryptedMessageMediaPhoto8(r *tg.Reader) (*DecryptedMessageMediaPhoto8, error) {
	v := &DecryptedMessageMediaPhoto8{}
	_rThumb, _eThumb := r.ReadBytes()
	if _eThumb != nil {
		return nil, _eThumb
	}
	v.Thumb = _rThumb
	_rThumbW, _eThumbW := r.ReadInt32()
	if _eThumbW != nil {
		return nil, _eThumbW
	}
	v.ThumbW = _rThumbW
	_rThumbH, _eThumbH := r.ReadInt32()
	if _eThumbH != nil {
		return nil, _eThumbH
	}
	v.ThumbH = _rThumbH
	_rW, _eW := r.ReadInt32()
	if _eW != nil {
		return nil, _eW
	}
	v.W = _rW
	_rH, _eH := r.ReadInt32()
	if _eH != nil {
		return nil, _eH
	}
	v.H = _rH
	_rSize, _eSize := r.ReadInt32()
	if _eSize != nil {
		return nil, _eSize
	}
	v.Size = _rSize
	_rKey, _eKey := r.ReadBytes()
	if _eKey != nil {
		return nil, _eKey
	}
	v.Key = _rKey
	_rIv, _eIv := r.ReadBytes()
	if _eIv != nil {
		return nil, _eIv
	}
	v.Iv = _rIv
	return v, nil
}

func init() {
	Registry[DecryptedMessageMediaPhoto8TypeID] = func(r *tg.Reader) (tg.TLObject, error) {
		return DecodeDecryptedMessageMediaPhoto8(r)
	}
}

// DecryptedMessageMediaVideo8 represents the TL constructor decryptedMessageMediaVideo8 (0x4cee6ef3).
type DecryptedMessageMediaVideo8 struct {
	Thumb    []byte `json:"thumb,omitempty"`
	ThumbW   int32  `json:"thumb_w,omitempty"`
	ThumbH   int32  `json:"thumb_h,omitempty"`
	Duration int32  `json:"duration,omitempty"`
	W        int32  `json:"w,omitempty"`
	H        int32  `json:"h,omitempty"`
	Size     int32  `json:"size,omitempty"`
	Key      []byte `json:"key,omitempty"`
	Iv       []byte `json:"iv,omitempty"`
}

// ConstructorID returns the TL constructor identifier 0x4cee6ef3.
func (v *DecryptedMessageMediaVideo8) ConstructorID() uint32 {
	return DecryptedMessageMediaVideo8TypeID
}

// Encode serializes DecryptedMessageMediaVideo8 to a bytes.Buffer using the TL binary protocol.
func (v *DecryptedMessageMediaVideo8) Encode(b *bytes.Buffer) error {
	tg.WriteInt(b, DecryptedMessageMediaVideo8TypeID)
	tg.WriteBytes(b, v.Thumb)
	tg.WriteInt(b, uint32(v.ThumbW))
	tg.WriteInt(b, uint32(v.ThumbH))
	tg.WriteInt(b, uint32(v.Duration))
	tg.WriteInt(b, uint32(v.W))
	tg.WriteInt(b, uint32(v.H))
	tg.WriteInt(b, uint32(v.Size))
	tg.WriteBytes(b, v.Key)
	tg.WriteBytes(b, v.Iv)
	return nil
}

// DecodeDecryptedMessageMediaVideo8 deserializes a DecryptedMessageMediaVideo8 from a reader using the TL binary protocol.
func DecodeDecryptedMessageMediaVideo8(r *tg.Reader) (*DecryptedMessageMediaVideo8, error) {
	v := &DecryptedMessageMediaVideo8{}
	_rThumb, _eThumb := r.ReadBytes()
	if _eThumb != nil {
		return nil, _eThumb
	}
	v.Thumb = _rThumb
	_rThumbW, _eThumbW := r.ReadInt32()
	if _eThumbW != nil {
		return nil, _eThumbW
	}
	v.ThumbW = _rThumbW
	_rThumbH, _eThumbH := r.ReadInt32()
	if _eThumbH != nil {
		return nil, _eThumbH
	}
	v.ThumbH = _rThumbH
	_rDuration, _eDuration := r.ReadInt32()
	if _eDuration != nil {
		return nil, _eDuration
	}
	v.Duration = _rDuration
	_rW, _eW := r.ReadInt32()
	if _eW != nil {
		return nil, _eW
	}
	v.W = _rW
	_rH, _eH := r.ReadInt32()
	if _eH != nil {
		return nil, _eH
	}
	v.H = _rH
	_rSize, _eSize := r.ReadInt32()
	if _eSize != nil {
		return nil, _eSize
	}
	v.Size = _rSize
	_rKey, _eKey := r.ReadBytes()
	if _eKey != nil {
		return nil, _eKey
	}
	v.Key = _rKey
	_rIv, _eIv := r.ReadBytes()
	if _eIv != nil {
		return nil, _eIv
	}
	v.Iv = _rIv
	return v, nil
}

func init() {
	Registry[DecryptedMessageMediaVideo8TypeID] = func(r *tg.Reader) (tg.TLObject, error) {
		return DecodeDecryptedMessageMediaVideo8(r)
	}
}

// DecryptedMessageMediaGeoPoint represents the TL constructor decryptedMessageMediaGeoPoint (0x35480a59).
type DecryptedMessageMediaGeoPoint struct {
	Lat  float64 `json:"lat,omitempty"`
	Long float64 `json:"long,omitempty"`
}

// ConstructorID returns the TL constructor identifier 0x35480a59.
func (v *DecryptedMessageMediaGeoPoint) ConstructorID() uint32 {
	return DecryptedMessageMediaGeoPointTypeID
}

// Encode serializes DecryptedMessageMediaGeoPoint to a bytes.Buffer using the TL binary protocol.
func (v *DecryptedMessageMediaGeoPoint) Encode(b *bytes.Buffer) error {
	tg.WriteInt(b, DecryptedMessageMediaGeoPointTypeID)
	tg.WriteDouble(b, v.Lat)
	tg.WriteDouble(b, v.Long)
	return nil
}

// DecodeDecryptedMessageMediaGeoPoint deserializes a DecryptedMessageMediaGeoPoint from a reader using the TL binary protocol.
func DecodeDecryptedMessageMediaGeoPoint(r *tg.Reader) (*DecryptedMessageMediaGeoPoint, error) {
	v := &DecryptedMessageMediaGeoPoint{}
	_rLat, _eLat := r.ReadFloat64()
	if _eLat != nil {
		return nil, _eLat
	}
	v.Lat = _rLat
	_rLong, _eLong := r.ReadFloat64()
	if _eLong != nil {
		return nil, _eLong
	}
	v.Long = _rLong
	return v, nil
}

func init() {
	Registry[DecryptedMessageMediaGeoPointTypeID] = func(r *tg.Reader) (tg.TLObject, error) {
		return DecodeDecryptedMessageMediaGeoPoint(r)
	}
}

// DecryptedMessageMediaContact represents the TL constructor decryptedMessageMediaContact (0x588a0a97).
type DecryptedMessageMediaContact struct {
	PhoneNumber string `json:"phone_number,omitempty"`
	FirstName   string `json:"first_name,omitempty"`
	LastName    string `json:"last_name,omitempty"`
	UserID      int32  `json:"user_id,omitempty"`
}

// ConstructorID returns the TL constructor identifier 0x588a0a97.
func (v *DecryptedMessageMediaContact) ConstructorID() uint32 {
	return DecryptedMessageMediaContactTypeID
}

// Encode serializes DecryptedMessageMediaContact to a bytes.Buffer using the TL binary protocol.
func (v *DecryptedMessageMediaContact) Encode(b *bytes.Buffer) error {
	tg.WriteInt(b, DecryptedMessageMediaContactTypeID)
	tg.WriteString(b, v.PhoneNumber)
	tg.WriteString(b, v.FirstName)
	tg.WriteString(b, v.LastName)
	tg.WriteInt(b, uint32(v.UserID))
	return nil
}

// DecodeDecryptedMessageMediaContact deserializes a DecryptedMessageMediaContact from a reader using the TL binary protocol.
func DecodeDecryptedMessageMediaContact(r *tg.Reader) (*DecryptedMessageMediaContact, error) {
	v := &DecryptedMessageMediaContact{}
	_rPhoneNumber, _ePhoneNumber := r.ReadString()
	if _ePhoneNumber != nil {
		return nil, _ePhoneNumber
	}
	v.PhoneNumber = _rPhoneNumber
	_rFirstName, _eFirstName := r.ReadString()
	if _eFirstName != nil {
		return nil, _eFirstName
	}
	v.FirstName = _rFirstName
	_rLastName, _eLastName := r.ReadString()
	if _eLastName != nil {
		return nil, _eLastName
	}
	v.LastName = _rLastName
	_rUserID, _eUserID := r.ReadInt32()
	if _eUserID != nil {
		return nil, _eUserID
	}
	v.UserID = _rUserID
	return v, nil
}

func init() {
	Registry[DecryptedMessageMediaContactTypeID] = func(r *tg.Reader) (tg.TLObject, error) {
		return DecodeDecryptedMessageMediaContact(r)
	}
}

// DecryptedMessageMediaDocument8 represents the TL constructor decryptedMessageMediaDocument8 (0xb095434b).
type DecryptedMessageMediaDocument8 struct {
	Thumb    []byte `json:"thumb,omitempty"`
	ThumbW   int32  `json:"thumb_w,omitempty"`
	ThumbH   int32  `json:"thumb_h,omitempty"`
	FileName string `json:"file_name,omitempty"`
	MimeType string `json:"mime_type,omitempty"`
	Size     int32  `json:"size,omitempty"`
	Key      []byte `json:"key,omitempty"`
	Iv       []byte `json:"iv,omitempty"`
}

// ConstructorID returns the TL constructor identifier 0xb095434b.
func (v *DecryptedMessageMediaDocument8) ConstructorID() uint32 {
	return DecryptedMessageMediaDocument8TypeID
}

// Encode serializes DecryptedMessageMediaDocument8 to a bytes.Buffer using the TL binary protocol.
func (v *DecryptedMessageMediaDocument8) Encode(b *bytes.Buffer) error {
	tg.WriteInt(b, DecryptedMessageMediaDocument8TypeID)
	tg.WriteBytes(b, v.Thumb)
	tg.WriteInt(b, uint32(v.ThumbW))
	tg.WriteInt(b, uint32(v.ThumbH))
	tg.WriteString(b, v.FileName)
	tg.WriteString(b, v.MimeType)
	tg.WriteInt(b, uint32(v.Size))
	tg.WriteBytes(b, v.Key)
	tg.WriteBytes(b, v.Iv)
	return nil
}

// DecodeDecryptedMessageMediaDocument8 deserializes a DecryptedMessageMediaDocument8 from a reader using the TL binary protocol.
func DecodeDecryptedMessageMediaDocument8(r *tg.Reader) (*DecryptedMessageMediaDocument8, error) {
	v := &DecryptedMessageMediaDocument8{}
	_rThumb, _eThumb := r.ReadBytes()
	if _eThumb != nil {
		return nil, _eThumb
	}
	v.Thumb = _rThumb
	_rThumbW, _eThumbW := r.ReadInt32()
	if _eThumbW != nil {
		return nil, _eThumbW
	}
	v.ThumbW = _rThumbW
	_rThumbH, _eThumbH := r.ReadInt32()
	if _eThumbH != nil {
		return nil, _eThumbH
	}
	v.ThumbH = _rThumbH
	_rFileName, _eFileName := r.ReadString()
	if _eFileName != nil {
		return nil, _eFileName
	}
	v.FileName = _rFileName
	_rMimeType, _eMimeType := r.ReadString()
	if _eMimeType != nil {
		return nil, _eMimeType
	}
	v.MimeType = _rMimeType
	_rSize, _eSize := r.ReadInt32()
	if _eSize != nil {
		return nil, _eSize
	}
	v.Size = _rSize
	_rKey, _eKey := r.ReadBytes()
	if _eKey != nil {
		return nil, _eKey
	}
	v.Key = _rKey
	_rIv, _eIv := r.ReadBytes()
	if _eIv != nil {
		return nil, _eIv
	}
	v.Iv = _rIv
	return v, nil
}

func init() {
	Registry[DecryptedMessageMediaDocument8TypeID] = func(r *tg.Reader) (tg.TLObject, error) {
		return DecodeDecryptedMessageMediaDocument8(r)
	}
}

// DecryptedMessageMediaAudio8 represents the TL constructor decryptedMessageMediaAudio8 (0x6080758f).
type DecryptedMessageMediaAudio8 struct {
	Duration int32  `json:"duration,omitempty"`
	Size     int32  `json:"size,omitempty"`
	Key      []byte `json:"key,omitempty"`
	Iv       []byte `json:"iv,omitempty"`
}

// ConstructorID returns the TL constructor identifier 0x6080758f.
func (v *DecryptedMessageMediaAudio8) ConstructorID() uint32 {
	return DecryptedMessageMediaAudio8TypeID
}

// Encode serializes DecryptedMessageMediaAudio8 to a bytes.Buffer using the TL binary protocol.
func (v *DecryptedMessageMediaAudio8) Encode(b *bytes.Buffer) error {
	tg.WriteInt(b, DecryptedMessageMediaAudio8TypeID)
	tg.WriteInt(b, uint32(v.Duration))
	tg.WriteInt(b, uint32(v.Size))
	tg.WriteBytes(b, v.Key)
	tg.WriteBytes(b, v.Iv)
	return nil
}

// DecodeDecryptedMessageMediaAudio8 deserializes a DecryptedMessageMediaAudio8 from a reader using the TL binary protocol.
func DecodeDecryptedMessageMediaAudio8(r *tg.Reader) (*DecryptedMessageMediaAudio8, error) {
	v := &DecryptedMessageMediaAudio8{}
	_rDuration, _eDuration := r.ReadInt32()
	if _eDuration != nil {
		return nil, _eDuration
	}
	v.Duration = _rDuration
	_rSize, _eSize := r.ReadInt32()
	if _eSize != nil {
		return nil, _eSize
	}
	v.Size = _rSize
	_rKey, _eKey := r.ReadBytes()
	if _eKey != nil {
		return nil, _eKey
	}
	v.Key = _rKey
	_rIv, _eIv := r.ReadBytes()
	if _eIv != nil {
		return nil, _eIv
	}
	v.Iv = _rIv
	return v, nil
}

func init() {
	Registry[DecryptedMessageMediaAudio8TypeID] = func(r *tg.Reader) (tg.TLObject, error) {
		return DecodeDecryptedMessageMediaAudio8(r)
	}
}

// DecryptedMessageMediaVideo23 represents the TL constructor decryptedMessageMediaVideo23 (0x524a415d).
type DecryptedMessageMediaVideo23 struct {
	Thumb    []byte `json:"thumb,omitempty"`
	ThumbW   int32  `json:"thumb_w,omitempty"`
	ThumbH   int32  `json:"thumb_h,omitempty"`
	Duration int32  `json:"duration,omitempty"`
	MimeType string `json:"mime_type,omitempty"`
	W        int32  `json:"w,omitempty"`
	H        int32  `json:"h,omitempty"`
	Size     int32  `json:"size,omitempty"`
	Key      []byte `json:"key,omitempty"`
	Iv       []byte `json:"iv,omitempty"`
}

// ConstructorID returns the TL constructor identifier 0x524a415d.
func (v *DecryptedMessageMediaVideo23) ConstructorID() uint32 {
	return DecryptedMessageMediaVideo23TypeID
}

// Encode serializes DecryptedMessageMediaVideo23 to a bytes.Buffer using the TL binary protocol.
func (v *DecryptedMessageMediaVideo23) Encode(b *bytes.Buffer) error {
	tg.WriteInt(b, DecryptedMessageMediaVideo23TypeID)
	tg.WriteBytes(b, v.Thumb)
	tg.WriteInt(b, uint32(v.ThumbW))
	tg.WriteInt(b, uint32(v.ThumbH))
	tg.WriteInt(b, uint32(v.Duration))
	tg.WriteString(b, v.MimeType)
	tg.WriteInt(b, uint32(v.W))
	tg.WriteInt(b, uint32(v.H))
	tg.WriteInt(b, uint32(v.Size))
	tg.WriteBytes(b, v.Key)
	tg.WriteBytes(b, v.Iv)
	return nil
}

// DecodeDecryptedMessageMediaVideo23 deserializes a DecryptedMessageMediaVideo23 from a reader using the TL binary protocol.
func DecodeDecryptedMessageMediaVideo23(r *tg.Reader) (*DecryptedMessageMediaVideo23, error) {
	v := &DecryptedMessageMediaVideo23{}
	_rThumb, _eThumb := r.ReadBytes()
	if _eThumb != nil {
		return nil, _eThumb
	}
	v.Thumb = _rThumb
	_rThumbW, _eThumbW := r.ReadInt32()
	if _eThumbW != nil {
		return nil, _eThumbW
	}
	v.ThumbW = _rThumbW
	_rThumbH, _eThumbH := r.ReadInt32()
	if _eThumbH != nil {
		return nil, _eThumbH
	}
	v.ThumbH = _rThumbH
	_rDuration, _eDuration := r.ReadInt32()
	if _eDuration != nil {
		return nil, _eDuration
	}
	v.Duration = _rDuration
	_rMimeType, _eMimeType := r.ReadString()
	if _eMimeType != nil {
		return nil, _eMimeType
	}
	v.MimeType = _rMimeType
	_rW, _eW := r.ReadInt32()
	if _eW != nil {
		return nil, _eW
	}
	v.W = _rW
	_rH, _eH := r.ReadInt32()
	if _eH != nil {
		return nil, _eH
	}
	v.H = _rH
	_rSize, _eSize := r.ReadInt32()
	if _eSize != nil {
		return nil, _eSize
	}
	v.Size = _rSize
	_rKey, _eKey := r.ReadBytes()
	if _eKey != nil {
		return nil, _eKey
	}
	v.Key = _rKey
	_rIv, _eIv := r.ReadBytes()
	if _eIv != nil {
		return nil, _eIv
	}
	v.Iv = _rIv
	return v, nil
}

func init() {
	Registry[DecryptedMessageMediaVideo23TypeID] = func(r *tg.Reader) (tg.TLObject, error) {
		return DecodeDecryptedMessageMediaVideo23(r)
	}
}

// DecryptedMessageMediaAudio represents the TL constructor decryptedMessageMediaAudio (0x57e0a9cb).
type DecryptedMessageMediaAudio struct {
	Duration int32  `json:"duration,omitempty"`
	MimeType string `json:"mime_type,omitempty"`
	Size     int32  `json:"size,omitempty"`
	Key      []byte `json:"key,omitempty"`
	Iv       []byte `json:"iv,omitempty"`
}

// ConstructorID returns the TL constructor identifier 0x57e0a9cb.
func (v *DecryptedMessageMediaAudio) ConstructorID() uint32 {
	return DecryptedMessageMediaAudioTypeID
}

// Encode serializes DecryptedMessageMediaAudio to a bytes.Buffer using the TL binary protocol.
func (v *DecryptedMessageMediaAudio) Encode(b *bytes.Buffer) error {
	tg.WriteInt(b, DecryptedMessageMediaAudioTypeID)
	tg.WriteInt(b, uint32(v.Duration))
	tg.WriteString(b, v.MimeType)
	tg.WriteInt(b, uint32(v.Size))
	tg.WriteBytes(b, v.Key)
	tg.WriteBytes(b, v.Iv)
	return nil
}

// DecodeDecryptedMessageMediaAudio deserializes a DecryptedMessageMediaAudio from a reader using the TL binary protocol.
func DecodeDecryptedMessageMediaAudio(r *tg.Reader) (*DecryptedMessageMediaAudio, error) {
	v := &DecryptedMessageMediaAudio{}
	_rDuration, _eDuration := r.ReadInt32()
	if _eDuration != nil {
		return nil, _eDuration
	}
	v.Duration = _rDuration
	_rMimeType, _eMimeType := r.ReadString()
	if _eMimeType != nil {
		return nil, _eMimeType
	}
	v.MimeType = _rMimeType
	_rSize, _eSize := r.ReadInt32()
	if _eSize != nil {
		return nil, _eSize
	}
	v.Size = _rSize
	_rKey, _eKey := r.ReadBytes()
	if _eKey != nil {
		return nil, _eKey
	}
	v.Key = _rKey
	_rIv, _eIv := r.ReadBytes()
	if _eIv != nil {
		return nil, _eIv
	}
	v.Iv = _rIv
	return v, nil
}

func init() {
	Registry[DecryptedMessageMediaAudioTypeID] = func(r *tg.Reader) (tg.TLObject, error) {
		return DecodeDecryptedMessageMediaAudio(r)
	}
}

// DecryptedMessageMediaExternalDocument represents the TL constructor decryptedMessageMediaExternalDocument (0xfa95b0dd).
type DecryptedMessageMediaExternalDocument struct {
	ID         int64                    `json:"id,omitempty"`
	AccessHash int64                    `json:"access_hash,omitempty"`
	Date       int32                    `json:"date,omitempty"`
	MimeType   string                   `json:"mime_type,omitempty"`
	Size       int32                    `json:"size,omitempty"`
	Thumb      PhotoSizeClass           `json:"thumb,omitempty"`
	DCID       int32                    `json:"dcid,omitempty"`
	Attributes []DocumentAttributeClass `json:"attributes,omitempty"`
}

// ConstructorID returns the TL constructor identifier 0xfa95b0dd.
func (v *DecryptedMessageMediaExternalDocument) ConstructorID() uint32 {
	return DecryptedMessageMediaExternalDocumentTypeID
}

// Encode serializes DecryptedMessageMediaExternalDocument to a bytes.Buffer using the TL binary protocol.
func (v *DecryptedMessageMediaExternalDocument) Encode(b *bytes.Buffer) error {
	tg.WriteInt(b, DecryptedMessageMediaExternalDocumentTypeID)
	tg.WriteLong(b, v.ID)
	tg.WriteLong(b, v.AccessHash)
	tg.WriteInt(b, uint32(v.Date))
	tg.WriteString(b, v.MimeType)
	tg.WriteInt(b, uint32(v.Size))
	tg.EncodeTLObject(b, v.Thumb)
	tg.WriteInt(b, uint32(v.DCID))
	tg.WriteInt(b, 0x1cb5c415)
	tg.WriteInt(b, uint32(len(v.Attributes)))
	for _, _item := range v.Attributes {
		tg.EncodeTLObject(b, _item)
	}
	return nil
}

// DecodeDecryptedMessageMediaExternalDocument deserializes a DecryptedMessageMediaExternalDocument from a reader using the TL binary protocol.
func DecodeDecryptedMessageMediaExternalDocument(r *tg.Reader) (*DecryptedMessageMediaExternalDocument, error) {
	v := &DecryptedMessageMediaExternalDocument{}
	_rID, _eID := r.ReadInt64()
	if _eID != nil {
		return nil, _eID
	}
	v.ID = _rID
	_rAccessHash, _eAccessHash := r.ReadInt64()
	if _eAccessHash != nil {
		return nil, _eAccessHash
	}
	v.AccessHash = _rAccessHash
	_rDate, _eDate := r.ReadInt32()
	if _eDate != nil {
		return nil, _eDate
	}
	v.Date = _rDate
	_rMimeType, _eMimeType := r.ReadString()
	if _eMimeType != nil {
		return nil, _eMimeType
	}
	v.MimeType = _rMimeType
	_rSize, _eSize := r.ReadInt32()
	if _eSize != nil {
		return nil, _eSize
	}
	v.Size = _rSize
	_objThumb, _errThumb := ReadE2ETLObject(r)
	if _errThumb != nil {
		return nil, _errThumb
	}
	v.Thumb = _objThumb.(PhotoSizeClass)
	_rDCID, _eDCID := r.ReadInt32()
	if _eDCID != nil {
		return nil, _eDCID
	}
	v.DCID = _rDCID
	_vhdrAttributes, _ehdrAttributes := r.ReadUint32()
	if _ehdrAttributes != nil {
		return nil, _ehdrAttributes
	}
	_cntAttributes, _ecntAttributes := r.ReadUint32()
	if _ecntAttributes != nil {
		return nil, _ecntAttributes
	}
	if _errAttributes := tg.CheckVectorCount(_cntAttributes); _errAttributes != nil {
		return nil, _errAttributes
	}
	v.Attributes = make([]DocumentAttributeClass, _cntAttributes)
	for _iAttributes := range v.Attributes {
		_objAttributes, _errAttributes := ReadE2ETLObject(r)
		if _errAttributes != nil {
			return nil, _errAttributes
		}
		v.Attributes[_iAttributes] = _objAttributes.(DocumentAttributeClass)
	}
	_ = _vhdrAttributes
	return v, nil
}

func init() {
	Registry[DecryptedMessageMediaExternalDocumentTypeID] = func(r *tg.Reader) (tg.TLObject, error) {
		return DecodeDecryptedMessageMediaExternalDocument(r)
	}
}

// DecryptedMessageMediaPhoto represents the TL constructor decryptedMessageMediaPhoto (0xf1fa8d78).
type DecryptedMessageMediaPhoto struct {
	Thumb   []byte `json:"thumb,omitempty"`
	ThumbW  int32  `json:"thumb_w,omitempty"`
	ThumbH  int32  `json:"thumb_h,omitempty"`
	W       int32  `json:"w,omitempty"`
	H       int32  `json:"h,omitempty"`
	Size    int32  `json:"size,omitempty"`
	Key     []byte `json:"key,omitempty"`
	Iv      []byte `json:"iv,omitempty"`
	Caption string `json:"caption,omitempty"`
}

// ConstructorID returns the TL constructor identifier 0xf1fa8d78.
func (v *DecryptedMessageMediaPhoto) ConstructorID() uint32 {
	return DecryptedMessageMediaPhotoTypeID
}

// Encode serializes DecryptedMessageMediaPhoto to a bytes.Buffer using the TL binary protocol.
func (v *DecryptedMessageMediaPhoto) Encode(b *bytes.Buffer) error {
	tg.WriteInt(b, DecryptedMessageMediaPhotoTypeID)
	tg.WriteBytes(b, v.Thumb)
	tg.WriteInt(b, uint32(v.ThumbW))
	tg.WriteInt(b, uint32(v.ThumbH))
	tg.WriteInt(b, uint32(v.W))
	tg.WriteInt(b, uint32(v.H))
	tg.WriteInt(b, uint32(v.Size))
	tg.WriteBytes(b, v.Key)
	tg.WriteBytes(b, v.Iv)
	tg.WriteString(b, v.Caption)
	return nil
}

// DecodeDecryptedMessageMediaPhoto deserializes a DecryptedMessageMediaPhoto from a reader using the TL binary protocol.
func DecodeDecryptedMessageMediaPhoto(r *tg.Reader) (*DecryptedMessageMediaPhoto, error) {
	v := &DecryptedMessageMediaPhoto{}
	_rThumb, _eThumb := r.ReadBytes()
	if _eThumb != nil {
		return nil, _eThumb
	}
	v.Thumb = _rThumb
	_rThumbW, _eThumbW := r.ReadInt32()
	if _eThumbW != nil {
		return nil, _eThumbW
	}
	v.ThumbW = _rThumbW
	_rThumbH, _eThumbH := r.ReadInt32()
	if _eThumbH != nil {
		return nil, _eThumbH
	}
	v.ThumbH = _rThumbH
	_rW, _eW := r.ReadInt32()
	if _eW != nil {
		return nil, _eW
	}
	v.W = _rW
	_rH, _eH := r.ReadInt32()
	if _eH != nil {
		return nil, _eH
	}
	v.H = _rH
	_rSize, _eSize := r.ReadInt32()
	if _eSize != nil {
		return nil, _eSize
	}
	v.Size = _rSize
	_rKey, _eKey := r.ReadBytes()
	if _eKey != nil {
		return nil, _eKey
	}
	v.Key = _rKey
	_rIv, _eIv := r.ReadBytes()
	if _eIv != nil {
		return nil, _eIv
	}
	v.Iv = _rIv
	_rCaption, _eCaption := r.ReadString()
	if _eCaption != nil {
		return nil, _eCaption
	}
	v.Caption = _rCaption
	return v, nil
}

func init() {
	Registry[DecryptedMessageMediaPhotoTypeID] = func(r *tg.Reader) (tg.TLObject, error) {
		return DecodeDecryptedMessageMediaPhoto(r)
	}
}

// DecryptedMessageMediaVideo represents the TL constructor decryptedMessageMediaVideo (0x970c8c0e).
type DecryptedMessageMediaVideo struct {
	Thumb    []byte `json:"thumb,omitempty"`
	ThumbW   int32  `json:"thumb_w,omitempty"`
	ThumbH   int32  `json:"thumb_h,omitempty"`
	Duration int32  `json:"duration,omitempty"`
	MimeType string `json:"mime_type,omitempty"`
	W        int32  `json:"w,omitempty"`
	H        int32  `json:"h,omitempty"`
	Size     int32  `json:"size,omitempty"`
	Key      []byte `json:"key,omitempty"`
	Iv       []byte `json:"iv,omitempty"`
	Caption  string `json:"caption,omitempty"`
}

// ConstructorID returns the TL constructor identifier 0x970c8c0e.
func (v *DecryptedMessageMediaVideo) ConstructorID() uint32 {
	return DecryptedMessageMediaVideoTypeID
}

// Encode serializes DecryptedMessageMediaVideo to a bytes.Buffer using the TL binary protocol.
func (v *DecryptedMessageMediaVideo) Encode(b *bytes.Buffer) error {
	tg.WriteInt(b, DecryptedMessageMediaVideoTypeID)
	tg.WriteBytes(b, v.Thumb)
	tg.WriteInt(b, uint32(v.ThumbW))
	tg.WriteInt(b, uint32(v.ThumbH))
	tg.WriteInt(b, uint32(v.Duration))
	tg.WriteString(b, v.MimeType)
	tg.WriteInt(b, uint32(v.W))
	tg.WriteInt(b, uint32(v.H))
	tg.WriteInt(b, uint32(v.Size))
	tg.WriteBytes(b, v.Key)
	tg.WriteBytes(b, v.Iv)
	tg.WriteString(b, v.Caption)
	return nil
}

// DecodeDecryptedMessageMediaVideo deserializes a DecryptedMessageMediaVideo from a reader using the TL binary protocol.
func DecodeDecryptedMessageMediaVideo(r *tg.Reader) (*DecryptedMessageMediaVideo, error) {
	v := &DecryptedMessageMediaVideo{}
	_rThumb, _eThumb := r.ReadBytes()
	if _eThumb != nil {
		return nil, _eThumb
	}
	v.Thumb = _rThumb
	_rThumbW, _eThumbW := r.ReadInt32()
	if _eThumbW != nil {
		return nil, _eThumbW
	}
	v.ThumbW = _rThumbW
	_rThumbH, _eThumbH := r.ReadInt32()
	if _eThumbH != nil {
		return nil, _eThumbH
	}
	v.ThumbH = _rThumbH
	_rDuration, _eDuration := r.ReadInt32()
	if _eDuration != nil {
		return nil, _eDuration
	}
	v.Duration = _rDuration
	_rMimeType, _eMimeType := r.ReadString()
	if _eMimeType != nil {
		return nil, _eMimeType
	}
	v.MimeType = _rMimeType
	_rW, _eW := r.ReadInt32()
	if _eW != nil {
		return nil, _eW
	}
	v.W = _rW
	_rH, _eH := r.ReadInt32()
	if _eH != nil {
		return nil, _eH
	}
	v.H = _rH
	_rSize, _eSize := r.ReadInt32()
	if _eSize != nil {
		return nil, _eSize
	}
	v.Size = _rSize
	_rKey, _eKey := r.ReadBytes()
	if _eKey != nil {
		return nil, _eKey
	}
	v.Key = _rKey
	_rIv, _eIv := r.ReadBytes()
	if _eIv != nil {
		return nil, _eIv
	}
	v.Iv = _rIv
	_rCaption, _eCaption := r.ReadString()
	if _eCaption != nil {
		return nil, _eCaption
	}
	v.Caption = _rCaption
	return v, nil
}

func init() {
	Registry[DecryptedMessageMediaVideoTypeID] = func(r *tg.Reader) (tg.TLObject, error) {
		return DecodeDecryptedMessageMediaVideo(r)
	}
}

// DecryptedMessageMediaDocument46 represents the TL constructor decryptedMessageMediaDocument46 (0x7afe8ae2).
type DecryptedMessageMediaDocument46 struct {
	Thumb      []byte                   `json:"thumb,omitempty"`
	ThumbW     int32                    `json:"thumb_w,omitempty"`
	ThumbH     int32                    `json:"thumb_h,omitempty"`
	MimeType   string                   `json:"mime_type,omitempty"`
	Size       int32                    `json:"size,omitempty"`
	Key        []byte                   `json:"key,omitempty"`
	Iv         []byte                   `json:"iv,omitempty"`
	Attributes []DocumentAttributeClass `json:"attributes,omitempty"`
	Caption    string                   `json:"caption,omitempty"`
}

// ConstructorID returns the TL constructor identifier 0x7afe8ae2.
func (v *DecryptedMessageMediaDocument46) ConstructorID() uint32 {
	return DecryptedMessageMediaDocument46TypeID
}

// Encode serializes DecryptedMessageMediaDocument46 to a bytes.Buffer using the TL binary protocol.
func (v *DecryptedMessageMediaDocument46) Encode(b *bytes.Buffer) error {
	tg.WriteInt(b, DecryptedMessageMediaDocument46TypeID)
	tg.WriteBytes(b, v.Thumb)
	tg.WriteInt(b, uint32(v.ThumbW))
	tg.WriteInt(b, uint32(v.ThumbH))
	tg.WriteString(b, v.MimeType)
	tg.WriteInt(b, uint32(v.Size))
	tg.WriteBytes(b, v.Key)
	tg.WriteBytes(b, v.Iv)
	tg.WriteInt(b, 0x1cb5c415)
	tg.WriteInt(b, uint32(len(v.Attributes)))
	for _, _item := range v.Attributes {
		tg.EncodeTLObject(b, _item)
	}
	tg.WriteString(b, v.Caption)
	return nil
}

// DecodeDecryptedMessageMediaDocument46 deserializes a DecryptedMessageMediaDocument46 from a reader using the TL binary protocol.
func DecodeDecryptedMessageMediaDocument46(r *tg.Reader) (*DecryptedMessageMediaDocument46, error) {
	v := &DecryptedMessageMediaDocument46{}
	_rThumb, _eThumb := r.ReadBytes()
	if _eThumb != nil {
		return nil, _eThumb
	}
	v.Thumb = _rThumb
	_rThumbW, _eThumbW := r.ReadInt32()
	if _eThumbW != nil {
		return nil, _eThumbW
	}
	v.ThumbW = _rThumbW
	_rThumbH, _eThumbH := r.ReadInt32()
	if _eThumbH != nil {
		return nil, _eThumbH
	}
	v.ThumbH = _rThumbH
	_rMimeType, _eMimeType := r.ReadString()
	if _eMimeType != nil {
		return nil, _eMimeType
	}
	v.MimeType = _rMimeType
	_rSize, _eSize := r.ReadInt32()
	if _eSize != nil {
		return nil, _eSize
	}
	v.Size = _rSize
	_rKey, _eKey := r.ReadBytes()
	if _eKey != nil {
		return nil, _eKey
	}
	v.Key = _rKey
	_rIv, _eIv := r.ReadBytes()
	if _eIv != nil {
		return nil, _eIv
	}
	v.Iv = _rIv
	_vhdrAttributes, _ehdrAttributes := r.ReadUint32()
	if _ehdrAttributes != nil {
		return nil, _ehdrAttributes
	}
	_cntAttributes, _ecntAttributes := r.ReadUint32()
	if _ecntAttributes != nil {
		return nil, _ecntAttributes
	}
	if _errAttributes := tg.CheckVectorCount(_cntAttributes); _errAttributes != nil {
		return nil, _errAttributes
	}
	v.Attributes = make([]DocumentAttributeClass, _cntAttributes)
	for _iAttributes := range v.Attributes {
		_objAttributes, _errAttributes := ReadE2ETLObject(r)
		if _errAttributes != nil {
			return nil, _errAttributes
		}
		v.Attributes[_iAttributes] = _objAttributes.(DocumentAttributeClass)
	}
	_ = _vhdrAttributes
	_rCaption, _eCaption := r.ReadString()
	if _eCaption != nil {
		return nil, _eCaption
	}
	v.Caption = _rCaption
	return v, nil
}

func init() {
	Registry[DecryptedMessageMediaDocument46TypeID] = func(r *tg.Reader) (tg.TLObject, error) {
		return DecodeDecryptedMessageMediaDocument46(r)
	}
}

// DecryptedMessageMediaVenue represents the TL constructor decryptedMessageMediaVenue (0x8a0df56f).
type DecryptedMessageMediaVenue struct {
	Lat      float64 `json:"lat,omitempty"`
	Long     float64 `json:"long,omitempty"`
	Title    string  `json:"title,omitempty"`
	Address  string  `json:"address,omitempty"`
	Provider string  `json:"provider,omitempty"`
	VenueID  string  `json:"venue_id,omitempty"`
}

// ConstructorID returns the TL constructor identifier 0x8a0df56f.
func (v *DecryptedMessageMediaVenue) ConstructorID() uint32 {
	return DecryptedMessageMediaVenueTypeID
}

// Encode serializes DecryptedMessageMediaVenue to a bytes.Buffer using the TL binary protocol.
func (v *DecryptedMessageMediaVenue) Encode(b *bytes.Buffer) error {
	tg.WriteInt(b, DecryptedMessageMediaVenueTypeID)
	tg.WriteDouble(b, v.Lat)
	tg.WriteDouble(b, v.Long)
	tg.WriteString(b, v.Title)
	tg.WriteString(b, v.Address)
	tg.WriteString(b, v.Provider)
	tg.WriteString(b, v.VenueID)
	return nil
}

// DecodeDecryptedMessageMediaVenue deserializes a DecryptedMessageMediaVenue from a reader using the TL binary protocol.
func DecodeDecryptedMessageMediaVenue(r *tg.Reader) (*DecryptedMessageMediaVenue, error) {
	v := &DecryptedMessageMediaVenue{}
	_rLat, _eLat := r.ReadFloat64()
	if _eLat != nil {
		return nil, _eLat
	}
	v.Lat = _rLat
	_rLong, _eLong := r.ReadFloat64()
	if _eLong != nil {
		return nil, _eLong
	}
	v.Long = _rLong
	_rTitle, _eTitle := r.ReadString()
	if _eTitle != nil {
		return nil, _eTitle
	}
	v.Title = _rTitle
	_rAddress, _eAddress := r.ReadString()
	if _eAddress != nil {
		return nil, _eAddress
	}
	v.Address = _rAddress
	_rProvider, _eProvider := r.ReadString()
	if _eProvider != nil {
		return nil, _eProvider
	}
	v.Provider = _rProvider
	_rVenueID, _eVenueID := r.ReadString()
	if _eVenueID != nil {
		return nil, _eVenueID
	}
	v.VenueID = _rVenueID
	return v, nil
}

func init() {
	Registry[DecryptedMessageMediaVenueTypeID] = func(r *tg.Reader) (tg.TLObject, error) {
		return DecodeDecryptedMessageMediaVenue(r)
	}
}

// DecryptedMessageMediaWebPage represents the TL constructor decryptedMessageMediaWebPage (0xe50511d8).
type DecryptedMessageMediaWebPage struct {
	URL string `json:"url,omitempty"`
}

// ConstructorID returns the TL constructor identifier 0xe50511d8.
func (v *DecryptedMessageMediaWebPage) ConstructorID() uint32 {
	return DecryptedMessageMediaWebPageTypeID
}

// Encode serializes DecryptedMessageMediaWebPage to a bytes.Buffer using the TL binary protocol.
func (v *DecryptedMessageMediaWebPage) Encode(b *bytes.Buffer) error {
	tg.WriteInt(b, DecryptedMessageMediaWebPageTypeID)
	tg.WriteString(b, v.URL)
	return nil
}

// DecodeDecryptedMessageMediaWebPage deserializes a DecryptedMessageMediaWebPage from a reader using the TL binary protocol.
func DecodeDecryptedMessageMediaWebPage(r *tg.Reader) (*DecryptedMessageMediaWebPage, error) {
	v := &DecryptedMessageMediaWebPage{}
	_rURL, _eURL := r.ReadString()
	if _eURL != nil {
		return nil, _eURL
	}
	v.URL = _rURL
	return v, nil
}

func init() {
	Registry[DecryptedMessageMediaWebPageTypeID] = func(r *tg.Reader) (tg.TLObject, error) {
		return DecodeDecryptedMessageMediaWebPage(r)
	}
}

// DecryptedMessageMediaDocument represents the TL constructor decryptedMessageMediaDocument (0x6abd9782).
type DecryptedMessageMediaDocument struct {
	Thumb      []byte                   `json:"thumb,omitempty"`
	ThumbW     int32                    `json:"thumb_w,omitempty"`
	ThumbH     int32                    `json:"thumb_h,omitempty"`
	MimeType   string                   `json:"mime_type,omitempty"`
	Size       int64                    `json:"size,omitempty"`
	Key        []byte                   `json:"key,omitempty"`
	Iv         []byte                   `json:"iv,omitempty"`
	Attributes []DocumentAttributeClass `json:"attributes,omitempty"`
	Caption    string                   `json:"caption,omitempty"`
}

// ConstructorID returns the TL constructor identifier 0x6abd9782.
func (v *DecryptedMessageMediaDocument) ConstructorID() uint32 {
	return DecryptedMessageMediaDocumentTypeID
}

// Encode serializes DecryptedMessageMediaDocument to a bytes.Buffer using the TL binary protocol.
func (v *DecryptedMessageMediaDocument) Encode(b *bytes.Buffer) error {
	tg.WriteInt(b, DecryptedMessageMediaDocumentTypeID)
	tg.WriteBytes(b, v.Thumb)
	tg.WriteInt(b, uint32(v.ThumbW))
	tg.WriteInt(b, uint32(v.ThumbH))
	tg.WriteString(b, v.MimeType)
	tg.WriteLong(b, v.Size)
	tg.WriteBytes(b, v.Key)
	tg.WriteBytes(b, v.Iv)
	tg.WriteInt(b, 0x1cb5c415)
	tg.WriteInt(b, uint32(len(v.Attributes)))
	for _, _item := range v.Attributes {
		tg.EncodeTLObject(b, _item)
	}
	tg.WriteString(b, v.Caption)
	return nil
}

// DecodeDecryptedMessageMediaDocument deserializes a DecryptedMessageMediaDocument from a reader using the TL binary protocol.
func DecodeDecryptedMessageMediaDocument(r *tg.Reader) (*DecryptedMessageMediaDocument, error) {
	v := &DecryptedMessageMediaDocument{}
	_rThumb, _eThumb := r.ReadBytes()
	if _eThumb != nil {
		return nil, _eThumb
	}
	v.Thumb = _rThumb
	_rThumbW, _eThumbW := r.ReadInt32()
	if _eThumbW != nil {
		return nil, _eThumbW
	}
	v.ThumbW = _rThumbW
	_rThumbH, _eThumbH := r.ReadInt32()
	if _eThumbH != nil {
		return nil, _eThumbH
	}
	v.ThumbH = _rThumbH
	_rMimeType, _eMimeType := r.ReadString()
	if _eMimeType != nil {
		return nil, _eMimeType
	}
	v.MimeType = _rMimeType
	_rSize, _eSize := r.ReadInt64()
	if _eSize != nil {
		return nil, _eSize
	}
	v.Size = _rSize
	_rKey, _eKey := r.ReadBytes()
	if _eKey != nil {
		return nil, _eKey
	}
	v.Key = _rKey
	_rIv, _eIv := r.ReadBytes()
	if _eIv != nil {
		return nil, _eIv
	}
	v.Iv = _rIv
	_vhdrAttributes, _ehdrAttributes := r.ReadUint32()
	if _ehdrAttributes != nil {
		return nil, _ehdrAttributes
	}
	_cntAttributes, _ecntAttributes := r.ReadUint32()
	if _ecntAttributes != nil {
		return nil, _ecntAttributes
	}
	if _errAttributes := tg.CheckVectorCount(_cntAttributes); _errAttributes != nil {
		return nil, _errAttributes
	}
	v.Attributes = make([]DocumentAttributeClass, _cntAttributes)
	for _iAttributes := range v.Attributes {
		_objAttributes, _errAttributes := ReadE2ETLObject(r)
		if _errAttributes != nil {
			return nil, _errAttributes
		}
		v.Attributes[_iAttributes] = _objAttributes.(DocumentAttributeClass)
	}
	_ = _vhdrAttributes
	_rCaption, _eCaption := r.ReadString()
	if _eCaption != nil {
		return nil, _eCaption
	}
	v.Caption = _rCaption
	return v, nil
}

func init() {
	Registry[DecryptedMessageMediaDocumentTypeID] = func(r *tg.Reader) (tg.TLObject, error) {
		return DecodeDecryptedMessageMediaDocument(r)
	}
}
