// Code generated by tlgen. DO NOT EDIT.

package e2e

import (
	"bytes"
	"io"

	"github.com/mtgo-labs/mtgo/tg"
)

// DecryptedMessageLayerTypeID is the constructor ID for TL type decryptedMessageLayer.
const DecryptedMessageLayerTypeID = 0x1be31789

// DecryptedMessageLayer represents the TL constructor decryptedMessageLayer (0x1be31789).
type DecryptedMessageLayer struct {
	RandomBytes []byte                `json:"random_bytes,omitempty"`
	Layer       int32                 `json:"layer,omitempty"`
	InSeqNo     int32                 `json:"in_seq_no,omitempty"`
	OutSeqNo    int32                 `json:"out_seq_no,omitempty"`
	Message     DecryptedMessageClass `json:"message,omitempty"`
}

// ConstructorID returns the TL constructor identifier 0x1be31789.
func (v *DecryptedMessageLayer) ConstructorID() uint32 {
	return DecryptedMessageLayerTypeID
}

// Encode serializes DecryptedMessageLayer to a bytes.Buffer using the TL binary protocol.
func (v *DecryptedMessageLayer) Encode(b *bytes.Buffer) error {
	tg.WriteInt(b, DecryptedMessageLayerTypeID)
	tg.WriteBytes(b, v.RandomBytes)
	tg.WriteInt(b, uint32(v.Layer))
	tg.WriteInt(b, uint32(v.InSeqNo))
	tg.WriteInt(b, uint32(v.OutSeqNo))
	tg.EncodeTLObject(b, v.Message)
	return nil
}

// DecodeDecryptedMessageLayer deserializes a DecryptedMessageLayer from a reader using the TL binary protocol.
func DecodeDecryptedMessageLayer(r io.Reader) (*DecryptedMessageLayer, error) {
	v := &DecryptedMessageLayer{}
	v.RandomBytes = tg.ReadBytes(r)
	v.Layer = int32(tg.ReadInt(r))
	v.InSeqNo = int32(tg.ReadInt(r))
	v.OutSeqNo = int32(tg.ReadInt(r))
	_objMessage, _ := ReadE2ETLObject(r)
	v.Message = _objMessage.(DecryptedMessageClass)
	return v, nil
}

func init() {
	Registry[DecryptedMessageLayerTypeID] = func(r io.Reader) (tg.TLObject, error) {
		return DecodeDecryptedMessageLayer(r)
	}
}
