// Code generated by tlgen. DO NOT EDIT.

package e2e

import (
	"bytes"
	"io"

	"github.com/mtgo-labs/mtgo/tg"
)

// FileLocationClass is the interface for TL type FileLocation.
// Implementations must satisfy tg.TLObject and are used to represent
// any constructor of the FileLocation TL type.
type FileLocationClass interface {
	tg.TLObject
	isFileLocation()
}

// FileLocationUnavailableTypeID is the constructor ID for TL type fileLocationUnavailable.
const FileLocationUnavailableTypeID = 0x7c596b46

// FileLocationTLTypeID is the constructor ID for TL type fileLocation.
const FileLocationTLTypeID = 0x53d69076

// isFileLocation marks FileLocationUnavailable as implementing the FileLocationClass interface.
func (*FileLocationUnavailable) isFileLocation() {}

// isFileLocation marks FileLocationTL as implementing the FileLocationClass interface.
func (*FileLocationTL) isFileLocation() {}

// FileLocationUnavailable represents the TL constructor fileLocationUnavailable (0x7c596b46).
type FileLocationUnavailable struct {
	VolumeID int64 `json:"volume_id,omitempty"`
	LocalID  int32 `json:"local_id,omitempty"`
	Secret   int64 `json:"secret,omitempty"`
}

// ConstructorID returns the TL constructor identifier 0x7c596b46.
func (v *FileLocationUnavailable) ConstructorID() uint32 {
	return FileLocationUnavailableTypeID
}

// Encode serializes FileLocationUnavailable to a bytes.Buffer using the TL binary protocol.
func (v *FileLocationUnavailable) Encode(b *bytes.Buffer) error {
	tg.WriteInt(b, FileLocationUnavailableTypeID)
	tg.WriteLong(b, v.VolumeID)
	tg.WriteInt(b, uint32(v.LocalID))
	tg.WriteLong(b, v.Secret)
	return nil
}

// DecodeFileLocationUnavailable deserializes a FileLocationUnavailable from a reader using the TL binary protocol.
func DecodeFileLocationUnavailable(r io.Reader) (*FileLocationUnavailable, error) {
	v := &FileLocationUnavailable{}
	v.VolumeID = tg.ReadLong(r)
	v.LocalID = int32(tg.ReadInt(r))
	v.Secret = tg.ReadLong(r)
	return v, nil
}

func init() {
	Registry[FileLocationUnavailableTypeID] = func(r io.Reader) (tg.TLObject, error) {
		return DecodeFileLocationUnavailable(r)
	}
}

// FileLocationTL represents the TL constructor fileLocation (0x53d69076).
type FileLocationTL struct {
	DcID     int32 `json:"dc_id,omitempty"`
	VolumeID int64 `json:"volume_id,omitempty"`
	LocalID  int32 `json:"local_id,omitempty"`
	Secret   int64 `json:"secret,omitempty"`
}

// ConstructorID returns the TL constructor identifier 0x53d69076.
func (v *FileLocationTL) ConstructorID() uint32 {
	return FileLocationTLTypeID
}

// Encode serializes FileLocationTL to a bytes.Buffer using the TL binary protocol.
func (v *FileLocationTL) Encode(b *bytes.Buffer) error {
	tg.WriteInt(b, FileLocationTLTypeID)
	tg.WriteInt(b, uint32(v.DcID))
	tg.WriteLong(b, v.VolumeID)
	tg.WriteInt(b, uint32(v.LocalID))
	tg.WriteLong(b, v.Secret)
	return nil
}

// DecodeFileLocationTL deserializes a FileLocationTL from a reader using the TL binary protocol.
func DecodeFileLocationTL(r io.Reader) (*FileLocationTL, error) {
	v := &FileLocationTL{}
	v.DcID = int32(tg.ReadInt(r))
	v.VolumeID = tg.ReadLong(r)
	v.LocalID = int32(tg.ReadInt(r))
	v.Secret = tg.ReadLong(r)
	return v, nil
}

func init() {
	Registry[FileLocationTLTypeID] = func(r io.Reader) (tg.TLObject, error) {
		return DecodeFileLocationTL(r)
	}
}
