package tlgen

import (
	"fmt"
	"go/format"
	"maps"
	"os"
	"path/filepath"
	"sort"
	"strings"
)

func classifyTypeDomain(typeName string, constructors []Combinator) string {
	nsCounts := map[string]int{}
	for _, c := range constructors {
		if c.Namespace != "" {
			nsCounts[c.Namespace]++
		}
	}
	if len(nsCounts) == 1 {
		for ns := range nsCounts {
			return ns
		}
	}
	if len(nsCounts) > 1 {
		best := ""
		bestN := 0
		for ns, n := range nsCounts {
			if n > bestN {
				best = ns
				bestN = n
			}
		}
		if best != "" {
			return best
		}
	}

	lower := strings.ToLower(typeName)

	keywords := []struct {
		keys   []string
		domain string
	}{
		{[]string{"auth", "login", "sentcode", "password", "passkey", "authorization"}, "auth"},
		{[]string{"message", "dialog", "sticker", "emoji", "reaction", "forum", "quickreply", "todo", "sponsored"}, "messages"},
		{[]string{"peer", "user", "chat", "channel", "contact", "participant", "invite", "username", "admin"}, "peer"},
		{[]string{"document", "photo", "video", "audio", "upload", "webpage", "maskcoord", "videosize", "filesize"}, "media"},
		{[]string{"update", "difference", "pts"}, "updates"},
		{[]string{"account", "privacy", "notify", "contentsetting", "autodownload", "autosave", "wallpaper", "business", "birthday", "connectedbot"}, "account"},
		{[]string{"bot", "keyboard", "inline", "game", "attachmenu", "webview", "botmenu"}, "bots"},
		{[]string{"payment", "star", "invoice", "shipping", "premium", "boost", "giveaway", "bankcard", "stargift"}, "payments"},
		{[]string{"phone", "call", "groupcall", "conference"}, "phone"},
		{[]string{"stor"}, "stories"},
		{[]string{"page", "richtext", "textblock"}, "pages"},
		{[]string{"poll", "vote"}, "polls"},
		{[]string{"chatlist", "folder", "dialogfilter"}, "chatlists"},
		{[]string{"encrypt", "decrypt", "dhinner", "pqinner"}, "crypto"},
		{[]string{"geo", "location"}, "geo"},
		{[]string{"config", "dcoption", "apponfig", "langpack", "country", "timezone", "invite", "nearestdc", "deeplink", "promodata", "termsofservice", "support", "apdate", "cdnconfig", "httwait", "req_pq", "res_pq", "ping", "pong", "future_salt", "msg_detailed", "msg_resend", "msgs_", "rpc_", "destroy_", "new_session", "bad_", "bind_auth", "init_connection", "invoke_", "set_client", "client_dh", "server_dh"}, "core"},
		{[]string{"sms_job", "smsjob"}, "smsjobs"},
		{[]string{"ai_compose", "aicompose"}, "aicompose"},
	}

	for _, kw := range keywords {
		for _, k := range kw.keys {
			if strings.Contains(lower, k) {
				return kw.domain
			}
		}
	}
	return "core"
}

func classifyFuncDomain(c Combinator) string {
	if c.Namespace != "" {
		return c.Namespace
	}
	return "core"
}

func domainFileOrder(domains map[string]bool) []string {
	order := []string{
		"auth", "messages", "peer", "media", "updates", "account",
		"bots", "payments", "phone", "stories", "chatlists",
		"pages", "polls", "geo", "crypto", "smsjobs", "aicompose",
		"system", "core",
	}
	var result []string
	for _, d := range order {
		if domains[d] {
			result = append(result, d)
		}
	}

	var rest []string
	for d := range domains {
		found := false
		for _, o := range order {
			if o == d {
				found = true
				break
			}
		}
		if !found {
			rest = append(rest, d)
		}
	}
	sort.Strings(rest)
	result = append(result, rest...)
	return result
}

func writeGoFile(path string, content string) error {
	formatted, err := format.Source([]byte(content))
	if err != nil {
		return fmt.Errorf("format error in %s: %w\n--- raw ---\n%s", path, err, content)
	}
	dir := filepath.Dir(path)
	if err := os.MkdirAll(dir, 0755); err != nil {
		return err
	}
	return os.WriteFile(path, formatted, 0644)
}

func cleanupGeneratedFiles(outDir string, patterns []string) error {
	entries, err := os.ReadDir(outDir)
	if err != nil {
		if os.IsNotExist(err) {
			return nil
		}
		return err
	}
	for _, e := range entries {
		if e.IsDir() {
			continue
		}
		name := e.Name()
		for _, p := range patterns {
			if match, _ := filepath.Match(p, name); match {
				os.Remove(filepath.Join(outDir, name))
				break
			}
		}
	}
	return nil
}

func flagSyncCondition(fs flagSync) string {
	switch fs.GoType {
	case "bool":
		return fmt.Sprintf("v.%s", fs.Field)
	case "string":
		return fmt.Sprintf("v.%s != \"\"", fs.Field)
	case "int32", "int64", "float64", "uint32":
		return fmt.Sprintf("v.%s != 0", fs.Field)
	default:
		return fmt.Sprintf("v.%s != nil", fs.Field)
	}
}

func GeneratePackageFiles(outDir, pkgName string, layer int) error {
	docContent := "// Code generated by tlgen. DO NOT EDIT.\n\n// Package " + pkgName + " provides auto-generated Go types for the Telegram MTProto TL schema.\n//\n// Each type implements the tg.TLObject interface with Encode and ConstructorID methods.\n// Use Decode{Name} functions to deserialize types from a reader.\n// Use tg.Registry to look up decoders by constructor ID.\npackage " + pkgName + "\n"
	return writeGoFile(filepath.Join(outDir, "doc.go"), docContent)
}

func GenerateInterfaces(outDir string, combos []Combinator) error {
	typeCombos := filterCombos(combos, SectionTypes)
	baseTypes := computeBaseTypes(combos)

	typeMap := map[string][]Combinator{}
	typeOrder := []string{}
	for _, c := range typeCombos {
		if _, exists := typeMap[c.Type]; !exists {
			typeOrder = append(typeOrder, c.Type)
		}
		typeMap[c.Type] = append(typeMap[c.Type], c)
	}

	var buf strings.Builder
	buf.WriteString("// Code generated by tlgen. DO NOT EDIT.\n\npackage tg\n\n")

	count := 0
	for _, typeName := range typeOrder {
		constructors := typeMap[typeName]
		if len(constructors) <= 1 {
			continue
		}
		basePascal := SnakeToPascal(typeName)
		fmt.Fprintf(&buf, "// %s is the interface for TL type %s.\n// Implementations must satisfy TLObject and are used to represent\n// any constructor of the %s TL type.\ntype %s interface {\n\tTLObject\n\tis%s()\n}\n\n", basePascal+"Class", basePascal, basePascal, basePascal+"Class", basePascal)
		_ = baseTypes
		count++
	}

	if count == 0 {
		buf.WriteString("// No polymorphic TL types in this schema.\n")
	}

	return writeGoFile(filepath.Join(outDir, "interfaces_gen.go"), buf.String())
}

func GenerateEnums(outDir string, combos []Combinator) error {
	typeCombos := filterCombos(combos, SectionTypes)

	var boolConstructors, trueConstructors, nullConstructors []Combinator
	for _, c := range typeCombos {
		switch c.Type {
		case "Bool":
			boolConstructors = append(boolConstructors, c)
		case "True":
			trueConstructors = append(trueConstructors, c)
		case "Null":
			nullConstructors = append(nullConstructors, c)
		}
	}

	var buf strings.Builder
	buf.WriteString("// Code generated by tlgen. DO NOT EDIT.\n\npackage tg\n\n")
	buf.WriteString("import \"bytes\"\n\n")

	if len(boolConstructors) > 0 {
		for _, c := range boolConstructors {
			pascal := SnakeToPascal(c.QualName)
			fmt.Fprintf(&buf, "// %sTypeID is the constructor ID for %s.\nconst %sTypeID = 0x%08x\n\n", pascal, c.QualName, pascal, c.ID)
		}
		buf.WriteString("// EncodeBool writes a TL Bool value.\nfunc EncodeBool(b *bytes.Buffer, val bool) {\n\tif val {\n\t\tWriteInt(b, BoolTrueTypeID)\n\t} else {\n\t\tWriteInt(b, BoolFalseTypeID)\n\t}\n}\n")
	}

	if len(nullConstructors) > 0 {
		for _, c := range nullConstructors {
			pascal := SnakeToPascal(c.QualName)
			fmt.Fprintf(&buf, "\nconst %sTypeID = 0x%08x\n", pascal, c.ID)
		}
	}

	return writeGoFile(filepath.Join(outDir, "enums_gen.go"), buf.String())
}

func GenerateCodecHelpers(outDir string, combos []Combinator) error {
	typeCombos := filterCombos(combos, SectionTypes)

	var buf strings.Builder
	buf.WriteString("// Code generated by tlgen. DO NOT EDIT.\n\npackage tg\n\n")
	buf.WriteString("import (\n\t\"bytes\"\n\t\"io\"\n)\n\n")

	buf.WriteString("// vectorBareID is the constructor ID for bare vectors.\nconst vectorBareID uint32 = 0x1cb5c415\n\n")

	buf.WriteString("// EncodeTLObject encodes any TLObject to the buffer.\nfunc EncodeTLObject(b *bytes.Buffer, obj TLObject) error {\n\tif obj == nil {\n\t\treturn nil\n\t}\n\treturn obj.Encode(b)\n}\n\n")

	buf.WriteString("// DecodeTLObjectByConstructorID reads a constructor ID and decodes the corresponding TLObject.\nfunc DecodeTLObjectByConstructorID(r io.Reader) (TLObject, error) {\n\treturn ReadTLObject(r)\n}\n\n")

	buf.WriteString("// RegisterTypes registers all generated TL type decoders into the global Registry.\nfunc RegisterTypes() {\n")

	typeMap := map[string][]Combinator{}
	typeOrder := []string{}
	for _, c := range typeCombos {
		if _, exists := typeMap[c.Type]; !exists {
			typeOrder = append(typeOrder, c.Type)
		}
		typeMap[c.Type] = append(typeMap[c.Type], c)
	}

	baseTypes := computeBaseTypes(combos)
	typeToConstructor := computeTypeToConstructor(combos)
	allNames := map[string]bool{}

	for _, typeName := range typeOrder {
		constructors := typeMap[typeName]
		groupAllNames := map[string]bool{}
		maps.Copy(groupAllNames, allNames)

		for _, c := range constructors {
			td := buildTypeData(c, "types", baseTypes, typeToConstructor, groupAllNames)
			constName := td.Name + "TypeID"
			fmt.Fprintf(&buf, "\tRegistry[%s] = func(r io.Reader) (TLObject, error) {\n\t\treturn Decode%s(r)\n\t}\n", constName, td.Name)
		}

		maps.Copy(allNames, groupAllNames)
	}

	buf.WriteString("}\n")

	return writeGoFile(filepath.Join(outDir, "codec_gen.go"), buf.String())
}

func GenerateGroupedTypes(outDir string, combos []Combinator, layer int) error {
	typeCombos := filterCombos(combos, SectionTypes)
	baseTypes := computeBaseTypes(combos)
	typeToConstructor := computeTypeToConstructor(combos)

	if err := cleanupGeneratedFiles(outDir, []string{"tl_*_gen.go", "*_types_gen.go"}); err != nil {
		return err
	}

	typeMap := map[string][]Combinator{}
	typeOrder := []string{}
	for _, c := range typeCombos {
		if _, exists := typeMap[c.Type]; !exists {
			typeOrder = append(typeOrder, c.Type)
		}
		typeMap[c.Type] = append(typeMap[c.Type], c)
	}

	typeToDomain := map[string]string{}
	for _, typeName := range typeOrder {
		typeToDomain[typeName] = classifyTypeDomain(typeName, typeMap[typeName])
	}

	domainTypes := map[string][]string{}
	domainSet := map[string]bool{}
	for _, typeName := range typeOrder {
		domain := typeToDomain[typeName]
		domainTypes[domain] = append(domainTypes[domain], typeName)
		domainSet[domain] = true
	}

	allNames := map[string]bool{}

	for _, domain := range domainFileOrder(domainSet) {
		typeNames := domainTypes[domain]

		var buf strings.Builder
		buf.WriteString("// Code generated by tlgen. DO NOT EDIT.\n\npackage tg\n\n")
		buf.WriteString("import (\n\t\"bytes\"\n\t\"io\"\n)\n")

		for _, typeName := range typeNames {
			constructors := typeMap[typeName]

			domainAllNames := map[string]bool{}
			maps.Copy(domainAllNames, allNames)

			var types []typeTemplateData
			for _, c := range constructors {
				td := buildTypeData(c, "types", baseTypes, typeToConstructor, domainAllNames)
				types = append(types, td)
			}

			basePascal := SnakeToPascal(typeName)
			isMulti := len(types) > 1

			if isMulti {
				fmt.Fprintf(&buf, "\n// %s is the interface for TL type %s.\n// Implementations must satisfy TLObject and are used to represent\n// any constructor of the %s TL type.\ntype %s interface {\n\tTLObject\n\tis%s()\n}\n", basePascal+"Class", basePascal, basePascal, basePascal+"Class", basePascal)
			}

			for _, td := range types {
				constName := td.Name + "TypeID"
				fmt.Fprintf(&buf, "\n// %s is the constructor ID for TL type %s.\nconst %s = 0x%08x\n", constName, td.QualName, constName, td.ID)
			}

			for _, td := range types {
				if isMulti {
					fmt.Fprintf(&buf, "\n// is%s marks %s as implementing the %sClass interface.\nfunc (*%s) is%s() {}\n", basePascal, td.Name, basePascal, td.Name, basePascal)
				}
			}

			for _, td := range types {
				fmt.Fprintf(&buf, "\n// %s represents the TL constructor %s (0x%08x).\n//\n// See https://core.telegram.org/constructor/%s for reference.\ntype %s struct {\n", td.Name, td.QualName, td.ID, td.QualName, td.Name)
				for _, f := range td.Fields {
					if f.IsFlags {
						fmt.Fprintf(&buf, "\t%s %s `json:\"-\"`\n", f.Name, f.GoType)
					} else {
						fmt.Fprintf(&buf, "\t%s %s `json:\"%s,omitempty\"`\n", f.Name, f.GoType, f.JSONTag)
					}
				}
				buf.WriteString("}\n")

				constName := td.Name + "TypeID"
				if td.HasFlags {
					fmt.Fprintf(&buf, "\n// SetFlags computes flags from non-zero optional fields.\nfunc (v *%s) SetFlags() {\n", td.Name)
					for _, fs := range td.FlagSyncs {
						fmt.Fprintf(&buf, "\tif %s {\n\t\tv.%s.Set(%d)\n\t}\n", flagSyncCondition(fs), fs.FlagName, fs.Bit)
					}
					buf.WriteString("}\n")
				}
				fmt.Fprintf(&buf, "\n// ConstructorID returns the TL constructor identifier 0x%08x.\nfunc (v *%s) ConstructorID() uint32 {\n\treturn %s\n}\n", td.ID, td.Name, constName)

				fmt.Fprintf(&buf, "\n// Encode serializes %s to a bytes.Buffer using the TL binary protocol.\nfunc (v *%s) Encode(b *bytes.Buffer) error {\n\tWriteInt(b, %s)\n", td.Name, td.Name, constName)
				if td.HasFlags {
					buf.WriteString("\tv.SetFlags()\n")
					for _, f := range td.Fields {
						if f.IsFlags {
							fmt.Fprintf(&buf, "\tWriteInt(b, uint32(v.%s))\n", f.Name)
						}
					}
				}
				for _, wl := range td.WriteLines {
					if wl.IsFlags {
						continue
					}
					if wl.IsGuarded {
						fmt.Fprintf(&buf, "\tif v.%s.Has(%d) {\n\t\t%s\n\t}\n", wl.FlagName, wl.FlagBit, wl.Code)
					} else {
						fmt.Fprintf(&buf, "\t%s\n", wl.Code)
					}
				}
				buf.WriteString("\treturn nil\n}\n")

				fmt.Fprintf(&buf, "\n// Decode%s deserializes a %s from a reader using the TL binary protocol.\nfunc Decode%s(r io.Reader) (*%s, error) {\n\tv := &%s{}\n", td.Name, td.Name, td.Name, td.Name, td.Name)
				for _, rl := range td.ReadLines {
					fmt.Fprintf(&buf, "\t%s\n", rl.Code)
				}
				buf.WriteString("\treturn v, nil\n}\n")

				fmt.Fprintf(&buf, "\nfunc init() {\n\tRegistry[%s] = func(r io.Reader) (TLObject, error) {\n\t\treturn Decode%s(r)\n\t}\n}\n", constName, td.Name)
			}

			maps.Copy(allNames, domainAllNames)
		}

		fileName := fmt.Sprintf("%s_types_gen.go", domain)
		if err := writeGoFile(filepath.Join(outDir, fileName), buf.String()); err != nil {
			return err
		}
	}

	return nil
}

func GenerateGroupedFunctions(outDir string, combos []Combinator, layer int) error {
	funcCombos := filterCombos(combos, SectionFunctions)
	baseTypes := computeBaseTypes(combos)
	typeToConstructor := computeTypeToConstructor(combos)
	knownTypes := computeKnownTypes(combos)

	if err := os.MkdirAll(outDir, 0755); err != nil {
		return err
	}

	if err := cleanupGeneratedFiles(outDir, []string{"tl_*_gen.go", "*_methods_gen.go"}); err != nil {
		return err
	}

	namespaceMap := map[string][]Combinator{}
	namespaceOrder := []string{}
	for _, c := range funcCombos {
		ns := classifyFuncDomain(c)
		if _, exists := namespaceMap[ns]; !exists {
			namespaceOrder = append(namespaceOrder, ns)
		}
		namespaceMap[ns] = append(namespaceMap[ns], c)
	}

	allNames := map[string]bool{}

	for _, ns := range namespaceOrder {
		nsCombos := namespaceMap[ns]

		needsFmt := false
		for _, c := range nsCombos {
			rt := resolveReturnType(c, baseTypes, typeToConstructor, knownTypes)
			if !rt.IsBool && !rt.IsVector && rt.GoType != "TLObject" && rt.GoType != "" {
				needsFmt = true
				break
			}
		}

		var buf strings.Builder
		buf.WriteString("// Code generated by tlgen. DO NOT EDIT.\n\npackage tg\n\n")

		imports := []string{"\"bytes\"", "\"context\"", "\"io\""}
		if needsFmt {
			imports = append(imports, "\"fmt\"")
		}
		buf.WriteString("import (\n")
		for _, imp := range imports {
			fmt.Fprintf(&buf, "\t%s\n", imp)
		}
		buf.WriteString(")\n")

		nsAllNames := map[string]bool{}
		maps.Copy(nsAllNames, allNames)

		for _, c := range nsCombos {
			groupAllNames := map[string]bool{}
			maps.Copy(groupAllNames, nsAllNames)

			td := buildTypeData(c, "functions", baseTypes, typeToConstructor, groupAllNames)
			constName := td.Name + "TypeID"
			retType := resolveReturnType(c, baseTypes, typeToConstructor, knownTypes)
			structName := td.Name + "Request"

			tlMethod := td.QualName
			methodPath := strings.ReplaceAll(tlMethod, ".", "/")
			fmt.Fprintf(&buf, "\n// %s is the constructor ID for the RPC function %s.\nconst %s = 0x%08x\n", constName, tlMethod, constName, td.ID)

			fmt.Fprintf(&buf, "\n// %s represents TL type `%s#%08x`.\n//\n// See https://core.telegram.org/method/%s for reference.\ntype %s struct {\n", structName, tlMethod, td.ID, methodPath, structName)
			for _, f := range td.Fields {
				if f.IsFlags {
					fmt.Fprintf(&buf, "\t%s %s `json:\"-\"`\n", f.Name, f.GoType)
				} else {
					fmt.Fprintf(&buf, "\t%s %s `json:\"%s,omitempty\"`\n", f.Name, f.GoType, f.JSONTag)
				}
			}
			buf.WriteString("}\n")

			if len(td.FlagSyncs) > 0 {
				fmt.Fprintf(&buf, "\n// SetFlags computes flags from non-zero optional fields.\nfunc (v *%s) SetFlags() {\n", structName)
				for _, fs := range td.FlagSyncs {
					fmt.Fprintf(&buf, "\tif %s {\n\t\tv.%s.Set(%d)\n\t}\n", flagSyncCondition(fs), fs.FlagName, fs.Bit)
				}
				buf.WriteString("}\n")
			}

			fmt.Fprintf(&buf, "\n// ConstructorID returns the TL constructor identifier 0x%08x.\nfunc (v *%s) ConstructorID() uint32 {\n\treturn %s\n}\n", td.ID, structName, constName)

			fmt.Fprintf(&buf, "\n// Encode serializes %s to a bytes.Buffer using the TL binary protocol.\nfunc (v *%s) Encode(b *bytes.Buffer) error {\n\tWriteInt(b, %s)\n", structName, structName, constName)
			if td.HasFlags {
				buf.WriteString("\tv.SetFlags()\n")
				for _, f := range td.Fields {
					if f.IsFlags {
						fmt.Fprintf(&buf, "\tWriteInt(b, uint32(v.%s))\n", f.Name)
					}
				}
			}
			for _, wl := range td.WriteLines {
				if wl.IsFlags {
					continue
				}
				if wl.IsGuarded {
					fmt.Fprintf(&buf, "\tif v.%s.Has(%d) {\n\t\t%s\n\t}\n", wl.FlagName, wl.FlagBit, wl.Code)
				} else {
					fmt.Fprintf(&buf, "\t%s\n", wl.Code)
				}
			}
			buf.WriteString("\treturn nil\n}\n")

			generateInvokeMethod(&buf, td, retType, structName)

			maps.Copy(nsAllNames, groupAllNames)
		}

		fileName := fmt.Sprintf("%s_methods_gen.go", ns)
		if err := writeGoFile(filepath.Join(outDir, fileName), buf.String()); err != nil {
			return err
		}

		maps.Copy(allNames, nsAllNames)
	}

	clientBuf := generateClientBoilerplate()
	return writeGoFile(filepath.Join(outDir, "tl_client_gen.go"), clientBuf.String())
}

func GenerateGroupedConstructors(outDir string, combos []Combinator) error {
	typeCombos := filterCombos(combos, SectionTypes)
	baseTypes := computeBaseTypes(combos)
	typeToConstructor := computeTypeToConstructor(combos)

	typeMap := map[string][]Combinator{}
	for _, c := range typeCombos {
		typeMap[c.Type] = append(typeMap[c.Type], c)
	}

	typeToDomain := map[string]string{}
	for typeName, constructors := range typeMap {
		typeToDomain[typeName] = classifyTypeDomain(typeName, constructors)
	}

	domainTypes := map[string][]string{}
	domainSet := map[string]bool{}
	for typeName := range typeMap {
		domain := typeToDomain[typeName]
		domainTypes[domain] = append(domainTypes[domain], typeName)
		domainSet[domain] = true
	}

	allNames := map[string]bool{}

	for _, domain := range domainFileOrder(domainSet) {
		typeNames := domainTypes[domain]

		var buf strings.Builder
		buf.WriteString("// Code generated by tlgen. DO NOT EDIT.\n\npackage tg\n\n")
		fmt.Fprintf(&buf, "// ConstructorMap%s maps constructor IDs to factory functions.\nvar ConstructorMap%s = map[uint32]func() TLObject{\n", domainTitle(domain), domainTitle(domain))

		for _, typeName := range typeNames {
			constructors := typeMap[typeName]
			groupAllNames := map[string]bool{}
			maps.Copy(groupAllNames, allNames)

			for _, c := range constructors {
				td := buildTypeData(c, "types", baseTypes, typeToConstructor, groupAllNames)
				fmt.Fprintf(&buf, "\t0x%08x: func() TLObject { return &%s{} },\n", td.ID, td.Name)
			}

			maps.Copy(allNames, groupAllNames)
		}

		buf.WriteString("}\n")

		fileName := fmt.Sprintf("%s_constructors_gen.go", domain)
		if err := writeGoFile(filepath.Join(outDir, fileName), buf.String()); err != nil {
			return err
		}
	}

	var unionBuf strings.Builder
	unionBuf.WriteString("// Code generated by tlgen. DO NOT EDIT.\n\npackage tg\n\n")
	unionBuf.WriteString("// ConstructorMap maps constructor IDs to factory functions that return zero-value TLObjects.\nvar ConstructorMap = map[uint32]func() TLObject{\n")

	for _, domain := range domainFileOrder(domainSet) {
		fmt.Fprintf(&unionBuf, "\t// %s types\n", domain)
		typeNames := domainTypes[domain]
		groupAllNames := map[string]bool{}
		maps.Copy(groupAllNames, allNames)

		for _, typeName := range typeNames {
			constructors := typeMap[typeName]
			for _, c := range constructors {
				td := buildTypeData(c, "types", baseTypes, typeToConstructor, groupAllNames)
				fmt.Fprintf(&unionBuf, "\t0x%08x: func() TLObject { return &%s{} },\n", td.ID, td.Name)
			}
		}

		maps.Copy(allNames, groupAllNames)
	}

	unionBuf.WriteString("}\n")
	return writeGoFile(filepath.Join(outDir, "tl_constructors_gen.go"), unionBuf.String())
}

func domainTitle(domain string) string {
	if domain == "" {
		return "Core"
	}
	return strings.ToUpper(domain[:1]) + domain[1:]
}

func GenerateNamesMap(outDir string, combos []Combinator) error {
	var buf strings.Builder
	buf.WriteString("// Code generated by tlgen. DO NOT EDIT.\n\npackage tg\n\n")
	buf.WriteString("// NamesMap maps TL qualified names (e.g. \"messages.sendMessage\") to their constructor IDs.\n")
	buf.WriteString("var NamesMap = map[string]uint32{\n")

	for _, c := range combos {
		fmt.Fprintf(&buf, "\t%q: 0x%08x,\n", c.QualName, c.ID)
	}

	buf.WriteString("}\n")
	return writeGoFile(filepath.Join(outDir, "tl_names_gen.go"), buf.String())
}

func GenerateFunctionsMap(outDir string, combos []Combinator) error {
	funcCombos := filterCombos(combos, SectionFunctions)
	baseTypes := computeBaseTypes(combos)
	typeToConstructor := computeTypeToConstructor(combos)
	allNames := map[string]bool{}

	var buf strings.Builder
	buf.WriteString("// Code generated by tlgen. DO NOT EDIT.\n\npackage tg\n\n")
	buf.WriteString("// FunctionsMap maps function constructor IDs to factory functions that return zero-value request objects.\n")
	buf.WriteString("var FunctionsMap = map[uint32]func() TLObject{\n")

	for _, c := range funcCombos {
		td := buildTypeData(c, "functions", baseTypes, typeToConstructor, allNames)
		structName := td.Name + "Request"
		fmt.Fprintf(&buf, "\t0x%08x: func() TLObject { return &%s{} },\n", td.ID, structName)
	}

	buf.WriteString("}\n")
	return writeGoFile(filepath.Join(outDir, "tl_functions_gen.go"), buf.String())
}

func GenerateE2EPackage(outDir string, combos []Combinator, layer int) error {
	typeCombos := filterCombos(combos, SectionTypes)
	baseTypes := computeBaseTypes(combos)
	typeToConstructor := computeTypeToConstructor(combos)
	allNames := map[string]bool{}

	if err := os.MkdirAll(outDir, 0755); err != nil {
		return err
	}

	docContent := "// Code generated by tlgen. DO NOT EDIT.\n\n// Package e2e provides auto-generated Go types for the Telegram end-to-end encrypted (secret chat) TL schema.\n//\n// Each type implements the tg.TLObject interface with Encode and ConstructorID methods.\n// Use Decode{Name} functions to deserialize types from a reader.\npackage e2e\n"
	if err := writeGoFile(filepath.Join(outDir, "doc.go"), docContent); err != nil {
		return err
	}

	e2eRegistry := func() string {
		var buf strings.Builder
		buf.WriteString("// Code generated by tlgen. DO NOT EDIT.\n\npackage e2e\n\n")
		buf.WriteString("import (\n\t\"bytes\"\n\t\"encoding/binary\"\n\t\"io\"\n\n\t\"github.com/mtgo-labs/mtgo/tg\"\n)\n\n")
		buf.WriteString("// Registry maps TL constructor IDs to factory functions.\nvar Registry = map[uint32]func(io.Reader) (tg.TLObject, error){}\n\n")
		buf.WriteString("// ReadE2ETLObject reads a TLObject from r using the e2e Registry.\nfunc ReadE2ETLObject(r io.Reader) (tg.TLObject, error) {\n\tvar id uint32\n\tif err := binary.Read(r, binary.LittleEndian, &id); err != nil {\n\t\treturn nil, err\n\t}\n\tconstructor, ok := Registry[id]\n\tif !ok {\n\t\treturn nil, &tg.UnknownConstructorError{ID: id}\n\t}\n\treturn constructor(r)\n}\n\n")
		buf.WriteString("const vectorBareID uint32 = 0x1cb5c415\n\n")
		buf.WriteString("// EncodeTLObject encodes any TLObject to the buffer.\nfunc EncodeTLObject(b *bytes.Buffer, obj tg.TLObject) error {\n\treturn obj.Encode(b)\n}\n")
		return buf.String()
	}
	if err := writeGoFile(filepath.Join(outDir, "e2e.go"), e2eRegistry()); err != nil {
		return err
	}

	typeMap := map[string][]Combinator{}
	typeOrder := []string{}
	for _, c := range typeCombos {
		if _, exists := typeMap[c.Type]; !exists {
			typeOrder = append(typeOrder, c.Type)
		}
		typeMap[c.Type] = append(typeMap[c.Type], c)
	}

	for _, typeName := range typeOrder {
		groupCombos := typeMap[typeName]
		groupAllNames := map[string]bool{}
		maps.Copy(groupAllNames, allNames)

		var types []typeTemplateData
		for _, c := range groupCombos {
			td := buildTypeData(c, "e2e", baseTypes, typeToConstructor, groupAllNames)
			types = append(types, td)
		}

		basePascal := SnakeToPascal(typeName)
		isMulti := len(types) > 1

		typeIDConstName := func(name string) string {
			return name + "TypeID"
		}

		var buf strings.Builder
		buf.WriteString("// Code generated by tlgen. DO NOT EDIT.\n\npackage e2e\n\n")
		buf.WriteString("import (\n\t\"bytes\"\n\t\"io\"\n\n\t\"github.com/mtgo-labs/mtgo/tg\"\n)\n")

		if isMulti {
			fmt.Fprintf(&buf, "\n// %s is the interface for TL type %s.\n// Implementations must satisfy tg.TLObject and are used to represent\n// any constructor of the %s TL type.\ntype %s interface {\n\ttg.TLObject\n\tis%s()\n}\n", basePascal+"Class", basePascal, basePascal, basePascal+"Class", basePascal)
		}

		for _, td := range types {
			constName := typeIDConstName(td.Name)
			fmt.Fprintf(&buf, "\n// %s is the constructor ID for TL type %s.\nconst %s = 0x%08x\n", constName, td.QualName, constName, td.ID)
		}

		for _, td := range types {
			if isMulti {
				fmt.Fprintf(&buf, "\n// is%s marks %s as implementing the %sClass interface.\nfunc (*%s) is%s() {}\n", basePascal, td.Name, basePascal, td.Name, basePascal)
			}
		}

		for _, td := range types {
			fmt.Fprintf(&buf, "\n// %s represents the TL constructor %s (0x%08x).\ntype %s struct {\n", td.Name, td.QualName, td.ID, td.Name)
			for _, f := range td.Fields {
				if f.IsFlags {
					fmt.Fprintf(&buf, "\t%s %s `json:\"-\"`\n", f.Name, f.GoType)
				} else {
					fmt.Fprintf(&buf, "\t%s %s `json:\"%s,omitempty\"`\n", f.Name, f.GoType, f.JSONTag)
				}
			}
			buf.WriteString("}\n")

			constName := typeIDConstName(td.Name)
			if td.HasFlags {
				fmt.Fprintf(&buf, "\n// SetFlags computes flags from non-zero optional fields.\nfunc (v *%s) SetFlags() {\n", td.Name)
				for _, fs := range td.FlagSyncs {
					fmt.Fprintf(&buf, "\tif %s {\n\t\tv.%s.Set(%d)\n\t}\n", flagSyncCondition(fs), fs.FlagName, fs.Bit)
				}
				buf.WriteString("}\n")
			}
			fmt.Fprintf(&buf, "\n// ConstructorID returns the TL constructor identifier 0x%08x.\nfunc (v *%s) ConstructorID() uint32 {\n\treturn %s\n}\n", td.ID, td.Name, constName)

			fmt.Fprintf(&buf, "\n// Encode serializes %s to a bytes.Buffer using the TL binary protocol.\nfunc (v *%s) Encode(b *bytes.Buffer) error {\n\ttg.WriteInt(b, %s)\n", td.Name, td.Name, constName)
			if td.HasFlags {
				buf.WriteString("\tv.SetFlags()\n")
				for _, f := range td.Fields {
					if f.IsFlags {
						fmt.Fprintf(&buf, "\ttg.WriteInt(b, uint32(v.%s))\n", f.Name)
					}
				}
			}
			for _, wl := range td.WriteLines {
				if wl.IsFlags {
					continue
				}
				code := wl.Code
				replacements := []struct{ from, to string }{
					{"WriteInt(b,", "tg.WriteInt(b,"},
					{"WriteLong(b,", "tg.WriteLong(b,"},
					{"WriteString(b,", "tg.WriteString(b,"},
					{"WriteBytes(b,", "tg.WriteBytes(b,"},
					{"WriteDouble(b,", "tg.WriteDouble(b,"},
					{"WriteInt128(b,", "tg.WriteInt128(b,"},
					{"WriteInt256(b,", "tg.WriteInt256(b,"},
					{"WriteBool(b,", "tg.WriteBool(b,"},
					{"WriteVectorInt(b,", "tg.WriteVectorInt(b,"},
					{"WriteVectorLong(b,", "tg.WriteVectorLong(b,"},
					{"WriteVectorString(b,", "tg.WriteVectorString(b,"},
					{"WriteVectorBytes(b,", "tg.WriteVectorBytes(b,"},
					{"EncodeTLObject(b,", "tg.EncodeTLObject(b,"},
				}
				for _, r := range replacements {
					code = strings.ReplaceAll(code, r.from, r.to)
				}
				if wl.IsGuarded {
					fmt.Fprintf(&buf, "\tif v.%s.Has(%d) {\n\t\t%s\n\t}\n", wl.FlagName, wl.FlagBit, code)
				} else {
					fmt.Fprintf(&buf, "\t%s\n", code)
				}
			}
			buf.WriteString("\treturn nil\n}\n")

			fmt.Fprintf(&buf, "\n// Decode%s deserializes a %s from a reader using the TL binary protocol.\nfunc Decode%s(r io.Reader) (*%s, error) {\n\tv := &%s{}\n", td.Name, td.Name, td.Name, td.Name, td.Name)
			for _, rl := range td.ReadLines {
				code := rl.Code
				readReplacements := []struct{ from, to string }{
					{"ReadInt(r)", "tg.ReadInt(r)"},
					{"ReadIntErr(r)", "tg.ReadIntErr(r)"},
					{"ReadLong(r)", "tg.ReadLong(r)"},
					{"ReadString(r)", "tg.ReadString(r)"},
					{"ReadBytes(r)", "tg.ReadBytes(r)"},
					{"ReadDouble(r)", "tg.ReadDouble(r)"},
					{"ReadInt128(r)", "tg.ReadInt128(r)"},
					{"ReadInt256(r)", "tg.ReadInt256(r)"},
					{"ReadBool(r)", "tg.ReadBool(r)"},
					{"ReadVectorInt(r)", "tg.ReadVectorInt(r)"},
					{"ReadVectorLong(r)", "tg.ReadVectorLong(r)"},
					{"ReadVectorString(r)", "tg.ReadVectorString(r)"},
					{"ReadVectorBytes(r)", "tg.ReadVectorBytes(r)"},
					{"ReadTLObject(r)", "ReadE2ETLObject(r)"},
					{"Fields(", "tg.Fields("},
					{".Has(", ".Has("},
				}
				for _, r := range readReplacements {
					code = strings.ReplaceAll(code, r.from, r.to)
				}
				fmt.Fprintf(&buf, "\t%s\n", code)
			}
			buf.WriteString("\treturn v, nil\n}\n")

			fmt.Fprintf(&buf, "\nfunc init() {\n\tRegistry[%s] = func(r io.Reader) (tg.TLObject, error) {\n\t\treturn Decode%s(r)\n\t}\n}\n", constName, td.Name)
		}

		fileName := fmt.Sprintf("tl_%s_gen.go", CamelToSnake(basePascal))
		if err := writeGoFile(filepath.Join(outDir, fileName), buf.String()); err != nil {
			return err
		}

		maps.Copy(allNames, groupAllNames)
	}

	return generateE2ENamesMap(outDir, combos)
}

func generateE2ENamesMap(outDir string, combos []Combinator) error {
	var buf strings.Builder
	buf.WriteString("// Code generated by tlgen. DO NOT EDIT.\n\npackage e2e\n\n")
	buf.WriteString("// NamesMap maps TL qualified names to their constructor IDs.\n")
	buf.WriteString("var NamesMap = map[string]uint32{\n")

	for _, c := range combos {
		if c.Section != SectionTypes {
			continue
		}
		fmt.Fprintf(&buf, "\t%q: 0x%08x,\n", c.QualName, c.ID)
	}

	buf.WriteString("}\n")
	return writeGoFile(filepath.Join(outDir, "tl_names_gen.go"), buf.String())
}

func generateClientBoilerplate() *strings.Builder {
	var buf strings.Builder
	buf.WriteString("// Code generated by tlgen. DO NOT EDIT.\n\npackage tg\n\n")
	buf.WriteString("import (\n\t\"context\"\n\t\"io\"\n)\n\n")
	buf.WriteString("// RPCClient provides typed RPC methods for all TL functions.\ntype RPCClient struct {\n\trpc Invoker\n}\n\n")
	buf.WriteString("// NewRPCClient creates a new RPCClient.\nfunc NewRPCClient(rpc Invoker) *RPCClient {\n\treturn &RPCClient{rpc: rpc}\n}\n\n")
	buf.WriteString("func (c *RPCClient) invoke(ctx context.Context, req TLObject, decode func(io.Reader) (TLObject, error)) (TLObject, error) {\n")
	buf.WriteString("\treturn c.rpc.RPCInvoke(ctx, req, decode)\n}\n")
	return &buf
}

func generateInvokeMethod(buf *strings.Builder, td typeTemplateData, retType returnType, structName string) {
	hasArgs := len(td.Fields) > 0
	methodName := td.Name
	qualName := td.QualName
	requestName := structName

	fmt.Fprintf(buf, "\n// %s invokes the %s RPC method on the server.\n//\n// Parameters:\n//   - ctx: context for cancellation and timeout\n//   - req: the request parameters\n//\n// Returns the result of the RPC call, or an error if the invocation fails.\nfunc (c *RPCClient) %s(ctx context.Context", methodName, qualName, methodName)
	if hasArgs {
		fmt.Fprintf(buf, ", req *%s", requestName)
	}
	fmt.Fprintf(buf, ") (%s, error) {\n", retType.GoType)

	invokeBody := func(reqExpr string) {
		buf.WriteString("\tresult, err := c.invoke(ctx, ")
		buf.WriteString(reqExpr)
		buf.WriteString(", func(r io.Reader) (TLObject, error) {\n")
		buf.WriteString("\t\treturn ReadTLObject(r)\n")
		buf.WriteString("\t})\n")
	}

	reqExpr := "req"
	if !hasArgs {
		reqExpr = fmt.Sprintf("&%s{}", requestName)
	}

	if retType.IsBool {
		invokeBody(reqExpr)
		buf.WriteString("\tif err != nil {\n\t\treturn false, err\n\t}\n")
		buf.WriteString("\t_ = result\n\treturn true, nil\n")
	} else if retType.IsVector {
		invokeBody(reqExpr)
		buf.WriteString("\tif err != nil {\n\t\treturn nil, err\n\t}\n")
		buf.WriteString("\t_ = result\n\treturn nil, nil\n")
	} else if retType.GoType == "TLObject" {
		invokeBody(reqExpr)
		buf.WriteString("\tif err != nil {\n\t\treturn nil, err\n\t}\n")
		buf.WriteString("\treturn result, nil\n")
	} else {
		invokeBody(reqExpr)
		buf.WriteString("\tif err != nil {\n\t\treturn nil, err\n\t}\n")
		fmt.Fprintf(buf, "\tif _c, _ok := result.(%s); _ok {\n\t\treturn _c, nil\n\t}\n\treturn nil, fmt.Errorf(\"unexpected result type %%T\", result)\n", retType.GoType)
	}
	buf.WriteString("}\n")
}
